import type {
  Flashcard
} from "@/content/flashcards/histologia/cards"

const filosofiaDeHayekFlashcards: Flashcard[] = [
  {
      id: "hayek-parcial-2-libertad-001",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Libertad y libertades",
      subtopic: "Libertad individual",
      front: "¿Qué es la libertad individual?",
      back: "Ausencia de coacción arbitraria ejercida por otros.",
      tags: ["filosofia", "hayek", "parcial-2", "libertad", "libertad-individual"]
    },
  {
      id: "hayek-parcial-2-libertad-002",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Libertad y libertades",
      subtopic: "Libertad individual",
      front: "¿Por qué la libertad individual es una relación social?",
      back: "Porque trata de si una persona está sometida a la voluntad arbitraria de otra.",
      tags: ["filosofia", "hayek", "parcial-2", "libertad", "coaccion"]
    },
  {
      id: "hayek-parcial-2-libertad-003",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Libertad y libertades",
      subtopic: "Libertad individual",
      front: "¿Qué diferencia hay entre limitación y coacción?",
      back: "La limitación reduce opciones; la coacción somete a alguien a la voluntad de otro.",
      tags: ["filosofia", "hayek", "parcial-2", "libertad", "coaccion"]
    },
  {
      id: "hayek-parcial-2-libertad-004",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Libertad y libertades",
      subtopic: "Libertad individual",
      front: "¿Por qué tener pocas opciones no implica falta de libertad?",
      back: "Porque las opciones pueden estar limitadas por circunstancias, no por coacción arbitraria.",
      tags: ["filosofia", "hayek", "parcial-2", "libertad", "opciones"]
    },
  {
      id: "hayek-parcial-2-libertad-005",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Libertad y libertades",
      subtopic: "Libertad individual",
      front: "¿Por qué pobreza no equivale automáticamente a falta de libertad?",
      back: "Porque reduce medios, pero no necesariamente implica coacción arbitraria.",
      tags: ["filosofia", "hayek", "parcial-2", "libertad", "pobreza"]
    },
  {
      id: "hayek-parcial-2-libertad-006",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Libertad y libertades",
      subtopic: "Libertad individual",
      front: "¿Cuándo la pobreza puede relacionarse con falta de libertad?",
      back: "Cuando surge de impedimentos coercitivos para trabajar, comerciar o usar bienes propios.",
      tags: ["filosofia", "hayek", "parcial-2", "libertad", "pobreza"]
    },
  {
      id: "hayek-parcial-2-libertad-007",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Libertad y libertades",
      subtopic: "Libertad política",
      front: "¿Qué es libertad política?",
      back: "Participar en la elección del gobierno o en decisiones colectivas.",
      tags: ["filosofia", "hayek", "parcial-2", "libertad-politica", "democracia"]
    },
  {
      id: "hayek-parcial-2-libertad-008",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Libertad y libertades",
      subtopic: "Libertad política",
      front: "¿Por qué votar no garantiza libertad individual?",
      back: "Porque una mayoría puede votar medidas coercitivas contra individuos o minorías.",
      tags: ["filosofia", "hayek", "parcial-2", "libertad-politica", "libertad-individual"]
    },
  {
      id: "hayek-parcial-2-libertad-009",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Libertad y libertades",
      subtopic: "Libertad interior",
      front: "¿Qué es libertad interior?",
      back: "Dominio de uno mismo frente a impulsos, pasiones o debilidades.",
      tags: ["filosofia", "hayek", "parcial-2", "libertad-interior"]
    },
  {
      id: "hayek-parcial-2-libertad-010",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Libertad y libertades",
      subtopic: "Libertad interior",
      front: "¿Por qué libertad interior no es libertad individual?",
      back: "Porque trata del autocontrol, no de la coacción ejercida por otros.",
      tags: ["filosofia", "hayek", "parcial-2", "libertad-interior", "libertad-individual"]
    },
  {
      id: "hayek-parcial-2-libertad-011",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Libertad y libertades",
      subtopic: "Libertad como poder",
      front: "¿Qué es libertad como poder?",
      back: "Confundir libertad con capacidad material de hacer lo que uno desea.",
      tags: ["filosofia", "hayek", "parcial-2", "libertad-como-poder"]
    },
  {
      id: "hayek-parcial-2-libertad-012",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Libertad y libertades",
      subtopic: "Libertad como poder",
      front: "¿Por qué Hayek separa libertad y poder?",
      back: "Porque libertad es ausencia de coacción; poder es capacidad o medios para lograr fines.",
      tags: ["filosofia", "hayek", "parcial-2", "libertad-como-poder"]
    },
  {
      id: "hayek-parcial-2-libertad-013",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Libertad y libertades",
      subtopic: "Libertad como poder",
      front: "¿Por qué identificar libertad con poder puede justificar coacción?",
      back: "Porque permite quitar recursos a unos para aumentar el poder material de otros.",
      tags: ["filosofia", "hayek", "parcial-2", "libertad-como-poder", "coaccion"]
    },
  {
      id: "hayek-parcial-2-libertad-014",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Libertad y libertades",
      subtopic: "Esfera privada",
      front: "¿Qué es la esfera privada?",
      back: "Un ámbito donde la persona puede actuar y planear sin interferencia arbitraria.",
      tags: ["filosofia", "hayek", "parcial-2", "esfera-privada", "libertad"]
    },
  {
      id: "hayek-parcial-2-libertad-015",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Libertad y libertades",
      subtopic: "Esfera privada",
      front: "¿Por qué la esfera privada permite hacer planes propios?",
      back: "Porque da previsibilidad frente a la voluntad ajena.",
      tags: ["filosofia", "hayek", "parcial-2", "esfera-privada", "planes"]
    },
  {
      id: "hayek-parcial-2-coaccion-001",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Coacción y ley",
      subtopic: "Coacción",
      front: "¿Cuándo hay coacción?",
      back: "Cuando alguien usa amenaza o control para hacer que otro sirva sus fines.",
      tags: ["filosofia", "hayek", "parcial-2", "coaccion"]
    },
  {
      id: "hayek-parcial-2-coaccion-002",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Coacción y ley",
      subtopic: "Coacción",
      front: "¿Por qué una amenaza reduce la libertad?",
      back: "Porque organiza la elección mediante el daño que otro promete imponer.",
      tags: ["filosofia", "hayek", "parcial-2", "coaccion", "amenaza"]
    },
  {
      id: "hayek-parcial-2-coaccion-003",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Coacción y ley",
      subtopic: "Coacción",
      front: "¿Qué es coacción indirecta?",
      back: "Controlar un recurso indispensable para imponer condiciones arbitrarias.",
      tags: ["filosofia", "hayek", "parcial-2", "coaccion", "recursos"]
    },
  {
      id: "hayek-parcial-2-coaccion-004",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Coacción y ley",
      subtopic: "Coacción",
      front: "¿Cuándo el control de un recurso puede volverse coercitivo?",
      back: "Cuando permite imponer condiciones arbitrarias sin alternativas razonables.",
      tags: ["filosofia", "hayek", "parcial-2", "coaccion", "recursos"]
    },
  {
      id: "hayek-parcial-2-coaccion-005",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Coacción y ley",
      subtopic: "Coacción estatal",
      front: "¿Por qué Hayek acepta cierta coacción estatal?",
      back: "Porque puede impedir la coacción privada y proteger la esfera individual.",
      tags: ["filosofia", "hayek", "parcial-2", "coaccion-estatal"]
    },
  {
      id: "hayek-parcial-2-coaccion-006",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Coacción y ley",
      subtopic: "Coacción estatal",
      front: "¿Por qué la coacción estatal debe limitarse estrictamente?",
      back: "Porque el Estado concentra fuerza legal y puede volverse la mayor fuente de arbitrariedad.",
      tags: ["filosofia", "hayek", "parcial-2", "estado", "coaccion"]
    },
  {
      id: "hayek-parcial-2-coaccion-007",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Coacción y ley",
      subtopic: "Reglas generales",
      front: "¿Qué tipo de reglas protegen la libertad individual?",
      back: "Reglas generales, iguales, conocidas y previsibles.",
      tags: ["filosofia", "hayek", "parcial-2", "reglas-generales", "libertad"]
    },
  {
      id: "hayek-parcial-2-coaccion-008",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Coacción y ley",
      subtopic: "Reglas generales",
      front: "¿Por qué una regla previsible ayuda a la libertad?",
      back: "Porque permite saber a qué atenerse y organizar planes propios.",
      tags: ["filosofia", "hayek", "parcial-2", "reglas-generales", "previsibilidad"]
    },
  {
      id: "hayek-parcial-2-coaccion-009",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Coacción y ley",
      subtopic: "Arbitrariedad",
      front: "¿Qué es una orden arbitraria?",
      back: "Una imposición particular basada en la voluntad discrecional de una autoridad.",
      tags: ["filosofia", "hayek", "parcial-2", "arbitrariedad", "ordenes"]
    },
  {
      id: "hayek-parcial-2-coaccion-010",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Coacción y ley",
      subtopic: "Arbitrariedad",
      front: "¿Por qué una orden arbitraria reduce la libertad?",
      back: "Porque somete a alguien a una voluntad ajena e imprevisible.",
      tags: ["filosofia", "hayek", "parcial-2", "arbitrariedad", "libertad"]
    },
  {
      id: "hayek-parcial-2-civilizacion-001",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Civilización y conocimiento",
      subtopic: "Ignorancia y conocimiento disperso",
      front: "¿Por qué reconocer la ignorancia humana favorece la libertad?",
      back: "Porque muestra que nadie posee todo el conocimiento necesario para dirigir la sociedad.",
      tags: ["filosofia", "hayek", "parcial-2", "ignorancia", "libertad"]
    },
  {
      id: "hayek-parcial-2-civilizacion-002",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Civilización y conocimiento",
      subtopic: "Ignorancia y conocimiento disperso",
      front: "¿Qué significa conocimiento disperso?",
      back: "Que el conocimiento está repartido entre muchas personas y no concentrado en una mente.",
      tags: ["filosofia", "hayek", "parcial-2", "conocimiento-disperso"]
    },
  {
      id: "hayek-parcial-2-civilizacion-003",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Civilización y conocimiento",
      subtopic: "Ignorancia y conocimiento disperso",
      front: "¿Por qué el conocimiento práctico es difícil de centralizar?",
      back: "Porque depende de circunstancias concretas, locales y cambiantes.",
      tags: ["filosofia", "hayek", "parcial-2", "conocimiento-practico", "centralizacion"]
    },
  {
      id: "hayek-parcial-2-civilizacion-004",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Civilización y conocimiento",
      subtopic: "Civilización",
      front: "¿Cómo ayuda la civilización al individuo?",
      back: "Le permite beneficiarse de conocimientos que él mismo no posee.",
      tags: ["filosofia", "hayek", "parcial-2", "civilizacion", "conocimiento"]
    },
  {
      id: "hayek-parcial-2-civilizacion-005",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Civilización y conocimiento",
      subtopic: "Civilización",
      front: "¿Por qué la civilización aumenta el poder individual?",
      back: "Porque incorpora conocimientos ajenos en herramientas, reglas, prácticas e instituciones.",
      tags: ["filosofia", "hayek", "parcial-2", "civilizacion"]
    },
  {
      id: "hayek-parcial-2-civilizacion-006",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Civilización y conocimiento",
      subtopic: "Conocimiento incorporado",
      front: "¿Qué es conocimiento incorporado?",
      back: "Conocimiento acumulado en hábitos, técnicas, tradiciones, instituciones y herramientas.",
      tags: ["filosofia", "hayek", "parcial-2", "conocimiento-incorporado"]
    },
  {
      id: "hayek-parcial-2-civilizacion-007",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Civilización y conocimiento",
      subtopic: "Tradiciones",
      front: "¿Qué papel cumplen las tradiciones?",
      back: "Transmiten experiencia acumulada por generaciones.",
      tags: ["filosofia", "hayek", "parcial-2", "tradicion", "experiencia"]
    },
  {
      id: "hayek-parcial-2-civilizacion-008",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Civilización y conocimiento",
      subtopic: "Tradiciones",
      front: "¿Por qué no toda tradición es automáticamente buena?",
      back: "Porque puede dejar de cumplir una función útil.",
      tags: ["filosofia", "hayek", "parcial-2", "tradicion"]
    },
  {
      id: "hayek-parcial-2-civilizacion-009",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Civilización y conocimiento",
      subtopic: "Tradiciones",
      front: "¿Por qué no conviene destruir instituciones solo porque no entendemos su función?",
      back: "Porque pueden contener conocimiento acumulado que todavía no sabemos explicar.",
      tags: ["filosofia", "hayek", "parcial-2", "instituciones", "tradicion"]
    },
  {
      id: "hayek-parcial-2-civilizacion-010",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Civilización y conocimiento",
      subtopic: "Razón humilde",
      front: "¿Qué es razón humilde?",
      back: "Razón que reconoce sus límites y reforma instituciones con prudencia.",
      tags: ["filosofia", "hayek", "parcial-2", "razon-humilde"]
    },
  {
      id: "hayek-parcial-2-civilizacion-011",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Civilización y conocimiento",
      subtopic: "Razón humilde",
      front: "¿Qué es razón arrogante?",
      back: "Razón que cree poder rediseñar toda la sociedad desde cero.",
      tags: ["filosofia", "hayek", "parcial-2", "razon-arrogante", "constructivismo"]
    },
  {
      id: "hayek-parcial-2-civilizacion-012",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Civilización y conocimiento",
      subtopic: "Aprendizaje social",
      front: "¿Por qué la libertad favorece el descubrimiento?",
      back: "Porque permite probar soluciones distintas usando conocimientos locales.",
      tags: ["filosofia", "hayek", "parcial-2", "descubrimiento", "libertad"]
    },
  {
      id: "hayek-parcial-2-civilizacion-013",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Civilización y conocimiento",
      subtopic: "Aprendizaje social",
      front: "¿Por qué los errores descentralizados suelen ser menos peligrosos?",
      back: "Porque afectan ámbitos limitados y pueden corregirse sin imponer el error a todos.",
      tags: ["filosofia", "hayek", "parcial-2", "error", "descentralizacion"]
    },
  {
      id: "hayek-parcial-2-civilizacion-014",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Civilización y conocimiento",
      subtopic: "Aprendizaje social",
      front: "¿Por qué un error centralizado puede ser más dañino?",
      back: "Porque puede imponerse a toda la sociedad.",
      tags: ["filosofia", "hayek", "parcial-2", "error", "centralizacion"]
    },
  {
      id: "hayek-parcial-2-civilizacion-015",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Civilización y conocimiento",
      subtopic: "Aprendizaje social",
      front: "¿Por qué la imitación importa para el aprendizaje social?",
      back: "Porque permite que soluciones descubiertas por pocos se extiendan a muchos.",
      tags: ["filosofia", "hayek", "parcial-2", "imitacion", "aprendizaje-social"]
    },
  {
      id: "hayek-parcial-2-progreso-001",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Progreso",
      subtopic: "Progreso como descubrimiento",
      front: "¿Por qué todo cambio no es progreso?",
      back: "Porque un cambio puede ser inútil, dañino o tener consecuencias no previstas.",
      tags: ["filosofia", "hayek", "parcial-2", "progreso", "cambio"]
    },
  {
      id: "hayek-parcial-2-progreso-002",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Progreso",
      subtopic: "Progreso como descubrimiento",
      front: "¿Qué distingue al progreso de un simple cambio?",
      back: "El progreso implica aprendizaje, descubrimiento o mejora útil.",
      tags: ["filosofia", "hayek", "parcial-2", "progreso"]
    },
  {
      id: "hayek-parcial-2-progreso-003",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Progreso",
      subtopic: "Progreso como descubrimiento",
      front: "¿Por qué el progreso es imprevisible?",
      back: "Porque consiste en descubrir conocimiento que aún no tenemos.",
      tags: ["filosofia", "hayek", "parcial-2", "progreso", "imprevisible"]
    },
  {
      id: "hayek-parcial-2-progreso-004",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Progreso",
      subtopic: "Progreso como descubrimiento",
      front: "¿Por qué planificar totalmente el progreso puede frenarlo?",
      back: "Porque limita los esfuerzos a objetivos ya visibles.",
      tags: ["filosofia", "hayek", "parcial-2", "progreso", "planificacion"]
    },
  {
      id: "hayek-parcial-2-progreso-005",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Progreso",
      subtopic: "Progreso como descubrimiento",
      front: "¿Por qué una idea sin utilidad inmediata puede ser valiosa?",
      back: "Porque puede servir de base para descubrimientos futuros.",
      tags: ["filosofia", "hayek", "parcial-2", "progreso", "utilidad"]
    },
  {
      id: "hayek-parcial-2-progreso-006",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Progreso",
      subtopic: "Progreso y desigualdad",
      front: "¿Por qué el progreso suele llegar primero a pocos?",
      back: "Porque lo nuevo suele ser caro, raro o difícil de producir al inicio.",
      tags: ["filosofia", "hayek", "parcial-2", "progreso", "desigualdad"]
    },
  {
      id: "hayek-parcial-2-progreso-007",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Progreso",
      subtopic: "Progreso y desigualdad",
      front: "¿Qué función experimental puede cumplir cierta desigualdad?",
      back: "Permitir que algunos prueben posibilidades aún no disponibles para todos.",
      tags: ["filosofia", "hayek", "parcial-2", "progreso", "desigualdad"]
    },
  {
      id: "hayek-parcial-2-progreso-008",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Progreso",
      subtopic: "Progreso y desigualdad",
      front: "¿Qué significa que los lujos de hoy pueden ser necesidades de mañana?",
      back: "Que bienes accesibles primero a pocos pueden volverse comunes con el tiempo.",
      tags: ["filosofia", "hayek", "parcial-2", "progreso", "lujos"]
    },
  {
      id: "hayek-parcial-2-progreso-009",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Progreso",
      subtopic: "Progreso y desigualdad",
      front: "¿Por qué prohibir algo hasta que todos puedan tenerlo puede frenar el progreso?",
      back: "Porque impide probarlo, mejorarlo y abaratarlo.",
      tags: ["filosofia", "hayek", "parcial-2", "progreso", "igualdad"]
    },
  {
      id: "hayek-parcial-2-progreso-010",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Progreso",
      subtopic: "Progreso y descontento",
      front: "¿Por qué el progreso puede crear nuevos deseos?",
      back: "Porque muestra posibilidades que antes no imaginábamos.",
      tags: ["filosofia", "hayek", "parcial-2", "progreso", "deseos"]
    },
  {
      id: "hayek-parcial-2-progreso-011",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Progreso",
      subtopic: "Progreso y descontento",
      front: "¿Por qué una persona puede estar mejor y sentirse más insatisfecha?",
      back: "Porque ve nuevas posibilidades y sus expectativas aumentan.",
      tags: ["filosofia", "hayek", "parcial-2", "progreso", "expectativas"]
    },
  {
      id: "hayek-parcial-2-tradicion-001",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Libertad, razón y tradición",
      subtopic: "Tradiciones de libertad",
      front: "¿Qué dos tradiciones de libertad distingue Hayek?",
      back: "La tradición inglesa evolutiva y la tradición francesa racionalista.",
      tags: ["filosofia", "hayek", "parcial-2", "tradicion-inglesa", "tradicion-francesa"]
    },
  {
      id: "hayek-parcial-2-tradicion-002",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Libertad, razón y tradición",
      subtopic: "Tradición inglesa",
      front: "¿Cómo entiende la libertad la tradición inglesa?",
      back: "Como resultado gradual de instituciones formadas por experiencia.",
      tags: ["filosofia", "hayek", "parcial-2", "tradicion-inglesa"]
    },
  {
      id: "hayek-parcial-2-tradicion-003",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Libertad, razón y tradición",
      subtopic: "Tradición francesa",
      front: "¿Cómo entiende la libertad la tradición francesa racionalista?",
      back: "Como diseño racional de un orden social desde principios abstractos.",
      tags: ["filosofia", "hayek", "parcial-2", "tradicion-francesa", "racionalismo"]
    },
  {
      id: "hayek-parcial-2-tradicion-004",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Libertad, razón y tradición",
      subtopic: "Tradición inglesa",
      front: "¿Por qué la tradición inglesa encaja con el conocimiento disperso?",
      back: "Porque ve las instituciones como resultado de ensayos, errores e imitaciones acumuladas.",
      tags: ["filosofia", "hayek", "parcial-2", "tradicion-inglesa", "conocimiento-disperso"]
    },
  {
      id: "hayek-parcial-2-tradicion-005",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Libertad, razón y tradición",
      subtopic: "Tradición francesa",
      front: "¿Cuál es el peligro del racionalismo constructivista?",
      back: "Destruir instituciones que contienen conocimiento acumulado que no comprendemos totalmente.",
      tags: ["filosofia", "hayek", "parcial-2", "racionalismo", "constructivismo"]
    },
  {
      id: "hayek-parcial-2-tradicion-006",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Libertad, razón y tradición",
      subtopic: "Orden social",
      front: "¿Qué significa que no todo orden viene del diseño?",
      back: "Que puede haber coordinación social sin una mente que planee el resultado total.",
      tags: ["filosofia", "hayek", "parcial-2", "orden", "diseno"]
    },
  {
      id: "hayek-parcial-2-tradicion-007",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Libertad, razón y tradición",
      subtopic: "Orden social",
      front: "¿Por qué un idioma es orden espontáneo?",
      back: "Porque tiene reglas, pero evolucionó por uso e imitación, no por diseño único.",
      tags: ["filosofia", "hayek", "parcial-2", "orden-espontaneo", "lenguaje"]
    },
  {
      id: "hayek-parcial-2-tradicion-008",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Libertad, razón y tradición",
      subtopic: "Orden social",
      front: "¿Por qué una sociedad libre no debe tratarse como una empresa?",
      back: "Porque una empresa tiene un fin común, mientras la sociedad libre permite fines múltiples.",
      tags: ["filosofia", "hayek", "parcial-2", "sociedad", "organizacion"]
    },
  {
      id: "hayek-parcial-2-responsabilidad-001",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Responsabilidad y libertad",
      subtopic: "Responsabilidad",
      front: "¿Por qué libertad y responsabilidad son inseparables?",
      back: "Porque quien puede elegir debe cargar con las consecuencias de sus actos.",
      tags: ["filosofia", "hayek", "parcial-2", "responsabilidad", "libertad"]
    },
  {
      id: "hayek-parcial-2-responsabilidad-002",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Responsabilidad y libertad",
      subtopic: "Responsabilidad",
      front: "¿Qué significa responsabilidad?",
      back: "Responder por las consecuencias de las propias acciones y poder aprender de ellas.",
      tags: ["filosofia", "hayek", "parcial-2", "responsabilidad"]
    },
  {
      id: "hayek-parcial-2-responsabilidad-003",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Responsabilidad y libertad",
      subtopic: "Responsabilidad",
      front: "¿Por qué responsabilidad no significa controlar totalmente el resultado?",
      back: "Porque también influyen azar, circunstancias externas y factores no controlados.",
      tags: ["filosofia", "hayek", "parcial-2", "responsabilidad", "azar"]
    },
  {
      id: "hayek-parcial-2-responsabilidad-004",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Responsabilidad y libertad",
      subtopic: "Responsabilidad",
      front: "¿Cuál es la función de asignar responsabilidad?",
      back: "Influir en la conducta futura mediante consecuencias, premios o censura.",
      tags: ["filosofia", "hayek", "parcial-2", "responsabilidad", "conducta"]
    },
  {
      id: "hayek-parcial-2-responsabilidad-005",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Responsabilidad y libertad",
      subtopic: "Responsabilidad",
      front: "¿Por qué una sociedad libre necesita responsabilidad?",
      back: "Porque guía la conducta sin control estatal constante.",
      tags: ["filosofia", "hayek", "parcial-2", "responsabilidad", "sociedad-libre"]
    },
  {
      id: "hayek-parcial-2-responsabilidad-006",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Responsabilidad y libertad",
      subtopic: "Responsabilidad",
      front: "¿Por qué la libertad puede sentirse como una carga?",
      back: "Porque exige decidir bajo incertidumbre y asumir consecuencias.",
      tags: ["filosofia", "hayek", "parcial-2", "responsabilidad", "carga"]
    },
  {
      id: "hayek-parcial-2-responsabilidad-007",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Responsabilidad y libertad",
      subtopic: "Determinismo y voluntarismo",
      front: "¿Qué es determinismo extremo?",
      back: "Negar responsabilidad porque las acciones estarían determinadas por causas previas.",
      tags: ["filosofia", "hayek", "parcial-2", "determinismo"]
    },
  {
      id: "hayek-parcial-2-responsabilidad-008",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Responsabilidad y libertad",
      subtopic: "Determinismo y voluntarismo",
      front: "¿Qué es voluntarismo extremo?",
      back: "Fundar responsabilidad en una voluntad totalmente separada de causas e influencias.",
      tags: ["filosofia", "hayek", "parcial-2", "voluntarismo"]
    },
  {
      id: "hayek-parcial-2-responsabilidad-009",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Responsabilidad y libertad",
      subtopic: "Determinismo y voluntarismo",
      front: "¿Cómo justifica Hayek la responsabilidad?",
      back: "Por su función práctica: influir en quienes pueden aprender de consecuencias.",
      tags: ["filosofia", "hayek", "parcial-2", "responsabilidad"]
    },
  {
      id: "hayek-parcial-2-responsabilidad-010",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Responsabilidad y libertad",
      subtopic: "Paternalismo",
      front: "¿Qué es paternalismo?",
      back: "Que una autoridad decida por alguien para protegerlo de sus propios errores.",
      tags: ["filosofia", "hayek", "parcial-2", "paternalismo"]
    },
  {
      id: "hayek-parcial-2-responsabilidad-011",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Responsabilidad y libertad",
      subtopic: "Paternalismo",
      front: "¿Por qué el paternalismo debilita la responsabilidad?",
      back: "Porque separa decisiones de consecuencias y reduce el aprendizaje individual.",
      tags: ["filosofia", "hayek", "parcial-2", "paternalismo", "responsabilidad"]
    },
  {
      id: "hayek-parcial-2-igualdad-001",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Igualdad, valor y mérito",
      subtopic: "Igualdad ante la ley",
      front: "¿Qué igualdad es compatible con la libertad?",
      back: "La igualdad ante la ley.",
      tags: ["filosofia", "hayek", "parcial-2", "igualdad", "ley"]
    },
  {
      id: "hayek-parcial-2-igualdad-002",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Igualdad, valor y mérito",
      subtopic: "Igualdad ante la ley",
      front: "¿Qué significa igualdad ante la ley?",
      back: "Todos están sujetos a reglas generales, previsibles e iguales.",
      tags: ["filosofia", "hayek", "parcial-2", "igualdad", "ley"]
    },
  {
      id: "hayek-parcial-2-igualdad-003",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Igualdad, valor y mérito",
      subtopic: "Igualdad material",
      front: "¿Qué es igualdad material?",
      back: "Buscar igualar condiciones o resultados entre personas.",
      tags: ["filosofia", "hayek", "parcial-2", "igualdad-material"]
    },
  {
      id: "hayek-parcial-2-igualdad-004",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Igualdad, valor y mérito",
      subtopic: "Igualdad material",
      front: "¿Por qué igualdad material e igualdad ante la ley pueden chocar?",
      back: "Porque igualar resultados exige tratar desigualmente a las personas.",
      tags: ["filosofia", "hayek", "parcial-2", "igualdad-material", "ley"]
    },
  {
      id: "hayek-parcial-2-igualdad-005",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Igualdad, valor y mérito",
      subtopic: "Igualdad y diferencias humanas",
      front: "¿Por qué tratar igual ante la ley produce resultados desiguales?",
      back: "Porque las personas tienen talentos, familias, hábitos, suerte y circunstancias distintas.",
      tags: ["filosofia", "hayek", "parcial-2", "igualdad", "desigualdad"]
    },
  {
      id: "hayek-parcial-2-igualdad-006",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Igualdad, valor y mérito",
      subtopic: "Igualdad de oportunidades",
      front: "¿Qué significa igualdad liberal de oportunidades?",
      back: "Que nadie sea bloqueado por barreras legales arbitrarias para intentar mejorar.",
      tags: ["filosofia", "hayek", "parcial-2", "igualdad-de-oportunidades"]
    },
  {
      id: "hayek-parcial-2-igualdad-007",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Igualdad, valor y mérito",
      subtopic: "Igualdad de oportunidades",
      front: "¿Qué no promete la igualdad liberal de oportunidades?",
      back: "No promete mismo punto de partida, mismas probabilidades ni mismos resultados.",
      tags: ["filosofia", "hayek", "parcial-2", "igualdad-de-oportunidades"]
    },
  {
      id: "hayek-parcial-2-igualdad-008",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Igualdad, valor y mérito",
      subtopic: "Familia y herencia",
      front: "¿Qué transmite la familia además de recursos?",
      back: "Hábitos, valores, lenguaje, disciplina, cultura y expectativas.",
      tags: ["filosofia", "hayek", "parcial-2", "familia", "herencia"]
    },
  {
      id: "hayek-parcial-2-igualdad-009",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Igualdad, valor y mérito",
      subtopic: "Familia y herencia",
      front: "¿Por qué eliminar toda ventaja familiar puede debilitar la cultura?",
      back: "Porque la familia transmite hábitos, valores y conocimientos entre generaciones.",
      tags: ["filosofia", "hayek", "parcial-2", "familia", "cultura"]
    },
  {
      id: "hayek-parcial-2-igualdad-010",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Igualdad, valor y mérito",
      subtopic: "Familia y herencia",
      front: "¿Por qué una ventaja inmerecida puede tener valor social?",
      back: "Porque puede permitir producir algo útil para otros.",
      tags: ["filosofia", "hayek", "parcial-2", "ventaja", "valor-social"]
    },
  {
      id: "hayek-parcial-2-valor-merito-001",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Igualdad, valor y mérito",
      subtopic: "Valor y mérito",
      front: "¿Qué es mérito?",
      back: "Dignidad moral del esfuerzo, intención o sacrificio de una persona.",
      tags: ["filosofia", "hayek", "parcial-2", "merito"]
    },
  {
      id: "hayek-parcial-2-valor-merito-002",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Igualdad, valor y mérito",
      subtopic: "Valor y mérito",
      front: "¿Qué es valor?",
      back: "Utilidad o importancia que otros perciben en un bien, servicio o capacidad.",
      tags: ["filosofia", "hayek", "parcial-2", "valor"]
    },
  {
      id: "hayek-parcial-2-valor-merito-003",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Igualdad, valor y mérito",
      subtopic: "Valor y mérito",
      front: "¿Por qué mérito y valor no son lo mismo?",
      back: "El mérito mira el esfuerzo interno; el valor mira la utilidad para otros.",
      tags: ["filosofia", "hayek", "parcial-2", "valor", "merito"]
    },
  {
      id: "hayek-parcial-2-valor-merito-004",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Igualdad, valor y mérito",
      subtopic: "Valor y mérito",
      front: "¿Por qué alguien puede esforzarse mucho y producir poco valor social?",
      back: "Porque su resultado puede no resolver una necesidad que otros valoren.",
      tags: ["filosofia", "hayek", "parcial-2", "valor", "merito"]
    },
  {
      id: "hayek-parcial-2-valor-merito-005",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Igualdad, valor y mérito",
      subtopic: "Valor y mérito",
      front: "¿Qué recompensa principalmente el mercado?",
      back: "El valor que otros atribuyen al resultado.",
      tags: ["filosofia", "hayek", "parcial-2", "mercado", "valor"]
    },
  {
      id: "hayek-parcial-2-valor-merito-006",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Igualdad, valor y mérito",
      subtopic: "Valor y mérito",
      front: "¿Por qué el mercado no es juez moral?",
      back: "Porque no mide virtud, sacrificio ni dignidad personal.",
      tags: ["filosofia", "hayek", "parcial-2", "mercado", "merito"]
    },
  {
      id: "hayek-parcial-2-valor-merito-007",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Igualdad, valor y mérito",
      subtopic: "Justicia distributiva",
      front: "¿Qué es justicia distributiva?",
      back: "Asignar recompensas según un patrón como mérito, necesidad, igualdad o esfuerzo.",
      tags: ["filosofia", "hayek", "parcial-2", "justicia-distributiva"]
    },
  {
      id: "hayek-parcial-2-valor-merito-008",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Igualdad, valor y mérito",
      subtopic: "Justicia distributiva",
      front: "¿Por qué la justicia distributiva choca con una sociedad libre?",
      back: "Porque exige un distribuidor central que imponga un patrón común.",
      tags: ["filosofia", "hayek", "parcial-2", "justicia-distributiva", "sociedad-libre"]
    },
  {
      id: "hayek-parcial-2-democracia-001",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Gobierno mayoritario",
      subtopic: "Liberalismo y democracia",
      front: "¿Qué pregunta responde la democracia?",
      back: "Quién decide o cómo se toman decisiones colectivas.",
      tags: ["filosofia", "hayek", "parcial-2", "democracia"]
    },
  {
      id: "hayek-parcial-2-democracia-002",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Gobierno mayoritario",
      subtopic: "Liberalismo y democracia",
      front: "¿Qué pregunta responde el liberalismo?",
      back: "Hasta dónde puede llegar el poder coercitivo.",
      tags: ["filosofia", "hayek", "parcial-2", "liberalismo", "democracia"]
    },
  {
      id: "hayek-parcial-2-democracia-003",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Gobierno mayoritario",
      subtopic: "Liberalismo y democracia",
      front: "¿Por qué liberalismo y democracia no son lo mismo?",
      back: "La democracia decide el método; el liberalismo limita el poder.",
      tags: ["filosofia", "hayek", "parcial-2", "liberalismo", "democracia"]
    },
  {
      id: "hayek-parcial-2-democracia-004",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Gobierno mayoritario",
      subtopic: "Democracia como medio",
      front: "¿Por qué Hayek acepta el gobierno mayoritario?",
      back: "Porque permite tomar decisiones comunes y cambiar gobiernos pacíficamente.",
      tags: ["filosofia", "hayek", "parcial-2", "democracia", "gobierno-mayoritario"]
    },
  {
      id: "hayek-parcial-2-democracia-005",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Gobierno mayoritario",
      subtopic: "Democracia como medio",
      front: "¿Qué no garantiza la democracia por sí sola?",
      back: "No garantiza verdad, justicia ni libertad individual.",
      tags: ["filosofia", "hayek", "parcial-2", "democracia", "libertad"]
    },
  {
      id: "hayek-parcial-2-democracia-006",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Gobierno mayoritario",
      subtopic: "Democracia dogmática",
      front: "¿Qué es democracia dogmática?",
      back: "Tratar la voluntad de la mayoría como autoridad final o ilimitada.",
      tags: ["filosofia", "hayek", "parcial-2", "democracia-dogmatica"]
    },
  {
      id: "hayek-parcial-2-democracia-007",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Gobierno mayoritario",
      subtopic: "Democracia dogmática",
      front: "¿Por qué la democracia dogmática amenaza la libertad?",
      back: "Porque permite que la mayoría coaccione arbitrariamente a individuos o minorías.",
      tags: ["filosofia", "hayek", "parcial-2", "democracia-dogmatica", "libertad"]
    },
  {
      id: "hayek-parcial-2-democracia-008",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Gobierno mayoritario",
      subtopic: "Demarquía",
      front: "¿Qué es democracia liberal o demarquía?",
      back: "Democracia donde la mayoría decide bajo reglas generales y límites liberales.",
      tags: ["filosofia", "hayek", "parcial-2", "demarquia", "democracia-liberal"]
    },
  {
      id: "hayek-parcial-2-democracia-009",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Gobierno mayoritario",
      subtopic: "Opinión pública",
      front: "¿Por qué la opinión pública debe formarse libremente?",
      back: "Porque si el Estado la controla, la mayoría puede ser manipulada.",
      tags: ["filosofia", "hayek", "parcial-2", "opinion-publica", "libertad"]
    },
  {
      id: "hayek-parcial-2-democracia-010",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Gobierno mayoritario",
      subtopic: "Opinión pública",
      front: "¿Por qué proteger opiniones minoritarias es importante?",
      back: "Porque la mayoría puede equivocarse y las minorías pueden corregirla en el futuro.",
      tags: ["filosofia", "hayek", "parcial-2", "opinion-publica", "minorias"]
    },
  {
      id: "hayek-parcial-2-democracia-011",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Gobierno mayoritario",
      subtopic: "Demagogia",
      front: "¿Qué es demagogia?",
      back: "Usar apoyo popular para justificar medidas arbitrarias o beneficios inmediatos.",
      tags: ["filosofia", "hayek", "parcial-2", "demagogia"]
    },
  {
      id: "hayek-parcial-2-democracia-012",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Gobierno mayoritario",
      subtopic: "Demagogia",
      front: "¿Por qué la demagogia amenaza la libertad?",
      back: "Porque usa la mayoría como excusa para violar reglas generales o atacar minorías.",
      tags: ["filosofia", "hayek", "parcial-2", "demagogia", "libertad"]
    },
  {
      id: "hayek-parcial-2-cap8-001",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Trabajo e independencia",
      subtopic: "Trabajo por cuenta ajena",
      front: "¿Qué tipo de trabajador depende de salario fijo y tareas asignadas?",
      back: "El trabajador por cuenta ajena.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-8", "trabajo-asalariado"]
    },
  {
      id: "hayek-parcial-2-cap8-002",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Trabajo e independencia",
      subtopic: "Actividad independiente",
      front: "¿Qué tipo de trabajador asume directamente riesgos y decisiones económicas?",
      back: "El trabajador independiente.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-8", "trabajo-independiente"]
    },
  {
      id: "hayek-parcial-2-cap8-003",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Trabajo e independencia",
      subtopic: "Trabajo por cuenta ajena",
      front: "¿Qué busca principalmente el trabajador por cuenta ajena?",
      back: "Seguridad, salario estable y menor riesgo personal.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-8", "seguridad"]
    },
  {
      id: "hayek-parcial-2-cap8-004",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Trabajo e independencia",
      subtopic: "Actividad independiente",
      front: "¿Qué exige más la actividad independiente?",
      back: "Asumir riesgos, decidir fines y cargar con los resultados.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-8", "responsabilidad"]
    },
  {
      id: "hayek-parcial-2-cap8-005",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Trabajo e independencia",
      subtopic: "Libertad del asalariado",
      front: "¿Por qué el asalariado puede seguir siendo libre?",
      back: "Porque puede elegir entre distintos empleadores.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-8", "asalariado", "libertad"]
    },
  {
      id: "hayek-parcial-2-cap8-006",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Trabajo e independencia",
      subtopic: "Libertad del asalariado",
      front: "¿Qué protege al asalariado frente al abuso de un empleador?",
      back: "La existencia de empleadores alternativos.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-8", "empleadores", "libertad"]
    },
  {
      id: "hayek-parcial-2-cap8-007",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Trabajo e independencia",
      subtopic: "Libertad del asalariado",
      front: "¿Por qué un único empleador amenaza la libertad del trabajador?",
      back: "Porque elimina la posibilidad real de cambiar de patrono.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-8", "empleador-unico"]
    },
  {
      id: "hayek-parcial-2-cap8-008",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Trabajo e independencia",
      subtopic: "Libertad del asalariado",
      front: "¿Qué empleador único sería especialmente peligroso?",
      back: "El Estado.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-8", "estado", "empleador-unico"]
    },
  {
      id: "hayek-parcial-2-cap8-009",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Trabajo e independencia",
      subtopic: "Mentalidad asalariada",
      front: "¿Qué mentalidad puede formar el trabajo asalariado?",
      back: "Preferir seguridad, estabilidad y reglas predecibles.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-8", "mentalidad-asalariada"]
    },
  {
      id: "hayek-parcial-2-cap8-010",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Trabajo e independencia",
      subtopic: "Mentalidad independiente",
      front: "¿Qué mentalidad puede formar la actividad independiente?",
      back: "Preferir autonomía, riesgo y responsabilidad personal.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-8", "mentalidad-independiente"]
    },
  {
      id: "hayek-parcial-2-cap8-011",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Trabajo e independencia",
      subtopic: "Mérito y valor",
      front: "¿Qué criterio suele dominar dentro de una organización laboral?",
      back: "Mérito, cumplimiento y obediencia funcional.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-8", "merito", "organizacion"]
    },
  {
      id: "hayek-parcial-2-cap8-012",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Trabajo e independencia",
      subtopic: "Mérito y valor",
      front: "¿Qué criterio domina en el mercado libre?",
      back: "Valor producido para otros.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-8", "valor", "mercado"]
    },
  {
      id: "hayek-parcial-2-cap8-013",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Trabajo e independencia",
      subtopic: "Mérito y valor",
      front: "¿Qué problema surge al remunerar toda la sociedad por mérito?",
      back: "Alguien debe decidir qué mérito merece recompensa.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-8", "merito", "arbitrariedad"]
    },
  {
      id: "hayek-parcial-2-cap8-014",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Trabajo e independencia",
      subtopic: "Sociedad de empleados",
      front: "¿Por qué una sociedad libre necesita trabajadores independientes?",
      back: "Porque crean nuevas oportunidades y asumen riesgos.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-8", "trabajo-independiente"]
    },
  {
      id: "hayek-parcial-2-cap8-015",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Trabajo e independencia",
      subtopic: "Sociedad de empleados",
      front: "¿Por qué una sociedad de solo empleados sería débil?",
      back: "Porque faltaría gente que emprenda, arriesgue e innove.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-8", "empleados", "innovacion"]
    },
  {
      id: "hayek-parcial-2-cap8-016",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Trabajo e independencia",
      subtopic: "Empresario independiente",
      front: "¿Qué función cumple el empresario independiente?",
      back: "Organiza recursos y descubre oportunidades nuevas.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-8", "empresario"]
    },
  {
      id: "hayek-parcial-2-cap8-017",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Trabajo e independencia",
      subtopic: "Empresario independiente",
      front: "¿Por qué el empresario puede beneficiar a otros sin proponérselo directamente?",
      back: "Porque al buscar oportunidades crea bienes, empleo o innovación.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-8", "empresario", "orden-espontaneo"]
    },
  {
      id: "hayek-parcial-2-cap8-018",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Trabajo e independencia",
      subtopic: "Independencia económica",
      front: "¿Por qué la independencia económica protege la libertad personal?",
      back: "Porque reduce la dependencia de una sola voluntad ajena.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-8", "independencia-economica"]
    },
  {
      id: "hayek-parcial-2-cap8-019",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Trabajo e independencia",
      subtopic: "Independencia económica",
      front: "¿Qué ventaja social tiene que existan personas con recursos propios?",
      back: "Pueden apoyar ideas y proyectos que la mayoría aún no acepta.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-8", "riqueza", "ideas-minoritarias"]
    },
  {
      id: "hayek-parcial-2-cap8-020",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Trabajo e independencia",
      subtopic: "Mecenazgo privado",
      front: "¿Qué peligro habría si solo el Estado financiara cultura e ideas?",
      back: "Tendría poder para decidir qué cultura e ideas sobreviven.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-8", "estado", "cultura"]
    },
  {
      id: "hayek-parcial-2-cap8-021",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Trabajo e independencia",
      subtopic: "Mecenazgo privado",
      front: "¿Qué función cumple el mecenazgo privado?",
      back: "Financiar cultura, ciencia o ideas fuera del control estatal.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-8", "mecenazgo", "cultura"]
    },
  {
      id: "hayek-parcial-2-cap8-022",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Trabajo e independencia",
      subtopic: "Ocio creador",
      front: "¿Qué tipo de ocio puede tener valor social?",
      back: "El ocio usado para cultura, pensamiento, ciencia o creación.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-8", "ocio-creador"]
    },
  {
      id: "hayek-parcial-2-cap8-023",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Trabajo e independencia",
      subtopic: "Sociedad libre",
      front: "¿Cuál es el peligro de aplicar la lógica de una empresa a toda la sociedad?",
      back: "Convertir la sociedad en una organización dirigida por mandatos.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-8", "sociedad", "organizacion"]
    },
  {
      id: "hayek-parcial-2-cap8-024",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Trabajo e independencia",
      subtopic: "Sociedad libre",
      front: "¿Por qué una sociedad libre no debe tener un fin único?",
      back: "Porque cada persona persigue fines distintos.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-8", "sociedad-libre", "fines"]
    },
  {
      id: "hayek-parcial-2-guia-001",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Libertad y libertades",
      subtopic: "Libertad individual",
      front: "¿Por qué la libertad no es un estado natural?",
      back: "Porque necesita reglas, instituciones y límites a la coacción arbitraria.",
      tags: ["filosofia", "hayek", "parcial-2", "libertad", "instituciones"]
    },
  {
      id: "hayek-parcial-2-guia-002",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Libertad y libertades",
      subtopic: "Libertad individual",
      front: "¿Qué hace posible la libertad individual?",
      back: "Una esfera privada protegida por reglas generales.",
      tags: ["filosofia", "hayek", "parcial-2", "libertad", "esfera-privada"]
    },
  {
      id: "hayek-parcial-2-guia-003",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Libertad y libertades",
      subtopic: "Libertad individual",
      front: "¿Por qué una persona aislada no es “libre” en sentido hayekiano?",
      back: "Porque la libertad individual solo trata de relaciones entre personas.",
      tags: ["filosofia", "hayek", "parcial-2", "libertad", "sociedad"]
    },
  {
      id: "hayek-parcial-2-guia-004",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Libertad y libertades",
      subtopic: "Libertades concretas",
      front: "¿Qué riesgo hay en tratar las libertades como permisos?",
      back: "Que la autoridad pueda concederlas o retirarlas discrecionalmente.",
      tags: ["filosofia", "hayek", "parcial-2", "libertades", "permisos"]
    },
  {
      id: "hayek-parcial-2-guia-005",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Libertad y libertades",
      subtopic: "Libertad como poder",
      front: "¿Qué confunde la libertad como poder?",
      back: "Confunde libertad con medios, capacidades o recursos.",
      tags: ["filosofia", "hayek", "parcial-2", "libertad-como-poder"]
    },
  {
      id: "hayek-parcial-2-guia-006",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Libertad y libertades",
      subtopic: "Libertad interior",
      front: "¿Qué problema confunde la libertad interior con libertad individual?",
      back: "Confunde falta de autocontrol con coacción ejercida por otros.",
      tags: ["filosofia", "hayek", "parcial-2", "libertad-interior"]
    },
  {
      id: "hayek-parcial-2-guia-007",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Libertad y libertades",
      subtopic: "Libertad política",
      front: "¿Por qué el voto no garantiza libertad individual?",
      back: "Porque una mayoría puede votar medidas coercitivas contra individuos.",
      tags: ["filosofia", "hayek", "parcial-2", "libertad-politica", "democracia"]
    },
  {
      id: "hayek-parcial-2-guia-008",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Coacción y ley",
      subtopic: "Derecho y permiso",
      front: "¿Qué significa vivir por derecho?",
      back: "Actuar bajo reglas generales sin depender de permisos discrecionales.",
      tags: ["filosofia", "hayek", "parcial-2", "derecho", "permisos"]
    },
  {
      id: "hayek-parcial-2-guia-009",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Coacción y ley",
      subtopic: "Derecho y permiso",
      front: "¿Qué significa vivir por permiso?",
      back: "Depender de autorizaciones particulares de una autoridad.",
      tags: ["filosofia", "hayek", "parcial-2", "permisos", "coaccion"]
    },
  {
      id: "hayek-parcial-2-guia-010",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Coacción y ley",
      subtopic: "Derecho y permiso",
      front: "¿Por qué vivir por permiso amenaza la libertad?",
      back: "Porque somete los planes personales al criterio de una autoridad.",
      tags: ["filosofia", "hayek", "parcial-2", "permisos", "libertad"]
    },
  {
      id: "hayek-parcial-2-guia-011",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Coacción y ley",
      subtopic: "Derecho y permiso",
      front: "¿Por qué vivir por derecho facilita planear la vida?",
      back: "Porque las reglas conocidas permiten prever consecuencias.",
      tags: ["filosofia", "hayek", "parcial-2", "derecho", "previsibilidad"]
    },
  {
      id: "hayek-parcial-2-guia-012",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Coacción y ley",
      subtopic: "Derecho y permiso",
      front: "¿Qué distingue un permiso bajo regla general de un permiso discrecional?",
      back: "El primero depende de requisitos claros; el segundo del criterio particular de la autoridad.",
      tags: ["filosofia", "hayek", "parcial-2", "permisos", "reglas-generales"]
    },
  {
      id: "hayek-parcial-2-guia-013",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Libertad, razón y tradición",
      subtopic: "Tradiciones de libertad",
      front: "¿Qué tradición confía más en instituciones evolucionadas?",
      back: "La tradición británica o evolutiva.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-4", "tradicion-britanica"]
    },
  {
      id: "hayek-parcial-2-guia-014",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Libertad, razón y tradición",
      subtopic: "Tradiciones de libertad",
      front: "¿Qué tradición confía más en rediseñar la sociedad desde la razón?",
      back: "La tradición francesa o racionalista.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-4", "tradicion-francesa"]
    },
  {
      id: "hayek-parcial-2-guia-015",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Libertad, razón y tradición",
      subtopic: "Tradición británica",
      front: "¿Cómo cambia la tradición británica las instituciones?",
      back: "Con reformas graduales basadas en experiencia.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-4", "tradicion-britanica"]
    },
  {
      id: "hayek-parcial-2-guia-016",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Libertad, razón y tradición",
      subtopic: "Tradición francesa",
      front: "¿Qué tipo de cambio favorece el racionalismo constructivista?",
      back: "Cambios planificados desde principios abstractos.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-4", "racionalismo"]
    },
  {
      id: "hayek-parcial-2-guia-017",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Libertad, razón y tradición",
      subtopic: "Instituciones",
      front: "¿Por qué una institución contiene conocimiento acumulado?",
      back: "Porque se formó por ensayo, error e imitación durante generaciones.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-4", "instituciones"]
    },
  {
      id: "hayek-parcial-2-guia-018",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Libertad, razón y tradición",
      subtopic: "Instituciones",
      front: "¿Qué error comete quien intenta diseñar instituciones desde cero?",
      back: "Ignora el conocimiento acumulado que contienen las instituciones existentes.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-4", "constructivismo"]
    },
  {
      id: "hayek-parcial-2-guia-019",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Libertad, razón y tradición",
      subtopic: "Razón limitada",
      front: "¿Cómo debe usarse la razón ante instituciones heredadas?",
      back: "Para reformarlas prudentemente, no para destruirlas automáticamente.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-4", "razon"]
    },
  {
      id: "hayek-parcial-2-guia-020",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Gobierno mayoritario",
      subtopic: "Liberalismo y democracia",
      front: "¿Qué pregunta responde el liberalismo?",
      back: "Qué límites debe tener el poder coercitivo.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-7", "liberalismo"]
    },
  {
      id: "hayek-parcial-2-guia-021",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Gobierno mayoritario",
      subtopic: "Liberalismo y democracia",
      front: "¿Qué pregunta responde la democracia?",
      back: "Quién decide o cómo se toman decisiones colectivas.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-7", "democracia"]
    },
  {
      id: "hayek-parcial-2-guia-022",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Gobierno mayoritario",
      subtopic: "Democracia limitada",
      front: "¿Cuándo la democracia es compatible con la libertad?",
      back: "Cuando está limitada por reglas generales y principios liberales.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-7", "democracia-liberal"]
    },
  {
      id: "hayek-parcial-2-guia-023",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Gobierno mayoritario",
      subtopic: "Democracia dogmática",
      front: "¿Qué convierte a la democracia en poder absoluto?",
      back: "Tratar la voluntad de la mayoría como autoridad sin límites.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-7", "democracia-dogmatica"]
    },
  {
      id: "hayek-parcial-2-guia-024",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Gobierno mayoritario",
      subtopic: "Demagogia",
      front: "¿Qué hace el demagogo con la mayoría?",
      back: "Usa sus deseos para justificar medidas arbitrarias.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-7", "demagogia"]
    },
  {
      id: "hayek-parcial-2-guia-025",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Gobierno mayoritario",
      subtopic: "Demagogia",
      front: "¿Por qué la demagogia amenaza a las minorías?",
      back: "Porque puede sacrificar su libertad para complacer a la mayoría.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-7", "demagogia", "minorías"]
    },
  {
      id: "hayek-parcial-2-guia-026",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Gobierno mayoritario",
      subtopic: "Opinión pública",
      front: "¿Por qué la opinión pública necesita libertad de discusión?",
      back: "Porque las ideas deben formarse sin dirección estatal.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-7", "opinion-publica"]
    },
  {
      id: "hayek-parcial-2-guia-027",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Gobierno mayoritario",
      subtopic: "Opinión pública",
      front: "¿Por qué una opinión minoritaria debe poder circular?",
      back: "Porque puede corregir a la mayoría y volverse aceptada después.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-7", "opinion-publica", "minorías"]
    },
  {
      id: "hayek-parcial-2-guia-028",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Gobierno mayoritario",
      subtopic: "Opinión pública",
      front: "¿Qué peligro aparece si el gobierno forma la opinión pública?",
      back: "La mayoría puede votar ideas inducidas por el propio poder.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-7", "opinion-publica", "estado"]
    },
  {
      id: "hayek-parcial-2-guia-029",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Civilización y conocimiento",
      subtopic: "Comunidad y sociedad",
      front: "¿Qué caracteriza a una comunidad?",
      back: "Relaciones cercanas, trato directo y fines más compartidos.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-2", "comunidad"]
    },
  {
      id: "hayek-parcial-2-guia-030",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Civilización y conocimiento",
      subtopic: "Comunidad y sociedad",
      front: "¿Qué caracteriza a una sociedad amplia?",
      back: "Cooperación entre desconocidos mediante reglas e instituciones.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-2", "sociedad"]
    },
  {
      id: "hayek-parcial-2-guia-031",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Civilización y conocimiento",
      subtopic: "Comunidad y sociedad",
      front: "¿Por qué la sociedad amplia necesita reglas impersonales?",
      back: "Porque coordina personas que no se conocen directamente.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-2", "sociedad", "reglas"]
    },
  {
      id: "hayek-parcial-2-guia-032",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Civilización y conocimiento",
      subtopic: "Cultura y autarquía",
      front: "¿Qué es autarquía?",
      back: "Depender solo de lo que uno mismo sabe, produce o controla.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-2", "autarquia"]
    },
  {
      id: "hayek-parcial-2-guia-033",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Civilización y conocimiento",
      subtopic: "Cultura y autarquía",
      front: "¿Por qué la civilización supera la autarquía?",
      back: "Porque permite usar conocimiento que uno no posee personalmente.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-2", "civilizacion", "autarquia"]
    },
  {
      id: "hayek-parcial-2-guia-034",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Civilización y conocimiento",
      subtopic: "Cultura y autarquía",
      front: "¿Qué es cultura en clave hayekiana?",
      back: "Conocimiento heredado convertido en hábitos, reglas e instituciones.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-2", "cultura"]
    },
  {
      id: "hayek-parcial-2-guia-035",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Civilización y conocimiento",
      subtopic: "Cultura y autarquía",
      front: "¿Qué es barbarie en clave hayekiana?",
      back: "Pérdida de reglas e instituciones que permiten cooperación.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-2", "barbarie"]
    },
  {
      id: "hayek-parcial-2-guia-036",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Civilización y conocimiento",
      subtopic: "Ignorancia útil",
      front: "¿Por qué la ignorancia puede ayudar a vivir en sociedad?",
      back: "Porque permite usar conocimiento ajeno sin tener que comprenderlo todo.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-2", "ignorancia"]
    },
  {
      id: "hayek-parcial-2-guia-037",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Civilización y conocimiento",
      subtopic: "Ignorancia útil",
      front: "¿Por qué no necesitamos saber cómo se produce todo lo que usamos?",
      back: "Porque la civilización incorpora conocimiento de otros en herramientas y prácticas.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-2", "civilizacion", "conocimiento"]
    },
  {
      id: "hayek-parcial-2-guia-038",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Civilización y conocimiento",
      subtopic: "Problemas sociales",
      front: "¿Qué hace complejo a un problema social?",
      back: "Conocimiento disperso, fines múltiples y circunstancias cambiantes.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-2", "problemas-sociales"]
    },
  {
      id: "hayek-parcial-2-guia-039",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Civilización y conocimiento",
      subtopic: "Problemas sociales",
      front: "¿Por qué un problema social no se resuelve como problema técnico?",
      back: "Porque no tiene datos completos ni un objetivo único definido.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-2", "problemas-sociales"]
    },
  {
      id: "hayek-parcial-2-guia-040",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Progreso",
      subtopic: "Progreso como descubrimiento",
      front: "¿Por qué el progreso no puede pronosticarse completamente?",
      back: "Porque consiste en descubrir lo que todavía no sabemos.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-3", "progreso"]
    },
  {
      id: "hayek-parcial-2-guia-041",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Progreso",
      subtopic: "Progreso como descubrimiento",
      front: "¿Por qué el progreso necesita libertad?",
      back: "Porque requiere probar, fallar, corregir, innovar e imitar.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-3", "progreso", "libertad"]
    },
  {
      id: "hayek-parcial-2-guia-042",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Progreso",
      subtopic: "Progreso como descubrimiento",
      front: "¿Por qué la planificación central frena el progreso?",
      back: "Porque limita caminos no previstos por el planificador.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-3", "planificacion", "progreso"]
    },
  {
      id: "hayek-parcial-2-guia-043",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Progreso",
      subtopic: "Progreso como descubrimiento",
      front: "¿Por qué no todo cambio es progreso?",
      back: "Porque un cambio puede ser inútil, dañino o fallido.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-3", "progreso"]
    },
  {
      id: "hayek-parcial-2-guia-044",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Progreso",
      subtopic: "Progreso incómodo",
      front: "¿Por qué el progreso puede crear frustraciones nuevas?",
      back: "Porque abre posibilidades que antes no deseábamos.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-3", "progreso", "deseos"]
    },
  {
      id: "hayek-parcial-2-guia-045",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Progreso",
      subtopic: "Progreso desigual",
      front: "¿Por qué el progreso no beneficia a todos inmediatamente?",
      back: "Porque las innovaciones suelen difundirse de forma gradual.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-3", "progreso", "desigualdad"]
    },
  {
      id: "hayek-parcial-2-guia-046",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Progreso",
      subtopic: "Sociedad progresiva",
      front: "¿Qué caracteriza a una sociedad progresiva?",
      back: "Permite desviación, experimentación, error e innovación.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-3", "sociedad-progresiva"]
    },
  {
      id: "hayek-parcial-2-guia-047",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Progreso",
      subtopic: "Sociedad estacionaria",
      front: "¿Qué caracteriza a una sociedad estacionaria?",
      back: "Limita la experimentación a lo que la autoridad ya conoce.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-3", "sociedad-estacionaria"]
    },
  {
      id: "hayek-parcial-2-guia-048",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Progreso",
      subtopic: "Visión liberal",
      front: "¿Cómo descubre fines una sociedad liberal?",
      back: "Permitiendo libertad, experimentación y aprendizaje social.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-3", "vision-liberal"]
    },
  {
      id: "hayek-parcial-2-guia-049",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Progreso",
      subtopic: "Visión racionalista",
      front: "¿Qué presupone la visión racionalista del desarrollo?",
      back: "Que la autoridad conoce los fines sociales y los medios adecuados.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-3", "racionalismo"]
    },
  {
      id: "hayek-parcial-2-guia-050",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Responsabilidad y libertad",
      subtopic: "Responsabilidad",
      front: "¿Qué significa ser responsable?",
      back: "Elegir, actuar y cargar con consecuencias.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-5", "responsabilidad"]
    },
  {
      id: "hayek-parcial-2-guia-051",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Responsabilidad y libertad",
      subtopic: "Responsabilidad",
      front: "¿Por qué la responsabilidad hace más pesada la libertad?",
      back: "Porque obliga a asumir riesgos, errores y consecuencias.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-5", "responsabilidad", "libertad"]
    },
  {
      id: "hayek-parcial-2-guia-052",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Responsabilidad y libertad",
      subtopic: "Responsabilidad",
      front: "¿Qué pasa si el Estado asume la responsabilidad de todos?",
      back: "También adquiere poder para dirigir la vida de todos.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-5", "estado", "responsabilidad"]
    },
  {
      id: "hayek-parcial-2-guia-053",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Responsabilidad y libertad",
      subtopic: "Responsabilidad",
      front: "¿Por qué un error estatal puede ser más peligroso que un error individual?",
      back: "Porque puede afectar a toda la sociedad.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-5", "estado", "riesgo"]
    },
  {
      id: "hayek-parcial-2-guia-054",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Responsabilidad y libertad",
      subtopic: "Determinismo y voluntarismo",
      front: "¿Qué error comete el determinismo extremo?",
      back: "Niega responsabilidad al reducir la acción a causas externas.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-5", "determinismo"]
    },
  {
      id: "hayek-parcial-2-guia-055",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Responsabilidad y libertad",
      subtopic: "Determinismo y voluntarismo",
      front: "¿Qué error comete el voluntarismo extremo?",
      back: "Separa la voluntad de toda experiencia e influencia.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-5", "voluntarismo"]
    },
  {
      id: "hayek-parcial-2-guia-056",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Responsabilidad y libertad",
      subtopic: "Determinismo y voluntarismo",
      front: "¿Por qué la responsabilidad necesita aprendizaje?",
      back: "Porque la persona debe prever consecuencias y ajustar su conducta.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-5", "responsabilidad", "aprendizaje"]
    },
  {
      id: "hayek-parcial-2-guia-057",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Responsabilidad y libertad",
      subtopic: "Tragedia de los comunes",
      front: "¿Qué problema expresa la tragedia de los comunes?",
      back: "Lo que no pertenece a nadie tiende a cuidarse peor.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-5", "propiedad", "comunes"]
    },
  {
      id: "hayek-parcial-2-guia-058",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Responsabilidad y libertad",
      subtopic: "Tragedia de los comunes",
      front: "¿Por qué la propiedad privada ayuda a cuidar recursos?",
      back: "Porque conecta uso, beneficio y responsabilidad.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-5", "propiedad-privada", "responsabilidad"]
    },
  {
      id: "hayek-parcial-2-guia-059",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Igualdad, valor y mérito",
      subtopic: "Igualdad",
      front: "¿Qué igualdad defiende Hayek?",
      back: "Igualdad ante la ley.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-6", "igualdad"]
    },
  {
      id: "hayek-parcial-2-guia-060",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Igualdad, valor y mérito",
      subtopic: "Igualdad",
      front: "¿Qué igualdad exige coacción redistributiva?",
      back: "La igualdad material.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-6", "igualdad-material"]
    },
  {
      id: "hayek-parcial-2-guia-061",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Igualdad, valor y mérito",
      subtopic: "Igualdad",
      front: "¿Por qué iguales reglas producen resultados desiguales?",
      back: "Porque las personas tienen capacidades, hábitos y circunstancias distintas.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-6", "igualdad", "desigualdad"]
    },
  {
      id: "hayek-parcial-2-guia-062",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Igualdad, valor y mérito",
      subtopic: "Igualdad",
      front: "¿Qué desigualdad amenaza la libertad?",
      back: "La que surge de privilegios legales o decisiones arbitrarias.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-6", "desigualdad", "privilegios"]
    },
  {
      id: "hayek-parcial-2-guia-063",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Igualdad, valor y mérito",
      subtopic: "Igualdad de oportunidades",
      front: "¿Qué ofrece la igualdad de posibilidades?",
      back: "Caminos abiertos para mejorar sin barreras legales arbitrarias.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-6", "igualdad-de-oportunidades"]
    },
  {
      id: "hayek-parcial-2-guia-064",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Igualdad, valor y mérito",
      subtopic: "Igualdad de oportunidades",
      front: "¿Qué exige igualar totalmente oportunidades reales?",
      back: "Intervenir familia, educación, recursos y ambiente.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-6", "igualdad-de-oportunidades"]
    },
  {
      id: "hayek-parcial-2-guia-065",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Igualdad, valor y mérito",
      subtopic: "Justicia redistributiva",
      front: "¿Qué busca la justicia redistributiva?",
      back: "Asignar recursos según un patrón decidido políticamente.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-6", "justicia-redistributiva"]
    },
  {
      id: "hayek-parcial-2-guia-066",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Igualdad, valor y mérito",
      subtopic: "Justicia redistributiva",
      front: "¿Por qué la redistribución puede violar igualdad ante la ley?",
      back: "Porque trata distinto a personas para lograr un resultado elegido.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-6", "redistribucion", "igualdad"]
    },
  {
      id: "hayek-parcial-2-guia-067",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Igualdad, valor y mérito",
      subtopic: "Valor y mérito",
      front: "¿Qué es valor?",
      back: "Utilidad que otros atribuyen a un resultado.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-6", "valor"]
    },
  {
      id: "hayek-parcial-2-guia-068",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Igualdad, valor y mérito",
      subtopic: "Valor y mérito",
      front: "¿Qué es mérito?",
      back: "Dignidad moral del esfuerzo o intención.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-6", "merito"]
    },
  {
      id: "hayek-parcial-2-guia-069",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Igualdad, valor y mérito",
      subtopic: "Valor y mérito",
      front: "¿Qué premia principalmente el mercado?",
      back: "Valor para otros.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-6", "mercado", "valor"]
    },
  {
      id: "hayek-parcial-2-guia-070",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Igualdad, valor y mérito",
      subtopic: "Valor y mérito",
      front: "¿Qué problema aparece al premiar mérito desde el Estado?",
      back: "La autoridad decide qué esfuerzos merecen recompensa.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-6", "merito", "estado"]
    },
  {
      id: "hayek-parcial-2-guia-071",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Trabajo e independencia",
      subtopic: "Asalariado e independiente",
      front: "¿Qué busca normalmente el trabajador por cuenta ajena?",
      back: "Seguridad, salario estable y menor riesgo.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-8", "asalariado"]
    },
  {
      id: "hayek-parcial-2-guia-072",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Trabajo e independencia",
      subtopic: "Asalariado e independiente",
      front: "¿Qué exige normalmente la actividad independiente?",
      back: "Autonomía, riesgo y responsabilidad directa.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-8", "independiente"]
    },
  {
      id: "hayek-parcial-2-guia-073",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Trabajo e independencia",
      subtopic: "Asalariado e independiente",
      front: "¿De qué depende la libertad del asalariado?",
      back: "De poder elegir entre varios empleadores.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-8", "asalariado", "libertad"]
    },
  {
      id: "hayek-parcial-2-guia-074",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Trabajo e independencia",
      subtopic: "Estado empleador",
      front: "¿Por qué un único empleador amenaza la libertad laboral?",
      back: "Porque elimina alternativas reales de salida.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-8", "empleador", "libertad"]
    },
  {
      id: "hayek-parcial-2-guia-075",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Trabajo e independencia",
      subtopic: "Estado empleador",
      front: "¿Por qué el Estado como único empleador es peligroso?",
      back: "Porque concentra ingreso, trabajo y autoridad política.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-8", "estado", "empleador"]
    },
  {
      id: "hayek-parcial-2-guia-076",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Trabajo e independencia",
      subtopic: "Independencia económica",
      front: "¿Por qué una sociedad libre necesita personas independientes?",
      back: "Porque pueden emprender, innovar y sostener ideas minoritarias.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-8", "independencia"]
    },
  {
      id: "hayek-parcial-2-guia-077",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Trabajo e independencia",
      subtopic: "Riqueza independiente",
      front: "¿Por qué la riqueza independiente puede proteger la libertad?",
      back: "Porque permite actuar sin pedir permiso a la mayoría o al Estado.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-8", "riqueza", "libertad"]
    },
  {
      id: "hayek-parcial-2-guia-078",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Trabajo e independencia",
      subtopic: "Mecenazgo privado",
      front: "¿Por qué el mecenazgo privado protege la cultura?",
      back: "Porque evita que solo el Estado decida qué ideas financiar.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-8", "mecenazgo", "cultura"]
    },
  {
      id: "hayek-parcial-2-guia-079",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Trabajo e independencia",
      subtopic: "Mentalidad asalariada",
      front: "¿Qué peligro político tiene la mentalidad asalariada?",
      back: "Convertir seguridad y estabilidad en obligaciones para toda la sociedad.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-8", "asalariado", "politica"]
    },
  {
      id: "hayek-parcial-2-guia-080",
      subject: "Filosofía",
      book: "Fundamentos de la libertad",
      chapter: "Parcial 2",
      topic: "Trabajo e independencia",
      subtopic: "Sociedad libre",
      front: "¿Por qué una sociedad de solo empleados perdería dinamismo?",
      back: "Porque faltaría gente dispuesta a asumir riesgos e iniciar proyectos.",
      tags: ["filosofia", "hayek", "parcial-2", "capitulo-8", "sociedad-libre", "emprendimiento"]
    }
]

export default filosofiaDeHayekFlashcards
