import { mcq } from "../questionTypes"

const chapter = "Capítulo 19"

const cap19QuestionsInSourceOrder = [
  mcq("micro-cap19-001", chapter, "Fundamentos", "easy", "¿Cuál es la finalidad inmunológica principal de una vacuna?", ["Inducir una respuesta activa y específica que pueda dejar memoria", "Administrar anticuerpos terminados para protección inmediata", "Eliminar directamente cualquier microorganismo de la sangre", "Producir inflamación sin reconocimiento antigénico"], 0, "La vacuna aporta un inmunógeno para que el propio sistema inmunitario genere una respuesta específica y, por lo general, memoria."),
  mcq("micro-cap19-002", chapter, "Fundamentos", "medium", "¿Qué definición incluye correctamente a vacunas vivas, inactivadas, recombinantes y de ácidos nucleicos?", ["Preparaciones biológicas con inmunógenos capaces de inducir inmunidad activa", "Suspensiones formadas siempre por bacterias muertas completas", "Soluciones de anticuerpos obtenidas únicamente de caballos", "Preparaciones destinadas exclusivamente a neutralizar toxinas circulantes"], 0, "Una definición amplia debe abarcar microorganismos completos, componentes, vectores y material genético, todos usados como inmunógenos."),
  mcq("micro-cap19-003", chapter, "Fundamentos", "medium", "Después de recibir una vacuna, ¿quién produce la respuesta protectora?", ["El sistema inmunitario del receptor", "El animal del que se extrajo el suero", "El fabricante durante la purificación", "Los anticuerpos preformados de la preparación"], 0, "En la inmunización activa, el receptor reconoce el inmunógeno y produce su propia respuesta celular y humoral."),
  mcq("micro-cap19-004", chapter, "Fundamentos", "hard", "¿Por qué es impreciso definir toda vacuna como una suspensión de microorganismos que perdieron agresividad?", ["Porque algunas contienen solo antígenos purificados, vectores o ácidos nucleicos", "Porque todas las vacunas contienen anticuerpos y no antígenos", "Porque ninguna vacuna puede contener microorganismos completos", "Porque la inmunidad activa no necesita un inmunógeno"], 0, "La definición clásica no abarca plataformas modernas ni vacunas de subunidades, toxoides o conjugadas."),
  mcq("micro-cap19-005", chapter, "Vacuna ideal", "easy", "¿Qué combinación corresponde mejor a una vacuna ideal?", ["Segura, eficaz, duradera, estable, accesible y fácil de administrar", "Muy reactogénica, costosa y dependiente de numerosas dosis", "Inestable, de efecto inmediato y sin memoria", "Eficaz únicamente en personas previamente infectadas"], 0, "Una vacuna ideal busca maximizar protección y seguridad mientras facilita conservación, administración y acceso."),
  mcq("micro-cap19-006", chapter, "Vacuna ideal", "medium", "¿Por qué una vacuna ideal debería requerir pocas dosis?", ["Facilita completar el esquema y mejora la adherencia", "Evita que se formen células de memoria", "Convierte la inmunidad activa en pasiva", "Impide toda respuesta secundaria"], 0, "Un esquema sencillo reduce oportunidades de abandono y facilita la ejecución del programa de vacunación."),
  mcq("micro-cap19-007", chapter, "Vacuna ideal", "medium", "¿Qué propiedad permite transportar y almacenar una vacuna sin perder fácilmente su potencia?", ["Estabilidad", "Virulencia residual", "Heterología", "Reactogenicidad"], 0, "La estabilidad ayuda a preservar la integridad del producto durante almacenamiento y transporte."),
  mcq("micro-cap19-008", chapter, "Vacuna ideal", "hard", "Afirmar que una vacuna ideal debe ser absolutamente inocua significa, en la práctica, que debería:", ["Presentar un balance beneficio-riesgo muy favorable y mínimos efectos adversos", "Ser incapaz de provocar cualquier molestia local", "No activar la inmunidad innata", "Producir enfermedad leve en todos los receptores"], 0, "Ninguna intervención es literalmente libre de todo efecto; la meta real es alta seguridad con beneficio claramente superior al riesgo."),
  mcq("micro-cap19-009", chapter, "Vacuna ideal", "medium", "¿Por qué puede ser ventajoso imitar la vía natural de entrada de un patógeno?", ["Puede favorecer defensas en el sitio donde se inicia la infección", "Garantiza que nunca se necesiten refuerzos", "Transforma el antígeno en anticuerpo", "Evita por completo la respuesta sistémica"], 0, "La vía de presentación puede orientar la respuesta hacia compartimentos relevantes, incluida la inmunidad de mucosas."),
  mcq("micro-cap19-010", chapter, "Vacuna ideal", "hard", "¿Cuál NO es una propiedad razonable para evaluar una vacuna?", ["Que produzca protección idéntica de por vida en absolutamente todas las personas", "Que mantenga estabilidad durante su conservación", "Que sea accesible económicamente", "Que induzca una respuesta específica eficaz"], 0, "La duración puede variar según vacuna y huésped; exigir protección vitalicia universal no es un criterio realista."),

  mcq("micro-cap19-011", chapter, "Vacunas vivas", "easy", "¿Qué contienen las vacunas vivas atenuadas?", ["Microorganismos viables cuya virulencia ha sido reducida", "Anticuerpos humanos purificados", "Solo toxinas activas en baja concentración", "Microorganismos muertos incapaces de conservar antígenos"], 0, "La atenuación disminuye la capacidad de causar enfermedad manteniendo replicación limitada y antigenicidad."),
  mcq("micro-cap19-012", chapter, "Vacunas vivas", "medium", "¿Qué ventaja suele asociarse con las vacunas vivas atenuadas?", ["Inducen una respuesta que se aproxima a la infección natural", "No requieren ninguna precaución en inmunodeficiencia", "Proporcionan anticuerpos preformados", "Son siempre más estables al calor"], 0, "La replicación limitada expone al sistema inmunitario a antígenos de manera semejante a la infección natural."),
  mcq("micro-cap19-013", chapter, "Vacunas vivas", "medium", "¿En qué situación se evitan generalmente las vacunas vivas atenuadas?", ["Embarazo o inmunodeficiencia grave", "Esquema atrasado en una persona sana", "Necesidad de inducir memoria", "Antecedente de vacunación intramuscular"], 0, "Por su capacidad de replicación, las vacunas vivas suelen estar contraindicadas durante el embarazo y en inmunosupresión grave."),
  mcq("micro-cap19-014", chapter, "Vacunas vivas", "hard", "¿Cuál afirmación sobre las vacunas vivas atenuadas es demasiado absoluta?", ["Nunca pueden producir enfermedad en ninguna circunstancia", "Conservan actividad antigénica", "Contienen microorganismos vivos", "Su virulencia está disminuida"], 0, "Aunque son seguras para la población indicada, pueden representar riesgo en huéspedes con inmunodeficiencia grave."),
  mcq("micro-cap19-015", chapter, "Vacunas inactivadas", "easy", "¿Qué caracteriza a una vacuna inactivada?", ["El microorganismo no puede replicarse", "El microorganismo mantiene toda su virulencia", "Contiene exclusivamente anticuerpos", "Genera inmunidad pasiva"], 0, "La inactivación impide la multiplicación, aunque conserva estructuras capaces de ser reconocidas como antígenos."),
  mcq("micro-cap19-016", chapter, "Vacunas inactivadas", "medium", "¿Por qué las vacunas inactivadas suelen requerir varias dosis o refuerzos?", ["La estimulación puede ser menos intensa o duradera que con una vacuna replicativa", "Sus microorganismos recuperan virulencia después de una dosis", "Los anticuerpos administrados desaparecen en horas", "No contienen antígenos reconocibles"], 0, "Al no replicarse, la exposición antigénica suele ser más limitada y puede requerir dosis adicionales."),
  mcq("micro-cap19-017", chapter, "Subunidades", "easy", "Una vacuna formada solo por estructuras seleccionadas de un microorganismo se clasifica como:", ["De subunidades", "Heteróloga", "Antisuero", "Viva no atenuada"], 0, "Las vacunas de subunidades presentan componentes antigénicos específicos sin incluir el microorganismo completo."),
  mcq("micro-cap19-018", chapter, "Recombinantes", "medium", "¿Cómo puede producirse el antígeno de una vacuna recombinante?", ["Expresando mediante ingeniería genética el gen que codifica una proteína antigénica", "Extrayendo anticuerpos del receptor después de vacunarlo", "Activando una toxina antes de administrarla", "Mezclando suero humano con suero equino"], 0, "La tecnología recombinante permite fabricar un antígeno en un sistema productor a partir de su información genética."),
  mcq("micro-cap19-019", chapter, "Toxoides", "easy", "¿Qué contiene una vacuna de toxoide?", ["Una toxina inactivada que conserva antigenicidad", "Una toxina plenamente activa", "Anticuerpos contra todas las bacterias", "Un virus utilizado como vector"], 0, "El toxoide carece de toxicidad funcional, pero puede inducir anticuerpos contra la toxina original."),
  mcq("micro-cap19-020", chapter, "Toxoides", "medium", "La protección de una vacuna de toxoide se dirige principalmente contra:", ["El efecto patógeno de una toxina", "La cápsula de cualquier bacteria", "Todos los antígenos del microorganismo", "La replicación de un vector viral"], 0, "Los anticuerpos inducidos neutralizan la toxina responsable de una parte importante de la enfermedad."),
  mcq("micro-cap19-021", chapter, "Conjugadas", "medium", "¿Qué se une en una vacuna conjugada?", ["Un polisacárido antigénico y una proteína transportadora", "Dos inmunoglobulinas humanas normales", "Una toxina activa y un conservante", "Un virus atenuado y un antibiótico"], 0, "La conjugación enlaza un polisacárido con una proteína que permite una respuesta inmunitaria más eficaz."),
  mcq("micro-cap19-022", chapter, "Conjugadas", "hard", "¿Qué problema busca resolver la conjugación de un polisacárido bacteriano con una proteína?", ["La respuesta débil y con poca memoria frente al polisacárido, especialmente en lactantes", "La replicación excesiva de vacunas vivas", "La degradación de anticuerpos pasivos", "La toxicidad de los vectores virales"], 0, "La proteína transportadora favorece participación de linfocitos T, cambio de clase y memoria frente al polisacárido."),
  mcq("micro-cap19-023", chapter, "Vectores virales", "medium", "¿Qué función cumple el virus modificado en una vacuna de vector viral?", ["Transportar información genética para que células produzcan el antígeno", "Producir anticuerpos fuera del organismo", "Actuar como conservante", "Neutralizar toxinas mediante su cápside"], 0, "El vector lleva la secuencia genética del antígeno a células del receptor para que estas lo expresen."),
  mcq("micro-cap19-024", chapter, "Ácidos nucleicos", "medium", "Una vacuna de ARNm aporta directamente:", ["Instrucciones temporales para producir un antígeno", "Anticuerpos maduros contra el patógeno", "Una toxina inactivada", "Un microorganismo bacteriano completo"], 0, "El ARNm funciona como plantilla transitoria; el receptor produce el antígeno que será reconocido por el sistema inmunitario."),
  mcq("micro-cap19-025", chapter, "Ácidos nucleicos", "hard", "¿Por qué una vacuna de ARNm sigue produciendo inmunización activa?", ["Porque el receptor fabrica el antígeno y desarrolla su propia respuesta inmunitaria", "Porque el ARNm es una inmunoglobulina preformada", "Porque transfiere células de memoria de un donante", "Porque contiene suero heterólogo"], 0, "Aunque la plataforma aporta información genética, la respuesta protectora es generada por el propio receptor."),
  mcq("micro-cap19-026", chapter, "Clasificación", "hard", "¿Cuál asociación entre plataforma y contenido es correcta?", ["Toxoide—toxina sin capacidad tóxica pero antigénica", "Conjugada—anticuerpo unido a un linfocito", "Subunidad—microorganismo vivo con virulencia completa", "Inactivada—anticuerpos obtenidos de plasma"], 0, "El toxoide conserva determinantes antigénicos de la toxina después de eliminar su toxicidad."),

  mcq("micro-cap19-027", chapter, "Administración", "easy", "¿Cuál es una vía frecuente para vacunas como hepatitis B, influenza inactivada o Tdap?", ["Intramuscular", "Conjuntival", "Sublingual", "Intraarterial"], 0, "Muchas vacunas no vivas se administran por vía intramuscular para depositarlas en tejido muscular."),
  mcq("micro-cap19-028", chapter, "Administración", "easy", "¿Qué vacuna constituye un ejemplo clásico de administración intradérmica?", ["BCG", "Rotavirus", "Influenza intranasal", "Poliovirus oral"], 0, "La BCG se administra en la dermis mediante una técnica específica."),
  mcq("micro-cap19-029", chapter, "Administración", "medium", "¿Qué pareja está formada por vacunas administradas por vía oral?", ["Rotavirus y poliovirus oral", "BCG y hepatitis B", "Tdap e influenza inactivada", "Varicela e inmunoglobulina antirrábica"], 0, "Rotavirus y la formulación oral contra poliovirus son ejemplos de vacunación por mucosa digestiva."),
  mcq("micro-cap19-030", chapter, "Administración", "medium", "¿Qué vacuna puede administrarse por vía intranasal en una formulación específica?", ["Influenza viva atenuada", "Toxoide tetánico", "Hepatitis B recombinante", "BCG"], 0, "Existe una formulación viva atenuada contra influenza destinada a la mucosa nasal."),
  mcq("micro-cap19-031", chapter, "Administración", "hard", "¿Por qué no basta con memorizar una sola vía para cada enfermedad?", ["La vía depende de la formulación concreta y de sus indicaciones", "Toda vacuna puede administrarse por cualquier vía", "La vía solo cambia el color del producto", "Las vías no influyen en seguridad ni respuesta"], 0, "Una misma enfermedad puede tener distintas plataformas o formulaciones; siempre debe respetarse la vía autorizada del producto."),
  mcq("micro-cap19-032", chapter, "Administración", "hard", "Administrar una vacuna por una vía diferente de la indicada puede afectar principalmente:", ["Su seguridad y la calidad de la respuesta", "La especie del donante", "La clasificación homóloga o heteróloga", "La existencia del antígeno dentro del vial"], 0, "La técnica y la vía forman parte de las condiciones necesarias para lograr una inmunización segura y eficaz."),

  mcq("micro-cap19-033", chapter, "Componentes", "easy", "¿Qué componente de una vacuna desencadena la respuesta específica?", ["El antígeno o inmunógeno", "El diluyente", "El estabilizante", "El conservante"], 0, "El antígeno contiene los determinantes que serán reconocidos por la respuesta adaptativa."),
  mcq("micro-cap19-034", chapter, "Componentes", "medium", "¿Cuál es la función general de un adyuvante?", ["Potenciar o modular la respuesta frente al antígeno", "Aportar anticuerpos preformados", "Reemplazar siempre al antígeno", "Impedir toda inflamación local"], 0, "Los adyuvantes activan señales innatas y mejoran la magnitud, calidad o persistencia de la respuesta."),
  mcq("micro-cap19-035", chapter, "Componentes", "hard", "¿Qué afirmación sobre los adyuvantes es más precisa?", ["Su acción no se limita a liberar lentamente el antígeno", "Todos son lípidos que destruyen macrófagos", "Convierten cualquier vacuna en inmunización pasiva", "Son obligatorios en todas las vacunas"], 0, "El efecto depósito es una explicación incompleta; los adyuvantes también activan células y señales de la inmunidad innata."),
  mcq("micro-cap19-036", chapter, "Componentes", "easy", "¿Para qué sirve el diluyente de una vacuna liofilizada?", ["Para reconstituir el producto antes de administrarlo", "Para producir memoria por sí mismo", "Para neutralizar toxinas circulantes", "Para sustituir la cadena de frío"], 0, "El diluyente devuelve la formulación a la concentración y volumen adecuados para su uso."),
  mcq("micro-cap19-037", chapter, "Componentes", "medium", "¿Qué componente ayuda a conservar la potencia durante almacenamiento?", ["El estabilizante", "La inmunoglobulina hiperinmune", "El antisuero equino", "La toxina activa"], 0, "Los estabilizantes protegen los componentes de cambios físicos o químicos durante la conservación."),
  mcq("micro-cap19-038", chapter, "Componentes", "medium", "¿Qué función corresponde a un conservante?", ["Reducir el riesgo de contaminación microbiana del producto", "Inducir memoria inmunológica específica", "Transportar genes a células humanas", "Transformar polisacáridos en proteínas"], 0, "Los conservantes se usan especialmente para evitar contaminación en determinadas presentaciones, como algunos viales multidosis."),
  mcq("micro-cap19-039", chapter, "Componentes", "hard", "¿Cuál diferencia correctamente estabilizante de conservante?", ["El estabilizante protege la integridad; el conservante ayuda a evitar contaminación", "El estabilizante es el antígeno; el conservante es siempre un anticuerpo", "Ambos tienen únicamente función adyuvante", "No existe diferencia funcional entre ellos"], 0, "Aunque ambos contribuyen a mantener el producto utilizable, sus objetivos principales son distintos."),
  mcq("micro-cap19-040", chapter, "Componentes", "medium", "Respecto a la composición de las vacunas, es correcto afirmar que:", ["No todas contienen todos los componentes auxiliares", "Todas contienen microorganismos vivos y adyuvantes", "Todas necesitan conservante y diluyente", "Ninguna contiene estabilizantes"], 0, "La formulación depende de la plataforma, presentación y necesidades de conservación."),

  mcq("micro-cap19-041", chapter, "Eficacia", "medium", "¿Cuál es un factor propio de la vacuna que influye en el éxito de la inmunización?", ["Naturaleza y dosis del inmunógeno", "Edad del receptor", "Enfermedad inmunosupresora del huésped", "Adherencia de la comunidad al esquema"], 0, "La plataforma, dosis, estado del antígeno y vía pertenecen a factores inherentes al producto y su administración."),
  mcq("micro-cap19-042", chapter, "Eficacia", "medium", "¿Cuál es un factor propio del huésped?", ["Edad y estado inmunitario", "Cadena de frío del programa", "Número previsto de dosis", "Tipo de adyuvante"], 0, "La edad, genética, nutrición, enfermedades y tratamientos pueden modificar la capacidad de responder."),
  mcq("micro-cap19-043", chapter, "Eficacia", "medium", "¿Qué factor pertenece al programa de vacunación?", ["Cumplir dosis, intervalos y refuerzos indicados", "Secuencia genética del antígeno", "Virulencia del microorganismo original", "Concentración de anticuerpos del donante"], 0, "La ejecución correcta del esquema es esencial para alcanzar la protección esperada."),
  mcq("micro-cap19-044", chapter, "Eficacia", "hard", "Una vacuna eficaz pierde potencia porque fue almacenada incorrectamente. ¿Qué factor falló?", ["La cadena de frío y conservación del programa", "La especificidad de los linfocitos B", "El origen homólogo del producto", "La memoria del donante"], 0, "La conservación inadecuada puede degradar antígenos y reducir la respuesta incluso si la formulación era correcta."),
  mcq("micro-cap19-045", chapter, "Eficacia", "hard", "Dos personas reciben correctamente la misma vacuna, pero una está bajo inmunosupresión intensa. ¿Qué explica una respuesta diferente?", ["Un factor del huésped", "La vía cambió automáticamente", "La vacuna se volvió heteróloga", "El diluyente produjo inmunidad pasiva"], 0, "El estado inmunitario puede disminuir la magnitud de la respuesta y modificar indicaciones o tiempos."),
  mcq("micro-cap19-046", chapter, "Eficacia", "medium", "¿Qué debe hacerse generalmente ante un esquema atrasado?", ["Continuarlo con las dosis faltantes según lineamientos vigentes", "Reiniciarlo siempre desde la primera dosis", "Sustituirlo por suero equino", "Considerarlo completo con una sola dosis"], 0, "Los esquemas incompletos suelen continuarse sin reiniciar, respetando recomendaciones oficiales aplicables."),

  mcq("micro-cap19-047", chapter, "Activa y pasiva", "easy", "¿Qué se administra en la inmunización activa artificial?", ["Un inmunógeno mediante una vacuna", "Anticuerpos preformados", "Células de memoria de un donante", "Suero sin anticuerpos"], 0, "La vacunación presenta antígeno para que el receptor produzca su respuesta."),
  mcq("micro-cap19-048", chapter, "Activa y pasiva", "easy", "¿Qué se administra en la inmunización pasiva artificial?", ["Anticuerpos preformados", "Un antígeno para activar linfocitos vírgenes", "Un adyuvante sin anticuerpos", "Un microorganismo atenuado"], 0, "La protección pasiva proviene de anticuerpos producidos previamente por otra fuente."),
  mcq("micro-cap19-049", chapter, "Activa y pasiva", "medium", "¿Qué ventaja principal tiene la inmunización pasiva?", ["La protección aparece de manera inmediata", "Siempre dura toda la vida", "Produce memoria B y T robusta", "El receptor fabrica los anticuerpos administrados"], 0, "Como los anticuerpos ya están formados, pueden actuar sin esperar el desarrollo de una respuesta primaria."),
  mcq("micro-cap19-050", chapter, "Activa y pasiva", "medium", "¿Qué desventaja caracteriza a la inmunización pasiva?", ["Es temporal y no establece memoria propia", "Necesita semanas para comenzar a actuar", "Siempre causa enfermedad del suero", "No puede neutralizar toxinas"], 0, "Los anticuerpos transferidos se degradan y no equivalen a generar clones de memoria en el receptor."),
  mcq("micro-cap19-051", chapter, "Activa y pasiva", "medium", "¿Qué patrón temporal corresponde a la inmunización activa?", ["Inicio más lento y protección generalmente más prolongada", "Inicio inmediato y desaparición siempre en horas", "Protección sin participación del receptor", "Ausencia completa de memoria"], 0, "La respuesta primaria necesita tiempo para desarrollarse, pero puede dejar células de memoria y protección duradera."),
  mcq("micro-cap19-052", chapter, "Activa y pasiva", "hard", "¿Por qué es incorrecto decir que el suero inmune contiene anticuerpos propios del receptor?", ["Los anticuerpos fueron producidos previamente por otro individuo, animal o sistema", "Porque los sueros solo contienen antígenos", "Porque ningún anticuerpo puede transferirse", "Porque toda inmunización pasiva ocurre por vacuna"], 0, "El receptor recibe anticuerpos ajenos ya preparados; por eso la respuesta no deja memoria propia equivalente."),
  mcq("micro-cap19-053", chapter, "Activa y pasiva", "hard", "¿Cuál comparación es correcta?", ["Vacuna: el cuerpo aprende; inmunoglobulina: recibe anticuerpos temporales", "Vacuna: anticuerpos prestados; inmunoglobulina: memoria propia", "Ambas producen siempre memoria de por vida", "Ambas contienen necesariamente microorganismos vivos"], 0, "La comparación resume quién genera la respuesta y explica las diferencias de rapidez y duración."),
  mcq("micro-cap19-054", chapter, "Activa y pasiva", "hard", "¿En qué situación pueden combinarse protección activa y pasiva?", ["Cuando se necesita cobertura inmediata mientras la vacuna induce una respuesta duradera", "Cuando se desea impedir que el receptor forme memoria", "Cuando toda vacuna está contraindicada por su vía", "Cuando el antígeno carece de cualquier inmunogenicidad"], 0, "En algunas profilaxis posexposición se administran vacuna e inmunoglobulina en sitios distintos para cubrir ambos tiempos."),

  mcq("micro-cap19-055", chapter, "Inmunoglobulinas", "easy", "¿Qué contiene la inmunoglobulina humana normal?", ["Una mezcla amplia de anticuerpos procedentes de plasma humano combinado", "Un solo anticuerpo producido por un caballo", "Microorganismos vivos atenuados", "Toxinas bacterianas activas"], 0, "Se prepara a partir de grupos de donantes y contiene un repertorio de anticuerpos comunes en la población."),
  mcq("micro-cap19-056", chapter, "Inmunoglobulinas", "medium", "¿Qué distingue a una inmunoglobulina específica o hiperinmune?", ["Posee títulos altos contra un agente o antígeno concreto", "Carece por completo de IgG", "Contiene siempre proteínas animales", "Induce memoria como una vacuna viva"], 0, "Los donantes se seleccionan por concentraciones elevadas del anticuerpo buscado."),
  mcq("micro-cap19-057", chapter, "Inmunoglobulinas", "medium", "¿Cuál es un ejemplo de inmunoglobulina humana específica?", ["Inmunoglobulina contra hepatitis B", "Vacuna recombinante contra hepatitis B", "Toxoide diftérico", "Vacuna BCG"], 0, "La HBIG aporta anti-HBs preformado para situaciones concretas de profilaxis posexposición."),
  mcq("micro-cap19-058", chapter, "Inmunoglobulinas", "medium", "¿Cuál pareja contiene preparaciones humanas específicas de inmunización pasiva?", ["Inmunoglobulina antirrábica e inmunoglobulina antitetánica", "BCG y vacuna oral contra poliovirus", "Toxoide diftérico y vacuna conjugada", "Vacuna de ARNm y vector viral"], 0, "RIG y TIG aportan anticuerpos específicos ya formados contra rabia y toxina tetánica, respectivamente."),
  mcq("micro-cap19-059", chapter, "Sueros inmunes", "easy", "¿Qué es un suero inmune en el contexto de la hoja?", ["Una preparación con anticuerpos preformados contra un blanco determinado", "Una vacuna formada por ácidos nucleicos", "Un adyuvante sin antígeno", "Una suspensión de leucocitos del receptor"], 0, "Su finalidad es proporcionar protección pasiva inmediata mediante anticuerpos ya producidos."),
  mcq("micro-cap19-060", chapter, "Sueros inmunes", "medium", "¿Cuál secuencia resume la producción clásica de un antisuero heterólogo?", ["Inmunizar un animal, obtener plasma o suero y purificar los anticuerpos", "Vacunar al paciente, extraer sus anticuerpos y devolvérselos", "Inactivar todos los anticuerpos y administrar el antígeno", "Mezclar un toxoide con una vacuna de ARNm"], 0, "Animales como el caballo pueden desarrollar títulos altos; después se recolecta y procesa la fracción de anticuerpos."),
  mcq("micro-cap19-061", chapter, "Homólogos y heterólogos", "medium", "¿Qué significa que un producto pasivo sea homólogo?", ["Que procede de seres humanos, la misma especie del receptor", "Que procede obligatoriamente de caballos", "Que contiene un microorganismo idéntico al patógeno", "Que induce anticuerpos propios sin administrarlos"], 0, "Los productos homólogos humanos suelen persistir más y provocar menos reacciones contra proteínas extrañas."),
  mcq("micro-cap19-062", chapter, "Homólogos y heterólogos", "medium", "¿Qué ventaja productiva ofrecen los antisueros heterólogos?", ["Permiten obtener grandes cantidades de anticuerpos usando animales grandes", "Generan memoria permanente en el receptor", "Eliminan todo riesgo de hipersensibilidad", "Permanecen siempre más que las inmunoglobulinas humanas"], 0, "La producción animal facilita disponer de volúmenes importantes frente a ciertos blancos, como toxinas."),
  mcq("micro-cap19-063", chapter, "Homólogos y heterólogos", "hard", "¿Qué limitación es más característica de un antisuero de origen animal?", ["Riesgo de hipersensibilidad y enfermedad del suero", "Incapacidad absoluta de neutralizar toxinas", "Inducción inevitable de memoria B", "Ausencia de proteínas reconocibles"], 0, "Las proteínas heterólogas pueden ser reconocidas como extrañas y producir reacciones inmediatas o tardías."),
  mcq("micro-cap19-064", chapter, "Homólogos y heterólogos", "hard", "¿Cuál comparación es correcta?", ["El producto humano suele persistir más; el animal suele eliminarse antes y ser más reactogénico", "El producto animal siempre dura años; el humano solo horas", "Solo el producto animal proporciona protección inmediata", "Solo el producto humano contiene anticuerpos"], 0, "Ambos aportan anticuerpos, pero difieren en permanencia y riesgo de respuesta contra proteínas extrañas."),
  mcq("micro-cap19-065", chapter, "Uso clínico", "medium", "¿Cuándo resulta especialmente útil la inmunización pasiva?", ["Después de una exposición cuando no hay tiempo para esperar una respuesta activa", "Para sustituir todos los esquemas regulares", "Para crear memoria inmunológica de por vida", "Antes de toda vacunación infantil sin evaluar riesgo"], 0, "Los anticuerpos preformados se reservan para indicaciones en las que la protección inmediata aporta beneficio."),
  mcq("micro-cap19-066", chapter, "Uso clínico", "medium", "¿Qué producto se orienta directamente a neutralizar una toxina bacteriana ya presente?", ["Una antitoxina", "Un diluyente", "Una vacuna conjugada sin anticuerpos", "Un estabilizante"], 0, "Las antitoxinas contienen anticuerpos capaces de unirse a la toxina y limitar su acción."),

  mcq("micro-cap19-067", chapter, "Situaciones especiales", "medium", "¿Qué principio debe aplicarse a la vacunación durante el embarazo?", ["Evaluar cada producto e indicación y evitar generalmente las vacunas vivas", "Suspender todas las vacunas e inmunoglobulinas", "Administrar únicamente vacunas vivas", "Usar siempre antisueros equinos en lugar de vacunas"], 0, "El embarazo no contraindica toda inmunización; la decisión depende de la plataforma, riesgo y lineamientos vigentes."),
  mcq("micro-cap19-068", chapter, "Situaciones especiales", "medium", "¿Por qué el personal de salud puede requerir vacunación específica?", ["Por exposición ocupacional a sangre, fluidos o agentes infecciosos", "Porque no desarrolla inmunidad activa", "Porque toda vacuna dura menos en esa profesión", "Porque solo puede recibir productos heterólogos"], 0, "La indicación se ajusta al tipo de exposición previsible, como el riesgo de hepatitis B por contacto con sangre."),
  mcq("micro-cap19-069", chapter, "Situaciones especiales", "medium", "¿Qué determina las vacunas adicionales de un viajero?", ["El destino, riesgo de exposición y requisitos o recomendaciones vigentes", "Únicamente su preferencia por una vía", "El color de la tarjeta de vacunación", "La disponibilidad de sueros animales"], 0, "La epidemiología del destino, duración y actividades del viaje orientan las recomendaciones."),
  mcq("micro-cap19-070", chapter, "Situaciones especiales", "hard", "Durante un brote, una campaña de vacunación busca principalmente:", ["Reducir susceptibles y limitar transmisión o enfermedad", "Transformar inmunidad activa en pasiva", "Reemplazar toda vigilancia epidemiológica", "Administrar únicamente inmunoglobulina normal"], 0, "La vacunación dirigida puede aumentar rápidamente la protección de la población en riesgo."),
  mcq("micro-cap19-071", chapter, "Situaciones especiales", "hard", "Una persona con enfermedad crónica o alteración del bazo necesita una decisión de vacunación. ¿Qué es lo más correcto?", ["Aplicar recomendaciones específicas según su condición y el esquema vigente", "Omitir automáticamente todas las vacunas", "Administrar cualquier vacuna viva sin evaluación", "Usar el calendario de otro país sin modificaciones"], 0, "Las condiciones de riesgo pueden justificar vacunas adicionales, pero las indicaciones deben seguir lineamientos nacionales actuales."),
  mcq("micro-cap19-072", chapter, "Situaciones especiales", "medium", "Si un libro reproduce un calendario antiguo de otro país, ¿cómo debe usarse para una tarea en Guatemala?", ["Como base conceptual, verificando indicaciones concretas con el MSPAS vigente", "Como autoridad definitiva sin revisar fecha", "Descartando también todos sus conceptos inmunológicos", "Sustituyendo las vacunas por sueros"], 0, "Los conceptos pueden ser útiles, pero edades, dosis y grupos especiales cambian por país y con el tiempo."),

  mcq("micro-cap19-073", chapter, "Integración", "hard", "Una persona no vacunada sufre una exposición de alto riesgo y necesita protección inmediata y futura. ¿Qué estrategia conceptual cubre ambos objetivos cuando está indicada?", ["Inmunoglobulina para protección inmediata y vacuna para respuesta activa", "Dos estabilizantes administrados por vías distintas", "Solo un diluyente seguido de un conservante", "Una vacuna conjugada y suspensión de todo seguimiento"], 0, "La combinación aporta anticuerpos de acción inmediata mientras el receptor desarrolla inmunidad activa."),
  mcq("micro-cap19-074", chapter, "Integración", "hard", "Un lactante responde pobremente a un polisacárido bacteriano aislado. ¿Qué plataforma mejora la respuesta?", ["Vacuna conjugada con una proteína transportadora", "Antisuero heterólogo sin antígeno", "Toxina bacteriana activa", "Diluyente sin inmunógeno"], 0, "La conjugación recluta ayuda de linfocitos T y favorece una respuesta más eficaz y con memoria."),
  mcq("micro-cap19-075", chapter, "Integración", "hard", "Una vacuna conserva su antígeno, pero genera una respuesta débil en adultos sanos. ¿Qué componente podría añadirse para mejorarla?", ["Un adyuvante apropiado", "Una toxina activa", "Un anticuerpo que elimine el antígeno antes de presentarse", "Suero animal sin purificar"], 0, "Los adyuvantes se seleccionan para potenciar o dirigir la respuesta al inmunógeno."),
  mcq("micro-cap19-076", chapter, "Integración", "hard", "Una persona recibe anticuerpos y queda protegida de inmediato, pero meses después no conserva memoria. ¿Qué ocurrió?", ["Inmunización pasiva", "Vacunación viva atenuada", "Respuesta secundaria activa", "Inmunización por toxoide"], 0, "La rapidez unida a temporalidad y ausencia de memoria identifica transferencia pasiva de anticuerpos."),
  mcq("micro-cap19-077", chapter, "Integración", "hard", "Tras una vacuna, se detectan células B y T de memoria. ¿Qué conclusión es correcta?", ["El receptor desarrolló inmunidad activa", "Solo recibió un antisuero heterólogo", "Los anticuerpos fueron fabricados por un caballo", "La protección necesariamente desaparecerá en días"], 0, "La formación de memoria propia es una característica central de la respuesta activa."),
  mcq("micro-cap19-078", chapter, "Integración", "hard", "¿Cuál explicación integra mejor vacunas e inmunoglobulinas?", ["Son herramientas distintas: una induce respuesta propia y la otra transfiere anticuerpos", "Ambas son vacunas porque contienen siempre antígeno", "Ambas producen memoria con idéntica duración", "Las inmunoglobulinas actúan más lento que las vacunas"], 0, "La inmunización activa y la pasiva pueden ser complementarias, pero difieren en contenido, mecanismo, rapidez y duración."),
]

// Mantiene una distribución uniforme de la clave correcta entre A, B, C y D
// aunque las opciones no se barajen durante una sesión.
export const cap19Questions = cap19QuestionsInSourceOrder.map((question, index) => {
  const shift = index % question.options.length
  const options = [
    ...question.options.slice(shift),
    ...question.options.slice(0, shift)
  ]

  return {
    ...question,
    options,
    correctAnswers: [
      (question.correctAnswers[0] - shift + question.options.length) % question.options.length
    ]
  }
})
