export type BioquimicaQuestion = {
  id: string
  chapter: string
  topic: string
  tags: string[]
  difficulty: "easy" | "medium" | "hard"
  type: "single"
  question: string
  options: string[]
  correctAnswers: number[]
  explanation: string
}

type Row = readonly [
  topic: string,
  difficulty: BioquimicaQuestion["difficulty"],
  question: string,
  correct: string,
  distractor1: string,
  distractor2: string,
  distractor3: string,
  explanation: string
]

const coreRows: readonly Row[] = [
  ["Glucólisis", "medium", "Una célula necesita captar glucosa y evitar que vuelva a salir por su transportador. ¿Qué transformación logra ese efecto?", "Glucosa a glucosa-6-fosfato por hexoquinasa.", "Glucosa-6-fosfato a fructosa-6-fosfato por fosfoglucosa isomerasa.", "Fructosa-6-fosfato a fructosa-1,6-bisfosfato por PFK-1.", "Fosfoenolpiruvato a piruvato por piruvato quinasa.", "La primera fosforilación atrapa la glucosa como glucosa-6-fosfato dentro de la célula."],
  ["Glucólisis", "hard", "¿Qué combinación de señales favorece que disminuya el flujo glucolítico?", "ATP y citrato elevados.", "AMP y fructosa-2,6-bisfosfato elevados.", "Insulina y fructosa-2,6-bisfosfato elevadas.", "ADP y fosfato inorgánico elevados.", "ATP y citrato señalan abundancia energética e inhiben sobre todo a PFK-1."],
  ["Glucólisis", "medium", "¿Cuál reacción corresponde a una fosforilación a nivel de sustrato de la glucólisis?", "1,3-bisfosfoglicerato a 3-fosfoglicerato.", "Glucosa a glucosa-6-fosfato.", "Fructosa-6-fosfato a fructosa-1,6-bisfosfato.", "Gliceraldehído-3-fosfato a 1,3-bisfosfoglicerato.", "La fosfoglicerato quinasa transfiere un fosfato de alta energía al ADP."],
  ["Glucólisis", "hard", "Si no se reoxida el NADH producido en glucólisis, ¿qué consecuencia inmediata ocurre?", "Se agota el NAD+ y se detiene la oxidación de gliceraldehído-3-fosfato.", "Se bloquea la formación de glucosa-6-fosfato por hexoquinasa.", "Se acumula oxaloacetato dentro de la matriz mitocondrial.", "Se inactiva la glucógeno sintasa por desfosforilación.", "La gliceraldehído-3-fosfato deshidrogenasa necesita NAD+; sin reciclarlo, la vía no puede continuar."],
  ["Glucólisis", "medium", "¿Qué destino del piruvato regenera NAD+ en condiciones anaerobias humanas?", "Su reducción a lactato.", "Su oxidación a acetil-CoA.", "Su carboxilación a oxaloacetato.", "Su conversión directa a citrato.", "La lactato deshidrogenasa reduce piruvato y oxida NADH a NAD+."],
  ["Glucólisis", "hard", "¿Cuál enzima se asocia de manera correcta con la reacción que cataliza?", "Aldolasa: fructosa-1,6-bisfosfato a dos triosas fosfato.", "PFK-1: glucosa a glucosa-6-fosfato.", "Piruvato quinasa: 1,3-bisfosfoglicerato a 3-fosfoglicerato.", "Fosfoglicerato quinasa: fosfoenolpiruvato a piruvato.", "La aldolasa escinde la hexosa fosforilada en gliceraldehído-3-fosfato y dihidroxiacetona fosfato."],
  ["Glucólisis", "easy", "¿Cuál es el rendimiento neto de ATP de la glucólisis por una glucosa?", "2 ATP netos.", "0 ATP netos.", "4 ATP netos.", "6 ATP netos.", "Se producen cuatro ATP, pero se invierten dos en las reacciones iniciales."],
  ["Glucólisis", "medium", "En hígado, ¿qué enzima fosforila glucosa y se conoce como hexoquinasa IV?", "Glucoquinasa.", "Fosfoglucosa isomerasa.", "Glucosa-6-fosfatasa.", "Glucógeno fosforilasa.", "La glucoquinasa es la isoenzima hepática que fosforila glucosa."],
  ["Glucólisis", "hard", "Un eritrocito aumenta 2,3-BPG en hipoxia. ¿Qué efecto favorece?", "Liberación de oxígeno desde hemoglobina hacia los tejidos.", "Mayor afinidad de hemoglobina por oxígeno en el pulmón.", "Conversión de lactato a piruvato en la mitocondria.", "Producción de acetil-CoA para Krebs.", "El 2,3-BPG disminuye la afinidad de la hemoglobina por oxígeno y desplaza la curva a la derecha."],
  ["Glucólisis", "medium", "¿Qué lanzadera entrega los electrones del NADH citosólico directamente a coenzima Q y por ello rinde menos ATP?", "La lanzadera glicerol-3-fosfato.", "La lanzadera malato-aspartato.", "El ciclo de Cori.", "El ciclo glucosa-alanina.", "La lanzadera glicerol-3-fosfato transfiere electrones a FAD y luego a coenzima Q."],

  ["Ciclo de Krebs", "easy", "¿En qué compartimento ocurre el ciclo de Krebs?", "Matriz mitocondrial.", "Citosol.", "Espacio intermembrana.", "Retículo endoplásmico liso.", "Las enzimas del ciclo se encuentran principalmente en la matriz mitocondrial."],
  ["Ciclo de Krebs", "medium", "¿Qué par de sustratos se condensa al inicio del ciclo de Krebs?", "Oxaloacetato y acetil-CoA.", "Piruvato y lactato.", "Succinato y fumarato.", "Citrato y alfa-cetoglutarato.", "La citrato sintasa une oxaloacetato con acetil-CoA para formar citrato."],
  ["Ciclo de Krebs", "hard", "¿Qué perfil se obtiene por cada acetil-CoA oxidado en el ciclo de Krebs?", "3 NADH, 1 FADH₂, 1 GTP y 2 CO₂.", "2 NADH, 2 FADH₂, 2 ATP y 1 CO₂.", "4 NADH, 1 FADH₂, 2 GTP y 0 CO₂.", "1 NADH, 3 FADH₂, 2 ATP y 2 CO₂.", "Una vuelta libera dos carbonos como CO₂ y conserva energía en tres NADH, un FADH₂ y un GTP."],
  ["Ciclo de Krebs", "medium", "¿Cuál reacción genera GTP por fosforilación a nivel de sustrato?", "Succinil-CoA a succinato.", "Citrato a isocitrato.", "Succinato a fumarato.", "Malato a oxaloacetato.", "La succinil-CoA sintetasa forma GTP al convertir succinil-CoA en succinato."],
  ["Ciclo de Krebs", "hard", "¿Cuál conjunto contiene solo enzimas reguladoras irreversibles del ciclo?", "Citrato sintasa, isocitrato deshidrogenasa y alfa-cetoglutarato deshidrogenasa.", "Aconitasa, fumarasa y malato deshidrogenasa.", "Succinato deshidrogenasa, fumarasa y citrato sintasa.", "Piruvato carboxilasa, PEPCK y fructosa-1,6-bisfosfatasa.", "Las tres enzimas indicadas son los principales puntos de control irreversibles del ciclo."],
  ["Ciclo de Krebs", "medium", "Durante contracción muscular, ¿qué ion activa enzimas del ciclo de Krebs?", "Calcio.", "Sodio.", "Cloruro.", "Bicarbonato.", "El Ca²⁺ vincula el aumento de demanda contráctil con mayor producción de energía."],
  ["Ciclo de Krebs", "hard", "¿Por qué concentraciones altas de NADH inhiben el ciclo de Krebs?", "Porque indican abundancia de poder reductor y frenan deshidrogenasas clave.", "Porque convierten acetil-CoA en glucosa directamente.", "Porque abren los canales de protones de la ATP sintasa.", "Porque activan la glucógeno fosforilasa.", "El exceso de NADH limita reacciones oxidativas y señala que la célula no necesita más energía."],
  ["Ciclo de Krebs", "hard", "Una célula extrae oxaloacetato para gluconeogénesis. ¿Qué reacción ayuda a mantener el ciclo?", "Piruvato a oxaloacetato por piruvato carboxilasa.", "Acetil-CoA a piruvato por piruvato deshidrogenasa.", "Citrato a acetil-CoA por ATP citrato liasa.", "Lactato a piruvato por lactato deshidrogenasa.", "La carboxilación de piruvato repone oxaloacetato y es una reacción anaplerótica."],
  ["Ciclo de Krebs", "medium", "¿Por qué el ciclo de Krebs depende funcionalmente del oxígeno aunque no lo consuma de forma directa?", "Porque necesita reoxidar NADH y FADH₂ en la cadena respiratoria.", "Porque el oxígeno se incorpora al citrato.", "Porque el oxígeno activa directamente a citrato sintasa.", "Porque el oxígeno forma glucosa-6-fosfato.", "Sin oxígeno, la cadena no reoxida coenzimas reducidas y el ciclo se frena."],
  ["Ciclo de Krebs", "easy", "¿Cuántas vueltas del ciclo de Krebs siguen a la oxidación de una glucosa?", "Dos vueltas.", "Una vuelta.", "Tres vueltas.", "Seis vueltas.", "Una glucosa origina dos piruvatos y, después de su conversión, dos acetil-CoA."],

  ["Cadena respiratoria", "easy", "¿Dónde se localiza la cadena transportadora de electrones?", "En la membrana mitocondrial interna.", "En la membrana mitocondrial externa.", "En el citosol.", "En la matriz nuclear.", "Los complejos respiratorios son proteínas de la membrana mitocondrial interna."],
  ["Cadena respiratoria", "medium", "¿Cuál es el aceptor final de electrones de la cadena respiratoria?", "Oxígeno.", "NAD+.", "Coenzima Q.", "ATP.", "El oxígeno acepta electrones y protones para formar agua."],
  ["Cadena respiratoria", "hard", "¿Qué ruta sigue correctamente un electrón proveniente de NADH?", "Complejo I → coenzima Q → complejo III → citocromo c → complejo IV.", "Complejo II → citocromo c → complejo I → complejo IV.", "Complejo I → ATP sintasa → coenzima Q → oxígeno.", "Complejo IV → coenzima Q → complejo III → oxígeno.", "NADH entra por complejo I; coenzima Q y citocromo c son los transportadores móviles intermedios."],
  ["Cadena respiratoria", "hard", "¿Cuál afirmación distingue correctamente el ingreso de FADH₂?", "Entra por complejo II y no provoca bombeo de protones en ese complejo.", "Entra por complejo I y bombea cuatro protones allí.", "Entra directamente por complejo IV y forma agua.", "Entra por ATP sintasa y genera GTP.", "El complejo II recibe electrones de FADH₂, pero no bombea protones."],
  ["Cadena respiratoria", "medium", "¿Qué complejos bombean protones hacia el espacio intermembrana?", "I, III y IV.", "I, II y III.", "II, III y ATP sintasa.", "I, II y IV.", "El complejo II no bombea protones; el bombeo ocurre en I, III y IV."],
  ["Cadena respiratoria", "medium", "¿Qué componente usa directamente el retorno de protones para fosforilar ADP?", "ATP sintasa.", "Citrato sintasa.", "Piruvato carboxilasa.", "Glucógeno sintasa.", "El flujo de H+ por la ATP sintasa impulsa la formación de ATP en la matriz."],
  ["Cadena respiratoria", "hard", "¿Qué localización de la ATP sintasa es correcta?", "F₀ en membrana interna y F₁ orientada hacia la matriz.", "F₀ en matriz y F₁ en espacio intermembrana.", "F₀ en membrana externa y F₁ en citosol.", "Ambas subunidades libres en la matriz.", "F₀ forma el canal de protones en la membrana y F₁ contiene el sitio catalítico matricial."],
  ["Cadena respiratoria", "hard", "Un tóxico bloquea el complejo IV. ¿Cuál es la consecuencia primaria?", "No se reduce oxígeno a agua y se detiene el flujo electrónico.", "No se forma citrato a partir de acetil-CoA.", "No se convierte glucosa-6-fosfato en fructosa-6-fosfato.", "No se desramifica glucógeno.", "El complejo IV entrega electrones al oxígeno; bloquearlo paraliza la cadena."],
  ["Cadena respiratoria", "medium", "¿Cuál es el rendimiento aproximado por NADH mitocondrial y por FADH₂?", "2.5 ATP y 1.5 ATP, respectivamente.", "1.5 ATP y 2.5 ATP, respectivamente.", "3 ATP y 2 ATP, respectivamente.", "2 ATP y 4 ATP, respectivamente.", "NADH bombea más protones que FADH₂, por lo que su rendimiento es mayor."],
  ["Cadena respiratoria", "hard", "¿Cuál lanzadera permite que el NADH citosólico conserve un rendimiento comparable al NADH mitocondrial?", "Malato-aspartato.", "Glicerol-3-fosfato.", "Cori.", "Glucosa-alanina.", "La lanzadera malato-aspartato transfiere los equivalentes reductores a NAD+ de la matriz."],

  ["Metabolismo del glucógeno", "easy", "¿Qué hormona favorece la glucogenogénesis después de comer?", "Insulina.", "Glucagón.", "Adrenalina.", "Cortisol.", "La insulina favorece el almacenamiento de glucosa como glucógeno."],
  ["Metabolismo del glucógeno", "medium", "¿Qué enzima libera glucosa-1-fosfato al romper enlaces alfa-1,4 del glucógeno?", "Glucógeno fosforilasa.", "Glucógeno sintasa.", "Enzima ramificante.", "Glucosa-6-fosfatasa.", "La glucógeno fosforilasa realiza fosforólisis de enlaces alfa-1,4."],
  ["Metabolismo del glucógeno", "medium", "¿Qué función diferencia a la enzima ramificante de glucógeno sintasa?", "La ramificante crea enlaces alfa-1,6.", "La ramificante rompe enlaces alfa-1,4.", "La ramificante convierte glucosa-6-fosfato en glucosa.", "La ramificante libera glucosa-1-fosfato.", "La glucógeno sintasa alarga cadenas alfa-1,4; la ramificante introduce puntos alfa-1,6."],
  ["Metabolismo del glucógeno", "hard", "En una rama límite de glucógeno, ¿qué actividad elimina el residuo unido por alfa-1,6?", "Alfa-1,6-glucosidasa de la enzima desramificante.", "Glucógeno fosforilasa.", "Fosfoglucomutasa.", "Glucoquinasa.", "La actividad glucosidasa hidroliza el enlace alfa-1,6 del residuo restante."],
  ["Metabolismo del glucógeno", "hard", "¿Qué estado covalente activa a la glucógeno fosforilasa?", "Fosforilado.", "Desfosforilado.", "Acetilado.", "Glucosilado.", "La fosforilasa se activa con fosforilación en respuesta a señales de movilización energética."],
  ["Metabolismo del glucógeno", "hard", "¿Qué estado covalente activa a la glucógeno sintasa?", "Desfosforilado.", "Fosforilado.", "Oxidado.", "Carboxilado.", "La insulina favorece su desfosforilación y activa la síntesis de glucógeno."],
  ["Metabolismo del glucógeno", "medium", "¿Qué combinación inhibe la glucógeno fosforilasa muscular?", "ATP y glucosa-6-fosfato elevados.", "AMP y calcio elevados.", "Glucagón y adrenalina elevados.", "Fosforilación y AMP elevados.", "ATP y G6P señalan suficiente energía y reducen la necesidad de glucogenólisis."],
  ["Metabolismo del glucógeno", "hard", "¿Por qué el glucógeno muscular no puede mantener directamente la glucemia?", "El músculo no tiene glucosa-6-fosfatasa.", "El músculo no tiene glucógeno fosforilasa.", "El músculo no puede fosforilar glucosa.", "El músculo no forma enlaces alfa-1,4.", "Sin glucosa-6-fosfatasa, el músculo no puede convertir G6P en glucosa libre exportable."],
  ["Metabolismo del glucógeno", "medium", "¿Qué proteína permite iniciar una cadena de glucógeno cuando no existe un cebador?", "Glucogenina.", "Glucagón.", "Glucosa-6-fosfatasa.", "Fosfofructoquinasa-1.", "La glucogenina se autoglucosila y crea el oligosacárido inicial para glucógeno sintasa."],
  ["Metabolismo del glucógeno", "medium", "¿En qué situación aumenta más la glucogenólisis hepática?", "Ayuno entre comidas.", "Después de una comida rica en carbohidratos.", "Durante aumento de insulina posprandial.", "Cuando glucosa-6-fosfato hepática es muy elevada.", "En ayuno, el hígado degrada glucógeno para ayudar a mantener la glucosa sanguínea."],

  ["Gluconeogénesis", "easy", "¿Cuál es la función principal de la gluconeogénesis?", "Formar glucosa a partir de precursores no glucídicos.", "Formar glucógeno a partir de glucosa.", "Convertir glucosa en piruvato.", "Oxidar acetil-CoA a CO₂.", "La gluconeogénesis aporta glucosa cuando su disponibilidad dietaria o del glucógeno disminuye."],
  ["Gluconeogénesis", "medium", "¿Cuál combinación contiene solo precursores gluconeogénicos?", "Lactato, glicerol y alanina.", "Acetil-CoA, colesterol y leucina.", "Ácidos grasos de cadena par y cuerpos cetónicos.", "Citrato, oxígeno y ATP.", "Lactato, glicerol y aminoácidos glucogénicos pueden aportar carbonos para glucosa."],
  ["Gluconeogénesis", "hard", "¿Qué enzima inicia el bypass de piruvato quinasa durante gluconeogénesis?", "Piruvato carboxilasa.", "PEP carboxiquinasa.", "Fructosa-1,6-bisfosfatasa.", "Glucosa-6-fosfatasa.", "La piruvato carboxilasa transforma piruvato en oxaloacetato en la matriz mitocondrial."],
  ["Gluconeogénesis", "hard", "¿Qué metabolito activa piruvato carboxilasa y favorece la gluconeogénesis?", "Acetil-CoA.", "Fructosa-2,6-bisfosfato.", "AMP.", "ADP.", "Acetil-CoA alto indica abundancia de energía y activa el primer bypass gluconeogénico."],
  ["Gluconeogénesis", "medium", "¿Qué enzima convierte oxaloacetato en fosfoenolpiruvato?", "PEP carboxiquinasa.", "Piruvato quinasa.", "Aldolasa.", "Glucógeno fosforilasa.", "La PEPCK usa energía para convertir oxaloacetato en fosfoenolpiruvato."],
  ["Gluconeogénesis", "hard", "¿Qué señal inhibe fructosa-1,6-bisfosfatasa?", "AMP elevado.", "Citrato elevado.", "ATP elevado.", "Acetil-CoA elevado.", "AMP bajo señala déficit energético, por lo que evita gastar energía formando glucosa."],
  ["Gluconeogénesis", "medium", "¿Qué ciclo lleva lactato al hígado para regenerar glucosa?", "Ciclo de Cori.", "Ciclo de la urea.", "Ciclo de Krebs.", "Ciclo de la carnitina.", "El lactato periférico llega al hígado, se convierte en piruvato y luego puede usarse para gluconeogénesis."],
  ["Gluconeogénesis", "medium", "¿Qué ciclo permite transportar alanina y nitrógeno desde músculo a hígado?", "Ciclo glucosa-alanina.", "Ciclo de Cori.", "Lanzadera malato-aspartato.", "Ciclo de pentosas.", "La alanina lleva el esqueleto carbonado y nitrógeno al hígado."],
  ["Gluconeogénesis", "hard", "¿Dónde se localiza la glucosa-6-fosfatasa y cuál es su función?", "En el retículo endoplásmico; libera glucosa desde glucosa-6-fosfato.", "En la matriz; convierte piruvato en oxaloacetato.", "En citosol; convierte glucosa en glucosa-6-fosfato.", "En membrana interna; bombea protones.", "La glucosa-6-fosfatasa permite al hígado y riñón exportar glucosa libre."],
  ["Gluconeogénesis", "medium", "¿Qué hormonas favorecen gluconeogénesis hepática?", "Glucagón, adrenalina y cortisol.", "Insulina, leptina y prolactina.", "Insulina, glucagón y somatostatina por igual.", "Solo hormona del crecimiento.", "Estas hormonas predominan en ayuno o estrés y favorecen la producción hepática de glucosa."],

  ["Vía de las pentosas", "easy", "¿Qué dos productos principales aporta la vía de las pentosas fosfato?", "NADPH y ribosa-5-fosfato.", "NADH y acetil-CoA.", "FADH₂ y oxaloacetato.", "ATP y lactato.", "La ruta aporta poder reductor como NADPH y pentosas para biosíntesis de nucleótidos."],
  ["Vía de las pentosas", "medium", "¿Cuál fase es irreversible y genera NADPH?", "La fase oxidativa.", "La fase no oxidativa.", "La fase de glucogenólisis.", "La fase de beta oxidación.", "La fase oxidativa convierte G6P y produce NADPH, CO₂ y ribulosa-5-fosfato."],
  ["Vía de las pentosas", "medium", "¿Cuál enzima controla la entrada a la fase oxidativa de la vía de las pentosas?", "Glucosa-6-fosfato deshidrogenasa.", "Glucosa-6-fosfatasa.", "Fosfofructoquinasa-1.", "Piruvato carboxilasa.", "G6PD es la enzima reguladora y fuente inicial de NADPH en la ruta."],
  ["Vía de las pentosas", "hard", "¿Cuál descripción de los productos de la fase oxidativa es correcta?", "NADPH, CO₂ y ribulosa-5-fosfato.", "ATP, lactato y NADH.", "FADH₂, succinato y CO₂.", "Glucógeno, UDP-glucosa y NADPH.", "La ribulosa-5-fosfato puede luego isomerizarse a ribosa-5-fosfato."],
  ["Vía de las pentosas", "medium", "¿Qué función de NADPH protege especialmente a los eritrocitos?", "Regenerar glutatión reducido contra oxidantes.", "Formar ATP mediante ATP sintasa.", "Convertir glucosa-6-fosfato en glucosa libre.", "Transportar oxígeno con hemoglobina.", "NADPH mantiene glutatión reducido, esencial para neutralizar peróxidos en eritrocitos."],
  ["Vía de las pentosas", "hard", "¿Qué explica la anemia hemolítica por deficiencia de G6PD?", "Menor NADPH deja al eritrocito vulnerable al estrés oxidativo.", "Exceso de NADH bloquea directamente la hemoglobina.", "Falta de FADH₂ impide el ciclo de Krebs.", "Exceso de ribosa-5-fosfato destruye la membrana.", "Sin G6PD se reduce NADPH y no se mantiene suficiente glutatión reducido."],
  ["Vía de las pentosas", "medium", "¿Cuál proceso biosintético necesita NADPH?", "Síntesis de ácidos grasos.", "Glucólisis hasta piruvato.", "Fosforilación a nivel de sustrato.", "Conversión de succinil-CoA a succinato.", "NADPH dona electrones para biosíntesis reductora, como síntesis de ácidos grasos."],
  ["Vía de las pentosas", "medium", "¿Cuál producto requiere ribosa-5-fosfato como precursor?", "Nucleótidos.", "Triglicéridos exclusivamente.", "Glucógeno muscular.", "Lactato.", "La ribosa-5-fosfato aporta el azúcar de nucleótidos y ácidos nucleicos."],
  ["Vía de las pentosas", "hard", "Una célula necesita ribosa-5-fosfato pero no necesita NADPH. ¿Qué estrategia es adecuada?", "Usar la fase no oxidativa para formar ribosa-5-fosfato desde intermediarios glucolíticos.", "Usar solo la fase oxidativa y desechar NADPH.", "Activar glucógeno fosforilasa y detener transquetolasa.", "Inhibir por completo la interconversión de azúcares.", "La fase no oxidativa reversible ajusta carbonos según la necesidad de ribosa o energía."],
  ["Vía de las pentosas", "hard", "Una célula necesita NADPH pero no ribosa-5-fosfato. ¿Qué combinación permite reciclar los carbonos?", "Fases oxidativa y no oxidativa.", "Solo gluconeogénesis.", "Solo glucogenólisis.", "Solo fase oxidativa sin reordenamiento de carbonos.", "La fase oxidativa produce NADPH y la no oxidativa devuelve carbonos a intermediarios glucolíticos."],
]

const extensionRows: readonly Row[] = [
  ["Glucólisis", "medium", "¿Qué paso de la glucólisis consume ATP y corresponde al compromiso de la glucosa con la vía?", "Fructosa-6-fosfato a fructosa-1,6-bisfosfato por PFK-1.", "Glucosa a glucosa-6-fosfato por hexoquinasa.", "1,3-bisfosfoglicerato a 3-fosfoglicerato por fosfoglicerato quinasa.", "Fosfoenolpiruvato a piruvato por piruvato quinasa.", "PFK-1 cataliza el paso comprometido e irreversible de la glucólisis."],
  ["Glucólisis", "hard", "En hígado, ¿qué cambio favorece glucólisis después de una comida rica en carbohidratos?", "Aumento de fructosa-2,6-bisfosfato que activa PFK-1.", "Disminución de fructosa-2,6-bisfosfato que activa fructosa-1,6-bisfosfatasa.", "Activación de glucosa-6-fosfatasa por insulina.", "Fosforilación de piruvato quinasa por glucagón.", "La insulina favorece fructosa-2,6-bisfosfato, estimulando PFK-1 y la glucólisis hepática."],
  ["Glucólisis", "medium", "¿Cuál enzima convierte dihidroxiacetona fosfato en gliceraldehído-3-fosfato?", "Triosa fosfato isomerasa.", "Aldolasa.", "Enolasa.", "Fosfoglucomutasa.", "La triosa fosfato isomerasa permite que ambas triosas continúen por la fase de obtención de energía."],
  ["Glucólisis", "hard", "¿Por qué los eritrocitos dependen especialmente de la glucólisis para obtener ATP?", "Porque carecen de mitocondrias.", "Porque no pueden convertir glucosa en glucosa-6-fosfato.", "Porque tienen ATP sintasa hiperactiva.", "Porque oxidan ácidos grasos en el citosol.", "Los eritrocitos no tienen mitocondrias y producen ATP por glucólisis anaerobia."],
  ["Glucólisis", "medium", "¿Qué reacción convierte fosfoenolpiruvato en piruvato?", "Piruvato quinasa con formación de ATP.", "PFK-1 con consumo de ATP.", "Lactato deshidrogenasa con consumo de NADH.", "Piruvato carboxilasa con consumo de ATP.", "La piruvato quinasa cataliza el último paso irreversible y genera ATP."],
  ["Glucólisis", "hard", "En ejercicio intenso, ¿por qué el lactato puede aumentar aunque haya oxígeno disponible?", "Porque la velocidad glucolítica puede superar la capacidad mitocondrial de oxidar piruvato y NADH.", "Porque el lactato solo se forma si no existe oxígeno alguno.", "Porque la ATP sintasa convierte directamente piruvato en lactato.", "Porque la gluconeogénesis muscular requiere lactato.", "La producción de lactato también puede acompañar una glucólisis muy acelerada."],

  ["Ciclo de Krebs", "medium", "¿Qué metabolito se convierte en alfa-cetoglutarato durante el ciclo de Krebs?", "Isocitrato.", "Citrato.", "Succinato.", "Malato.", "La isocitrato deshidrogenasa transforma isocitrato en alfa-cetoglutarato y produce NADH y CO₂."],
  ["Ciclo de Krebs", "hard", "¿Qué enzima del ciclo de Krebs también forma parte del complejo II de la cadena respiratoria?", "Succinato deshidrogenasa.", "Citrato sintasa.", "Aconitasa.", "Fumarasa.", "La succinato deshidrogenasa oxida succinato y transfiere electrones a FAD en la membrana interna."],
  ["Ciclo de Krebs", "medium", "¿Cuál es el destino biosintético clásico del citrato cuando sale de la mitocondria?", "Aportar acetil-CoA para síntesis de ácidos grasos y colesterol.", "Formar glucosa libre mediante glucosa-6-fosfatasa.", "Convertirse directamente en lactato.", "Activar la glucógeno fosforilasa muscular.", "El citrato exportado permite obtener acetil-CoA citosólico para lipogénesis."],
  ["Ciclo de Krebs", "hard", "¿Qué consecuencia tiene una extracción sostenida de intermediarios sin reposición anaplerótica?", "Disminuye la capacidad del ciclo para oxidar acetil-CoA.", "Aumenta obligatoriamente la síntesis de ATP por glucólisis.", "Se transforma FADH₂ en NADH.", "Se bloquea la formación de glucosa-6-fosfato.", "El ciclo requiere conservar sus intermediarios; extraerlos sin reponerlos reduce su flujo."],
  ["Ciclo de Krebs", "medium", "¿Qué producto del ciclo de Krebs es precursor importante para síntesis de hemo?", "Succinil-CoA.", "Citrato.", "Fumarato.", "Oxaloacetato.", "Succinil-CoA participa en la síntesis de porfirinas y hemo."],
  ["Ciclo de Krebs", "hard", "¿Por qué acetil-CoA no produce una ganancia neta de glucosa en humanos?", "Sus carbonos se pierden como CO₂ en el ciclo y no existe una vía neta hacia oxaloacetato.", "No puede entrar en la mitocondria.", "Se convierte directamente en lactato.", "Inhibe toda actividad de piruvato carboxilasa.", "El acetil-CoA entra al ciclo, pero sus carbonos no generan glucosa neta."],

  ["Cadena respiratoria", "medium", "¿Cuál es la función principal de coenzima Q en la cadena respiratoria?", "Transportar electrones desde complejos I y II hacia el complejo III.", "Bombear protones por el complejo IV.", "Sintetizar ATP directamente.", "Reducir oxígeno a agua.", "Coenzima Q es un transportador móvil liposoluble que conecta los complejos I/II con III."],
  ["Cadena respiratoria", "medium", "¿Qué transportador móvil lleva electrones del complejo III al complejo IV?", "Citocromo c.", "Coenzima A.", "Carnitina.", "Biotina.", "El citocromo c es una proteína soluble del espacio intermembrana que transporta electrones."],
  ["Cadena respiratoria", "hard", "¿Qué ocurre con el consumo de oxígeno si se administra cianuro?", "Disminuye drásticamente porque se bloquea el complejo IV.", "Aumenta porque se activa el complejo II.", "No cambia porque oxígeno no participa en la cadena.", "Aumenta solo en eritrocitos.", "El cianuro impide que el complejo IV entregue electrones al oxígeno."],
  ["Cadena respiratoria", "hard", "¿Qué caracteriza a un desacoplante de la fosforilación oxidativa?", "Disipa el gradiente de protones y reduce la síntesis de ATP mientras puede aumentar el consumo de oxígeno.", "Bloquea la entrada de NADH al complejo I sin cambiar el gradiente.", "Inhibe glucógeno sintasa y aumenta glucogénesis.", "Convierte directamente ADP en ATP sin protones.", "Un desacoplante permite el retorno de protones sin que esa energía se capture como ATP."],
  ["Cadena respiratoria", "medium", "¿Cuál es la consecuencia inmediata de inhibir ATP sintasa sin permitir el regreso de protones?", "Aumenta el gradiente hasta que se frena el transporte electrónico.", "Se acelera indefinidamente la cadena respiratoria.", "El oxígeno deja de ser aceptor final y se vuelve NAD+.", "Se forma glucosa libre en la matriz.", "Sin retorno de protones, el gradiente elevado hace termodinámicamente desfavorable seguir bombeándolos."],
  ["Cadena respiratoria", "hard", "¿Por qué la membrana mitocondrial interna debe ser poco permeable a protones?", "Para conservar el gradiente electroquímico que impulsa ATP sintasa.", "Para permitir que NADH salga al citosol.", "Para que glucosa entre directamente a la matriz.", "Para que complejo II bombee protones.", "La impermeabilidad relativa mantiene la fuerza protón-motriz."],

  ["Metabolismo del glucógeno", "medium", "¿Qué metabolito activa alostéricamente la glucógeno fosforilasa muscular durante contracción energética?", "AMP.", "ATP.", "Glucosa-6-fosfato.", "Citrato.", "AMP elevado señala baja energía y estimula degradación de glucógeno en músculo."],
  ["Metabolismo del glucógeno", "hard", "¿Qué enzima convierte glucosa-1-fosfato en glucosa-6-fosfato?", "Fosfoglucomutasa.", "Glucógeno sintasa.", "PFK-1.", "Glucosa-6-fosfatasa.", "Fosfoglucomutasa interconvierte glucosa-1-fosfato y glucosa-6-fosfato."],
  ["Metabolismo del glucógeno", "medium", "¿Qué molécula activada usa glucógeno sintasa como donador de glucosa?", "UDP-glucosa.", "Glucosa libre.", "Glucosa-6-fosfato.", "Fructosa-1,6-bisfosfato.", "La UDP-glucosa dona residuos de glucosa para alargar enlaces alfa-1,4."],
  ["Metabolismo del glucógeno", "hard", "¿Qué señal intracelular ayuda a activar glucogenólisis muscular durante la contracción?", "Calcio liberado del retículo sarcoplásmico.", "Aumento de fructosa-2,6-bisfosfato.", "Disminución de AMP.", "Aumento de glucosa sanguínea.", "El Ca²⁺ activa fosforilasa quinasa y vincula contracción con movilización de glucógeno."],
  ["Metabolismo del glucógeno", "medium", "¿Cuál es la ventaja metabólica de que el glucógeno sea muy ramificado?", "Permite liberar o añadir glucosa rápidamente desde muchos extremos no reductores.", "Evita por completo la necesidad de glucógeno fosforilasa.", "Hace que cada residuo tenga enlace alfa-1,6.", "Permite exportar glucosa desde músculo sin glucosa-6-fosfatasa.", "La ramificación aumenta el número de extremos accesibles para enzimas de síntesis y degradación."],
  ["Metabolismo del glucógeno", "hard", "¿Qué defecto explica que la glucógeno fosforilasa no degrade más allá de una rama límite?", "No puede romper enlaces alfa-1,6 sin la enzima desramificante.", "No puede romper ningún enlace alfa-1,4.", "No puede convertir glucosa-1-fosfato en glucosa-6-fosfato.", "No puede fosforilar glucosa libre.", "La fosforilasa se detiene cerca de enlaces alfa-1,6; la enzima desramificante resuelve la rama."],

  ["Gluconeogénesis", "hard", "¿Por qué la gluconeogénesis no es simplemente la glucólisis al revés?", "Porque debe evitar tres reacciones irreversibles mediante enzimas de bypass.", "Porque ocurre solo en el citosol y glucólisis solo en mitocondria.", "Porque no utiliza ATP ni GTP.", "Porque convierte acetil-CoA en lactato obligatoriamente.", "Las reacciones de hexoquinasa, PFK-1 y piruvato quinasa son irreversibles en glucólisis."],
  ["Gluconeogénesis", "medium", "¿Qué enzima realiza el bypass de PFK-1?", "Fructosa-1,6-bisfosfatasa.", "Fructosa-2,6-bisfosfatasa.", "Fosfoglucomutasa.", "Glucógeno fosforilasa.", "Fructosa-1,6-bisfosfatasa hidroliza fructosa-1,6-bisfosfato durante gluconeogénesis."],
  ["Gluconeogénesis", "hard", "¿Qué efecto tiene glucagón sobre fructosa-2,6-bisfosfato en hígado durante ayuno?", "La disminuye, inhibiendo PFK-1 y favoreciendo fructosa-1,6-bisfosfatasa.", "La aumenta, estimulando PFK-1.", "No tiene efecto sobre metabolismo hepático.", "La convierte directamente en glucosa libre.", "Glucagón reduce fructosa-2,6-bisfosfato para frenar glucólisis y favorecer gluconeogénesis."],
  ["Gluconeogénesis", "medium", "¿Qué tejido aporta glicerol para gluconeogénesis durante ayuno?", "Tejido adiposo, por lipólisis de triacilglicéridos.", "Eritrocito, por ciclo de Krebs.", "Músculo, por glucosa-6-fosfatasa.", "Cerebro, por beta-oxidación.", "La lipólisis libera glicerol, que el hígado usa como precursor gluconeogénico."],
  ["Gluconeogénesis", "hard", "¿Por qué oxaloacetato debe convertirse a malato o PEP para salir funcionalmente de la mitocondria?", "Porque oxaloacetato no cruza directamente la membrana mitocondrial interna.", "Porque oxaloacetato es el aceptor final de electrones.", "Porque PEP no puede formarse en hígado.", "Porque malato inhibe la gluconeogénesis.", "El traslado como malato o su conversión a PEP permite mover carbonos y equivalentes reductores al citosol."],
  ["Gluconeogénesis", "hard", "¿Qué costo energético aproximado requiere formar una glucosa desde dos piruvatos?", "4 ATP, 2 GTP y 2 NADH.", "2 ATP y 2 NADH.", "4 GTP sin ATP.", "No requiere energía porque invierte glucólisis.", "La gluconeogénesis es energéticamente costosa y usa ATP, GTP y NADH."],

  ["Vía de las pentosas", "medium", "¿Qué enzima de la fase no oxidativa transfiere unidades de dos carbonos?", "Transcetolasa.", "Transaldolasa.", "Glucosa-6-fosfato deshidrogenasa.", "Fosfoglicerato mutasa.", "La transcetolasa cataliza transferencias de dos carbonos y requiere tiamina pirofosfato."],
  ["Vía de las pentosas", "hard", "¿Qué cofactor necesita transcetolasa?", "Tiamina pirofosfato (vitamina B1).", "Biotina.", "Cobalamina.", "Piridoxal fosfato.", "Transcetolasa usa TPP, derivado de tiamina, para transferir unidades de dos carbonos."],
  ["Vía de las pentosas", "medium", "¿Qué tejido necesita especialmente NADPH para sintetizar hormonas esteroideas?", "Corteza suprarrenal.", "Eritrocito maduro.", "Músculo esquelético en reposo.", "Cartílago articular.", "La corteza suprarrenal usa NADPH en reacciones reductoras de esteroidogénesis."],
  ["Vía de las pentosas", "hard", "¿Qué hallazgo es más compatible con crisis hemolítica en deficiencia de G6PD tras un oxidante?", "Disminución de glutatión reducido en eritrocitos.", "Aumento de ATP mitocondrial eritrocitario.", "Aumento de síntesis de ácidos grasos en eritrocitos.", "Acumulación de acetil-CoA por bloqueo de Krebs.", "Sin NADPH, los eritrocitos no regeneran glutatión reducido y sufren daño oxidativo."],
  ["Vía de las pentosas", "medium", "¿Cuál intermediario glucolítico puede originarse a partir de reordenamientos no oxidativos de pentosas?", "Fructosa-6-fosfato.", "Acetil-CoA.", "Succinil-CoA.", "Oxaloacetato.", "La fase no oxidativa conecta pentosas con fructosa-6-fosfato y gliceraldehído-3-fosfato."],
  ["Vía de las pentosas", "hard", "Si una célula necesita tanto NADPH como ribosa-5-fosfato en proporciones similares, ¿qué ruta favorece?", "La fase oxidativa seguida de isomerización de ribulosa-5-fosfato a ribosa-5-fosfato.", "Solo glucólisis hasta lactato.", "Solo la fase no oxidativa sin oxidar glucosa-6-fosfato.", "Glucogenólisis sin vía de pentosas.", "La fase oxidativa entrega NADPH y produce ribulosa-5-fosfato, que puede convertirse en ribosa-5-fosfato."],
]

const rows: readonly Row[] = [...coreRows, ...extensionRows]

function slug(value: string) {
  return value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLocaleLowerCase("es").replaceAll(/[^a-z0-9]+/g, "-").replaceAll(/^-|-$/g, "")
}

export const bioquimicaQuestions: BioquimicaQuestion[] = rows.map((row, index) => {
  const [topic, difficulty, question, correct, distractor1, distractor2, distractor3, explanation] = row
  const options = [correct, distractor1, distractor2, distractor3]
  const correctIndex = index % options.length
  const rotated = [...options.slice(correctIndex), ...options.slice(0, correctIndex)]

  return {
    id: `bioquimica-${slug(topic)}-${String(index + 1).padStart(3, "0")}`,
    chapter: topic,
    topic,
    tags: ["bioquimica", slug(topic)],
    difficulty,
    type: "single",
    question,
    options: rotated,
    correctAnswers: [rotated.indexOf(correct)],
    explanation
  }
})
