import { createManualQuizBankFromRows, type ManualQuizRow } from "../manualQuiz"

// Preguntas independientes de las flashcards; respuesta y razón revisadas contra el solucionario.
const rows: readonly ManualQuizRow[] = [
  ["cap21-001", "Fundamentos endocrinos", "medium", "En un corte se observan cordones celulares endocrinos separados por capilares fenestrados, sin conductos excretores. ¿Qué propiedad explica mejor que sus secreciones puedan actuar sobre órganos distantes?", "Liberación hacia el intersticio y captación vascular", "Vertido al sistema de conductos", "Difusión exclusiva a células contiguas", "Almacenamiento en una luz epitelial", "La secreción endocrina llega a los vasos desde el intersticio."],
  ["cap21-002", "Fundamentos endocrinos", "hard", "Una hormona producida por una célula modifica la actividad de otra célula vecina sin pasar primero por la circulación sistémica. ¿Qué modalidad de señalización representa?", "Paracrina", "Endocrina", "Autocrina", "Sináptica", "La señal paracrina actúa sobre células vecinas."],
  ["cap21-003", "Fundamentos endocrinos", "medium", "Un estudiante afirma que todas las hormonas tiroideas actúan uniéndose a receptores de la superficie celular. ¿Qué rasgo de su mecanismo contradice esa afirmación?", "Su efecto sobre la transcripción génica mediante receptores intracelulares", "Su almacenamiento en vesículas sinápticas", "Su incapacidad de atravesar la sangre", "Su acción exclusiva por acetilcolina", "T3/T4 usan receptores intracelulares que regulan genes."],
  ["cap21-004", "Hipófisis e hipotálamo", "medium", "Un tejido hipofisario deriva de la bolsa de Rathke. ¿Cuál de los siguientes corresponde a ese origen?", "Porción distal", "Porción nerviosa", "Infundíbulo", "Eminencia media", "La porción distal pertenece a la adenohipófisis derivada de Rathke."],
  ["cap21-005", "Hipófisis e hipotálamo", "medium", "Se lesiona el plexo capilar primario de la eminencia media. ¿Qué comunicación se afecta de forma más directa?", "Llegada de hormonas reguladoras hipotalámicas a la porción distal", "Liberación de ADH desde la porción nerviosa", "Inervación simpática de la médula suprarrenal", "Producción de melatonina por la pineal", "El plexo primario inicia la vía porta hacia la porción distal."],
  ["cap21-006", "Hipófisis e hipotálamo", "hard", "En la porción distal se identifica una célula acidófila que produce una hormona que induce IGF-1. ¿Qué célula es?", "Somatótropa", "Tirótropa", "Gonadótropa", "Corticótropa", "La somatótropa secreta GH; GH estimula IGF-1."],
  ["cap21-007", "Hipófisis e hipotálamo", "medium", "Una disminución de la señal dopaminérgica hipotalámica tendría como consecuencia más directa:", "Mayor secreción de prolactina", "Menor secreción de prolactina", "Menor secreción de oxitocina", "Mayor secreción de aldosterona", "La dopamina inhibe de forma tónica la prolactina."],
  ["cap21-008", "Hipófisis e hipotálamo", "hard", "¿Qué pareja célula adenohipofisaria–producto es correcta?", "Corticótropa–POMC", "Gonadótropa–ACTH", "Tirótropa–GH", "Somatótropa–PRL", "La corticótropa produce POMC, precursor de ACTH."],
  ["cap21-009", "Hipófisis e hipotálamo", "medium", "Se observan pequeños quistes con coloide entre la porción distal y la porción nerviosa. ¿Qué región representan?", "Porción intermedia", "Porción tuberal", "Eminencia media", "Zona reticular", "Los quistes con coloide son restos de la bolsa de Rathke en la porción intermedia."],
  ["cap21-010", "Hipófisis e hipotálamo", "medium", "¿Cuál afirmación sobre la neurohipófisis es correcta?", "Almacena y libera hormonas sintetizadas en neuronas hipotalámicas", "Sintetiza ADH y oxitocina en pituicitos", "Es una evaginación del ectodermo bucofaríngeo", "Secreta TSH y ACTH hacia el sistema porta", "La neurohipófisis almacena y libera productos hipotalámicos."],
  ["cap21-011", "Hipófisis e hipotálamo", "medium", "Un microscopista ve dilataciones axónicas llenas de gránulos en la porción nerviosa. ¿Qué estructuras son?", "Cuerpos de Herring", "Folículos de Rathke", "Cuerpos arenáceos", "Células cromafines", "Los cuerpos de Herring son dilataciones axónicas neurosecretoras."],
  ["cap21-012", "Hipófisis e hipotálamo", "hard", "Un paciente produce ADH, pero sus conductos colectores no responden porque falla el receptor V2. ¿Qué mecanismo explica su poliuria?", "Falta de efecto renal de ADH", "Secreción excesiva de TSH", "Destrucción de pinealocitos", "Exceso de PTH", "La resistencia renal a ADH produce diabetes insípida nefrogénica."],
  ["cap21-013", "Glándula pineal", "medium", "Una microfotografía de una glándula del techo posterior del diencéfalo muestra calcificaciones en el parénquima. ¿Qué glándula y estructura son?", "Pineal; cuerpos arenáceos", "Paratiroides; coloide", "Tiroides; cuerpos de Herring", "Adenohipófisis; cuerpos arenáceos", "Pineal y cuerpos arenáceos."],
  ["cap21-014", "Glándula pineal", "medium", "¿Qué cambio se espera en la secreción de melatonina durante la oscuridad?", "Aumenta", "Disminuye por estimulación luminosa", "Permanece constante y depende solo de TSH", "Desaparece porque se almacena en coloide", "La secreción de melatonina aumenta en la oscuridad."],
  ["cap21-015", "Glándula tiroides", "medium", "Una célula tiroidea está dentro de la lámina basal folicular, pero no contacta el coloide. ¿Qué producto secreta?", "Calcitonina", "Tiroglobulina", "T4", "PTH", "La célula C perifolicular secreta calcitonina."],
  ["cap21-016", "Glándula tiroides", "medium", "El coloide de un folículo tiroideo está formado principalmente por una molécula precursora y de almacenamiento. ¿Cuál es?", "Tiroglobulina", "Calcitonina", "Transtiretina", "Proopiomelanocortina", "La tiroglobulina es el componente principal del coloide."],
  ["cap21-017", "Glándula tiroides", "hard", "Una alteración de pendrina disminuiría directamente:", "La salida apical de yoduro hacia el coloide", "La captación basolateral de yoduro desde la sangre", "La endocitosis de tiroglobulina por megalina", "La secreción de PTH", "Pendrina lleva yoduro desde la célula al coloide."],
  ["cap21-018", "Glándula tiroides", "hard", "¿Qué acoplamiento de residuos yodados origina T4?", "DIT + DIT", "MIT + MIT", "MIT + DIT", "T3 + MIT", "DIT + DIT produce T4."],
  ["cap21-019", "Glándula tiroides", "hard", "Tras estimulación con TSH, una célula folicular endocita coloide y degrada tiroglobulina. ¿En qué compartimento se liberan principalmente T3 y T4 de ese precursor?", "En los lisosomas", "En la luz del capilar", "En la membrana basal", "En los cuerpos arenáceos", "La proteólisis lisosómica libera las hormonas de la tiroglobulina."],
  ["cap21-020", "Glándula tiroides", "medium", "Una glándula tiroides muy activa muestra epitelio folicular alto y bordes irregulares del coloide próximos al polo apical. ¿Qué proceso explica mejor ese aspecto?", "Mayor reabsorción de coloide", "Menor reabsorción de tiroglobulina", "Secreción de catecolaminas", "Pérdida de las células principales paratiroideas", "La estimulación intensa aumenta la recuperación del coloide."],
  ["cap21-021", "Glándulas paratiroides", "medium", "¿Qué célula paratiroidea se reconoce por abundantes mitocondrias y citoplasma intensamente eosinófilo?", "Oxífila", "Principal", "Folicular", "Cromafín", "La célula oxífila es mitocondrial y eosinófila."],
  ["cap21-022", "Glándulas paratiroides", "medium", "Una caída del calcio sérico activa un receptor sensor de calcio de la paratiroides. ¿Qué respuesta sigue?", "Aumenta PTH y aumenta la reabsorción renal de calcio", "Disminuye PTH y disminuye la reabsorción renal de calcio", "Aumenta calcitonina y disminuye la fosfaturia", "Aumenta TSH y aumenta T4", "Hipocalcemia estimula PTH, que conserva calcio renal."],
  ["cap21-023", "Glándulas paratiroides", "hard", "¿Por qué aumenta la resorción ósea bajo exposición continua a PTH si los osteoclastos no tienen receptor para esta hormona?", "Las células de linaje osteoblástico aumentan la señal RANKL–RANK hacia precursores osteoclásticos", "PTH se une directamente a la membrana del osteoclasto", "El folículo tiroideo transforma PTH en calcitonina", "Los pituicitos producen RANKL", "PTH actúa indirectamente sobre osteoclastos vía RANKL–RANK."],
  ["cap21-024", "Glándulas paratiroides", "hard", "¿Qué combinación sobre los efectos renales de PTH es correcta?", "Mayor reabsorción de calcio y mayor excreción de fosfato", "Menor reabsorción de calcio y menor excreción de fosfato", "Mayor excreción de calcio y mayor excreción de fosfato", "Menor excreción de calcio y menor activación de vitamina D", "PTH conserva calcio y favorece la fosfaturia."],
  ["cap21-025", "Glándulas suprarrenales", "medium", "En un corte de suprarrenal, una zona bajo la cápsula presenta pequeños grupos ovoides y columnas arqueadas. ¿Qué hormona secreta principalmente?", "Aldosterona", "Cortisol", "DHEA", "Noradrenalina", "La zona glomerular produce aldosterona."],
  ["cap21-026", "Glándulas suprarrenales", "hard", "Se observan cordones rectos largos de células vacuoladas separados por sinusoides. ¿Qué zona suprarrenal es?", "Fasciculada", "Glomerular", "Reticular", "Médula", "La zona fasciculada tiene cordones rectos y muchas gotitas lipídicas."],
  ["cap21-027", "Glándulas suprarrenales", "medium", "¿Qué producto corresponde a la zona reticular de la corteza suprarrenal?", "Andrógenos suprarrenales como DHEA", "Melatonina", "Calcitonina", "ADH", "La zona reticular produce andrógenos suprarrenales."],
  ["cap21-028", "Glándulas suprarrenales", "medium", "Una fibra simpática presináptica libera acetilcolina sobre una célula medular suprarrenal. ¿Qué liberará esta célula a la sangre?", "Catecolaminas", "T3/T4", "PTH", "Aldosterona", "Las células cromafines liberan catecolaminas."],
  ["cap21-029", "Glándulas suprarrenales", "hard", "¿Por qué la médula suprarrenal recibe una influencia directa de los glucocorticoides corticales?", "Porque parte de la sangre medular llega desde los sinusoides corticales", "Porque el sistema porta hipofisario desemboca en la médula", "Porque los cuerpos de Herring rodean a las células cromafines", "Porque la corteza carece de irrigación", "Los sinusoides corticales llevan glucocorticoides a la médula."],
  ["cap21-030", "Glándulas suprarrenales", "hard", "¿Qué transformación favorecen los glucocorticoides corticales en las células cromafines?", "Noradrenalina → adrenalina", "Aldosterona → cortisol", "T4 → T3", "Dopamina → prolactina", "La exposición a glucocorticoides favorece la conversión de noradrenalina en adrenalina."],
  ["cap21-031", "Glándulas suprarrenales", "medium", "¿Qué señal domina la regulación de la zona glomerular?", "Angiotensina II del sistema renina–angiotensina–aldosterona", "Prolactina hipofisaria", "Melatonina pineal", "Oxitocina neurohipofisaria", "Angiotensina II regula la secreción de aldosterona de la zona glomerular."],
  ["cap21-032", "Glándulas suprarrenales", "medium", "¿Qué señal adenohipofisaria es especialmente importante para mantener la zona fasciculada y su secreción de cortisol?", "ACTH", "TSH", "FSH", "PRL", "ACTH mantiene y estimula la zona fasciculada."],
  ["cap21-033", "Glándulas suprarrenales", "hard", "¿Cuál es la relación correcta entre las dos regiones de la suprarrenal fetal?", "La corteza permanente periférica persiste; la gran zona fetal interna involuciona tras el nacimiento", "La zona fetal externa reemplaza a la corteza permanente interna", "Ambas proceden de la cresta neural y se transforman en médula", "La médula definitiva ocupa casi toda la glándula fetal", "La gran zona fetal involuciona y la corteza permanente madura."],
  ["cap21-034", "Glándulas suprarrenales", "hard", "¿Qué explicación vincula la suprarrenal fetal con la placenta?", "Intercambian precursores porque cada una carece de algunas enzimas necesarias para completar rutas de esteroides", "Ambas comparten un conducto excretor para hormonas", "La placenta produce todos los corticoides sin aporte fetal", "La suprarrenal fetal solo recibe catecolaminas placentarias", "La unidad fetoplacentaria intercambia precursores esteroideos."],
]

export const cap21Questions = createManualQuizBankFromRows("Capítulo 21", rows)

