import { createManualQuizBankFromRows, type ManualQuizRow } from "@/content/histologia/manualQuiz"
import type { HistologiaQuizQuestion } from "@/content/histologia/quizFromFlashcards"

export const CITO_III_PARTIAL = "Parcial 3 · Cito III"

// Banco exclusivo para la última vuelta. Se apoya en los capítulos 19 y 20 de
// Ross; del capítulo 20 solo usa el texto anterior al apartado de láminas.
// Las respuestas se guardan primero aquí y se mezclan al iniciar cada sesión.
const multipleChoiceRows: readonly ManualQuizRow[] = [
  ["cito3-01", "Respiratorio · porciones", "medium", "Un conducto muestra sus primeros alvéolos interrumpiendo la pared. ¿Qué segmento se está observando?", "Bronquiolo respiratorio.", "Bronquiolo terminal.", "Conducto alveolar.", "Bronquio intrapulmonar.", "El bronquiolo respiratorio inicia la porción de intercambio porque ya presenta alvéolos en su pared."],
  ["cito3-02", "Respiratorio · porciones", "medium", "¿Qué conjunto pertenece íntegramente a la porción conductora?", "Tráquea, bronquio y bronquiolo terminal.", "Tráquea, bronquiolo respiratorio y bronquio.", "Bronquio, conducto alveolar y bronquiolo terminal.", "Bronquiolo terminal, saco alveolar y bronquio.", "El bronquiolo terminal es el último segmento conductor; los bronquiolos respiratorios y alvéolos participan en el intercambio."],
  ["cito3-03", "Cavidad nasal", "medium", "¿Por qué los cornetes hacen más eficaz el calentamiento del aire inspirado?", "Amplían la superficie mucosa y generan turbulencia.", "Amplían la superficie mucosa y reducen el flujo capilar.", "Reducen la superficie mucosa y generan turbulencia.", "Reducen la superficie mucosa y eliminan la secreción.", "Los cornetes aumentan el contacto del aire con una mucosa muy vascularizada."],
  ["cito3-04", "Cavidad nasal", "medium", "Al avanzar del vestíbulo nasal a la región respiratoria, ¿qué cambio de revestimiento se espera?", "De plano estratificado a seudoestratificado ciliado.", "De seudoestratificado ciliado a plano estratificado.", "De plano estratificado a epitelio olfatorio.", "De epitelio olfatorio a seudoestratificado ciliado.", "El vestíbulo continúa la piel; más atrás comienza la mucosa respiratoria ciliada."],
  ["cito3-05", "Epitelio respiratorio", "hard", "Una célula respiratoria tiene microvellosidades romas y contacto con una terminación nerviosa aferente. ¿Cuál es?", "Célula en cepillo.", "Célula ciliada.", "Célula caliciforme.", "Célula de Kulchitsky.", "La célula en cepillo se relaciona con la sensibilidad química y con fibras nerviosas."],
  ["cito3-06", "Epitelio respiratorio", "medium", "Una célula pequeña se apoya en la membrana basal, no alcanza la luz y repone el epitelio respiratorio. Corresponde a:", "Célula basal.", "Célula en cepillo.", "Célula de Kulchitsky.", "Célula caliciforme.", "Las células basales son la población progenitora del epitelio respiratorio."],
  ["cito3-07", "Olfato", "hard", "Un campo nasal tiene neuronas receptoras y glándulas serosas, pero no células caliciformes. ¿Qué región es?", "Mucosa olfatoria.", "Mucosa respiratoria.", "Vestíbulo nasal.", "Mucosa de un seno paranasal.", "Las glándulas de Bowman y las neuronas bipolares distinguen la región olfatoria."],
  ["cito3-08", "Olfato", "hard", "Tras unirse un odorante al receptor en los cilios olfatorios, ¿qué señal favorece la apertura de canales catiónicos?", "Aumento de AMP cíclico.", "Aumento de GMP cíclico.", "Disminución de AMP cíclico.", "Disminución de calcio intracelular.", "La vía olfatoria activa adenilato ciclasa y cAMP, que abre canales para Na+ y Ca2+."],
  ["cito3-09", "Olfato", "medium", "¿Qué prolongación de la neurona olfatoria bipolar contribuye a formar el nervio olfatorio?", "Su axón basal.", "Su dendrita apical.", "Sus cilios olfatorios.", "Su botón dendrítico.", "Los axones de las neuronas receptoras atraviesan la lámina cribosa hacia el bulbo olfatorio."],
  ["cito3-10", "Olfato", "medium", "Después de un golpe en la base del cráneo aparece anosmia. ¿Qué estructura se lesiona con mayor probabilidad?", "Axones receptores olfatorios en la lámina cribosa.", "Dendritas receptoras olfatorias en el moco nasal.", "Células de soporte olfatorias en la lámina propia.", "Glándulas olfatorias serosas en la lámina propia.", "Las fibras olfatorias son vulnerables donde cruzan la lámina cribosa."],
  ["cito3-11", "Senos paranasales", "medium", "¿Qué revestimiento se espera en un seno paranasal comunicado con la cavidad nasal?", "Epitelio respiratorio seudoestratificado ciliado.", "Epitelio olfatorio seudoestratificado no ciliado.", "Epitelio plano estratificado no queratinizado.", "Epitelio cúbico simple con células en cepillo.", "Los senos tienen mucosa respiratoria, más delgada que la de la cavidad nasal."],
  ["cito3-12", "Laringe", "medium", "¿Qué pliegues vibran para producir la voz y resisten el roce del flujo de aire?", "Pliegues vocales verdaderos.", "Pliegues ventriculares superiores.", "Pliegues ariepiglóticos laterales.", "Pliegues glosoepiglóticos mediales.", "Los pliegues vocales verdaderos producen el sonido y tienen epitelio plano estratificado en la zona de fricción."],
  ["cito3-13", "Laringe", "hard", "En una sección laríngea, un pliegue superior con abundantes glándulas mucosas se distingue del pliegue vocal verdadero porque es:", "Pliegue ventricular o vestibular.", "Pliegue vocal con ligamento vocal.", "Cartílago aritenoides inferior.", "Músculo vocal de la glotis.", "Los pliegues ventriculares se encuentran por encima de los verdaderos y presentan glándulas mucosas prominentes."],
  ["cito3-14", "Tráquea", "medium", "Una lámina traqueal muestra los extremos abiertos del cartílago en C. ¿Qué estructura los une por detrás?", "Músculo traqueal liso.", "Músculo vocal estriado.", "Ligamento cricotiroideo.", "Músculo bronquial circular.", "El músculo traqueal cierra la parte posterior de los anillos traqueales."],
  ["cito3-15", "Tráquea", "hard", "¿Dónde se sitúan principalmente las glándulas seromucosas de la tráquea?", "En la submucosa, profundas a la mucosa.", "En la lámina propia, entre los cilios epiteliales.", "En la adventicia, externas a los cartílagos.", "En el pericondrio, entre condrocitos hialinos.", "La submucosa traqueal contiene glándulas que aportan secreción a la superficie epitelial."],
  ["cito3-16", "Bronquios", "medium", "Al observar un bronquio dentro del pulmón, ¿qué disposición cartilaginosa lo diferencia de la tráquea?", "Placas discontinuas alrededor de la pared.", "Anillos completos alrededor de la pared.", "Un anillo en C abierto posteriormente.", "Ausencia total de soporte cartilaginoso.", "El cartílago bronquial intrapulmonar forma placas, no anillos traqueales."],
  ["cito3-17", "Bronquiolos", "medium", "Un conducto pequeño tiene pared epitelial continua, músculo liso y carece de cartílago, glándulas y alvéolos. ¿Cómo se clasifica?", "Bronquiolo conductor.", "Bronquio intrapulmonar.", "Bronquiolo respiratorio.", "Conducto alveolar.", "La pared continua sin alvéolos lo sitúa en la porción conductora; la ausencia de cartílago y glándulas identifica un bronquiolo."],
  ["cito3-18", "Bronquiolos", "hard", "Hacia el bronquiolo terminal, ¿cómo cambia la composición epitelial?", "Aumentan las células de Clara y disminuyen las ciliadas.", "Disminuyen las células de Clara y aumentan las ciliadas.", "Aumentan las células caliciformes y desaparecen las de Clara.", "Aumentan los neumocitos tipo I y desaparecen las ciliadas.", "Las células de Clara o club predominan progresivamente al acercarse al extremo conductor."],
  ["cito3-19", "Acino pulmonar", "hard", "Ross llama unidad bronquiolar respiratoria a:", "Un bronquiolo respiratorio y los alvéolos que ventila.", "Un bronquiolo terminal y todos los bronquios anteriores.", "Un conducto alveolar y todos los bronquiolos terminales.", "Un saco alveolar y todas las ramas bronquiales del lóbulo.", "Es la menor unidad funcional pulmonar: un bronquiolo respiratorio y sus alvéolos."],
  ["cito3-20", "Acino pulmonar", "hard", "Según la definición empleada en este capítulo de Ross, ¿qué conjunto forma un acino pulmonar?", "Un bronquiolo terminal y sus ramas respiratorias y alveolares.", "Un bronquiolo respiratorio sin el bronquiolo terminal previo.", "Un bronquio intrapulmonar y todos los lobulillos de su segmento.", "Un conducto alveolar aislado sin sus ramas bronquiolares.", "Ross incluye el bronquiolo terminal y las ramas respiratorias que abastece dentro de cada acino."],
  ["cito3-21", "Células de Clara", "hard", "¿Qué propiedad corresponde a una célula de Clara o club bronquiolar?", "No es ciliada, tiene ápice abombado y aporta secreción protectora.", "Es ciliada, tiene ápice abombado y transporta el moco.", "No es ciliada, tiene gránulos de moco y reviste la tráquea.", "Es ciliada, tiene gránulos endocrinos y reviste bronquiolos.", "Las células club no poseen cilios; protegen el epitelio bronquiolar y aportan secreciones."],
  ["cito3-22", "Alvéolos", "medium", "¿Qué comparación entre neumocitos tipo I y II es correcta?", "El tipo I cubre más superficie; el tipo II es más numeroso.", "El tipo II cubre más superficie; el tipo I es más numeroso.", "Ambos cubren igual superficie y tienen igual abundancia.", "El tipo I produce surfactante; el tipo II forma la pared capilar.", "Los neumocitos tipo I son extensos y delgados; los tipo II son más numerosos, pero cubren menos superficie."],
  ["cito3-23", "Alvéolos", "medium", "Después de una lesión epitelial alveolar, ¿qué célula puede proliferar y reemplazar también a las células tipo I?", "Neumocito tipo II.", "Neumocito tipo I.", "Macrófago alveolar.", "Célula endotelial.", "Los neumocitos tipo II sirven como progenitores para la reparación del epitelio alveolar."],
  ["cito3-24", "Surfactante", "medium", "En microscopía electrónica se ven cuerpos laminares en una célula alveolar. ¿Qué contiene esa célula antes de secretarlo?", "Componentes del surfactante.", "Proteínas de la matriz alveolar.", "Enzimas del macrófago alveolar.", "Factores del endotelio capilar.", "Los cuerpos laminares almacenan componentes del surfactante en los neumocitos tipo II."],
  ["cito3-25", "Surfactante", "hard", "Una proteína del surfactante se une a microorganismos y modula la inflamación tras lesión aguda. ¿Cuál es?", "Proteína tensoactiva D (PTD).", "Proteína tensoactiva B (PTB).", "Proteína tensoactiva C (PTC).", "Proteína tensoactiva A (PTA).", "La PTD participa en defensa del hospedero y respuesta inflamatoria; PTB y PTC organizan la película, y PTA regula su homeostasis."],
  ["cito3-26", "Barrera hematogaseosa", "hard", "¿Qué combinación atraviesa el gas en la zona más delgada del tabique alveolar?", "Neumocito I, láminas basales y endotelio capilar.", "Neumocito II, láminas basales y endotelio capilar.", "Neumocito I, tejido conjuntivo grueso y endotelio.", "Neumocito I, láminas basales y célula mesotelial.", "La vía delgada comprende surfactante, neumocito I, sus láminas basales y endotelio."],
  ["cito3-27", "Barrera hematogaseosa", "hard", "En un tabique alveolar edematoso, ¿qué cambio dificulta primero la difusión de gases?", "Aumenta la distancia entre aire alveolar y sangre capilar.", "Disminuye el grosor de la barrera entre aire y capilar.", "Aumenta el gradiente de difusión por adelgazamiento septal.", "Disminuye la distancia por fusión de láminas basales.", "El edema engrosa la región intersticial de la barrera y alarga la distancia de difusión."],
  ["cito3-28", "Macrófagos alveolares", "medium", "Una partícula inhalada alcanza el alvéolo sin quedar atrapada en el moco. ¿Qué célula puede fagocitarla allí?", "Macrófago alveolar.", "Neumocito tipo I.", "Neumocito tipo II.", "Célula en cepillo.", "Los macrófagos alveolares eliminan partículas y material celular en el espacio aéreo."],
  ["cito3-29", "Alvéolos", "medium", "¿Qué estructura crea una vía de ventilación colateral entre dos alvéolos contiguos?", "Poro alveolar de Kohn.", "Conducto alveolar principal.", "Capilar del tabique alveolar.", "Bronquiolo respiratorio.", "Los poros de Kohn son aberturas en los tabiques interalveolares."],
  ["cito3-30", "Pleura", "medium", "¿Qué capas se reconocen en la pleura visceral adherida al pulmón?", "Mesotelio y tejido conjuntivo subyacente.", "Epitelio ciliado y cartílago hialino.", "Neumocitos y membrana basal glomerular.", "Urotelio y músculo liso subyacente.", "La pleura visceral es una serosa cubierta por mesotelio, con tejido conjuntivo profundo."],

  ["cito3-31", "Riñón · organización", "medium", "Una unidad renal reúne una pirámide medular y su corteza asociada. ¿Cuál es?", "Lóbulo renal.", "Lobulillo renal.", "Rayo medular.", "Laberinto cortical.", "Un lóbulo comprende una pirámide completa y el territorio cortical correspondiente."],
  ["cito3-32", "Riñón · organización", "hard", "Un campo cortical contiene túbulos rectos y colectores sin corpúsculos. ¿Qué región es?", "Rayo medular.", "Laberinto cortical.", "Columna renal.", "Médula interna.", "Los rayos medulares son bandas corticales de túbulos rectos y conductos colectores."],
  ["cito3-33", "Nefrona", "medium", "¿Qué estructura se agrega a la nefrona para formar el túbulo urinario según la terminología del capítulo?", "Conducto colector.", "Arteriola eferente.", "Cápsula fibrosa.", "Laberinto cortical.", "El túbulo urinario incluye nefrona más sistema colector."],
  ["cito3-34", "Corpúsculo renal", "medium", "En un corpúsculo renal, el espacio urinario se continúa con el túbulo proximal en el:", "Polo urinario.", "Polo vascular.", "Mesangio extraglomerular.", "Hilio renal.", "El túbulo contorneado proximal nace en el polo urinario, opuesto al ingreso y egreso arteriolar."],
  ["cito3-35", "Filtro glomerular", "hard", "¿Cuál rasgo de los capilares glomerulares favorece el ultrafiltrado frente a otros capilares fenestrados?", "Fenestraciones endoteliales sin diafragma.", "Fenestraciones endoteliales con diafragma.", "Endotelio continuo con uniones oclusivas.", "Endotelio discontinuo sin lámina basal.", "Las fenestraciones glomerulares carecen de diafragma; la MBG y los podocitos completan el filtro."],
  ["cito3-36", "Filtro glomerular", "hard", "Una molécula aniónica atraviesa el filtro menos que otra del mismo tamaño sin esa carga. ¿Qué componente explica la diferencia?", "Polianiones de la membrana basal glomerular.", "Fenestraciones del endotelio glomerular.", "Pedicelos de la capa visceral de Bowman.", "Matriz de las células mesangiales intraglomerulares.", "Las cargas negativas de glucosaminoglucanos en la MBG restringen solutos aniónicos."],
  ["cito3-37", "Podocitos", "hard", "La pérdida de nefrina altera de manera más directa:", "Diafragmas entre pedicelos de podocitos.", "Fenestraciones del endotelio glomerular.", "Lámina densa de la membrana basal glomerular.", "Matriz producida por células mesangiales.", "La nefrina forma parte esencial de los diafragmas de las ranuras de filtración."],
  ["cito3-38", "Mesangio", "medium", "Una célula sostiene asas glomerulares y retira complejos atrapados mediante fagocitosis. ¿Cuál es?", "Célula mesangial intraglomerular.", "Célula yuxtaglomerular aferente.", "Podocito de la capa visceral.", "Célula de la cápsula parietal.", "Las mesangiales aportan soporte, matriz y depuración de residuos dentro del glomérulo."],
  ["cito3-39", "Aparato yuxtaglomerular", "hard", "¿Qué trío constituye el aparato yuxtaglomerular?", "Mácula densa, células granulares y mesangiales extraglomerulares.", "Mácula densa, podocitos y mesangiales intraglomerulares.", "Túbulo proximal, células granulares y podocitos viscerales.", "Túbulo distal, células parietales y mesangiales intraglomerulares.", "Se reúne en el polo vascular: mácula densa, células yuxtaglomerulares y mesangio extraglomerular."],
  ["cito3-40", "Aparato yuxtaglomerular", "hard", "Una variación de NaCl en el líquido tubular distal llega al polo vascular. ¿Quién la detecta?", "Células de la mácula densa.", "Células granulares aferentes.", "Células mesangiales intraglomerulares.", "Podocitos de la capa visceral.", "La mácula densa está formada por células tubulares distales especializadas en detectar NaCl."],
  ["cito3-41", "Túbulo proximal", "medium", "En H&E, un túbulo cortical tiene citoplasma eosinófilo y luz borrosa por un borde en cepillo. ¿Cuál es?", "Túbulo contorneado proximal.", "Túbulo contorneado distal.", "Conducto colector cortical.", "Rama ascendente delgada.", "Las abundantes microvellosidades apicales hacen poco nítida la luz proximal."],
  ["cito3-42", "Túbulo proximal", "hard", "En el túbulo contorneado proximal, ¿qué par transporta la glucosa desde la luz hacia la sangre?", "SGLT2 apical y GLUT2 basolateral.", "SGLT1 apical y GLUT1 basolateral.", "GLUT2 apical y SGLT2 basolateral.", "AQP2 apical y GLUT2 basolateral.", "SGLT2 introduce glucosa con sodio y GLUT2 la libera por la membrana basolateral."],
  ["cito3-43", "Túbulo proximal", "hard", "La llegada de proteínas filtradas al túbulo proximal exige principalmente:", "Endocitosis apical y degradación lisosómica.", "Exocitosis apical y degradación mitocondrial.", "Filtración paracelular y degradación peroxisómica.", "Secreción basolateral y degradación en la luz.", "Las proteínas captadas por endocitosis se procesan en lisosomas; sus aminoácidos se recuperan."],
  ["cito3-44", "Asa renal", "medium", "Al descender por la rama delgada hacia una médula hiperosmótica, el líquido tubular se concentra porque:", "Sale agua desde la luz hacia el intersticio.", "Entra agua desde el intersticio hacia la luz.", "Entra NaCl desde la luz hacia el intersticio.", "Sale NaCl desde el intersticio hacia la luz.", "La rama descendente delgada es muy permeable al agua y pierde agua al intersticio."],
  ["cito3-45", "Asa renal", "medium", "El líquido se diluye en la rama ascendente del asa porque:", "Sale NaCl, mientras casi no puede salir agua.", "Sale agua, mientras casi no puede salir NaCl.", "Entra NaCl, mientras sale agua al intersticio.", "Entra agua, mientras sale NaCl a la luz.", "La rama ascendente retira solutos con baja permeabilidad al agua."],
  ["cito3-46", "Túbulo recto distal", "hard", "Una proteína que puede integrar cilindros urinarios se libera en la rama ascendente gruesa. ¿Cuál?", "Uromodulina o proteína de Tamm-Horsfall.", "Nefrina del diafragma de filtración.", "Uroplaquina de la célula sombrilla.", "Renina de la arteriola aferente.", "La uromodulina se secreta en el segmento grueso ascendente y puede precipitar en orina."],
  ["cito3-47", "Túbulo distal", "hard", "¿Qué comparación histológica identifica mejor un túbulo contorneado distal frente a uno proximal?", "Luz más nítida y menos microvellosidades apicales.", "Luz menos nítida y más microvellosidades apicales.", "Luz con podocitos y un espacio urinario periférico.", "Luz con células sombrilla y placas de uroplaquina.", "El túbulo distal carece del borde en cepillo prominente del túbulo proximal."],
  ["cito3-48", "Conductos colectores", "medium", "Tras liberar ADH, ¿qué canal aparece en la membrana apical de células principales colectoras?", "Acuaporina 2.", "Acuaporina 1.", "Canal de sodio ENaC.", "Cotransportador SGLT2.", "La ADH promueve la inserción apical de AQP2 y aumenta la permeabilidad al agua."],
  ["cito3-49", "Conductos colectores", "hard", "En una célula principal expuesta a aldosterona, ¿qué par de cambios es esperable?", "Mayor reabsorción de Na+ y mayor secreción de K+.", "Mayor secreción de Na+ y mayor reabsorción de K+.", "Mayor reabsorción de ambos iones hacia la sangre.", "Mayor secreción de ambos iones hacia la orina.", "La aldosterona favorece retención de sodio y excreción de potasio."],
  ["cito3-50", "Equilibrio ácido-base", "hard", "En acidosis, ¿qué célula intercalada ayuda más al secretar H+ al líquido tubular?", "Célula intercalada alfa.", "Célula intercalada beta.", "Célula principal colectora.", "Célula mesangial extraglomerular.", "La intercalada alfa secreta protones; la beta se especializa en secretar bicarbonato."],
  ["cito3-51", "Nefronas", "medium", "¿Qué rasgo favorece la concentración intensa de la orina en una nefrona yuxtamedular?", "Asa larga que penetra profundamente en la médula.", "Asa corta que regresa en la corteza externa.", "Corpúsculo superficial y ausencia de vasos rectos.", "Conducto colector que termina en la corteza.", "Las asas largas permiten generar y aprovechar el gradiente osmótico medular."],
  ["cito3-52", "Circulación renal", "hard", "¿Qué red nacida de arteriolas eferentes yuxtamedulares ayuda a conservar el gradiente medular?", "Vasos rectos.", "Capilares glomerulares.", "Arterias arqueadas.", "Venas interlobulillares.", "Los vasos rectos actúan como intercambiadores de contracorriente en la médula."],
  ["cito3-53", "Circulación renal", "hard", "Desde la arteria renal hacia una arteriola aferente, ¿qué orden arterial es correcto?", "Interlobular → arqueada → interlobulillar.", "Arqueada → interlobular → interlobulillar.", "Interlobulillar → arqueada → interlobular.", "Interlobular → interlobulillar → arqueada.", "Las interlobulares ascienden entre pirámides, luego siguen arqueadas en su base e interlobulillares en la corteza."],
  ["cito3-54", "Endocrino renal", "medium", "En enfermedad renal avanzada aparece anemia por menor liberación de:", "Eritropoyetina renal.", "Renina glomerular.", "Aldosterona cortical renal.", "Calcitriol suprarrenal.", "La eritropoyetina renal estimula la producción de eritrocitos en la médula ósea."],
  ["cito3-55", "Endocrino renal", "hard", "¿En qué segmento ocurre la segunda hidroxilación que produce calcitriol activo?", "Túbulo proximal renal.", "Túbulo distal renal.", "Conducto colector medular.", "Corpúsculo glomerular.", "Tras la primera hidroxilación hepática, la 1α-hidroxilasa renal actúa sobre todo en túbulos proximales."],
  ["cito3-56", "Urotelio", "medium", "Cuando la vejiga se distiende, ¿qué células superficiales conservan la barrera frente a la orina?", "Células sombrilla.", "Células basales.", "Células intermedias.", "Células intercaladas.", "Las células sombrilla del urotelio mantienen una barrera apical especializada durante el llenado."],
  ["cito3-57", "Urotelio", "hard", "¿Qué cambio permite ampliar la superficie apical de la célula sombrilla al llenarse la vejiga?", "Fusión de vesículas fusiformes con la membrana apical.", "Endocitosis de placas de uroplaquina desde la membrana apical.", "Proliferación inmediata de nuevas células basales uroteliales.", "Separación de las uniones entre células sombrilla adyacentes.", "Las vesículas fusiformes aportan placas de membrana a la superficie de las células sombrilla."],
  ["cito3-58", "Uréter", "medium", "Al llenarse la vejiga, ¿qué característica ayuda a impedir que la orina regrese al uréter?", "Trayecto oblicuo del uréter a través de la pared vesical.", "Trayecto perpendicular del uréter a través de la pared vesical.", "Apertura del meato ureteral por relajación del detrusor.", "Endurecimiento del urotelio en el orificio ureteral.", "El recorrido intramural oblicuo se comprime durante la distensión vesical."],
  ["cito3-59", "Vejiga y micción", "hard", "Para iniciar el vaciamiento voluntario, ¿qué combinación neuromuscular debe predominar?", "Contracción parasimpática del detrusor y relajación del esfínter externo.", "Relajación parasimpática del detrusor y contracción del esfínter externo.", "Contracción simpática del detrusor y contracción del esfínter externo.", "Relajación simpática del detrusor y relajación del esfínter interno.", "La micción combina contracción del músculo vesical y relajación voluntaria del esfínter externo."],
  ["cito3-60", "Uretra", "medium", "¿Qué segmento de la uretra masculina atraviesa el esfínter uretral externo?", "Uretra membranosa.", "Uretra prostática.", "Uretra esponjosa.", "Cuello vesical.", "La uretra membranosa cruza el espacio perineal profundo rodeada por el esfínter externo estriado."],
]

const statements: readonly [id: string, topic: string, statement: string, isTrue: boolean, explanation: string][] = [
  ["cito3-61", "Respiratorio · alvéolos", "Los neumocitos tipo II son más numerosos que los tipo I y, por ello, recubren la mayor parte de la superficie alveolar.", false, "Aunque los tipo II son más numerosos, las células planas tipo I cubren casi toda la superficie alveolar."],
  ["cito3-62", "Respiratorio · bronquiolos", "Al avanzar hacia bronquiolos terminales, aumenta la proporción de células de Clara mientras disminuye la de células ciliadas.", true, "Las células de Clara predominan progresivamente en los segmentos bronquiolares distales."],
  ["cito3-63", "Respiratorio · epitelio", "Las células de Kulchitsky poseen gránulos endocrinos, pero su secreción principal es el moco que desplazan los cilios.", false, "Son células neuroendocrinas; el moco corresponde a células caliciformes y su transporte a las ciliadas."],
  ["cito3-64", "Respiratorio · barrera", "En la zona más delgada de la barrera hematogaseosa, el cuerpo laminar del neumocito II separa el aire del endotelio capilar.", false, "La zona delgada incluye neumocito I, láminas basales y endotelio; el cuerpo laminar almacena surfactante dentro del tipo II."],
  ["cito3-65", "Respiratorio · pleura", "La pleura visceral está revestida por mesotelio apoyado sobre tejido conjuntivo.", true, "La pleura visceral es una serosa con mesotelio superficial y tejido conjuntivo subyacente."],
  ["cito3-66", "Respiratorio · olfato", "La región olfatoria normal carece de células caliciformes abundantes y presenta glándulas de Bowman en la lámina propia.", true, "Las glándulas olfatorias serosas distinguen la mucosa olfatoria de la respiratoria."],
  ["cito3-67", "Respiratorio · bronquios", "En los bronquios intrapulmonares, el cartílago aparece como placas discontinuas y no como los anillos en C de la tráquea.", true, "Los anillos traqueales pasan a placas cartilaginosas en el árbol bronquial intrapulmonar."],
  ["cito3-68", "Urinario · filtración", "El líquido que llega al espacio de Bowman ya tiene la composición final de la orina porque no sufrirá reabsorción tubular.", false, "El ultrafiltrado se modifica intensamente por reabsorción y secreción a lo largo de los túbulos."],
  ["cito3-69", "Urinario · mácula densa", "Las células de la mácula densa son células tubulares distales modificadas próximas al polo vascular.", true, "La mácula densa pertenece al túbulo distal y participa en el aparato yuxtaglomerular."],
  ["cito3-70", "Urinario · renina", "Las células yuxtaglomerulares que liberan renina derivan de músculo liso, sobre todo en la arteriola aferente.", true, "Son células musculares lisas vasculares modificadas con gránulos de renina."],
  ["cito3-71", "Urinario · mesangio", "Las células mesangiales solo existen dentro del glomérulo; no hay células mesangiales extraglomerulares.", false, "El aparato yuxtaglomerular también incluye células mesangiales extraglomerulares."],
  ["cito3-72", "Urinario · nefronas", "Las nefronas yuxtamedulares poseen asas largas que penetran en la médula y ayudan a concentrar la orina.", true, "Sus asas largas sostienen el gradiente osmótico medular."],
  ["cito3-73", "Urinario · filtro", "La barrera de filtración glomerular es funcionalmente estática: una vez formada, su permeabilidad ya no puede modificarse.", false, "La barrera es dinámica; la estructura y actividad de sus componentes pueden alterar la permeabilidad."],
  ["cito3-74", "Urinario · filtro", "Una gran cantidad de albúmina urinaria es compatible con una barrera glomerular intacta porque la albúmina se filtra libremente.", false, "La barrera restringe la albúmina; la albuminuria importante puede señalar lesión del filtro."],
]

const multipleChoice = createManualQuizBankFromRows(CITO_III_PARTIAL, multipleChoiceRows)

const trueFalse: HistologiaQuizQuestion[] = statements.map(([id, topic, question, isTrue, explanation]) => ({
  id: `quiz-${id}`,
  chapter: CITO_III_PARTIAL,
  topic,
  difficulty: "hard",
  type: "single",
  question,
  options: ["Verdadero", "Falso"],
  correctAnswers: [isTrue ? 0 : 1],
  explanation,
  tags: [CITO_III_PARTIAL, topic, "Banco manual"]
}))

export const citoIIIPrePartialQuestions: HistologiaQuizQuestion[] = [
  ...multipleChoice,
  ...trueFalse
]
