type Difficulty = "easy" | "medium" | "hard"

type Seed = {
  chapter: string
  topic: string
  difficulty: Difficulty
  question: string
  options: [string, string, string, string]
  correctAnswer: number
  explanation: string
}

export type SemiologiaQuestion = {
  id: string
  chapter: string
  topic: string
  tags: string[]
  difficulty: Difficulty
  type: "single"
  question: string
  options: string[]
  correctAnswers: number[]
  explanation: string
}

const seeds: Seed[] = [
  { chapter: "Bloque 1", topic: "Fundamentos", difficulty: "easy", question: "Un paciente refiere náusea, pero no existe una medida objetiva que la cuantifique. ¿Cómo se clasifica este dato?", options: ["Signo", "Síntoma", "Lesión", "Secuela"], correctAnswer: 1, explanation: "La náusea referida es una experiencia subjetiva, por lo que corresponde a un síntoma." },
  { chapter: "Bloque 1", topic: "Fundamentos", difficulty: "medium", question: "¿Cuál situación representa mejor un estado subclínico?", options: ["Fiebre de 39 °C", "Cambios moleculares antes de síntomas perceptibles", "Parálisis residual después de un ACV", "Dolor intenso por absceso"], correctAnswer: 1, explanation: "En el estado subclínico ya hay cambios biológicos, pero aún no son perceptibles." },
  { chapter: "Bloque 1", topic: "Fundamentos", difficulty: "medium", question: "¿Cuál pareja está correctamente relacionada?", options: ["Etiología—pronóstico esperado", "Patogénesis—mecanismo de desarrollo", "Secuela—causa inicial", "Síntoma—hallazgo cuantificable"], correctAnswer: 1, explanation: "La patogénesis describe cómo se desarrolla la enfermedad." },
  { chapter: "Bloque 1", topic: "Factores", difficulty: "easy", question: "¿Cuál es un factor extrínseco de enfermedad?", options: ["Edad", "Genotipo", "Radiación solar", "Respuesta inmunitaria"], correctAnswer: 2, explanation: "La radiación solar es un agente externo al paciente." },
  { chapter: "Bloque 1", topic: "Genética", difficulty: "medium", question: "Dos células poseen el mismo genoma, pero cumplen funciones distintas. ¿Qué proceso explica mejor esta diferencia?", options: ["Cariorrexis", "Diferenciación celular", "Opsonización", "Diapédesis"], correctAnswer: 1, explanation: "La diferenciación permite que cada función celular active grupos distintos de genes." },
  { chapter: "Bloque 1", topic: "Adaptación", difficulty: "easy", question: "El aumento del tamaño uterino durante el embarazo ejemplifica principalmente:", options: ["Atrofia", "Metaplasia", "Hipertrofia fisiológica", "Necrosis coagulativa"], correctAnswer: 2, explanation: "Es un ejemplo clásico de hipertrofia fisiológica." },
  { chapter: "Bloque 1", topic: "Adaptación", difficulty: "medium", question: "¿Cuál cambio consiste en sustituir reversiblemente un tipo de célula madura por otro?", options: ["Hiperplasia", "Metaplasia", "Displasia", "Apoptosis"], correctAnswer: 1, explanation: "Esa es la definición de metaplasia." },
  { chapter: "Bloque 1", topic: "Lesión celular", difficulty: "medium", question: "Una célula aumenta de volumen por entrada de agua tras una agresión leve. ¿Qué cambio describe mejor el hallazgo?", options: ["Tumefacción celular", "Calcificación", "Cariolisis", "Fibrosis"], correctAnswer: 0, explanation: "La tumefacción es un cambio reversible temprano por alteración del equilibrio de agua." },
  { chapter: "Bloque 1", topic: "Muerte celular", difficulty: "medium", question: "¿Qué hallazgo favorece necrosis sobre apoptosis?", options: ["Ausencia de inflamación", "Respuesta inflamatoria circundante", "Eliminación programada", "Muerte de una célula aislada"], correctAnswer: 1, explanation: "La necrosis suele liberar contenido celular y desencadenar inflamación." },
  { chapter: "Bloque 1", topic: "Muerte celular", difficulty: "hard", question: "En un corte, la cromatina aparece condensada en un núcleo pequeño y oscuro. ¿Qué cambio es?", options: ["Cariolisis", "Picnosis", "Cariorrexis", "Metaplasia"], correctAnswer: 1, explanation: "La picnosis es la contracción y condensación nuclear." },
  { chapter: "Bloque 1", topic: "Muerte celular", difficulty: "hard", question: "Un infarto conserva durante un tiempo el contorno general del tejido afectado. ¿Qué patrón de necrosis es más probable?", options: ["Licuefactiva", "Caseosa", "Coagulativa", "Grasa"], correctAnswer: 2, explanation: "La necrosis coagulativa conserva temporalmente la arquitectura tisular." },
  { chapter: "Bloque 1", topic: "Muerte celular", difficulty: "medium", question: "¿Qué patrón se asocia clásicamente con tuberculosis?", options: ["Caseoso", "Fibrinoso", "Seroso", "Gangrena seca"], correctAnswer: 0, explanation: "La tuberculosis se relaciona clásicamente con necrosis caseosa." },
  { chapter: "Bloque 1", topic: "Gangrena", difficulty: "medium", question: "Una extremidad isquémica presenta infección bacteriana y secreción purulenta. ¿Cuál diagnóstico describe mejor el proceso?", options: ["Gangrena seca", "Gangrena húmeda", "Apoptosis", "Metaplasia"], correctAnswer: 1, explanation: "La invasión bacteriana sobre tejido isquémico caracteriza la gangrena húmeda." },

  { chapter: "Bloque 2", topic: "Inflamación", difficulty: "easy", question: "¿Qué cambio vascular explica principalmente el rubor y el calor?", options: ["Vasoconstricción", "Vasodilatación", "Trombocitopenia", "Linfopenia"], correctAnswer: 1, explanation: "La vasodilatación incrementa el flujo sanguíneo local." },
  { chapter: "Bloque 2", topic: "Inflamación", difficulty: "medium", question: "¿Qué mecanismo explica mejor el edema inflamatorio?", options: ["Menor presión arterial", "Mayor permeabilidad vascular", "Menor flujo linfático basal", "Aumento de eritrocitos"], correctAnswer: 1, explanation: "La salida de proteínas y agua por aumento de permeabilidad produce edema." },
  { chapter: "Bloque 2", topic: "Inflamación", difficulty: "medium", question: "¿Cuál situación puede causar inflamación sin infección?", options: ["Trauma estéril", "Bacteriemia", "Micosis", "Parasitosis"], correctAnswer: 0, explanation: "La inflamación también responde a agentes físicos y daño tisular estéril." },
  { chapter: "Bloque 2", topic: "Exudado", difficulty: "medium", question: "Un líquido inflamatorio rico en fibrinógeno se clasifica como:", options: ["Seroso", "Fibrinoso", "Transudado", "Hemorrágico fisiológico"], correctAnswer: 1, explanation: "La abundancia de fibrinógeno y fibrina caracteriza el exudado fibrinoso." },
  { chapter: "Bloque 2", topic: "Migración", difficulty: "hard", question: "¿Cuál secuencia representa mejor la salida leucocitaria del vaso?", options: ["Diapédesis→marginación→adhesión", "Marginación→adhesión→diapédesis", "Quimiotaxis→necrosis→marginación", "Opsonización→adhesión→fibrosis"], correctAnswer: 1, explanation: "Primero ocurre marginación y adhesión; después, migración transendotelial o diapédesis." },
  { chapter: "Bloque 2", topic: "Migración", difficulty: "medium", question: "¿Qué dirige a un neutrófilo hacia una concentración mayor de señales químicas?", options: ["Osmosis", "Quimiotaxis", "Metaplasia", "Angiogénesis"], correctAnswer: 1, explanation: "La quimiotaxis es el movimiento dirigido por gradientes químicos." },
  { chapter: "Bloque 2", topic: "Leucocitos", difficulty: "easy", question: "¿Cuál célula suele llegar primero a una infección bacteriana aguda?", options: ["Linfocito", "Neutrófilo", "Célula plasmática", "Eosinófilo"], correctAnswer: 1, explanation: "Los neutrófilos predominan en la fase inicial de muchas inflamaciones bacterianas agudas." },
  { chapter: "Bloque 2", topic: "Leucocitos", difficulty: "medium", question: "Un paciente con parasitosis presenta alteración de la fórmula diferencial. ¿Qué célula es más probable que aumente?", options: ["Eosinófilo", "Plaqueta", "Eritrocito", "Basófilo exclusivamente"], correctAnswer: 0, explanation: "Los eosinófilos participan de manera destacada en respuestas contra parásitos." },
  { chapter: "Bloque 2", topic: "Leucocitos", difficulty: "medium", question: "¿Qué sustancias se encuentran en los gránulos de los basófilos?", options: ["Insulina y glucagón", "Histamina y heparina", "Colágeno y elastina", "Fibrina y queratina"], correctAnswer: 1, explanation: "Los basófilos almacenan histamina y heparina." },
  { chapter: "Bloque 2", topic: "Fagocitosis", difficulty: "hard", question: "¿Qué evento facilita que un fagocito reconozca y capture una bacteria?", options: ["Opsonización", "Atrofia", "Cariolisis", "Angiogénesis"], correctAnswer: 0, explanation: "Las opsoninas recubren el microorganismo y facilitan su reconocimiento." },
  { chapter: "Bloque 2", topic: "Fagocitosis", difficulty: "medium", question: "La fusión del fagosoma con lisosomas forma un:", options: ["Desmosoma", "Fagolisosoma", "Cromosoma", "Exudado"], correctAnswer: 1, explanation: "En el fagolisosoma se destruye el material ingerido." },
  { chapter: "Bloque 2", topic: "Macrófagos", difficulty: "medium", question: "¿Qué nombre reciben los macrófagos residentes del hígado?", options: ["Células de Langerhans", "Células de Kupffer", "Células de Schwann", "Células de Merkel"], correctAnswer: 1, explanation: "Los macrófagos hepáticos son las células de Kupffer." },
  { chapter: "Bloque 2", topic: "Células gigantes", difficulty: "hard", question: "¿Qué disposición nuclear orienta a una célula gigante de Langhans?", options: ["Núcleos periféricos en herradura", "Un solo núcleo central", "Núcleos ausentes", "Núcleos dentro de vacuolas"], correctAnswer: 0, explanation: "En las células de Langhans los núcleos se agrupan hacia la periferia." },
  { chapter: "Bloque 2", topic: "Hematología", difficulty: "medium", question: "¿Cuál fórmula diferencial es correcta?", options: ["Neutrófilos 50–70 %", "Eosinófilos 20–40 %", "Basófilos 10–20 %", "Monocitos 30–50 %"], correctAnswer: 0, explanation: "El rango para neutrófilos es 50–70 %." },
  { chapter: "Bloque 2", topic: "Plaquetas", difficulty: "medium", question: "¿Por qué la aspirina aumenta el riesgo de sangrado?", options: ["Eleva fibrinógeno", "Reduce tromboxano A₂", "Aumenta eritrocitos", "Activa vitamina K"], correctAnswer: 1, explanation: "La inhibición de ciclooxigenasa reduce tromboxano A₂ y la agregación plaquetaria." },
  { chapter: "Bloque 2", topic: "Inflamación crónica", difficulty: "hard", question: "¿Qué combinación caracteriza mejor la inflamación crónica?", options: ["Neutrófilos sin reparación", "Macrófagos, destrucción y fibrosis", "Solo vasodilatación", "Ausencia de lesión tisular"], correctAnswer: 1, explanation: "La crónica combina infiltrado mononuclear, destrucción y reparación con fibrosis." },

  { chapter: "Bloque 3", topic: "Ficha clínica", difficulty: "easy", question: "¿Cómo debe registrarse el motivo de consulta?", options: ["Solo con términos técnicos", "Con las palabras del paciente", "Después del tratamiento", "Únicamente si existe dolor"], correctAnswer: 1, explanation: "Debe preservarse la expresión original del paciente, idealmente entre comillas." },
  { chapter: "Bloque 3", topic: "Medicamentos", difficulty: "medium", question: "¿Qué antecedente farmacológico eleva el riesgo de osteonecrosis maxilar?", options: ["Antihistamínicos", "Bifosfonatos o denosumab", "Antiácidos", "Paracetamol ocasional"], correctAnswer: 1, explanation: "Los antirresortivos y ciertos monoclonales se asocian a osteonecrosis de los maxilares." },
  { chapter: "Bloque 3", topic: "ASA", difficulty: "medium", question: "Un paciente con enfermedad sistémica grave que limita su actividad, pero no amenaza constantemente su vida, corresponde a:", options: ["ASA I", "ASA II", "ASA III", "ASA V"], correctAnswer: 2, explanation: "Esa descripción corresponde a ASA III." },
  { chapter: "Bloque 3", topic: "Cardiovascular", difficulty: "hard", question: "¿Qué antecedente obliga a valorar riesgo de endocarditis y necesidad de consulta médica?", options: ["Efélides", "Prótesis valvular", "Queilitis exfoliativa", "Melasma"], correctAnswer: 1, explanation: "Las prótesis valvulares son relevantes al valorar riesgo de endocarditis." },
  { chapter: "Bloque 3", topic: "Cardiovascular", difficulty: "medium", question: "¿Cuál de los siguientes es un antiagregante plaquetario?", options: ["Warfarina", "Rivaroxabán", "Clopidogrel", "Denosumab"], correctAnswer: 2, explanation: "Clopidogrel inhibe la activación y agregación plaquetarias." },
  { chapter: "Bloque 3", topic: "Medicamentos", difficulty: "medium", question: "Un paciente con buena higiene presenta agrandamiento gingival. ¿Qué medicamento es un antecedente relevante?", options: ["Nifedipina", "Omeprazol", "Amoxicilina", "Acetaminofén"], correctAnswer: 0, explanation: "Nifedipina puede producir agrandamiento gingival." },
  { chapter: "Bloque 3", topic: "Diabetes", difficulty: "easy", question: "¿Cuál conjunto corresponde a las tres polis clásicas de diabetes?", options: ["Polidipsia, polifagia y poliuria", "Disfagia, disnea y disuria", "Parestesia, petequia y prurito", "Fiebre, dolor y edema"], correctAnswer: 0, explanation: "Las tres polis son polidipsia, polifagia y poliuria." },
  { chapter: "Bloque 3", topic: "Diabetes", difficulty: "medium", question: "¿Qué prueba refleja mejor el control glucémico aproximado de los últimos tres meses?", options: ["TP", "HbA1c", "Sialometría", "Hematocrito"], correctAnswer: 1, explanation: "La hemoglobina glucosilada refleja el promedio glucémico de varios meses." },
  { chapter: "Bloque 3", topic: "Sjögren", difficulty: "medium", question: "Una paciente dice sentir la boca seca, aunque todavía no se ha medido el flujo salival. ¿Qué término es correcto?", options: ["Sialadenitis", "Xerostomía", "Sialorrea", "Displasia"], correctAnswer: 1, explanation: "Xerostomía es la sensación subjetiva de boca seca." },
  { chapter: "Bloque 3", topic: "Sjögren", difficulty: "hard", question: "¿Qué estudio cuantifica directamente la producción salival?", options: ["Diascopía", "Sialometría", "Test de Schirmer", "INR"], correctAnswer: 1, explanation: "La sialometría mide el flujo o volumen de saliva." },
  { chapter: "Bloque 3", topic: "Sjögren", difficulty: "hard", question: "¿Por qué suele preferirse una biopsia de glándula salival menor a una de parótida?", options: ["La parótida no contiene tejido glandular", "Reduce el riesgo de lesionar el nervio facial", "Las menores producen más saliva", "Evita cualquier necesidad de histología"], correctAnswer: 1, explanation: "El abordaje de parótida implica mayor riesgo para el nervio facial." },
  { chapter: "Bloque 3", topic: "Respiratorio", difficulty: "medium", question: "¿Qué combinación hace sospechar tuberculosis activa?", options: ["Melasma y prurito", "Hemoptisis, fiebre y sudoración nocturna", "Polidipsia y poliuria", "Equimosis aislada"], correctAnswer: 1, explanation: "La combinación de síntomas constitucionales y hemoptisis requiere evaluación médica." },
  { chapter: "Bloque 3", topic: "Respiratorio", difficulty: "medium", question: "¿Qué medida previene candidiasis por un inhalador con corticosteroide?", options: ["No beber agua", "Enjuagarse después de usarlo", "Tomar aspirina", "Suspenderlo sin consulta"], correctAnswer: 1, explanation: "El enjuague reduce el residuo de esteroide en la cavidad oral." },
  { chapter: "Bloque 3", topic: "Gastrointestinal", difficulty: "medium", question: "¿Qué hallazgo oral puede orientar a reflujo gastroesofágico crónico?", options: ["Erosión dental", "Acantosis nigricans", "Petequias por sí solas", "Gránulos de Fordyce"], correctAnswer: 0, explanation: "El ácido gástrico puede erosionar químicamente el esmalte." },
  { chapter: "Bloque 3", topic: "Hematología", difficulty: "hard", question: "Ante petequias generalizadas sin trauma, ¿qué conjunto de pruebas es más pertinente?", options: ["TP, TPT, INR y plaquetas", "HbA1c y sialometría", "Radiografía panorámica solamente", "Diascopía y test de Schirmer"], correctAnswer: 0, explanation: "Estas pruebas exploran coagulación y número de plaquetas." },

  { chapter: "Bloque 4", topic: "Ganglios", difficulty: "medium", question: "¿Qué hallazgo ganglionar merece mayor preocupación?", options: ["Móvil y doloroso durante gripe", "Fijo, duro y persistente", "Pequeño y transitorio", "Bilateral después de infección"], correctAnswer: 1, explanation: "La fijación y dureza persistentes son señales de alarma." },
  { chapter: "Bloque 4", topic: "Cuello", difficulty: "medium", question: "Una masa cervical en la línea media sigue el trayecto embrionario de la tiroides. ¿Qué lesión es probable?", options: ["Quiste tirogloso", "Queratosis seborreica", "Efélide", "Angioma cherry"], correctAnswer: 0, explanation: "El quiste del conducto tirogloso aparece típicamente en la línea media." },
  { chapter: "Bloque 4", topic: "Pigmentadas", difficulty: "medium", question: "Múltiples máculas pigmentadas periorales pueden asociarse a:", options: ["Peutz-Jeghers", "EPOC", "Hemofilia", "Tuberculosis"], correctAnswer: 0, explanation: "La pigmentación mucocutánea es característica del síndrome de Peutz-Jeghers." },
  { chapter: "Bloque 4", topic: "Pigmentadas", difficulty: "medium", question: "¿Qué lesión es una mácula café adquirida por daño solar acumulado?", options: ["Léntigo solar", "Acrocordón", "Quiste epidermoide", "Rinofima"], correctAnswer: 0, explanation: "El léntigo solar es una mácula por exposición ultravioleta crónica." },
  { chapter: "Bloque 4", topic: "Vasculares", difficulty: "hard", question: "Una lesión roja palidece al presionarla con una lámina transparente. ¿Qué indica?", options: ["Sangre extravasada", "Componente vascular intraluminal", "Necrosis caseosa", "Lesión queratósica"], correctAnswer: 1, explanation: "El blanqueamiento en diascopía sugiere sangre contenida en vasos comprimibles." },
  { chapter: "Bloque 4", topic: "Vasculares", difficulty: "hard", question: "¿Por qué una equimosis produce diascopía negativa?", options: ["No contiene sangre", "La sangre está extravasada", "Es una lesión epitelial", "Siempre está calcificada"], correctAnswer: 1, explanation: "La presión no desplaza sangre que ya salió de los vasos." },
  { chapter: "Bloque 4", topic: "Rosácea", difficulty: "medium", question: "¿Qué manifestación corresponde a una forma avanzada de rosácea?", options: ["Rinofima", "Mácula melanótica", "Fordyce", "Fisura labial"], correctAnswer: 0, explanation: "El rinofima es engrosamiento nasal asociado a rosácea avanzada." },
  { chapter: "Bloque 4", topic: "Metabólicas", difficulty: "medium", question: "Oscurecimiento aterciopelado y engrosado en cuello y axilas sugiere:", options: ["Acantosis nigricans", "Queilitis actínica", "Telangiectasia", "Efélides"], correctAnswer: 0, explanation: "La acantosis nigricans se asocia con frecuencia a resistencia a la insulina." },
  { chapter: "Bloque 4", topic: "Labios", difficulty: "hard", question: "¿Qué lesión del labio exige vigilancia por su potencial de transformación maligna?", options: ["Gránulos de Fordyce", "Queilitis actínica", "Mácula melanótica estable", "Angioma cherry"], correctAnswer: 1, explanation: "La queilitis actínica es una lesión potencialmente maligna causada por daño solar crónico." },
  { chapter: "Bloque 4", topic: "Labios", difficulty: "easy", question: "Puntos amarillentos asintomáticos en mucosa labial, sin potencial maligno, corresponden a:", options: ["Gránulos de Fordyce", "Petequias", "Melasma", "Rinofima"], correctAnswer: 0, explanation: "Los gránulos de Fordyce son glándulas sebáceas ectópicas benignas." },
  { chapter: "Bloque 4", topic: "Piel", difficulty: "medium", question: "Una placa café, queratósica y con apariencia de estar adherida a la piel corresponde a:", options: ["Queratosis seborreica", "Telangiectasia", "Equimosis", "Quiste tirogloso"], correctAnswer: 0, explanation: "Esa apariencia es típica de la queratosis seborreica." },
  { chapter: "Bloque 4", topic: "Piel", difficulty: "medium", question: "La presencia de numerosos acrocordones puede motivar evaluación de:", options: ["Resistencia a la insulina", "Tuberculosis activa", "Hemofilia A", "Fiebre reumática"], correctAnswer: 0, explanation: "Múltiples acrocordones pueden asociarse a obesidad y alteraciones metabólicas." },

  { chapter: "Bloque 1", topic: "Fundamentos", difficulty: "medium", question: "Un paciente terminó el tratamiento, pero conserva una parálisis que antes no tenía. ¿Cómo se denomina esta alteración persistente?", options: ["Complicación", "Secuela", "Estado subclínico", "Resolución"], correctAnswer: 1, explanation: "Una secuela permanece después de la enfermedad e impide volver por completo al estado previo." },
  { chapter: "Bloque 1", topic: "Fundamentos", difficulty: "medium", question: "Durante una enfermedad surge una condición inesperada que empeora el pronóstico. ¿Qué término corresponde?", options: ["Síndrome", "Complicación", "Etiología", "Fenotipo"], correctAnswer: 1, explanation: "La complicación es adicional e inesperada y empeora el curso de la enfermedad." },
  { chapter: "Bloque 1", topic: "Fundamentos", difficulty: "easy", question: "¿Cuál hallazgo es un signo y no un síntoma?", options: ["Mareo referido", "Dolor dental", "Temperatura de 39 °C", "Náusea"], correctAnswer: 2, explanation: "La temperatura elevada puede medirse y corroborarse objetivamente." },
  { chapter: "Bloque 1", topic: "Factores", difficulty: "hard", question: "Una paciente con anemia desarrolla hipoxia tisular. ¿Cuál mecanismo explica mejor la relación?", options: ["Mayor viscosidad sanguínea", "Menor capacidad de transporte de oxígeno", "Exceso de anticuerpos", "Aumento de la permeabilidad vascular"], correctAnswer: 1, explanation: "La anemia reduce la cantidad o capacidad funcional de hemoglobina disponible para transportar oxígeno." },
  { chapter: "Bloque 1", topic: "Factores", difficulty: "medium", question: "¿Cuál combinación contiene únicamente factores intrínsecos?", options: ["Edad, genética y estado nutricional", "Radiación, tabaco y trauma", "Virus, hongos y pesticidas", "Temperatura, quimioterapia y toxinas"], correctAnswer: 0, explanation: "Edad, constitución genética y nutrición son características propias del paciente." },
  { chapter: "Bloque 1", topic: "Inmunidad", difficulty: "medium", question: "¿Qué alteración básica comparten Sjögren, CREST y artritis reumatoide?", options: ["Invasión bacteriana", "Pérdida de tolerancia a lo propio", "Oclusión arterial", "Deficiencia de plaquetas"], correctAnswer: 1, explanation: "Son enfermedades autoinmunes en las que el sistema inmune ataca tejidos propios." },
  { chapter: "Bloque 1", topic: "Homeostasis", difficulty: "hard", question: "Una agresión leve se elimina y la célula recupera su funcionamiento. ¿Qué propiedad permitió este desenlace?", options: ["Inmunovigilancia exclusivamente", "Homeostasis y adaptación", "Cariorrexis", "Metástasis"], correctAnswer: 1, explanation: "La adaptación celular puede compensar agresiones y restablecer la homeostasis si el daño es reversible." },
  { chapter: "Bloque 1", topic: "Genética", difficulty: "medium", question: "¿Qué afirmación explica por qué una neurona y un hepatocito son distintos pese a contener el mismo ADN?", options: ["Tienen diferente número de cromosomas", "Expresan regiones distintas del genoma", "Uno surge por meiosis", "Sus genes ocupan loci diferentes"], correctAnswer: 1, explanation: "La función y la ubicación determinan qué genes expresa cada célula diferenciada." },
  { chapter: "Bloque 1", topic: "Genética", difficulty: "easy", question: "Una célula germinal debe reducir su número cromosómico antes de formar un gameto. ¿Qué división realiza?", options: ["Mitosis", "Meiosis", "Fisión", "Apoptosis"], correctAnswer: 1, explanation: "La meiosis reduce a la mitad el número de cromosomas para producir gametos." },
  { chapter: "Bloque 1", topic: "Lesión celular", difficulty: "hard", question: "¿Cuál secuencia describe mejor la evolución de una lesión celular?", options: ["Síntoma→lesión molecular→cambio morfológico", "Lesión bioquímica→cambio morfológico→signos o síntomas", "Necrosis→homeostasis→etiología", "Signo→mutación→resolución"], correctAnswer: 1, explanation: "Los cambios metabólicos microscópicos pueden preceder la morfología visible y luego la expresión clínica." },
  { chapter: "Bloque 1", topic: "Adaptación", difficulty: "medium", question: "Un órgano disminuye porque sus células reducen su tamaño y algunas desaparecen. ¿Qué adaptación representa?", options: ["Hiperplasia", "Atrofia", "Metaplasia", "Hipertrofia"], correctAnswer: 1, explanation: "La atrofia reduce el tamaño del órgano mediante disminución del tamaño y/o número celular." },
  { chapter: "Bloque 1", topic: "Lesión celular", difficulty: "medium", question: "¿Cuál hallazgo describe específicamente degeneración vacuolar?", options: ["Grasa en hepatocitos", "Agua acumulada en vacuolas", "Fragmentación nuclear", "Fibrina intersticial"], correctAnswer: 1, explanation: "La degeneración vacuolar es una forma de acumulación intracelular de agua en vacuolas." },
  { chapter: "Bloque 1", topic: "Muerte celular", difficulty: "hard", question: "En un tejido muerto el núcleo se fragmenta y sus restos se dispersan. ¿Qué cambio nuclear se observa?", options: ["Picnosis", "Cariorrexis", "Cariolisis", "Metaplasia"], correctAnswer: 1, explanation: "La cariorrexis corresponde a fragmentación nuclear y dispersión de los restos." },
  { chapter: "Bloque 1", topic: "Muerte celular", difficulty: "medium", question: "Tras una lesión, el tejido es digerido por completo y queda una cavidad. ¿Qué patrón es compatible?", options: ["Coagulativo", "Licuefactivo", "Caseoso", "Gangrena seca"], correctAnswer: 1, explanation: "La necrosis licuefactiva digiere el tejido muerto y puede dejar un espacio vacío." },
  { chapter: "Bloque 1", topic: "Gangrena", difficulty: "hard", question: "Una extremidad presenta oclusión arterial, tejido seco y ausencia de secreción purulenta. ¿Qué proceso es más probable?", options: ["Gangrena húmeda", "Gangrena seca", "Necrosis caseosa", "Apoptosis fisiológica"], correctAnswer: 1, explanation: "La gangrena seca se relaciona con isquemia por oclusión arterial sin la invasión bacteriana propia de la húmeda." },

  { chapter: "Bloque 2", topic: "Inflamación", difficulty: "hard", question: "¿Qué resultado contradice los objetivos de una respuesta inflamatoria eficaz?", options: ["Contener el agente", "Diluir toxinas", "Impedir toda reparación", "Eliminar tejido dañado"], correctAnswer: 2, explanation: "La inflamación busca iniciar reparación, no impedirla." },
  { chapter: "Bloque 2", topic: "Inflamación", difficulty: "medium", question: "Una quemadura solar sin microorganismos produce eritema y dolor. ¿Qué demuestra?", options: ["Toda inflamación es infección", "Un agente físico puede iniciar inflamación", "El edema requiere bacterias", "La necrosis nunca inflama"], correctAnswer: 1, explanation: "La radiación solar es un agente físico capaz de activar inflamación estéril." },
  { chapter: "Bloque 2", topic: "Ganglios", difficulty: "medium", question: "Durante una faringitis aparece un ganglio cervical móvil y sensible. ¿Cuál interpretación inicial es más coherente?", options: ["Metástasis obligatoria", "Linfadenopatía reactiva", "Quiste tirogloso", "Acantosis nigricans"], correctAnswer: 1, explanation: "La movilidad y el contexto infeccioso favorecen un proceso reactivo." },
  { chapter: "Bloque 2", topic: "Exudado", difficulty: "hard", question: "¿Qué componente del exudado inicia una matriz provisional para la reparación?", options: ["Fibrina", "Melanina", "Queratina", "Insulina"], correctAnswer: 0, explanation: "El fibrinógeno sale del vaso y se convierte en fibrina, contribuyendo al inicio de la reparación." },
  { chapter: "Bloque 2", topic: "Exudado", difficulty: "medium", question: "Un exudado con pocas células y asociado a inflamación leve se clasifica como:", options: ["Supurativo", "Seroso", "Fibrinoso", "Caseoso"], correctAnswer: 1, explanation: "El exudado seroso contiene pocas células y aparece en procesos leves." },
  { chapter: "Bloque 2", topic: "Exudado", difficulty: "medium", question: "La presencia de microorganismos, abundantes leucocitos y pus orienta a exudado:", options: ["Seroso", "Fibrinoso", "Supurativo", "Subclínico"], correctAnswer: 2, explanation: "El material purulento y los microorganismos caracterizan el exudado supurativo." },
  { chapter: "Bloque 2", topic: "Migración", difficulty: "hard", question: "Los leucocitos aparecen alineados sobre el endotelio antes de atravesarlo. ¿En qué etapa están?", options: ["Quimiotaxis", "Pavimentación", "Opsonización", "Fagocitosis"], correctAnswer: 1, explanation: "La pavimentación describe la alineación y adhesión de numerosos leucocitos al endotelio." },
  { chapter: "Bloque 2", topic: "Respuesta inflamatoria", difficulty: "hard", question: "Después de eliminar el agente, ¿qué etapa evita que la propia inflamación continúe dañando al huésped?", options: ["Reconocimiento", "Regulación", "Marginación", "Picnosis"], correctAnswer: 1, explanation: "La regulación limita la respuesta y permite recuperar la homeostasis." },
  { chapter: "Bloque 2", topic: "Hematología", difficulty: "medium", question: "Una fórmula diferencial reporta eosinófilos de 3 %. ¿Cómo se interpreta?", options: ["Dentro del rango", "Eosinopenia extrema", "Leucocitosis", "Trombocitosis"], correctAnswer: 0, explanation: "El rango de eosinófilos es 1–4 %." },
  { chapter: "Bloque 2", topic: "Hematología", difficulty: "hard", question: "¿Cuál resultado está fuera de los rangos normales?", options: ["Linfocitos 30 %", "Monocitos 6 %", "Neutrófilos 60 %", "Basófilos 8 %"], correctAnswer: 3, explanation: "Los basófilos aparecen alrededor de 0.5 %, no 8 %." },
  { chapter: "Bloque 2", topic: "Neutrófilos", difficulty: "medium", question: "¿Qué característica NO corresponde al neutrófilo circulante?", options: ["Movimiento ameboide", "Gránulos con lisozima", "División activa en sangre", "Fagocitosis bacteriana"], correctAnswer: 2, explanation: "Una vez en la sangre, los neutrófilos ya no se dividen." },
  { chapter: "Bloque 2", topic: "Fagocitosis", difficulty: "hard", question: "Una bacteria ya fue englobada, pero todavía no se fusionó con lisosomas. ¿Dónde está?", options: ["Fagolisosoma", "Fagosoma", "Exudado", "Locus"], correctAnswer: 1, explanation: "La vesícula de ingestión inicial es el fagosoma; tras fusionarse con lisosomas se convierte en fagolisosoma." },
  { chapter: "Bloque 2", topic: "Macrófagos", difficulty: "medium", question: "Un monocito migra al tejido conectivo y se diferencia. ¿Cómo se denomina allí?", options: ["Histiocito", "Célula de Kupffer", "Basófilo", "Megacariocito"], correctAnswer: 0, explanation: "Los macrófagos residentes del tejido conectivo se denominan histiocitos." },
  { chapter: "Bloque 2", topic: "Macrófagos", difficulty: "medium", question: "¿Qué nombre recibe un macrófago ubicado en los alvéolos?", options: ["Macrófago linfoide", "Macrófago alveolar", "Célula de Langhans", "Célula plasmática"], correctAnswer: 1, explanation: "En el pulmón, los macrófagos residentes son alveolares." },
  { chapter: "Bloque 2", topic: "Células gigantes", difficulty: "hard", question: "Una célula gigante presenta muchos núcleos dispersos sin patrón periférico. ¿Cuál tipo favorece?", options: ["Langhans", "Cuerpo extraño", "Kupffer", "Plasmática"], correctAnswer: 1, explanation: "Las células gigantes de cuerpo extraño muestran núcleos distribuidos por el citoplasma." },
  { chapter: "Bloque 2", topic: "Plaquetas", difficulty: "medium", question: "¿Cuál es el estímulo inmediato para activar plaquetas en un vaso lesionado?", options: ["Contacto con matriz subendotelial", "Aumento de glucemia", "Luz ultravioleta", "Producción de saliva"], correctAnswer: 0, explanation: "La exposición de matriz subendotelial permite adhesión y activación plaquetaria." },
  { chapter: "Bloque 2", topic: "Plaquetas", difficulty: "hard", question: "Un recuento de 18,000 plaquetas/µL implica principalmente riesgo de:", options: ["Sangrado espontáneo", "Hipertrofia", "Leucocitosis", "Hiperglucemia"], correctAnswer: 0, explanation: "Por debajo de 20,000 pueden aparecer hemorragias espontáneas, incluido sangrado gingival." },
  { chapter: "Bloque 2", topic: "Inflamación crónica", difficulty: "hard", question: "¿Qué pareja refleja reparación activa dentro de inflamación crónica?", options: ["Fibrosis y angiogénesis", "Picnosis y cariorrexis", "Marginación y diapédesis", "Polidipsia y poliuria"], correctAnswer: 0, explanation: "La reparación crónica combina depósito fibroso y formación de nuevos vasos." },

  { chapter: "Bloque 3", topic: "Ficha clínica", difficulty: "medium", question: "¿Cuál elemento vuelve éticamente válido un procedimiento antes de realizarlo?", options: ["Motivo de consulta", "Consentimiento informado", "Sialometría", "Clasificación ASA por sí sola"], correctAnswer: 1, explanation: "El consentimiento documenta comprensión, voluntariedad y aceptación del procedimiento." },
  { chapter: "Bloque 3", topic: "Ficha clínica", difficulty: "hard", question: "¿Qué modalidad combina un cuestionario predefinido con entrevista clínica?", options: ["No estructurada", "Mixta", "Subclínica", "Radiográfica"], correctAnswer: 1, explanation: "La historia mixta usa formulario y diálogo para completar o aclarar información." },
  { chapter: "Bloque 3", topic: "Medicamentos", difficulty: "medium", question: "¿Cuál conjunto debe registrarse para cada medicamento?", options: ["Color, forma y precio", "Nombre, dosis, frecuencia e indicación", "Solo nombre comercial", "Solo duración"], correctAnswer: 1, explanation: "Estos datos permiten reconocer interacciones, riesgos e indicación real del fármaco." },
  { chapter: "Bloque 3", topic: "ASA", difficulty: "medium", question: "Un paciente moribundo que probablemente no sobrevivirá sin la intervención corresponde a:", options: ["ASA II", "ASA III", "ASA IV", "ASA V"], correctAnswer: 3, explanation: "ASA V corresponde al paciente moribundo o terminal." },
  { chapter: "Bloque 3", topic: "Cardiovascular", difficulty: "hard", question: "¿Por qué la fiebre reumática previa importa en la historia odontológica?", options: ["Puede dejar daño valvular susceptible a endocarditis", "Siempre causa xerostomía", "Produce plaquetas altas", "Impide toda anestesia local"], correctAnswer: 0, explanation: "La infección estreptocócica puede dañar válvulas y aumentar la relevancia de bacteriemias transitorias." },
  { chapter: "Bloque 3", topic: "Cardiovascular", difficulty: "medium", question: "¿Cuál combinación clasifica correctamente los antitrombóticos?", options: ["Warfarina—antiagregante; clopidogrel—anticoagulante", "Rivaroxabán—anticoagulante; clopidogrel—antiagregante", "Denosumab—anticoagulante; aspirina—bifosfonato", "Nifedipina—antiagregante; warfarina—antibiótico"], correctAnswer: 1, explanation: "Rivaroxabán anticoagula y clopidogrel inhibe la agregación plaquetaria." },
  { chapter: "Bloque 3", topic: "Cardiovascular", difficulty: "hard", question: "Una panorámica muestra radiopacidad cervical cerca de C3–C4. ¿Qué posibilidad sistémica debe considerarse?", options: ["Placa ateromatosa carotídea", "Quiste tirogloso", "Sialolitiasis submandibular obligatoria", "Erosión dental"], correctAnswer: 0, explanation: "Esa localización puede corresponder a un ateroma carotídeo y amerita evaluación." },
  { chapter: "Bloque 3", topic: "Diabetes", difficulty: "medium", question: "Una HbA1c de 6.1 % corresponde a:", options: ["Normal", "Prediabetes", "Diabetes confirmada por ese valor", "Hipoglucemia"], correctAnswer: 1, explanation: "El intervalo de prediabetes es 5.7–6.4 %." },
  { chapter: "Bloque 3", topic: "Diabetes", difficulty: "hard", question: "¿Cuál dato representa control de meses y no una medición puntual?", options: ["Glucemia preprandial", "HbA1c", "Pulso", "INR"], correctAnswer: 1, explanation: "La HbA1c refleja el promedio glucémico aproximado de los últimos tres meses." },
  { chapter: "Bloque 3", topic: "Sjögren", difficulty: "medium", question: "Una paciente tiene xerostomía y queratoconjuntivitis sicca sin otra enfermedad del colágeno. ¿Qué forma se considera?", options: ["Sjögren secundario", "Sjögren primario", "CREST obligatorio", "Rosácea"], correctAnswer: 1, explanation: "El Sjögren primario aparece sin una enfermedad del colágeno asociada." },
  { chapter: "Bloque 3", topic: "Sjögren", difficulty: "hard", question: "¿Cuál prueba evalúa producción lagrimal y no salival?", options: ["Sialometría", "Test de Schirmer", "Sialografía", "Centellografía salival"], correctAnswer: 1, explanation: "Schirmer cuantifica la producción de lágrimas; sialometría mide saliva." },
  { chapter: "Bloque 3", topic: "Sjögren", difficulty: "hard", question: "¿Qué estudio usa contraste radiográfico para visualizar conductos salivales?", options: ["Sialografía", "Sialometría", "Diascopía", "Bitewing"], correctAnswer: 0, explanation: "La sialografía introduce contraste para delinear conductos y glándula." },
  { chapter: "Bloque 3", topic: "Sjögren", difficulty: "medium", question: "¿Qué cambio histológico se espera en glándula salival menor afectada crónicamente?", options: ["Infiltrado linfocitario", "Necrosis coagulativa aislada", "Ausencia de células inmunes", "Hiperplasia sebácea"], correctAnswer: 0, explanation: "El Sjögren crónico produce infiltración linfocitaria y pérdida progresiva de tejido funcional." },
  { chapter: "Bloque 3", topic: "Respiratorio", difficulty: "medium", question: "Un paciente usa inhalador con esteroide y presenta placas blancas removibles con ardor. ¿Qué proceso es probable?", options: ["Candidiasis pseudomembranosa", "Queilitis actínica", "Melasma", "Necrosis caseosa oral obligatoria"], correctAnswer: 0, explanation: "El depósito local de corticosteroide favorece candidiasis pseudomembranosa." },
  { chapter: "Bloque 3", topic: "Respiratorio", difficulty: "hard", question: "¿Qué dato clínico ayuda a distinguir dolor sinusal referido de un dolor dental puramente local?", options: ["Empeora al inclinarse hacia delante", "Mejora con exposición solar", "Palidece con diascopía", "Aumenta después de comer azúcar"], correctAnswer: 0, explanation: "El dolor facial de origen sinusal puede aumentar al inclinarse hacia delante." },
  { chapter: "Bloque 3", topic: "Gastrointestinal", difficulty: "hard", question: "Un paciente con úlcera requiere analgésico. ¿Qué grupo merece especial cautela?", options: ["AINE", "Antifúngicos tópicos", "Anestésicos locales sin alergia", "Fluoruros"], correctAnswer: 0, explanation: "Aspirina y otros AINE pueden agravar alteraciones gastrointestinales." },
  { chapter: "Bloque 3", topic: "Hepático", difficulty: "hard", question: "¿Qué dos procesos pueden alterarse en un paciente con hepatitis o ictericia?", options: ["Metabolismo farmacológico y coagulación", "Sialometría y melanogénesis", "Diascopía y esmalte", "Mitosis y meiosis"], correctAnswer: 0, explanation: "El hígado participa en metabolismo de fármacos y síntesis de factores de coagulación." },
  { chapter: "Bloque 3", topic: "Genitourinario", difficulty: "medium", question: "¿Por qué importa la función renal al prescribir?", options: ["Determina la excreción de muchos fármacos", "Controla el color del esmalte", "Produce plaquetas", "Evita toda bacteriemia"], correctAnswer: 0, explanation: "La insuficiencia renal puede reducir eliminación y aumentar exposición a medicamentos." },
  { chapter: "Bloque 3", topic: "Neurológico", difficulty: "hard", question: "Una parestesia nueva y sin causa dental evidente debe investigarse porque puede representar:", options: ["Invasión neural por una lesión maligna", "Efélides", "Hipertrofia fisiológica", "Exudado seroso"], correctAnswer: 0, explanation: "La invasión de un nervio por malignidad puede debutar como parestesia." },
  { chapter: "Bloque 3", topic: "Hematología", difficulty: "hard", question: "¿Qué valor de hemoglobina está dentro del rango femenino?", options: ["8 g/dL", "13 g/dL", "19 g/dL", "22 g/dL"], correctAnswer: 1, explanation: "El rango para mujeres es 12–16 g/dL." },

  { chapter: "Bloque 4", topic: "Preparación", difficulty: "medium", question: "Antes de palpar al paciente, ¿qué secuencia es más adecuada?", options: ["Palpar y luego medir signos", "Verificar estudios, preparar material, medir signos y usar protección", "Omitir radiografías siempre", "Realizar solo inspección visual"], correctAnswer: 1, explanation: "La preparación integra estudios, instrumental, signos vitales, higiene de manos y protección personal." },
  { chapter: "Bloque 4", topic: "Quistes", difficulty: "medium", question: "Un nódulo cutáneo lento, asintomático y cubierto por piel normal en un adulto joven se extirpa y envía a patología. ¿Qué lesión coincide?", options: ["Quiste epidermoide", "Melasma", "Petequia", "Acantosis nigricans"], correctAnswer: 0, explanation: "El quiste epidermoide o sebáceo tiene crecimiento lento, cavidad epitelial y manejo mediante escisión y patología." },
  { chapter: "Bloque 4", topic: "Piel", difficulty: "medium", question: "Pápulas amarillentas con una depresión central en un adulto mayor son más compatibles con:", options: ["Hiperplasia sebácea", "Angioma cherry", "Efélides", "Acrocordones"], correctAnswer: 0, explanation: "La umbilicación central y el color sebáceo orientan a hiperplasia sebácea." },
  { chapter: "Bloque 4", topic: "Pigmentadas", difficulty: "hard", question: "¿Qué rasgo distingue una mácula de una pápula?", options: ["La mácula es un cambio plano de color", "La mácula siempre es vascular", "La pápula nunca se eleva", "La mácula contiene pus"], correctAnswer: 0, explanation: "Mácula es un término morfológico para una alteración de color sin elevación." },
  { chapter: "Bloque 4", topic: "Pigmentadas", difficulty: "medium", question: "Pigmentación café simétrica en el tercio medio facial durante el embarazo sugiere:", options: ["Melasma", "Rinofima", "Equimosis", "Queratosis seborreica"], correctAnswer: 0, explanation: "El melasma se asocia a hormonas y exposición solar y afecta áreas faciales." },
  { chapter: "Bloque 4", topic: "Vasculares", difficulty: "hard", question: "Numerosos puntos rojos aparecieron tras vómitos intensos. ¿Cuál lesión explica mejor el hallazgo?", options: ["Petequias", "Telangiectasias", "Acrocordones", "Léntigos"], correctAnswer: 0, explanation: "El aumento brusco de presión puede romper pequeños vasos y producir petequias por extravasación." },
  { chapter: "Bloque 4", topic: "Rosácea", difficulty: "medium", question: "¿Cuál factor puede exacerbar la rosácea?", options: ["Luz ultravioleta", "Disminución de fibrina", "Sialometría", "Meiosis"], correctAnswer: 0, explanation: "La radiación UV, temperatura, ejercicio, alcohol, tabaco, café y estrés pueden desencadenarla." },
  { chapter: "Bloque 4", topic: "Piel", difficulty: "hard", question: "Una placa café elevada, opaca y que parece pegada a la piel en una persona de 60 años es probablemente:", options: ["Queratosis seborreica", "Efélide", "Melasma", "Telangiectasia"], correctAnswer: 0, explanation: "La apariencia adherida y queratósica en mayores de 50 años es clásica de queratosis seborreica." },
  { chapter: "Bloque 4", topic: "Cuello", difficulty: "medium", question: "¿Por qué se pide al paciente girar la cabeza durante la palpación cervical?", options: ["Para hacer evidente el esternocleidomastoideo", "Para medir saliva", "Para blanquear lesiones vasculares", "Para evaluar HbA1c"], correctAnswer: 0, explanation: "El giro permite delimitar el esternocleidomastoideo y explorar cadenas cervicales." },
  { chapter: "Bloque 4", topic: "Cuello", difficulty: "hard", question: "La persistencia embrionaria de qué trayecto origina un quiste tirogloso?", options: ["Descenso de la tiroides desde el foramen ciego", "Migración de neutrófilos", "Conducto parotídeo", "Arteria carótida"], correctAnswer: 0, explanation: "La tiroides desciende desde el foramen ciego y sus restos pueden formar un quiste medial." },
  { chapter: "Bloque 4", topic: "Piel", difficulty: "medium", question: "¿Qué característica explica que un acrocordón pueda sangrar al traumatizarse?", options: ["Tiene un eje vascular", "Contiene fibrina caseosa", "Es una glándula sebácea", "Siempre es maligno"], correctAnswer: 0, explanation: "El pedículo del acrocordón contiene vasos sanguíneos." },
  { chapter: "Bloque 4", topic: "Metabólicas", difficulty: "hard", question: "Una placa hiperpigmentada y engrosada se encuentra en cuello, axilas e ingles. ¿Qué asociación debe investigarse?", options: ["Resistencia a la insulina", "Tuberculosis", "Fiebre reumática", "Hemofilia"], correctAnswer: 0, explanation: "La distribución en pliegues es típica de acantosis nigricans, relacionada con alteraciones metabólicas." },
  { chapter: "Bloque 4", topic: "Examen intraoral", difficulty: "medium", question: "¿Qué error aumenta el riesgo de omitir una masa durante palpación intraoral?", options: ["Recorrer de forma continua", "Levantar los dedos y saltar áreas", "Comparar ambos lados", "Usar técnica bidigital"], correctAnswer: 1, explanation: "La palpación debe ser continua, ordenada y bidigital para no omitir regiones." },
  { chapter: "Bloque 4", topic: "Labios", difficulty: "medium", question: "Descamación persistente del bermellón en una persona que se lame los labios orienta a:", options: ["Queilitis exfoliativa", "Queilitis actínica", "Mácula melanótica", "Angioma cherry"], correctAnswer: 0, explanation: "La irritación repetida y el lamido se asocian a queilitis exfoliativa." },
  { chapter: "Bloque 4", topic: "Labios", difficulty: "hard", question: "¿Qué hallazgo aumenta la necesidad de biopsia en una queilitis actínica?", options: ["Ulceración persistente", "Gránulos amarillos estables", "Color idéntico desde nacimiento", "Diascopía positiva"], correctAnswer: 0, explanation: "Ulceración u otros cambios sospechosos pueden indicar progresión y requieren estudio histológico." },
  { chapter: "Bloque 4", topic: "Labios", difficulty: "medium", question: "Una lesión pigmentada plana, única y estable en el labio corresponde con mayor probabilidad a:", options: ["Mácula melanótica", "Rinofima", "Acrocordón", "Quiste tirogloso"], correctAnswer: 0, explanation: "La mácula melanótica suele presentarse como pigmentación plana y solitaria del labio." },
  { chapter: "Bloque 4", topic: "Labios", difficulty: "hard", question: "¿Cuál lesión está formada por glándulas sebáceas ectópicas no vinculadas a folículos pilosos?", options: ["Gránulos de Fordyce", "Angioma cherry", "Petequias", "Léntigo solar"], correctAnswer: 0, explanation: "Los gránulos de Fordyce son glándulas sebáceas ectópicas benignas." },
  { chapter: "Bloque 4", topic: "Vasculares", difficulty: "medium", question: "Pequeñas pápulas rojas adquiridas que aumentan con la edad se denominan:", options: ["Angiomas cherry", "Efélides", "Acrocordones", "Quistes epidermoides"], correctAnswer: 0, explanation: "El angioma cherry es una proliferación vascular benigna adquirida frecuente en adultos." }
]

export const semiologiaQuestions: SemiologiaQuestion[] = seeds.map(
  ({ correctAnswer, ...seed }, index) => ({
    ...seed,
    id: `semio-q-${String(index + 1).padStart(3, "0")}`,
    tags: ["semiología", seed.chapter, seed.topic],
    type: "single",
    correctAnswers: [correctAnswer]
  })
)
