export const estudioFinalHayekQuestions = [
  {
    id: "hayek-manual-p2-q001",
    chapter: "Parcial 2",
    topic: "Derecho, ley y justicia",
    tags: ["filosofia", "hayek", "parcial-2", "derecho-ley-y-justicia"],
    difficulty: "easy",
    type: "single",
    question: "Según Hayek, la base del derecho en la civilización occidental es el conocimiento",
    options: ["La ley y la libertad son compatibles pues las leyes generales y abstractas protegen la libertad", "Práctico-normativo: tradiciones, normas evolutivas", "Ausencia de coacción arbitraria de un tercero", "Amenaza de coacción legítima y no arbitraria"],
    correctAnswers: [1],
    explanation: "La respuesta correcta es: Práctico-normativo: tradiciones, normas evolutivas",
  },
  {
    id: "hayek-manual-conceptos-q001",
    chapter: "Conceptos Importantes",
    topic: "Conceptos generales",
    tags: ["filosofia", "hayek", "conceptos-importantes", "conceptos-generales"],
    difficulty: "easy",
    type: "single",
    question: "Razón por la cual Hayek da importancia a la ignorancia humana",
    options: ["Por ser producto no intencional de la acción humana", "Por no compartir el método matemático para hacer ciencia económica.", "Se autogenera", "Mantiene que la razón tiene límites"],
    correctAnswers: [3],
    explanation: "La respuesta correcta es: Mantiene que la razón tiene límites",
  },
  {
    id: "hayek-manual-p1-q001",
    chapter: "Parcial 1",
    topic: "Tradiciones de la libertad",
    tags: ["filosofia", "hayek", "parcial-1", "tradiciones-de-la-libertad"],
    difficulty: "easy",
    type: "single",
    question: "Según Hayek, la tradición inglesa",
    options: ["Han sido diseñadas por la razón humana", "Promueve la confianza en las instituciones", "Como una confianza desmedida en el poder de la razón humana", "Ha provocado siempre utopias"],
    correctAnswers: [1],
    explanation: "La respuesta correcta es: Promueve la confianza en las instituciones",
  },
  {
    id: "hayek-manual-p2-q002",
    chapter: "Parcial 2",
    topic: "Derecho, ley y justicia",
    tags: ["filosofia", "hayek", "parcial-2", "derecho-ley-y-justicia"],
    difficulty: "easy",
    type: "single",
    question: "De acuerdo a las leyes hayekianas",
    options: ["Práctico-normativo: tradiciones, normas evolutivas", "Ausencia de coacción arbitraria de un tercero", "Amenaza de coacción legítima y no arbitraria", "La ley y la libertad son compatibles pues las leyes generales y abstractas protegen la libertad"],
    correctAnswers: [3],
    explanation: "La respuesta correcta es: La ley y la libertad son compatibles pues las leyes generales y abstractas protegen la libertad",
  },
  {
    id: "hayek-manual-p1-q002",
    chapter: "Parcial 1",
    topic: "Progreso y civilización",
    tags: ["filosofia", "hayek", "parcial-1", "progreso-y-civilizacion"],
    difficulty: "medium",
    type: "single",
    question: "La civilización inicia",
    options: ["No puede dirigirse", "Cuando en la persecución de sus fines el individuo puede sobrepasar los límites de su ignorancia, aprovechándose del conocimiento disperso.", "Ya que su uso producirá resultados imprevisibles", "Están constituidas por muchas más experiencias que las de una sola persona"],
    correctAnswers: [1],
    explanation: "La respuesta correcta es: Cuando en la persecución de sus fines el individuo puede sobrepasar los límites de su ignorancia, aprovechándose del conocimiento disperso.",
  },
  {
    id: "hayek-manual-p1-q003",
    chapter: "Parcial 1",
    topic: "Libertad y responsabilidad",
    tags: ["filosofia", "hayek", "parcial-1", "libertad-y-responsabilidad"],
    difficulty: "easy",
    type: "single",
    question: "La libertad en la tradición hayekiana",
    options: ["Una empírica y carente de sistema y otra especulativa y racionalista", "El individuo debe poder eludir el fruto de sus acciones.", "Asumir la consecuencia de los propios actos", "Es el valor que posibilita incorporar los demás valores en los planes de vida."],
    correctAnswers: [3],
    explanation: "La respuesta correcta es: Es el valor que posibilita incorporar los demás valores en los planes de vida.",
  },
  {
    id: "hayek-manual-p1-q004",
    chapter: "Parcial 1",
    topic: "Tradiciones de la libertad",
    tags: ["filosofia", "hayek", "parcial-1", "tradiciones-de-la-libertad"],
    difficulty: "medium",
    type: "single",
    question: "El racionalismo afirma que las instituciones sociales",
    options: ["Promueve la confianza en las instituciones", "Han sido diseñadas por la razón humana", "Como una confianza desmedida en el poder de la razón humana", "Ha provocado siempre utopias"],
    correctAnswers: [1],
    explanation: "La respuesta correcta es: Han sido diseñadas por la razón humana",
  },
  {
    id: "hayek-manual-p1-q005",
    chapter: "Parcial 1",
    topic: "Libertad y responsabilidad",
    tags: ["filosofia", "hayek", "parcial-1", "libertad-y-responsabilidad"],
    difficulty: "easy",
    type: "single",
    question: "Las dos tradiciones de la teoría de la libertad",
    options: ["Es el valor que posibilita incorporar los demás valores en los planes de vida.", "El individuo debe poder eludir el fruto de sus acciones.", "Asumir la consecuencia de los propios actos", "Una empírica y carente de sistema y otra especulativa y racionalista"],
    correctAnswers: [3],
    explanation: "La respuesta correcta es: Una empírica y carente de sistema y otra especulativa y racionalista",
  },
  {
    id: "hayek-manual-p1-q006",
    chapter: "Parcial 1",
    topic: "Libertad y responsabilidad",
    tags: ["filosofia", "hayek", "parcial-1", "libertad-y-responsabilidad"],
    difficulty: "easy",
    type: "single",
    question: "Con cual de las siguientes afirmaciones sobre la libertad estaría en desacuerdo Hayek",
    options: ["Es el valor que posibilita incorporar los demás valores en los planes de vida.", "El individuo debe poder eludir el fruto de sus acciones.", "Una empírica y carente de sistema y otra especulativa y racionalista", "Asumir la consecuencia de los propios actos"],
    correctAnswers: [1],
    explanation: "La respuesta correcta es: El individuo debe poder eludir el fruto de sus acciones.",
  },
  {
    id: "hayek-manual-p1-q007",
    chapter: "Parcial 1",
    topic: "Libertad y responsabilidad",
    tags: ["filosofia", "hayek", "parcial-1", "libertad-y-responsabilidad"],
    difficulty: "easy",
    type: "single",
    question: "Hayek presupone que la responsabilidad es la capacidad de",
    options: ["Es el valor que posibilita incorporar los demás valores en los planes de vida.", "Una empírica y carente de sistema y otra especulativa y racionalista", "El individuo debe poder eludir el fruto de sus acciones.", "Asumir la consecuencia de los propios actos"],
    correctAnswers: [3],
    explanation: "La respuesta correcta es: Asumir la consecuencia de los propios actos",
  },
  {
    id: "hayek-manual-p2-q003",
    chapter: "Parcial 2",
    topic: "Derecho, ley y justicia",
    tags: ["filosofia", "hayek", "parcial-2", "derecho-ley-y-justicia"],
    difficulty: "easy",
    type: "single",
    question: "Para Hayek la libertad es",
    options: ["Práctico-normativo: tradiciones, normas evolutivas", "Ausencia de coacción arbitraria de un tercero", "La ley y la libertad son compatibles pues las leyes generales y abstractas protegen la libertad", "Amenaza de coacción legítima y no arbitraria"],
    correctAnswers: [1],
    explanation: "La respuesta correcta es: Ausencia de coacción arbitraria de un tercero",
  },
  {
    id: "hayek-manual-p1-q008",
    chapter: "Parcial 1",
    topic: "Libertad y responsabilidad",
    tags: ["filosofia", "hayek", "parcial-1", "libertad-y-responsabilidad"],
    difficulty: "easy",
    type: "single",
    question: "Según Hayek, la persecución de los fines debe hacerse de modo que",
    options: ["Es el valor que posibilita incorporar los demás valores en los planes de vida.", "Una empírica y carente de sistema y otra especulativa y racionalista", "El individuo debe poder eludir el fruto de sus acciones.", "Cada quien escoja los suyos"],
    correctAnswers: [3],
    explanation: "La respuesta correcta es: Cada quien escoja los suyos",
  },
  {
    id: "hayek-manual-p2-q004",
    chapter: "Parcial 2",
    topic: "Tribu, sociedad y orden extenso",
    tags: ["filosofia", "hayek", "parcial-2", "tribu-sociedad-y-orden-extenso"],
    difficulty: "easy",
    type: "single",
    question: "En la sociedad libre, donde se desarrolla un orden extenso y complejo",
    options: ["El progreso tiende a estancarse e incluso a retroceder", "La recompensa provine del valor que otros otorgan a lo que hacemos", "El cientificismo ignora la enorme complejidad de la vida en sociedad.", "No, la sociedad tiene mayor tamaño y relaciones impersonales mas extensas que la comunidad"],
    correctAnswers: [1],
    explanation: "La respuesta correcta es: La recompensa provine del valor que otros otorgan a lo que hacemos",
  },
  {
    id: "hayek-manual-p2-q005",
    chapter: "Parcial 2",
    topic: "Tribu, sociedad y orden extenso",
    tags: ["filosofia", "hayek", "parcial-2", "tribu-sociedad-y-orden-extenso"],
    difficulty: "easy",
    type: "single",
    question: "En una sociedad centralmente planificada",
    options: ["La recompensa provine del valor que otros otorgan a lo que hacemos", "El cientificismo ignora la enorme complejidad de la vida en sociedad.", "No, la sociedad tiene mayor tamaño y relaciones impersonales mas extensas que la comunidad", "El progreso tiende a estancarse e incluso a retroceder"],
    correctAnswers: [3],
    explanation: "La respuesta correcta es: El progreso tiende a estancarse e incluso a retroceder",
  },
  {
    id: "hayek-manual-p2-q006",
    chapter: "Parcial 2",
    topic: "Tribu, sociedad y orden extenso",
    tags: ["filosofia", "hayek", "parcial-2", "tribu-sociedad-y-orden-extenso"],
    difficulty: "hard",
    type: "single",
    question: "Hayek critica y rechaza el cientificismo porque",
    options: ["La recompensa provine del valor que otros otorgan a lo que hacemos", "El cientificismo ignora la enorme complejidad de la vida en sociedad.", "El progreso tiende a estancarse e incluso a retroceder", "No, la sociedad tiene mayor tamaño y relaciones impersonales mas extensas que la comunidad"],
    correctAnswers: [1],
    explanation: "La respuesta correcta es: El cientificismo ignora la enorme complejidad de la vida en sociedad.",
  },
  {
    id: "hayek-manual-p1-q009",
    chapter: "Parcial 1",
    topic: "Órdenes e instituciones",
    tags: ["filosofia", "hayek", "parcial-1", "ordenes-e-instituciones"],
    difficulty: "medium",
    type: "single",
    question: "Según Hayek, la diferencia entre un orden espontáneo y una organización es que el primero",
    options: ["Que, regido por un orden funcional, no resulta de la voluntad de nadie", "Que, regido por normas tipo thesis, resulta de la voluntad de alguien", "Son, como afirmó Ferguson: results of human but not of human design", "Surge gracias a reglas abstractas y generales y las segunda gracias a mandatos"],
    correctAnswers: [3],
    explanation: "La respuesta correcta es: Surge gracias a reglas abstractas y generales y las segunda gracias a mandatos",
  },
  {
    id: "hayek-manual-p2-q007",
    chapter: "Parcial 2",
    topic: "Democracia y liberalismo",
    tags: ["filosofia", "hayek", "parcial-2", "democracia-y-liberalismo"],
    difficulty: "easy",
    type: "single",
    question: "Según Hayek la democracia como forma de gobierno:",
    options: ["Demagogia", "Expresa la opinion de la mayoría y no la voluntad de la sociedad", "La limitación del poder coactivo de todos los gobiernos", "Son la mayoría y tanto las políticas como la legislación responden a sus intereses"],
    correctAnswers: [1],
    explanation: "La respuesta correcta es: Expresa la opinion de la mayoría y no la voluntad de la sociedad",
  },
  {
    id: "hayek-manual-p1-q010",
    chapter: "Parcial 1",
    topic: "Teoría de la mente",
    tags: ["filosofia", "hayek", "parcial-1", "teoria-de-la-mente"],
    difficulty: "easy",
    type: "single",
    question: "Las tradiciones liberal y democrática difieren, principalmente, respecto de:",
    options: ["El mérito", "Tiene como fundamento una memoria nerviosa", "Que constituye un aparato que clasifica fenómenos, percepciones y acciones", "El alcance de la acción estatal que ha de ser guiada por decisiones democráticas"],
    correctAnswers: [3],
    explanation: "La respuesta correcta es: El alcance de la acción estatal que ha de ser guiada por decisiones democráticas",
  },
  {
    id: "hayek-manual-p2-q008",
    chapter: "Parcial 2",
    topic: "Democracia y liberalismo",
    tags: ["filosofia", "hayek", "parcial-2", "democracia-y-liberalismo"],
    difficulty: "easy",
    type: "single",
    question: "De acuerdo con Hayek, si la democracia parte del supuesto de considerar como justo todo aquello que la mayoría decide, degenera en",
    options: ["Expresa la opinion de la mayoría y no la voluntad de la sociedad", "Demagogia", "La limitación del poder coactivo de todos los gobiernos", "Son la mayoría y tanto las políticas como la legislación responden a sus intereses"],
    correctAnswers: [1],
    explanation: "La respuesta correcta es: Demagogia",
  },
  {
    id: "hayek-manual-p2-q009",
    chapter: "Parcial 2",
    topic: "Democracia y liberalismo",
    tags: ["filosofia", "hayek", "parcial-2", "democracia-y-liberalismo"],
    difficulty: "easy",
    type: "single",
    question: "El liberalismo se preocupa principalmente de",
    options: ["Expresa la opinion de la mayoría y no la voluntad de la sociedad", "Demagogia", "Son la mayoría y tanto las políticas como la legislación responden a sus intereses", "La limitación del poder coactivo de todos los gobiernos"],
    correctAnswers: [3],
    explanation: "La respuesta correcta es: La limitación del poder coactivo de todos los gobiernos",
  },
  {
    id: "hayek-manual-p2-q010",
    chapter: "Parcial 2",
    topic: "Democracia y liberalismo",
    tags: ["filosofia", "hayek", "parcial-2", "democracia-y-liberalismo"],
    difficulty: "easy",
    type: "single",
    question: "La trascendencia política del crecimiento en el número de asalariados es que",
    options: ["Expresa la opinion de la mayoría y no la voluntad de la sociedad", "Son la mayoría y tanto las políticas como la legislación responden a sus intereses", "Demagogia", "La limitación del poder coactivo de todos los gobiernos"],
    correctAnswers: [1],
    explanation: "La respuesta correcta es: Son la mayoría y tanto las políticas como la legislación responden a sus intereses",
  },
  {
    id: "hayek-manual-p2-q011",
    chapter: "Parcial 2",
    topic: "Valor, mérito y economía",
    tags: ["filosofia", "hayek", "parcial-2", "valor-merito-y-economia"],
    difficulty: "easy",
    type: "single",
    question: "Según Hayek, cual es la trascendencia que existan millonarios",
    options: ["La existencia de empresarios individuales dispuestos a invertir y actuar por iniciativa propia", "Colocando en el centro de la cuestión al individuo humano como actor que elige y renuncia.", "Cada quien escoja los suyos", "Mantienen el sistema de orden competitivo y pueden buscar objetivos no lucrativos"],
    correctAnswers: [3],
    explanation: "La respuesta correcta es: Mantienen el sistema de orden competitivo y pueden buscar objetivos no lucrativos",
  },
  {
    id: "hayek-manual-p2-q012",
    chapter: "Parcial 2",
    topic: "Derecho, ley y justicia",
    tags: ["filosofia", "hayek", "parcial-2", "derecho-ley-y-justicia"],
    difficulty: "easy",
    type: "single",
    question: "La definición de ley, según la propuesta de Hayek, es",
    options: ["Práctico-normativo: tradiciones, normas evolutivas", "Amenaza de coacción legítima y no arbitraria", "La ley y la libertad son compatibles pues las leyes generales y abstractas protegen la libertad", "Ausencia de coacción arbitraria de un tercero"],
    correctAnswers: [1],
    explanation: "La respuesta correcta es: Amenaza de coacción legítima y no arbitraria",
  },
  {
    id: "hayek-manual-p2-q013",
    chapter: "Parcial 2",
    topic: "Derecho, ley y justicia",
    tags: ["filosofia", "hayek", "parcial-2", "derecho-ley-y-justicia"],
    difficulty: "easy",
    type: "single",
    question: "Desde el punto de vista de Hayek, se considera como una buena ley la",
    options: ["Práctico-normativo: tradiciones, normas evolutivas", "La ley y la libertad son compatibles pues las leyes generales y abstractas protegen la libertad", "Ausencia de coacción arbitraria de un tercero", "No creada deliberadamente"],
    correctAnswers: [3],
    explanation: "La respuesta correcta es: No creada deliberadamente",
  },
  {
    id: "hayek-manual-p2-q014",
    chapter: "Parcial 2",
    topic: "Derecho, ley y justicia",
    tags: ["filosofia", "hayek", "parcial-2", "derecho-ley-y-justicia"],
    difficulty: "medium",
    type: "single",
    question: "La popular justicia social es un concepto incoherente debido a que es un término",
    options: ["Práctico-normativo: tradiciones, normas evolutivas", "Vacío, lógica y semánticamente", "La ley y la libertad son compatibles pues las leyes generales y abstractas protegen la libertad", "Ausencia de coacción arbitraria de un tercero"],
    correctAnswers: [1],
    explanation: "La respuesta correcta es: Vacío, lógica y semánticamente",
  },
  {
    id: "hayek-manual-p2-q015",
    chapter: "Parcial 2",
    topic: "Derecho, ley y justicia",
    tags: ["filosofia", "hayek", "parcial-2", "derecho-ley-y-justicia"],
    difficulty: "easy",
    type: "single",
    question: "El objetivo de la lucha por la libertad ha sido",
    options: ["Práctico-normativo: tradiciones, normas evolutivas", "La ley y la libertad son compatibles pues las leyes generales y abstractas protegen la libertad", "Ausencia de coacción arbitraria de un tercero", "El establecimiento de la igualdad ante la ley para todos los seres humanos"],
    correctAnswers: [3],
    explanation: "La respuesta correcta es: El establecimiento de la igualdad ante la ley para todos los seres humanos",
  },
  {
    id: "hayek-manual-p2-q016",
    chapter: "Parcial 2",
    topic: "Tribu, sociedad y orden extenso",
    tags: ["filosofia", "hayek", "parcial-2", "tribu-sociedad-y-orden-extenso"],
    difficulty: "easy",
    type: "single",
    question: "Comunidad es lo mismo que sociedad",
    options: ["La recompensa provine del valor que otros otorgan a lo que hacemos", "No, la sociedad tiene mayor tamaño y relaciones impersonales mas extensas que la comunidad", "El progreso tiende a estancarse e incluso a retroceder", "El cientificismo ignora la enorme complejidad de la vida en sociedad."],
    correctAnswers: [1],
    explanation: "La respuesta correcta es: No, la sociedad tiene mayor tamaño y relaciones impersonales mas extensas que la comunidad",
  },
  {
    id: "hayek-manual-p1-q011",
    chapter: "Parcial 1",
    topic: "Teoría de la mente",
    tags: ["filosofia", "hayek", "parcial-1", "teoria-de-la-mente"],
    difficulty: "easy",
    type: "single",
    question: "Al premiar el esfuerzo, las intenciones, el tiempo y la dedicación de las personas, independientemente del resultado, estamos refiriéndonos a",
    options: ["El alcance de la acción estatal que ha de ser guiada por decisiones democráticas", "Tiene como fundamento una memoria nerviosa", "Que constituye un aparato que clasifica fenómenos, percepciones y acciones", "El mérito"],
    correctAnswers: [3],
    explanation: "La respuesta correcta es: El mérito",
  },
  {
    id: "hayek-manual-p1-q012",
    chapter: "Parcial 1",
    topic: "Progreso y civilización",
    tags: ["filosofia", "hayek", "parcial-1", "progreso-y-civilizacion"],
    difficulty: "easy",
    type: "single",
    question: "Acerca del progreso afirma Hayek que",
    options: ["Cuando en la persecución de sus fines el individuo puede sobrepasar los límites de su ignorancia, aprovechándose del conocimiento disperso.", "No puede dirigirse", "Ya que su uso producirá resultados imprevisibles", "Están constituidas por muchas más experiencias que las de una sola persona"],
    correctAnswers: [1],
    explanation: "La respuesta correcta es: No puede dirigirse",
  },
  {
    id: "hayek-manual-p1-q013",
    chapter: "Parcial 1",
    topic: "Libertad y responsabilidad",
    tags: ["filosofia", "hayek", "parcial-1", "libertad-y-responsabilidad"],
    difficulty: "easy",
    type: "single",
    question: "Libertad como autodeterminación implica",
    options: ["Es el valor que posibilita incorporar los demás valores en los planes de vida.", "Una empírica y carente de sistema y otra especulativa y racionalista", "El individuo debe poder eludir el fruto de sus acciones.", "Poder elegir y perseguir los propios fines"],
    correctAnswers: [3],
    explanation: "La respuesta correcta es: Poder elegir y perseguir los propios fines",
  },
  {
    id: "hayek-manual-p1-q014",
    chapter: "Parcial 1",
    topic: "Progreso y civilización",
    tags: ["filosofia", "hayek", "parcial-1", "progreso-y-civilizacion"],
    difficulty: "easy",
    type: "single",
    question: "La libertad condice al progreso",
    options: ["Cuando en la persecución de sus fines el individuo puede sobrepasar los límites de su ignorancia, aprovechándose del conocimiento disperso.", "Ya que su uso producirá resultados imprevisibles", "No puede dirigirse", "Están constituidas por muchas más experiencias que las de una sola persona"],
    correctAnswers: [1],
    explanation: "La respuesta correcta es: Ya que su uso producirá resultados imprevisibles",
  },
  {
    id: "hayek-manual-p2-q017",
    chapter: "Parcial 2",
    topic: "Democracia y liberalismo",
    tags: ["filosofia", "hayek", "parcial-2", "democracia-y-liberalismo"],
    difficulty: "easy",
    type: "single",
    question: "De las siguientes proposiciones la que menos caracteriza a la democracia es",
    options: ["Expresa la opinion de la mayoría y no la voluntad de la sociedad", "Demagogia", "La limitación del poder coactivo de todos los gobiernos", "El tipo de decisiones está limitado al derecho individual"],
    correctAnswers: [3],
    explanation: "La respuesta correcta es: El tipo de decisiones está limitado al derecho individual",
  },
  {
    id: "hayek-manual-p2-q018",
    chapter: "Parcial 2",
    topic: "Valor, mérito y economía",
    tags: ["filosofia", "hayek", "parcial-2", "valor-merito-y-economia"],
    difficulty: "easy",
    type: "single",
    question: "El que haya muchas oportunidades de trabajo depende en definitiva de",
    options: ["Mantienen el sistema de orden competitivo y pueden buscar objetivos no lucrativos", "La existencia de empresarios individuales dispuestos a invertir y actuar por iniciativa propia", "Colocando en el centro de la cuestión al individuo humano como actor que elige y renuncia.", "Amenaza de coacción legítima y no arbitraria"],
    correctAnswers: [1],
    explanation: "La respuesta correcta es: La existencia de empresarios individuales dispuestos a invertir y actuar por iniciativa propia",
  },
  {
    id: "hayek-manual-p1-q015",
    chapter: "Parcial 1",
    topic: "Progreso y civilización",
    tags: ["filosofia", "hayek", "parcial-1", "progreso-y-civilizacion"],
    difficulty: "easy",
    type: "single",
    question: "El método de prueba y error con respecto a las instituciones indica que",
    options: ["Cuando en la persecución de sus fines el individuo puede sobrepasar los límites de su ignorancia, aprovechándose del conocimiento disperso.", "No puede dirigirse", "Ya que su uso producirá resultados imprevisibles", "Están constituidas por muchas más experiencias que las de una sola persona"],
    correctAnswers: [3],
    explanation: "La respuesta correcta es: Están constituidas por muchas más experiencias que las de una sola persona",
  },
  {
    id: "hayek-manual-p1-q016",
    chapter: "Parcial 1",
    topic: "Progreso y civilización",
    tags: ["filosofia", "hayek", "parcial-1", "progreso-y-civilizacion"],
    difficulty: "easy",
    type: "single",
    question: "El progreso en el pensamiento hayekiano",
    options: ["Cuando en la persecución de sus fines el individuo puede sobrepasar los límites de su ignorancia, aprovechándose del conocimiento disperso.", "Es un proceso evolutivo de prueba y error cuyo resultado es incierto", "No puede dirigirse", "Ya que su uso producirá resultados imprevisibles"],
    correctAnswers: [1],
    explanation: "La respuesta correcta es: Es un proceso evolutivo de prueba y error cuyo resultado es incierto",
  },
  {
    id: "hayek-manual-p1-q017",
    chapter: "Parcial 1",
    topic: "Libertad y responsabilidad",
    tags: ["filosofia", "hayek", "parcial-1", "libertad-y-responsabilidad"],
    difficulty: "easy",
    type: "single",
    question: "La responsabilidad implica",
    options: ["Es el valor que posibilita incorporar los demás valores en los planes de vida.", "Una empírica y carente de sistema y otra especulativa y racionalista", "El individuo debe poder eludir el fruto de sus acciones.", "Aceptar las consecuencias de actuar"],
    correctAnswers: [3],
    explanation: "La respuesta correcta es: Aceptar las consecuencias de actuar",
  },
  {
    id: "hayek-manual-p1-q018",
    chapter: "Parcial 1",
    topic: "Progreso y civilización",
    tags: ["filosofia", "hayek", "parcial-1", "progreso-y-civilizacion"],
    difficulty: "medium",
    type: "single",
    question: "Que importancia tiene la experiencia y su transmisión en la civilización",
    options: ["Cuando en la persecución de sus fines el individuo puede sobrepasar los límites de su ignorancia, aprovechándose del conocimiento disperso.", "Mucha importancia, ya que podría decirse que todas nuestras costumbres, conocimientos prácticos, actitudes emocionales, instrumentos e instituciones, son adaptaciones a experiencias pasadas.", "No puede dirigirse", "Ya que su uso producirá resultados imprevisibles"],
    correctAnswers: [1],
    explanation: "La respuesta correcta es: Mucha importancia, ya que podría decirse que todas nuestras costumbres, conocimientos prácticos, actitudes emocionales, instrumentos e instituciones, son adaptaciones a experiencias pasadas.",
  },
  {
    id: "hayek-manual-p1-q019",
    chapter: "Parcial 1",
    topic: "Progreso y civilización",
    tags: ["filosofia", "hayek", "parcial-1", "progreso-y-civilizacion"],
    difficulty: "easy",
    type: "single",
    question: "El progreso para Hayek es",
    options: ["Cuando en la persecución de sus fines el individuo puede sobrepasar los límites de su ignorancia, aprovechándose del conocimiento disperso.", "No puede dirigirse", "Ya que su uso producirá resultados imprevisibles", "Un proceso de adaptación y aprendizaje"],
    correctAnswers: [3],
    explanation: "La respuesta correcta es: Un proceso de adaptación y aprendizaje",
  },
  {
    id: "hayek-manual-p1-q020",
    chapter: "Parcial 1",
    topic: "Progreso y civilización",
    tags: ["filosofia", "hayek", "parcial-1", "progreso-y-civilizacion"],
    difficulty: "easy",
    type: "single",
    question: "Las desigualdades en el aspecto económico",
    options: ["Cuando en la persecución de sus fines el individuo puede sobrepasar los límites de su ignorancia, aprovechándose del conocimiento disperso.", "Hacen posible el progreso", "No puede dirigirse", "Ya que su uso producirá resultados imprevisibles"],
    correctAnswers: [1],
    explanation: "La respuesta correcta es: Hacen posible el progreso",
  },
  {
    id: "hayek-manual-p2-q019",
    chapter: "Parcial 2",
    topic: "Tribu, sociedad y orden extenso",
    tags: ["filosofia", "hayek", "parcial-2", "tribu-sociedad-y-orden-extenso"],
    difficulty: "easy",
    type: "single",
    question: "En la teoría social, la idea hayekiana de la mente nos permite",
    options: ["La recompensa provine del valor que otros otorgan a lo que hacemos", "El progreso tiende a estancarse e incluso a retroceder", "El cientificismo ignora la enorme complejidad de la vida en sociedad.", "Argumentar objetivamente en contra del intento de planear central entre la sociedad"],
    correctAnswers: [3],
    explanation: "La respuesta correcta es: Argumentar objetivamente en contra del intento de planear central entre la sociedad",
  },
  {
    id: "hayek-manual-p1-q021",
    chapter: "Parcial 1",
    topic: "Tradiciones de la libertad",
    tags: ["filosofia", "hayek", "parcial-1", "tradiciones-de-la-libertad"],
    difficulty: "medium",
    type: "single",
    question: "El racionalismo puede definirse",
    options: ["Promueve la confianza en las instituciones", "Como una confianza desmedida en el poder de la razón humana", "Han sido diseñadas por la razón humana", "Ha provocado siempre utopias"],
    correctAnswers: [1],
    explanation: "La respuesta correcta es: Como una confianza desmedida en el poder de la razón humana",
  },
  {
    id: "hayek-manual-p1-q022",
    chapter: "Parcial 1",
    topic: "Progreso y civilización",
    tags: ["filosofia", "hayek", "parcial-1", "progreso-y-civilizacion"],
    difficulty: "medium",
    type: "single",
    question: "El empirismo, en el fondo, lo que afirma es",
    options: ["Cuando en la persecución de sus fines el individuo puede sobrepasar los límites de su ignorancia, aprovechándose del conocimiento disperso.", "No puede dirigirse", "Ya que su uso producirá resultados imprevisibles", "Que la razón no puede adquirir conocimientos sino por la experiencia sensorial"],
    correctAnswers: [3],
    explanation: "La respuesta correcta es: Que la razón no puede adquirir conocimientos sino por la experiencia sensorial",
  },
  {
    id: "hayek-manual-p1-q023",
    chapter: "Parcial 1",
    topic: "Tradiciones de la libertad",
    tags: ["filosofia", "hayek", "parcial-1", "tradiciones-de-la-libertad"],
    difficulty: "medium",
    type: "single",
    question: "El racionalismo en cuanto a la teoría social",
    options: ["Promueve la confianza en las instituciones", "Ha provocado siempre utopias", "Han sido diseñadas por la razón humana", "Como una confianza desmedida en el poder de la razón humana"],
    correctAnswers: [1],
    explanation: "La respuesta correcta es: Ha provocado siempre utopias",
  },
  {
    id: "hayek-manual-p2-q020",
    chapter: "Parcial 2",
    topic: "Derecho, ley y justicia",
    tags: ["filosofia", "hayek", "parcial-2", "derecho-ley-y-justicia"],
    difficulty: "medium",
    type: "single",
    question: "El empirismo, en cuanto a la moral y el derecho",
    options: ["Práctico-normativo: tradiciones, normas evolutivas", "La ley y la libertad son compatibles pues las leyes generales y abstractas protegen la libertad", "Ausencia de coacción arbitraria de un tercero", "Ha enfatizado el apego de la tradición"],
    correctAnswers: [3],
    explanation: "La respuesta correcta es: Ha enfatizado el apego de la tradición",
  },
  {
    id: "hayek-manual-p2-q021",
    chapter: "Parcial 2",
    topic: "Derecho, ley y justicia",
    tags: ["filosofia", "hayek", "parcial-2", "derecho-ley-y-justicia"],
    difficulty: "easy",
    type: "single",
    question: "En cuanto la libertad, según Hayek, la ley:",
    options: ["Práctico-normativo: tradiciones, normas evolutivas", "Constituye un elemento que la garantiza", "La ley y la libertad son compatibles pues las leyes generales y abstractas protegen la libertad", "Ausencia de coacción arbitraria de un tercero"],
    correctAnswers: [1],
    explanation: "La respuesta correcta es: Constituye un elemento que la garantiza",
  },
  {
    id: "hayek-manual-p2-q022",
    chapter: "Parcial 2",
    topic: "Derecho, ley y justicia",
    tags: ["filosofia", "hayek", "parcial-2", "derecho-ley-y-justicia"],
    difficulty: "easy",
    type: "single",
    question: "Según Hayek y la tradición liberal, las buenas leyes",
    options: ["Práctico-normativo: tradiciones, normas evolutivas", "La ley y la libertad son compatibles pues las leyes generales y abstractas protegen la libertad", "Ausencia de coacción arbitraria de un tercero", "Son prohibitivas y no tienen que ver con fines"],
    correctAnswers: [3],
    explanation: "La respuesta correcta es: Son prohibitivas y no tienen que ver con fines",
  },
  {
    id: "hayek-manual-p1-q024",
    chapter: "Parcial 1",
    topic: "Teoría de la mente",
    tags: ["filosofia", "hayek", "parcial-1", "teoria-de-la-mente"],
    difficulty: "easy",
    type: "single",
    question: "Según Hayek la mente humana:",
    options: ["El alcance de la acción estatal que ha de ser guiada por decisiones democráticas", "Tiene como fundamento una memoria nerviosa", "El mérito", "Que constituye un aparato que clasifica fenómenos, percepciones y acciones"],
    correctAnswers: [1],
    explanation: "La respuesta correcta es: Tiene como fundamento una memoria nerviosa",
  },
  {
    id: "hayek-manual-p1-q025",
    chapter: "Parcial 1",
    topic: "Teoría de la mente",
    tags: ["filosofia", "hayek", "parcial-1", "teoria-de-la-mente"],
    difficulty: "easy",
    type: "single",
    question: "En si teoría de la mente Hayek afirma",
    options: ["El alcance de la acción estatal que ha de ser guiada por decisiones democráticas", "El mérito", "Tiene como fundamento una memoria nerviosa", "Que constituye un aparato que clasifica fenómenos, percepciones y acciones"],
    correctAnswers: [3],
    explanation: "La respuesta correcta es: Que constituye un aparato que clasifica fenómenos, percepciones y acciones",
  },
  {
    id: "hayek-manual-p1-q026",
    chapter: "Parcial 1",
    topic: "Teoría de la mente",
    tags: ["filosofia", "hayek", "parcial-1", "teoria-de-la-mente"],
    difficulty: "easy",
    type: "single",
    question: "Puede decirse que para Hayek los elementos que integran la mente son:",
    options: ["El alcance de la acción estatal que ha de ser guiada por decisiones democráticas", "El cerebro y el SN", "El mérito", "Tiene como fundamento una memoria nerviosa"],
    correctAnswers: [1],
    explanation: "La respuesta correcta es: El cerebro y el SN",
  },
  {
    id: "hayek-manual-p1-q027",
    chapter: "Parcial 1",
    topic: "Teoría de la mente",
    tags: ["filosofia", "hayek", "parcial-1", "teoria-de-la-mente"],
    difficulty: "easy",
    type: "single",
    question: "La función fundamental de la mente humana, a criterio de Hayek",
    options: ["El alcance de la acción estatal que ha de ser guiada por decisiones democráticas", "El mérito", "Tiene como fundamento una memoria nerviosa", "No es sino asegurar la sobrevivencia de los seres humanos"],
    correctAnswers: [3],
    explanation: "La respuesta correcta es: No es sino asegurar la sobrevivencia de los seres humanos",
  },
  {
    id: "hayek-manual-p1-q028",
    chapter: "Parcial 1",
    topic: "Libertad y responsabilidad",
    tags: ["filosofia", "hayek", "parcial-1", "libertad-y-responsabilidad"],
    difficulty: "easy",
    type: "single",
    question: "La libertad es",
    options: ["Es el valor que posibilita incorporar los demás valores en los planes de vida.", "Un valor que puede considerarse el más importante pues sin ella los otros valores no importan", "Una empírica y carente de sistema y otra especulativa y racionalista", "El individuo debe poder eludir el fruto de sus acciones."],
    correctAnswers: [1],
    explanation: "La respuesta correcta es: Un valor que puede considerarse el más importante pues sin ella los otros valores no importan",
  },
  {
    id: "hayek-manual-conceptos-q002",
    chapter: "Conceptos Importantes",
    topic: "Conceptos generales",
    tags: ["filosofia", "hayek", "conceptos-importantes", "conceptos-generales"],
    difficulty: "easy",
    type: "single",
    question: "El orden social espontáneo se denomina así",
    options: ["Mantiene que la razón tiene límites", "Por no compartir el método matemático para hacer ciencia económica.", "Se autogenera", "Por ser producto no intencional de la acción humana"],
    correctAnswers: [3],
    explanation: "La respuesta correcta es: Por ser producto no intencional de la acción humana",
  },
  {
    id: "hayek-manual-p2-q023",
    chapter: "Parcial 2",
    topic: "Derecho, ley y justicia",
    tags: ["filosofia", "hayek", "parcial-2", "derecho-ley-y-justicia"],
    difficulty: "easy",
    type: "single",
    question: "Se deriva del pensamiento liberal, Locke y Hayek, el que",
    options: ["Práctico-normativo: tradiciones, normas evolutivas", "Existen leyes y derechos anteriores y superiores a la legislación", "La ley y la libertad son compatibles pues las leyes generales y abstractas protegen la libertad", "Ausencia de coacción arbitraria de un tercero"],
    correctAnswers: [1],
    explanation: "La respuesta correcta es: Existen leyes y derechos anteriores y superiores a la legislación",
  },
  {
    id: "hayek-manual-p2-q024",
    chapter: "Parcial 2",
    topic: "Tribu, sociedad y orden extenso",
    tags: ["filosofia", "hayek", "parcial-2", "tribu-sociedad-y-orden-extenso"],
    difficulty: "easy",
    type: "single",
    question: "Los fundamentos de la libertad es una obra que",
    options: ["La recompensa provine del valor que otros otorgan a lo que hacemos", "El progreso tiende a estancarse e incluso a retroceder", "El cientificismo ignora la enorme complejidad de la vida en sociedad.", "Destaca una serie de principios rescatables, necesarios y esenciales para la vida en sociedad"],
    correctAnswers: [3],
    explanation: "La respuesta correcta es: Destaca una serie de principios rescatables, necesarios y esenciales para la vida en sociedad",
  },
  {
    id: "hayek-manual-p2-q025",
    chapter: "Parcial 2",
    topic: "Derecho, ley y justicia",
    tags: ["filosofia", "hayek", "parcial-2", "derecho-ley-y-justicia"],
    difficulty: "medium",
    type: "single",
    question: "Para Hayek, justicia social es un concepto",
    options: ["Práctico-normativo: tradiciones, normas evolutivas", "Cuyo significado es inexistente y no tiene contenido", "La ley y la libertad son compatibles pues las leyes generales y abstractas protegen la libertad", "Ausencia de coacción arbitraria de un tercero"],
    correctAnswers: [1],
    explanation: "La respuesta correcta es: Cuyo significado es inexistente y no tiene contenido",
  },
  {
    id: "hayek-manual-p1-q029",
    chapter: "Parcial 1",
    topic: "Órdenes e instituciones",
    tags: ["filosofia", "hayek", "parcial-1", "ordenes-e-instituciones"],
    difficulty: "medium",
    type: "single",
    question: "Cosmos es un tipo de orden:",
    options: ["Surge gracias a reglas abstractas y generales y las segunda gracias a mandatos", "Que, regido por normas tipo thesis, resulta de la voluntad de alguien", "Son, como afirmó Ferguson: results of human but not of human design", "Que, regido por un orden funcional, no resulta de la voluntad de nadie"],
    correctAnswers: [3],
    explanation: "La respuesta correcta es: Que, regido por un orden funcional, no resulta de la voluntad de nadie",
  },
  {
    id: "hayek-manual-p1-q030",
    chapter: "Parcial 1",
    topic: "Órdenes e instituciones",
    tags: ["filosofia", "hayek", "parcial-1", "ordenes-e-instituciones"],
    difficulty: "medium",
    type: "single",
    question: "Taxis es un tipo de orden",
    options: ["Surge gracias a reglas abstractas y generales y las segunda gracias a mandatos", "Que, regido por normas tipo thesis, resulta de la voluntad de alguien", "Que, regido por un orden funcional, no resulta de la voluntad de nadie", "Son, como afirmó Ferguson: results of human but not of human design"],
    correctAnswers: [1],
    explanation: "La respuesta correcta es: Que, regido por normas tipo thesis, resulta de la voluntad de alguien",
  },
  {
    id: "hayek-manual-p1-q031",
    chapter: "Parcial 1",
    topic: "Órdenes e instituciones",
    tags: ["filosofia", "hayek", "parcial-1", "ordenes-e-instituciones"],
    difficulty: "easy",
    type: "single",
    question: "Las instituciones que permiten la convivencia pacífica",
    options: ["Surge gracias a reglas abstractas y generales y las segunda gracias a mandatos", "Que, regido por un orden funcional, no resulta de la voluntad de nadie", "Que, regido por normas tipo thesis, resulta de la voluntad de alguien", "Son, como afirmó Ferguson: results of human but not of human design"],
    correctAnswers: [3],
    explanation: "La respuesta correcta es: Son, como afirmó Ferguson: results of human but not of human design",
  },
  {
    id: "hayek-manual-p2-q026",
    chapter: "Parcial 2",
    topic: "Derecho, ley y justicia",
    tags: ["filosofia", "hayek", "parcial-2", "derecho-ley-y-justicia"],
    difficulty: "easy",
    type: "single",
    question: "La justicia es un concepto que puede ser utilizado perfectamente",
    options: ["Práctico-normativo: tradiciones, normas evolutivas", "Solo en el ámbito del derecho", "La ley y la libertad son compatibles pues las leyes generales y abstractas protegen la libertad", "Ausencia de coacción arbitraria de un tercero"],
    correctAnswers: [1],
    explanation: "La respuesta correcta es: Solo en el ámbito del derecho",
  },
  {
    id: "hayek-manual-p1-q032",
    chapter: "Parcial 1",
    topic: "Tradiciones de la libertad",
    tags: ["filosofia", "hayek", "parcial-1", "tradiciones-de-la-libertad"],
    difficulty: "medium",
    type: "single",
    question: "Puede afirmarse sin dudas que Hayek",
    options: ["Promueve la confianza en las instituciones", "Han sido diseñadas por la razón humana", "Como una confianza desmedida en el poder de la razón humana", "Es un claro enemigo del racionalismo pero no de la razón."],
    correctAnswers: [3],
    explanation: "La respuesta correcta es: Es un claro enemigo del racionalismo pero no de la razón.",
  },
  {
    id: "hayek-manual-conceptos-q003",
    chapter: "Conceptos Importantes",
    topic: "Conceptos generales",
    tags: ["filosofia", "hayek", "conceptos-importantes", "conceptos-generales"],
    difficulty: "hard",
    type: "single",
    question: "Hayek al parecer, fue excluido de las cátedras de economía en Chicago",
    options: ["Mantiene que la razón tiene límites", "Por no compartir el método matemático para hacer ciencia económica.", "Por ser producto no intencional de la acción humana", "Se autogenera"],
    correctAnswers: [1],
    explanation: "La respuesta correcta es: Por no compartir el método matemático para hacer ciencia económica.",
  },
  {
    id: "hayek-manual-p2-q027",
    chapter: "Parcial 2",
    topic: "Valor, mérito y economía",
    tags: ["filosofia", "hayek", "parcial-2", "valor-merito-y-economia"],
    difficulty: "easy",
    type: "single",
    question: "La Escuela Austriaca de economía pudo resolver el problema del valor",
    options: ["Mantienen el sistema de orden competitivo y pueden buscar objetivos no lucrativos", "La existencia de empresarios individuales dispuestos a invertir y actuar por iniciativa propia", "Por ser producto no intencional de la acción humana", "Colocando en el centro de la cuestión al individuo humano como actor que elige y renuncia."],
    correctAnswers: [3],
    explanation: "La respuesta correcta es: Colocando en el centro de la cuestión al individuo humano como actor que elige y renuncia.",
  },
  {
    id: "hayek-manual-p1-q033",
    chapter: "Parcial 1",
    topic: "Teoría de la mente",
    tags: ["filosofia", "hayek", "parcial-1", "teoria-de-la-mente"],
    difficulty: "easy",
    type: "single",
    question: "La tradición francesa se diferencia de la inglesa en que",
    options: ["El alcance de la acción estatal que ha de ser guiada por decisiones democráticas", "Ingenuamente cree que la razón lo puede todos, mientras la inglesa no.", "El mérito", "Tiene como fundamento una memoria nerviosa"],
    correctAnswers: [1],
    explanation: "La respuesta correcta es: Ingenuamente cree que la razón lo puede todos, mientras la inglesa no.",
  },
  {
    id: "hayek-manual-p1-q034",
    chapter: "Parcial 1",
    topic: "Teoría de la mente",
    tags: ["filosofia", "hayek", "parcial-1", "teoria-de-la-mente"],
    difficulty: "medium",
    type: "single",
    question: "La tradición francesa acepta :",
    options: ["El alcance de la acción estatal que ha de ser guiada por decisiones democráticas", "El mérito", "Tiene como fundamento una memoria nerviosa", "La existencia únicamente de los ordenes creados deliberadamente (tipo taxis)"],
    correctAnswers: [3],
    explanation: "La respuesta correcta es: La existencia únicamente de los ordenes creados deliberadamente (tipo taxis)",
  },
  {
    id: "hayek-manual-conceptos-q004",
    chapter: "Conceptos Importantes",
    topic: "Conceptos generales",
    tags: ["filosofia", "hayek", "conceptos-importantes", "conceptos-generales"],
    difficulty: "easy",
    type: "single",
    question: "Un orden denominado espontáneo",
    options: ["Mantiene que la razón tiene límites", "Se autogenera", "Por ser producto no intencional de la acción humana", "Por no compartir el método matemático para hacer ciencia económica."],
    correctAnswers: [1],
    explanation: "La respuesta correcta es: Se autogenera",
  },
  {
    id: "hayek-manual-p1-q035",
    chapter: "Parcial 1",
    topic: "Órdenes e instituciones",
    tags: ["filosofia", "hayek", "parcial-1", "ordenes-e-instituciones"],
    difficulty: "medium",
    type: "single",
    question: "Un orden espontáneo",
    options: ["Surge gracias a reglas abstractas y generales y las segunda gracias a mandatos", "Que, regido por un orden funcional, no resulta de la voluntad de nadie", "Que, regido por normas tipo thesis, resulta de la voluntad de alguien", "Se profetice al actuar cada elemento obedeciendo patrones de conducta regulares"],
    correctAnswers: [3],
    explanation: "La respuesta correcta es: Se profetice al actuar cada elemento obedeciendo patrones de conducta regulares",
  },
  {
    id: "hayek-manual-p2-q028",
    chapter: "Parcial 2",
    topic: "Derecho, ley y justicia",
    tags: ["filosofia", "hayek", "parcial-2", "derecho-ley-y-justicia"],
    difficulty: "hard",
    type: "single",
    question: "El positivismo jurídico se resume en la siguiente afirmación:",
    options: ["Práctico-normativo: tradiciones, normas evolutivas", "No hay let un derecho sin un legislador", "La ley y la libertad son compatibles pues las leyes generales y abstractas protegen la libertad", "Ausencia de coacción arbitraria de un tercero"],
    correctAnswers: [1],
    explanation: "La respuesta correcta es: No hay let un derecho sin un legislador",
  },
  {
    id: "hayek-manual-p2-q029",
    chapter: "Parcial 2",
    topic: "Derecho, ley y justicia",
    tags: ["filosofia", "hayek", "parcial-2", "derecho-ley-y-justicia"],
    difficulty: "medium",
    type: "single",
    question: "La tradición del derecho consuetudinario (costumbre):",
    options: ["Práctico-normativo: tradiciones, normas evolutivas", "La ley y la libertad son compatibles pues las leyes generales y abstractas protegen la libertad", "Ausencia de coacción arbitraria de un tercero", "Afirma que la ley y el derecho son anteriores a la legislación."],
    correctAnswers: [3],
    explanation: "La respuesta correcta es: Afirma que la ley y el derecho son anteriores a la legislación.",
  },
  {
    id: "hayek-manual-p1-q036",
    chapter: "Parcial 1",
    topic: "Tradiciones de la libertad",
    tags: ["filosofia", "hayek", "parcial-1", "tradiciones-de-la-libertad"],
    difficulty: "easy",
    type: "single",
    question: "La tradición inglesa",
    options: ["Promueve la confianza en las instituciones", "Promovió la confianza en las instituciones y no en la naturaleza humana.", "Han sido diseñadas por la razón humana", "Como una confianza desmedida en el poder de la razón humana"],
    correctAnswers: [1],
    explanation: "La respuesta correcta es: Promovió la confianza en las instituciones y no en la naturaleza humana.",
  },
  {
    id: "hayek-manual-p2-q030",
    chapter: "Parcial 2",
    topic: "Derecho, ley y justicia",
    tags: ["filosofia", "hayek", "parcial-2", "derecho-ley-y-justicia"],
    difficulty: "easy",
    type: "single",
    question: "La libertad se define",
    options: ["Práctico-normativo: tradiciones, normas evolutivas", "La ley y la libertad son compatibles pues las leyes generales y abstractas protegen la libertad", "Ausencia de coacción arbitraria de un tercero", "Negativamente: ausencia de coacción arbitraria"],
    correctAnswers: [3],
    explanation: "La respuesta correcta es: Negativamente: ausencia de coacción arbitraria",
  },
  {
    id: "hayek-manual-p1-q037",
    chapter: "Parcial 1",
    topic: "Libertad y responsabilidad",
    tags: ["filosofia", "hayek", "parcial-1", "libertad-y-responsabilidad"],
    difficulty: "easy",
    type: "single",
    question: "La libertad tiene un ámbito estricto",
    options: ["Es el valor que posibilita incorporar los demás valores en los planes de vida.", "El de las relaciones entre los seres humanos", "Una empírica y carente de sistema y otra especulativa y racionalista", "El individuo debe poder eludir el fruto de sus acciones."],
    correctAnswers: [1],
    explanation: "La respuesta correcta es: El de las relaciones entre los seres humanos",
  },
  {
    id: "hayek-manual-p1-q038",
    chapter: "Parcial 1",
    topic: "Libertad y responsabilidad",
    tags: ["filosofia", "hayek", "parcial-1", "libertad-y-responsabilidad"],
    difficulty: "easy",
    type: "single",
    question: "Hoy en día se puede afirmar que:",
    options: ["Es el valor que posibilita incorporar los demás valores en los planes de vida.", "Una empírica y carente de sistema y otra especulativa y racionalista", "El individuo debe poder eludir el fruto de sus acciones.", "El mayor enemigo de la libertad es el gobierno"],
    correctAnswers: [3],
    explanation: "La respuesta correcta es: El mayor enemigo de la libertad es el gobierno",
  },
  {
    id: "hayek-manual-conceptos-q005",
    chapter: "Conceptos Importantes",
    topic: "Conceptos generales",
    tags: ["filosofia", "hayek", "conceptos-importantes", "conceptos-generales"],
    difficulty: "easy",
    type: "single",
    question: "Se puede afirmar que Hayek",
    options: ["Mantiene que la razón tiene límites", "Ve la necesidad de poner limites al poder gubernamental", "Por ser producto no intencional de la acción humana", "Por no compartir el método matemático para hacer ciencia económica."],
    correctAnswers: [1],
    explanation: "La respuesta correcta es: Ve la necesidad de poner limites al poder gubernamental",
  },
  {
    id: "hayek-manual-p2-q031",
    chapter: "Parcial 2",
    topic: "Derecho, ley y justicia",
    tags: ["filosofia", "hayek", "parcial-2", "derecho-ley-y-justicia"],
    difficulty: "easy",
    type: "single",
    question: "De acuerdo a las ideas hayekianas",
    options: ["Práctico-normativo: tradiciones, normas evolutivas", "La ley y la libertad son compatibles pues las leyes generales y abstractas protegen la libertad", "Ausencia de coacción arbitraria de un tercero", "La ley y la libertad son compatibles pues las buenas leyes protegen la libertad"],
    correctAnswers: [3],
    explanation: "La respuesta correcta es: La ley y la libertad son compatibles pues las buenas leyes protegen la libertad",
  },
  {
    id: "hayek-manual-p2-q032",
    chapter: "Parcial 2",
    topic: "Derecho, ley y justicia",
    tags: ["filosofia", "hayek", "parcial-2", "derecho-ley-y-justicia"],
    difficulty: "easy",
    type: "single",
    question: "La coacción que debe minimizarse, dice Hayek es la arbitraria",
    options: ["Práctico-normativo: tradiciones, normas evolutivas", "Pues resulta del antojo, discrecionalidad y parecer de los gobernantes", "La ley y la libertad son compatibles pues las leyes generales y abstractas protegen la libertad", "Ausencia de coacción arbitraria de un tercero"],
    correctAnswers: [1],
    explanation: "La respuesta correcta es: Pues resulta del antojo, discrecionalidad y parecer de los gobernantes",
  },
  {
    id: "hayek-manual-p2-q033",
    chapter: "Parcial 2",
    topic: "Tribu, sociedad y orden extenso",
    tags: ["filosofia", "hayek", "parcial-2", "tribu-sociedad-y-orden-extenso"],
    difficulty: "easy",
    type: "single",
    question: "La tribu puede definirse como",
    options: ["La recompensa provine del valor que otros otorgan a lo que hacemos", "El progreso tiende a estancarse e incluso a retroceder", "El cientificismo ignora la enorme complejidad de la vida en sociedad.", "Un grupo asentado en un sitio fijo en el que no existe la cooperación sino la obligatoriedad"],
    correctAnswers: [3],
    explanation: "La respuesta correcta es: Un grupo asentado en un sitio fijo en el que no existe la cooperación sino la obligatoriedad",
  },
  {
    id: "hayek-manual-p2-q034",
    chapter: "Parcial 2",
    topic: "Tribu, sociedad y orden extenso",
    tags: ["filosofia", "hayek", "parcial-2", "tribu-sociedad-y-orden-extenso"],
    difficulty: "easy",
    type: "single",
    question: "Una diferencia entre la tribu y la sociedad es",
    options: ["La recompensa provine del valor que otros otorgan a lo que hacemos", "Que la tribu regía el estatus adscrito y en la sociedad el estatus es adquirido", "El progreso tiende a estancarse e incluso a retroceder", "El cientificismo ignora la enorme complejidad de la vida en sociedad."],
    correctAnswers: [1],
    explanation: "La respuesta correcta es: Que la tribu regía el estatus adscrito y en la sociedad el estatus es adquirido",
  },
  {
    id: "hayek-manual-p1-q039",
    chapter: "Parcial 1",
    topic: "Teoría de la mente",
    tags: ["filosofia", "hayek", "parcial-1", "teoria-de-la-mente"],
    difficulty: "easy",
    type: "single",
    question: "Aunque el hombre tribal es profundamente solidario",
    options: ["El alcance de la acción estatal que ha de ser guiada por decisiones democráticas", "El mérito", "Tiene como fundamento una memoria nerviosa", "Su actitud hacia lo ajeno y extraño es de desconfianza y rechazo (incluso, de violencia)"],
    correctAnswers: [3],
    explanation: "La respuesta correcta es: Su actitud hacia lo ajeno y extraño es de desconfianza y rechazo (incluso, de violencia)",
  },
  {
    id: "hayek-manual-p2-q035",
    chapter: "Parcial 2",
    topic: "Democracia y liberalismo",
    tags: ["filosofia", "hayek", "parcial-2", "democracia-y-liberalismo"],
    difficulty: "easy",
    type: "single",
    question: "La evolución hacia la vida en el orden extenso de cooperación",
    options: ["Expresa la opinion de la mayoría y no la voluntad de la sociedad", "Ha conducido a que la gran mayoría de nuestras relaciones sean contra lectura les y transferibles", "Demagogia", "La limitación del poder coactivo de todos los gobiernos"],
    correctAnswers: [1],
    explanation: "La respuesta correcta es: Ha conducido a que la gran mayoría de nuestras relaciones sean contra lectura les y transferibles",
  },
  {
    id: "hayek-manual-p2-q036",
    chapter: "Parcial 2",
    topic: "Tribu, sociedad y orden extenso",
    tags: ["filosofia", "hayek", "parcial-2", "tribu-sociedad-y-orden-extenso"],
    difficulty: "easy",
    type: "single",
    question: "Los sentimientos, base de las relaciones tribales, se han sustituido en la sociedad:",
    options: ["La recompensa provine del valor que otros otorgan a lo que hacemos", "El progreso tiende a estancarse e incluso a retroceder", "El cientificismo ignora la enorme complejidad de la vida en sociedad.", "Por el sometimiento a normas generales, abstractas e iguales para todos."],
    correctAnswers: [3],
    explanation: "La respuesta correcta es: Por el sometimiento a normas generales, abstractas e iguales para todos.",
  },
  {
    id: "hayek-manual-p2-q037",
    chapter: "Parcial 2",
    topic: "Tribu, sociedad y orden extenso",
    tags: ["filosofia", "hayek", "parcial-2", "tribu-sociedad-y-orden-extenso"],
    difficulty: "medium",
    type: "single",
    question: "La idea fundamental al diferenciar la tribu de la sociedad es que",
    options: ["La recompensa provine del valor que otros otorgan a lo que hacemos", "Se trata de experiencias sociales tan distintas que la sustitución de un por la otra implica la destruction de ambas, la sociedad jamás puede funcionar como una tribu", "El progreso tiende a estancarse e incluso a retroceder", "El cientificismo ignora la enorme complejidad de la vida en sociedad."],
    correctAnswers: [1],
    explanation: "La respuesta correcta es: Se trata de experiencias sociales tan distintas que la sustitución de un por la otra implica la destruction de ambas, la sociedad jamás puede funcionar como una tribu",
  },
  {
    id: "hayek-manual-conceptos-q006",
    chapter: "Conceptos Importantes",
    topic: "Conceptos generales",
    tags: ["filosofia", "hayek", "conceptos-importantes", "conceptos-generales"],
    difficulty: "easy",
    type: "single",
    question: "El estilo de vida tibral empieza a abandonarse",
    options: ["Mantiene que la razón tiene límites", "Por ser producto no intencional de la acción humana", "Por no compartir el método matemático para hacer ciencia económica.", "Al surgir el gobierno que era algo desconocido por el pequeño grupo primitivo"],
    correctAnswers: [3],
    explanation: "La respuesta correcta es: Al surgir el gobierno que era algo desconocido por el pequeño grupo primitivo",
  },
  {
    id: "hayek-manual-p2-q038",
    chapter: "Parcial 2",
    topic: "Tribu, sociedad y orden extenso",
    tags: ["filosofia", "hayek", "parcial-2", "tribu-sociedad-y-orden-extenso"],
    difficulty: "medium",
    type: "single",
    question: "Existe alguna nostalgia por retornar a la tribu",
    options: ["La recompensa provine del valor que otros otorgan a lo que hacemos", "En algunos religiosos o intelectuales que creen que los I problemas económicos los resuelve el sentimiento del amor.", "El progreso tiende a estancarse e incluso a retroceder", "El cientificismo ignora la enorme complejidad de la vida en sociedad."],
    correctAnswers: [1],
    explanation: "La respuesta correcta es: En algunos religiosos o intelectuales que creen que los I problemas económicos los resuelve el sentimiento del amor.",
  },
  {
    id: "hayek-manual-p1-q040",
    chapter: "Parcial 1",
    topic: "Progreso y civilización",
    tags: ["filosofia", "hayek", "parcial-1", "progreso-y-civilizacion"],
    difficulty: "easy",
    type: "single",
    question: "El progreso es una idea",
    options: ["Cuando en la persecución de sus fines el individuo puede sobrepasar los límites de su ignorancia, aprovechándose del conocimiento disperso.", "No puede dirigirse", "Ya que su uso producirá resultados imprevisibles", "Propia del siglo 18 y desarrollada durante el 19 y 20"],
    correctAnswers: [3],
    explanation: "La respuesta correcta es: Propia del siglo 18 y desarrollada durante el 19 y 20",
  },
  {
    id: "hayek-manual-p1-q041",
    chapter: "Parcial 1",
    topic: "Progreso y civilización",
    tags: ["filosofia", "hayek", "parcial-1", "progreso-y-civilizacion"],
    difficulty: "easy",
    type: "single",
    question: "La idea de progreso surgió",
    options: ["Cuando en la persecución de sus fines el individuo puede sobrepasar los límites de su ignorancia, aprovechándose del conocimiento disperso.", "Con la convicción de que la historia humana era una serie de etapas que se superaban unas a otras.", "No puede dirigirse", "Ya que su uso producirá resultados imprevisibles"],
    correctAnswers: [1],
    explanation: "La respuesta correcta es: Con la convicción de que la historia humana era una serie de etapas que se superaban unas a otras.",
  },
  {
    id: "hayek-manual-p1-q042",
    chapter: "Parcial 1",
    topic: "Progreso y civilización",
    tags: ["filosofia", "hayek", "parcial-1", "progreso-y-civilizacion"],
    difficulty: "hard",
    type: "single",
    question: "Progreso, significo para Turgot",
    options: ["Cuando en la persecución de sus fines el individuo puede sobrepasar los límites de su ignorancia, aprovechándose del conocimiento disperso.", "No puede dirigirse", "Ya que su uso producirá resultados imprevisibles", "Lo mejor está por venir"],
    correctAnswers: [3],
    explanation: "La respuesta correcta es: Lo mejor está por venir",
  },
  {
    id: "hayek-manual-p1-q043",
    chapter: "Parcial 1",
    topic: "Progreso y civilización",
    tags: ["filosofia", "hayek", "parcial-1", "progreso-y-civilizacion"],
    difficulty: "hard",
    type: "single",
    question: "El pensamiento de Marx quizás fue el que mayor eco hizo a la idea de progreso",
    options: ["Cuando en la persecución de sus fines el individuo puede sobrepasar los límites de su ignorancia, aprovechándose del conocimiento disperso.", "Al proponer que la próxima etapa histórica sería el socialismo, antesala del comunismo mundial.", "No puede dirigirse", "Ya que su uso producirá resultados imprevisibles"],
    correctAnswers: [1],
    explanation: "La respuesta correcta es: Al proponer que la próxima etapa histórica sería el socialismo, antesala del comunismo mundial.",
  },
  {
    id: "hayek-manual-p2-q039",
    chapter: "Parcial 2",
    topic: "Derecho, ley y justicia",
    tags: ["filosofia", "hayek", "parcial-2", "derecho-ley-y-justicia"],
    difficulty: "easy",
    type: "single",
    question: "Ha habido pensadores sociales que han afirmado",
    options: ["Práctico-normativo: tradiciones, normas evolutivas", "La ley y la libertad son compatibles pues las leyes generales y abstractas protegen la libertad", "Ausencia de coacción arbitraria de un tercero", "Que el progreso es resultado de leyes impersonales y que nadie puede detenerlo"],
    correctAnswers: [3],
    explanation: "La respuesta correcta es: Que el progreso es resultado de leyes impersonales y que nadie puede detenerlo",
  },
  {
    id: "hayek-manual-p1-q044",
    chapter: "Parcial 1",
    topic: "Progreso y civilización",
    tags: ["filosofia", "hayek", "parcial-1", "progreso-y-civilizacion"],
    difficulty: "easy",
    type: "single",
    question: "Hayek habla del poder creador de la civilización libre",
    options: ["Cuando en la persecución de sus fines el individuo puede sobrepasar los límites de su ignorancia, aprovechándose del conocimiento disperso.", "Porque la civilización es algo relativamente reciente en comparación con la edad de la humanidad.", "No puede dirigirse", "Ya que su uso producirá resultados imprevisibles"],
    correctAnswers: [1],
    explanation: "La respuesta correcta es: Porque la civilización es algo relativamente reciente en comparación con la edad de la humanidad.",
  },
  {
    id: "hayek-manual-p1-q045",
    chapter: "Parcial 1",
    topic: "Teoría de la mente",
    tags: ["filosofia", "hayek", "parcial-1", "teoria-de-la-mente"],
    difficulty: "easy",
    type: "single",
    question: "La libertad se define negativamente",
    options: ["El alcance de la acción estatal que ha de ser guiada por decisiones democráticas", "El mérito", "Tiene como fundamento una memoria nerviosa", "Pero en práctica es actuar de acuerdo a planes y fines propios"],
    correctAnswers: [3],
    explanation: "La respuesta correcta es: Pero en práctica es actuar de acuerdo a planes y fines propios",
  },
  {
    id: "hayek-manual-p2-q040",
    chapter: "Parcial 2",
    topic: "Derecho, ley y justicia",
    tags: ["filosofia", "hayek", "parcial-2", "derecho-ley-y-justicia"],
    difficulty: "easy",
    type: "single",
    question: "Es preferible referirse al ámbito jurídico como",
    options: ["Práctico-normativo: tradiciones, normas evolutivas", "Jurisprudencia", "La ley y la libertad son compatibles pues las leyes generales y abstractas protegen la libertad", "Ausencia de coacción arbitraria de un tercero"],
    correctAnswers: [1],
    explanation: "La respuesta correcta es: Jurisprudencia",
  },
  {
    id: "hayek-manual-p1-q046",
    chapter: "Parcial 1",
    topic: "Libertad y responsabilidad",
    tags: ["filosofia", "hayek", "parcial-1", "libertad-y-responsabilidad"],
    difficulty: "easy",
    type: "single",
    question: "El que los seres humanos vayan tras fines diversos",
    options: ["Es el valor que posibilita incorporar los demás valores en los planes de vida.", "Una empírica y carente de sistema y otra especulativa y racionalista", "El individuo debe poder eludir el fruto de sus acciones.", "No es causa de conflictos o rompimiento del orden social"],
    correctAnswers: [3],
    explanation: "La respuesta correcta es: No es causa de conflictos o rompimiento del orden social",
  },
  {
    id: "hayek-manual-p2-q041",
    chapter: "Parcial 2",
    topic: "Tribu, sociedad y orden extenso",
    tags: ["filosofia", "hayek", "parcial-2", "tribu-sociedad-y-orden-extenso"],
    difficulty: "easy",
    type: "single",
    question: "La evolución de la tribu a la sociedad",
    options: ["La recompensa provine del valor que otros otorgan a lo que hacemos", "Hizo que las relaciones de cooperación se ampliaran y fueran más efectivas", "El progreso tiende a estancarse e incluso a retroceder", "El cientificismo ignora la enorme complejidad de la vida en sociedad."],
    correctAnswers: [1],
    explanation: "La respuesta correcta es: Hizo que las relaciones de cooperación se ampliaran y fueran más efectivas",
  },
  {
    id: "hayek-manual-p2-q042",
    chapter: "Parcial 2",
    topic: "Derecho, ley y justicia",
    tags: ["filosofia", "hayek", "parcial-2", "derecho-ley-y-justicia"],
    difficulty: "easy",
    type: "single",
    question: "La definición hayekiana de justicia",
    options: ["Práctico-normativo: tradiciones, normas evolutivas", "La ley y la libertad son compatibles pues las leyes generales y abstractas protegen la libertad", "Ausencia de coacción arbitraria de un tercero", "Es negativa (ausencia de actos injustos)"],
    correctAnswers: [3],
    explanation: "La respuesta correcta es: Es negativa (ausencia de actos injustos)",
  },
  {
    id: "hayek-manual-p2-q043",
    chapter: "Parcial 2",
    topic: "Derecho, ley y justicia",
    tags: ["filosofia", "hayek", "parcial-2", "derecho-ley-y-justicia"],
    difficulty: "easy",
    type: "single",
    question: "Justicia es, desde el punto de vista de Hayek",
    options: ["Práctico-normativo: tradiciones, normas evolutivas", "Ausencia de actos violatorios de las normas de recto actuar", "La ley y la libertad son compatibles pues las leyes generales y abstractas protegen la libertad", "Ausencia de coacción arbitraria de un tercero"],
    correctAnswers: [1],
    explanation: "La respuesta correcta es: Ausencia de actos violatorios de las normas de recto actuar",
  },
  {
    id: "hayek-manual-conceptos-q007",
    chapter: "Conceptos Importantes",
    topic: "Conceptos generales",
    tags: ["filosofia", "hayek", "conceptos-importantes", "conceptos-generales"],
    difficulty: "easy",
    type: "single",
    question: "Las llamadas normas de recto comportamiento",
    options: ["Mantiene que la razón tiene límites", "Por ser producto no intencional de la acción humana", "Por no compartir el método matemático para hacer ciencia económica.", "Son el criterio para saber cuando las acciones humans son justas o no"],
    correctAnswers: [3],
    explanation: "La respuesta correcta es: Son el criterio para saber cuando las acciones humans son justas o no",
  },
  {
    id: "hayek-manual-p2-q044",
    chapter: "Parcial 2",
    topic: "Derecho, ley y justicia",
    tags: ["filosofia", "hayek", "parcial-2", "derecho-ley-y-justicia"],
    difficulty: "easy",
    type: "single",
    question: "El criterio de justicia de acuerdo a Hayek debe ser",
    options: ["Práctico-normativo: tradiciones, normas evolutivas", "Impersonal y universal", "La ley y la libertad son compatibles pues las leyes generales y abstractas protegen la libertad", "Ausencia de coacción arbitraria de un tercero"],
    correctAnswers: [1],
    explanation: "La respuesta correcta es: Impersonal y universal",
  },
  {
    id: "hayek-manual-p2-q045",
    chapter: "Parcial 2",
    topic: "Derecho, ley y justicia",
    tags: ["filosofia", "hayek", "parcial-2", "derecho-ley-y-justicia"],
    difficulty: "easy",
    type: "single",
    question: "Justicia es un concepto hayekianamente hablando",
    options: ["Práctico-normativo: tradiciones, normas evolutivas", "La ley y la libertad son compatibles pues las leyes generales y abstractas protegen la libertad", "Ausencia de coacción arbitraria de un tercero", "Se aplica exclusivamente a las acciones humanas"],
    correctAnswers: [3],
    explanation: "La respuesta correcta es: Se aplica exclusivamente a las acciones humanas",
  },
  {
    id: "hayek-manual-p2-q046",
    chapter: "Parcial 2",
    topic: "Derecho, ley y justicia",
    tags: ["filosofia", "hayek", "parcial-2", "derecho-ley-y-justicia"],
    difficulty: "easy",
    type: "single",
    question: "La justicia es un valor que",
    options: ["Práctico-normativo: tradiciones, normas evolutivas", "Logran encarnar quienes respetan la esfera de derechos individuales de los demás.", "La ley y la libertad son compatibles pues las leyes generales y abstractas protegen la libertad", "Ausencia de coacción arbitraria de un tercero"],
    correctAnswers: [1],
    explanation: "La respuesta correcta es: Logran encarnar quienes respetan la esfera de derechos individuales de los demás.",
  },
  {
    id: "hayek-manual-p2-q047",
    chapter: "Parcial 2",
    topic: "Democracia y liberalismo",
    tags: ["filosofia", "hayek", "parcial-2", "democracia-y-liberalismo"],
    difficulty: "easy",
    type: "single",
    question: "La democracia, según Hayek",
    options: ["Expresa la opinion de la mayoría y no la voluntad de la sociedad", "Demagogia", "La limitación del poder coactivo de todos los gobiernos", "Solo puede sobrevivir si existe un verdadero estado de derecho."],
    correctAnswers: [3],
    explanation: "La respuesta correcta es: Solo puede sobrevivir si existe un verdadero estado de derecho.",
  },
  {
    id: "hayek-manual-p2-q048",
    chapter: "Parcial 2",
    topic: "Democracia y liberalismo",
    tags: ["filosofia", "hayek", "parcial-2", "democracia-y-liberalismo"],
    difficulty: "easy",
    type: "single",
    question: "El gobierno democrático fácilmente se puede",
    options: ["Expresa la opinion de la mayoría y no la voluntad de la sociedad", "Convertir en la tiranía de la mayoría sobre cualquier minoría", "Demagogia", "La limitación del poder coactivo de todos los gobiernos"],
    correctAnswers: [1],
    explanation: "La respuesta correcta es: Convertir en la tiranía de la mayoría sobre cualquier minoría",
  },
  {
    id: "hayek-manual-p2-q049",
    chapter: "Parcial 2",
    topic: "Democracia y liberalismo",
    tags: ["filosofia", "hayek", "parcial-2", "democracia-y-liberalismo"],
    difficulty: "easy",
    type: "single",
    question: "En torno a la democracia y otras formas de gobierno la opinion del liberalismo es",
    options: ["Expresa la opinion de la mayoría y no la voluntad de la sociedad", "Demagogia", "La limitación del poder coactivo de todos los gobiernos", "Que no importa la forma de gobierno sino poner limites al ejercicio del poder"],
    correctAnswers: [3],
    explanation: "La respuesta correcta es: Que no importa la forma de gobierno sino poner limites al ejercicio del poder",
  },
  {
    id: "hayek-manual-p2-q050",
    chapter: "Parcial 2",
    topic: "Democracia y liberalismo",
    tags: ["filosofia", "hayek", "parcial-2", "democracia-y-liberalismo"],
    difficulty: "easy",
    type: "single",
    question: "La degradación de la práctica democrática ha conducido a que se piense que",
    options: ["Expresa la opinion de la mayoría y no la voluntad de la sociedad", "Todo los une ocurre en la sociedad debe ser producto de la voluntad de la mayoría.", "Demagogia", "La limitación del poder coactivo de todos los gobiernos"],
    correctAnswers: [1],
    explanation: "La respuesta correcta es: Todo los une ocurre en la sociedad debe ser producto de la voluntad de la mayoría.",
  },
  {
    id: "hayek-manual-p2-q051",
    chapter: "Parcial 2",
    topic: "Democracia y liberalismo",
    tags: ["filosofia", "hayek", "parcial-2", "democracia-y-liberalismo"],
    difficulty: "medium",
    type: "single",
    question: "Con relación al valor y mérito nos percatamos que la mayoría de personas no combate la mera existencia de la desigualdad sino que",
    options: ["Expresa la opinion de la mayoría y no la voluntad de la sociedad", "Demagogia", "La limitación del poder coactivo de todos los gobiernos", "Se oponen a la desigualdad social, dado que la sociedad debería seer un medio para que toso tengan las mismas oportunidades"],
    correctAnswers: [3],
    explanation: "La respuesta correcta es: Se oponen a la desigualdad social, dado que la sociedad debería seer un medio para que toso tengan las mismas oportunidades",
  },
  {
    id: "hayek-manual-conceptos-q008",
    chapter: "Conceptos Importantes",
    topic: "Conceptos generales",
    tags: ["filosofia", "hayek", "conceptos-importantes", "conceptos-generales"],
    difficulty: "easy",
    type: "single",
    question: "Nuestro nivel de vida se ha elevado no solo porque podemos consumir mas de los mismo si no porque:",
    options: ["Mantiene que la razón tiene límites", "Usamos cosas diferentes y cosas desconocidas", "Por ser producto no intencional de la acción humana", "Por no compartir el método matemático para hacer ciencia económica."],
    correctAnswers: [1],
    explanation: "La respuesta correcta es: Usamos cosas diferentes y cosas desconocidas",
  },
  {
    id: "hayek-manual-p1-q047",
    chapter: "Parcial 1",
    topic: "Teoría de la mente",
    tags: ["filosofia", "hayek", "parcial-1", "teoria-de-la-mente"],
    difficulty: "hard",
    type: "single",
    question: "La propuesta esencial de Hayek es que en las ciencias sociales solamente se debe utilizar el",
    options: ["El alcance de la acción estatal que ha de ser guiada por decisiones democráticas", "El mérito", "Tiene como fundamento una memoria nerviosa", "Individualismo metodológico"],
    correctAnswers: [3],
    explanation: "La respuesta correcta es: Individualismo metodológico",
  },
  {
    id: "hayek-manual-p2-q052",
    chapter: "Parcial 2",
    topic: "Democracia y liberalismo",
    tags: ["filosofia", "hayek", "parcial-2", "democracia-y-liberalismo"],
    difficulty: "easy",
    type: "single",
    question: "La libertada se halla gravemente amenizada porque",
    options: ["Expresa la opinion de la mayoría y no la voluntad de la sociedad", "La mayoría de asalariada, trata de imponer sus criterios y opiniones sobre los demás", "Demagogia", "La limitación del poder coactivo de todos los gobiernos"],
    correctAnswers: [1],
    explanation: "La respuesta correcta es: La mayoría de asalariada, trata de imponer sus criterios y opiniones sobre los demás",
  },
  {
    id: "hayek-manual-p2-q053",
    chapter: "Parcial 2",
    topic: "Democracia y liberalismo",
    tags: ["filosofia", "hayek", "parcial-2", "democracia-y-liberalismo"],
    difficulty: "easy",
    type: "single",
    question: "La democracia deriva en demagogia cuando",
    options: ["Expresa la opinion de la mayoría y no la voluntad de la sociedad", "Demagogia", "La limitación del poder coactivo de todos los gobiernos", "Lo justo es lo que la mayoría decide"],
    correctAnswers: [3],
    explanation: "La respuesta correcta es: Lo justo es lo que la mayoría decide",
  },
  {
    id: "hayek-manual-p1-q048",
    chapter: "Parcial 1",
    topic: "Teoría de la mente",
    tags: ["filosofia", "hayek", "parcial-1", "teoria-de-la-mente"],
    difficulty: "hard",
    type: "single",
    question: "La postura que los deterministas sostienen sobre la responsabilidad es que",
    options: ["El alcance de la acción estatal que ha de ser guiada por decisiones democráticas", "Las acciones humanas están determinadas completamente por causas naturales, no pueden haber justificación para hacer responsables a los individuos y alabarles o censurarles por sus actos", "El mérito", "Tiene como fundamento una memoria nerviosa"],
    correctAnswers: [1],
    explanation: "La respuesta correcta es: Las acciones humanas están determinadas completamente por causas naturales, no pueden haber justificación para hacer responsables a los individuos y alabarles o censurarles por sus actos",
  },
  {
    id: "hayek-manual-conceptos-q009",
    chapter: "Conceptos Importantes",
    topic: "Conceptos generales",
    tags: ["filosofia", "hayek", "conceptos-importantes", "conceptos-generales"],
    difficulty: "easy",
    type: "single",
    question: "El desarrollo humano de los grupos dependerá de cohesion a un código ético, de sus ideales de bienestar pero también de",
    options: ["Mantiene que la razón tiene límites", "Por ser producto no intencional de la acción humana", "Por no compartir el método matemático para hacer ciencia económica.", "Del grado en que hayan aprendido o no a satisfacer sus necesidades materiales"],
    correctAnswers: [3],
    explanation: "La respuesta correcta es: Del grado en que hayan aprendido o no a satisfacer sus necesidades materiales",
  },
  {
    id: "hayek-manual-conceptos-q010",
    chapter: "Conceptos Importantes",
    topic: "Conceptos generales",
    tags: ["filosofia", "hayek", "conceptos-importantes", "conceptos-generales"],
    difficulty: "easy",
    type: "single",
    question: "De qué depende el que una persona sea libre",
    options: ["Mantiene que la razón tiene límites", "De la posibilidad de dirigir sus acciones según sus intenciones.", "Por ser producto no intencional de la acción humana", "Por no compartir el método matemático para hacer ciencia económica."],
    correctAnswers: [1],
    explanation: "La respuesta correcta es: De la posibilidad de dirigir sus acciones según sus intenciones.",
  },
  {
    id: "hayek-manual-conceptos-q011",
    chapter: "Conceptos Importantes",
    topic: "Conceptos generales",
    tags: ["filosofia", "hayek", "conceptos-importantes", "conceptos-generales"],
    difficulty: "easy",
    type: "single",
    question: "Le evolución social se refiere a",
    options: ["Mantiene que la razón tiene límites", "Por ser producto no intencional de la acción humana", "Por no compartir el método matemático para hacer ciencia económica.", "La imitación de hábitos, tradiciones e ideas exitosas en el tiempo"],
    correctAnswers: [3],
    explanation: "La respuesta correcta es: La imitación de hábitos, tradiciones e ideas exitosas en el tiempo",
  },
  {
    id: "hayek-manual-p1-q049",
    chapter: "Parcial 1",
    topic: "Progreso y civilización",
    tags: ["filosofia", "hayek", "parcial-1", "progreso-y-civilizacion"],
    difficulty: "easy",
    type: "single",
    question: "El poder creador de la civilización libre dio origen a prácticas sociales en grupos y esto fue posible por",
    options: ["Cuando en la persecución de sus fines el individuo puede sobrepasar los límites de su ignorancia, aprovechándose del conocimiento disperso.", "Para exitosas de ciertos grupos humanos, a través de ensayo y error", "No puede dirigirse", "Ya que su uso producirá resultados imprevisibles"],
    correctAnswers: [1],
    explanation: "La respuesta correcta es: Para exitosas de ciertos grupos humanos, a través de ensayo y error",
  },
  {
    id: "hayek-manual-p1-q050",
    chapter: "Parcial 1",
    topic: "Progreso y civilización",
    tags: ["filosofia", "hayek", "parcial-1", "progreso-y-civilizacion"],
    difficulty: "hard",
    type: "single",
    question: "En el orden sensorial Hayek aborda el asunto del desarrollo de la mente humano diciendo",
    options: ["Cuando en la persecución de sus fines el individuo puede sobrepasar los límites de su ignorancia, aprovechándose del conocimiento disperso.", "No puede dirigirse", "Ya que su uso producirá resultados imprevisibles", "Parte del desarrollo de la civilización"],
    correctAnswers: [3],
    explanation: "La respuesta correcta es: Parte del desarrollo de la civilización",
  },
];
