import type { Flashcard } from "@/content/flashcards/histologia/cards"

type Seed = readonly [topic: string, subtopic: string, front: string, back: string]

// El selector muestra estos bloques; mantenerlos amplios evita que el estudio
// quede dividido en demasiadas listas pequeñas.
const compactSubtopics: Record<string, string> = {
  "Glucólisis|Panorama": "Fundamentos y reacciones",
  "Glucólisis|Reacciones clave": "Fundamentos y reacciones",
  "Glucólisis|Regulación": "Regulación y destinos",
  "Glucólisis|NADH y destinos": "Regulación y destinos",
  "Glucólisis|Clínica": "Regulación y destinos",
  "Ciclo de Krebs|Panorama": "Fundamentos y rendimiento",
  "Ciclo de Krebs|Rendimiento": "Fundamentos y rendimiento",
  "Ciclo de Krebs|Control": "Regulación e integración",
  "Ciclo de Krebs|Reacciones": "Regulación e integración",
  "Ciclo de Krebs|Anaplerosis": "Regulación e integración",
  "Ciclo de Krebs|Integración": "Regulación e integración",
  "Cadena respiratoria|Ubicación": "Componentes y flujo electrónico",
  "Cadena respiratoria|Componentes": "Componentes y flujo electrónico",
  "Cadena respiratoria|Flujo electrónico": "Componentes y flujo electrónico",
  "Cadena respiratoria|Quimiosmosis": "ATP, lanzaderas e inhibidores",
  "Cadena respiratoria|ATP sintasa": "ATP, lanzaderas e inhibidores",
  "Cadena respiratoria|Rendimiento": "ATP, lanzaderas e inhibidores",
  "Cadena respiratoria|Inhibidores": "ATP, lanzaderas e inhibidores",
  "Cadena respiratoria|Lanzaderas": "ATP, lanzaderas e inhibidores",
  "Metabolismo del glucógeno|Panorama": "Síntesis y degradación",
  "Metabolismo del glucógeno|Síntesis": "Síntesis y degradación",
  "Metabolismo del glucógeno|Degradación": "Síntesis y degradación",
  "Metabolismo del glucógeno|Hormonas": "Regulación y tejidos",
  "Metabolismo del glucógeno|Regulación": "Regulación y tejidos",
  "Metabolismo del glucógeno|Tejidos": "Regulación y tejidos",
  "Gluconeogénesis|Panorama": "Fundamentos y precursores",
  "Gluconeogénesis|Precursores": "Fundamentos y precursores",
  "Gluconeogénesis|Bypasses": "Bypasses y regulación",
  "Gluconeogénesis|Regulación": "Bypasses y regulación",
  "Gluconeogénesis|Integración": "Bypasses y regulación",
  "Vía de las pentosas|Panorama": "Fases y productos",
  "Vía de las pentosas|Fases": "Fases y productos",
  "Vía de las pentosas|Regulación": "Fases y productos",
  "Vía de las pentosas|NADPH": "NADPH y relevancia clínica",
  "Vía de las pentosas|Ribosa": "NADPH y relevancia clínica",
  "Vía de las pentosas|Clínica": "NADPH y relevancia clínica",
  "Vía de las pentosas|Integración": "NADPH y relevancia clínica",
  "Vía de las pentosas|Tejidos": "NADPH y relevancia clínica",
  "Beta oxidación|Fundamentos": "Movilización, transporte y reacciones",
  "Beta oxidación|Transporte": "Movilización, transporte y reacciones",
  "Beta oxidación|Reacciones": "Movilización, transporte y reacciones",
  "Beta oxidación|Rendimiento e integración": "Rendimiento e integración",
  "Cetogénesis|Fundamentos": "Síntesis y cuerpos cetónicos",
  "Cetogénesis|Síntesis": "Síntesis y cuerpos cetónicos",
  "Cetogénesis|Uso y regulación": "Uso y regulación clínica",
  "Cetogénesis|Clínica": "Uso y regulación clínica",
  "Síntesis de ácidos grasos|Sustratos y reacciones": "Sustratos y reacciones",
  "Síntesis de ácidos grasos|Regulación y destinos": "Regulación y destinos",
  "Eicosanoides|Rutas y mediadores": "Rutas y mediadores",
  "Eicosanoides|Fármacos y clínica": "Fármacos y clínica",
  "Lipoproteínas|Estructura y transporte": "Estructura y transporte",
  "Lipoproteínas|Enzimas y captación": "Enzimas y captación",
  "Colesterol|Síntesis y regulación": "Síntesis y regulación",
  "Colesterol|Derivados y función": "Derivados y función"
}

const coreSeeds: readonly Seed[] = [
  ["Glucólisis", "Panorama", "¿Dónde ocurre la glucólisis?", "En el citosol."],
  ["Glucólisis", "Panorama", "¿Cuál es el rendimiento neto de la glucólisis por glucosa?", "2 piruvatos, 2 ATP netos y 2 NADH."],
  ["Glucólisis", "Panorama", "¿Qué dos etapas funcionales tiene la glucólisis?", "Una fase de inversión de energía y una fase de obtención de energía."],
  ["Glucólisis", "Regulación", "¿Cuál es la enzima reguladora principal de la glucólisis?", "La fosfofructoquinasa-1 (PFK-1)."],
  ["Glucólisis", "Regulación", "¿Qué metabolito activa de forma potente a la PFK-1?", "La fructosa-2,6-bisfosfato."],
  ["Glucólisis", "Regulación", "¿Qué indican concentraciones altas de ATP y citrato sobre la glucólisis?", "Que debe disminuir; ambos inhiben la PFK-1."],
  ["Glucólisis", "Regulación", "¿Qué hormona favorece la glucólisis hepática en estado alimentado?", "La insulina."],
  ["Glucólisis", "Regulación", "¿Cuál es el efecto general del glucagón sobre la glucólisis hepática?", "La inhibe."],
  ["Glucólisis", "Reacciones clave", "¿Qué enzima convierte glucosa en glucosa-6-fosfato?", "La hexoquinasa; en hígado, la glucoquinasa."],
  ["Glucólisis", "Reacciones clave", "¿Por qué fosforilar glucosa ayuda a retenerla dentro de la célula?", "Porque la glucosa-6-fosfato no cruza libremente la membrana por los transportadores de glucosa."],
  ["Glucólisis", "Reacciones clave", "¿Qué enzima rompe fructosa-1,6-bisfosfato en dos triosas?", "La aldolasa."],
  ["Glucólisis", "Reacciones clave", "¿En qué reacción aparece la primera fosforilación a nivel de sustrato?", "1,3-bisfosfoglicerato a 3-fosfoglicerato, por fosfoglicerato quinasa."],
  ["Glucólisis", "Reacciones clave", "¿En qué reacción aparece la segunda fosforilación a nivel de sustrato?", "Fosfoenolpiruvato a piruvato, por piruvato quinasa."],
  ["Glucólisis", "NADH y destinos", "¿Por qué debe reoxidarse el NADH citosólico para que continúe la glucólisis?", "Para regenerar NAD+, necesario para la reacción de gliceraldehído-3-fosfato deshidrogenasa."],
  ["Glucólisis", "NADH y destinos", "¿Qué lanzaderas llevan los equivalentes reductores del NADH citosólico a la mitocondria?", "Las lanzaderas malato-aspartato y glicerol-3-fosfato."],
  ["Glucólisis", "NADH y destinos", "¿Cuáles son los destinos principales del piruvato?", "Acetil-CoA en aerobiosis, lactato en condiciones anaerobias y etanol en microorganismos."],
  ["Glucólisis", "Clínica", "¿Qué efecto tiene el 2,3-bisfosfoglicerato eritrocitario sobre la hemoglobina?", "Disminuye su afinidad por oxígeno y facilita la liberación de O₂ a los tejidos."],
  ["Ciclo de Krebs", "Panorama", "¿Dónde ocurre el ciclo de Krebs?", "En la matriz mitocondrial."],
  ["Ciclo de Krebs", "Panorama", "¿Por qué el ciclo de Krebs se considera indirectamente aeróbico?", "Porque depende de que la cadena respiratoria reoxide NADH y FADH₂ usando oxígeno."],
  ["Ciclo de Krebs", "Panorama", "¿Qué significa que el ciclo de Krebs sea anfibólico?", "Que participa tanto en degradación energética como en la provisión de precursores biosintéticos."],
  ["Ciclo de Krebs", "Rendimiento", "¿Qué produce una vuelta del ciclo por acetil-CoA?", "3 NADH, 1 FADH₂, 1 GTP y 2 CO₂."],
  ["Ciclo de Krebs", "Rendimiento", "¿Cuántas vueltas de Krebs ocurren por cada glucosa?", "Dos, porque una glucosa genera dos acetil-CoA."],
  ["Ciclo de Krebs", "Control", "¿Qué enzima condensa oxaloacetato y acetil-CoA?", "La citrato sintasa."],
  ["Ciclo de Krebs", "Control", "¿Qué tres enzimas son puntos irreversibles importantes del ciclo?", "Citrato sintasa, isocitrato deshidrogenasa y alfa-cetoglutarato deshidrogenasa."],
  ["Ciclo de Krebs", "Control", "¿Qué señal activa el ciclo de Krebs en músculo durante la contracción?", "El Ca²⁺."],
  ["Ciclo de Krebs", "Control", "¿Qué efecto tienen ATP y NADH abundantes sobre el ciclo?", "Lo inhiben, porque señalan suficiente energía y poder reductor."],
  ["Ciclo de Krebs", "Reacciones", "¿Cuál es la única fosforilación a nivel de sustrato del ciclo de Krebs?", "Succinil-CoA a succinato por succinil-CoA sintetasa, con formación de GTP."],
  ["Ciclo de Krebs", "Anaplerosis", "¿Qué es una reacción anaplerótica?", "Una reacción que repone intermediarios extraídos del ciclo de Krebs."],
  ["Ciclo de Krebs", "Anaplerosis", "¿Cuál es el ejemplo anaplerótico principal?", "Piruvato a oxaloacetato por piruvato carboxilasa, consumiendo ATP."],
  ["Ciclo de Krebs", "Integración", "¿A dónde se dirigen los NADH y FADH₂ producidos en Krebs?", "A la cadena transportadora de electrones."],
  ["Cadena respiratoria", "Ubicación", "¿Dónde se sitúan los complejos de la cadena respiratoria?", "En la membrana mitocondrial interna."],
  ["Cadena respiratoria", "Componentes", "¿Qué complejos aceptan electrones de NADH y FADH₂?", "El complejo I recibe electrones de NADH; el complejo II, de FADH₂."],
  ["Cadena respiratoria", "Componentes", "¿Qué moléculas móviles trasladan electrones entre complejos?", "Coenzima Q y citocromo c."],
  ["Cadena respiratoria", "Componentes", "¿Qué complejos bombean protones hacia el espacio intermembrana?", "Los complejos I, III y IV."],
  ["Cadena respiratoria", "Flujo electrónico", "¿Cuál es el aceptor final de electrones de la cadena respiratoria?", "El oxígeno, que se reduce a agua."],
  ["Cadena respiratoria", "Flujo electrónico", "¿Por qué FADH₂ produce menos ATP que NADH?", "Porque entrega electrones al complejo II y evita el bombeo de protones del complejo I."],
  ["Cadena respiratoria", "Quimiosmosis", "¿Qué crea el gradiente de protones en la mitocondria?", "El bombeo de H+ desde la matriz hacia el espacio intermembrana por los complejos I, III y IV."],
  ["Cadena respiratoria", "Quimiosmosis", "¿Qué utiliza la ATP sintasa para formar ATP?", "La energía del retorno de protones a la matriz a favor de su gradiente."],
  ["Cadena respiratoria", "ATP sintasa", "¿Dónde se ubican las subunidades F₀ y F₁ de la ATP sintasa?", "F₀ está en la membrana interna; F₁ sobresale hacia la matriz mitocondrial."],
  ["Cadena respiratoria", "Rendimiento", "¿Cuál es el rendimiento aproximado de un NADH mitocondrial?", "Unos 2.5 ATP."],
  ["Cadena respiratoria", "Rendimiento", "¿Cuál es el rendimiento aproximado de un FADH₂?", "Unos 1.5 ATP."],
  ["Cadena respiratoria", "Inhibidores", "¿Qué inhibidor clásico bloquea el complejo IV?", "El cianuro."],
  ["Cadena respiratoria", "Inhibidores", "¿Qué pasa con la cadena respiratoria si falta oxígeno?", "Se detiene el flujo de electrones y no se reoxidan NADH y FADH₂."],
  ["Cadena respiratoria", "Lanzaderas", "¿Qué lanzadera conserva el equivalente energético de NADH citosólico?", "La lanzadera malato-aspartato."],
  ["Cadena respiratoria", "Lanzaderas", "¿Qué lanzadera entrega electrones citosólicos a coenzima Q y rinde menos ATP?", "La lanzadera glicerol-3-fosfato."],
  ["Metabolismo del glucógeno", "Panorama", "¿Dónde ocurren glucogénesis y glucogenólisis?", "En el citosol, sobre gránulos de glucógeno."],
  ["Metabolismo del glucógeno", "Hormonas", "¿Qué hormona estimula la síntesis de glucógeno?", "La insulina."],
  ["Metabolismo del glucógeno", "Hormonas", "¿Qué hormonas estimulan la degradación de glucógeno?", "Glucagón en hígado y adrenalina en hígado y músculo."],
  ["Metabolismo del glucógeno", "Síntesis", "¿Qué enzima forma enlaces alfa-1,4 al alargar el glucógeno?", "La glucógeno sintasa."],
  ["Metabolismo del glucógeno", "Síntesis", "¿Qué enzima forma enlaces alfa-1,6 del glucógeno?", "La enzima ramificante."],
  ["Metabolismo del glucógeno", "Síntesis", "¿Qué proteína inicia una nueva molécula de glucógeno?", "La glucogenina, que se autoglucosila y forma el cebador."],
  ["Metabolismo del glucógeno", "Degradación", "¿Qué producto libera la glucógeno fosforilasa al romper enlaces alfa-1,4?", "Glucosa-1-fosfato."],
  ["Metabolismo del glucógeno", "Degradación", "¿Qué dos actividades tiene la enzima desramificante?", "Transferasa y alfa-1,6-glucosidasa."],
  ["Metabolismo del glucógeno", "Regulación", "¿Cuándo está activa la glucógeno fosforilasa?", "Cuando está fosforilada."],
  ["Metabolismo del glucógeno", "Regulación", "¿Cuándo está activa la glucógeno sintasa?", "Cuando está desfosforilada."],
  ["Metabolismo del glucógeno", "Regulación", "¿Qué señal energética activa la glucógeno fosforilasa muscular?", "AMP elevado."],
  ["Metabolismo del glucógeno", "Regulación", "¿Qué metabolitos inhiben la glucógeno fosforilasa en músculo?", "ATP y glucosa-6-fosfato elevados."],
  ["Metabolismo del glucógeno", "Tejidos", "¿Por qué el hígado puede liberar glucosa a la sangre y el músculo no?", "Porque el hígado posee glucosa-6-fosfatasa; el músculo carece de ella."],
  ["Metabolismo del glucógeno", "Tejidos", "¿Cuándo es especialmente útil la glucogenólisis hepática?", "Durante el ayuno, para sostener la glucemia."],
  ["Gluconeogénesis", "Panorama", "¿Qué es la gluconeogénesis?", "La síntesis de glucosa a partir de precursores no glucídicos."],
  ["Gluconeogénesis", "Panorama", "¿Dónde ocurre principalmente la gluconeogénesis?", "Principalmente en hígado; también en corteza renal durante ayuno prolongado."],
  ["Gluconeogénesis", "Precursores", "¿Cuáles son precursores importantes de gluconeogénesis?", "Lactato, glicerol y aminoácidos glucogénicos como alanina."],
  ["Gluconeogénesis", "Precursores", "¿Qué ciclo lleva lactato de músculo o eritrocito al hígado para formar glucosa?", "El ciclo de Cori."],
  ["Gluconeogénesis", "Precursores", "¿Qué ciclo transporta nitrógeno desde músculo al hígado como alanina?", "El ciclo glucosa-alanina."],
  ["Gluconeogénesis", "Bypasses", "¿Qué enzima convierte piruvato en oxaloacetato?", "La piruvato carboxilasa, en la matriz mitocondrial."],
  ["Gluconeogénesis", "Bypasses", "¿Qué activa a la piruvato carboxilasa?", "El acetil-CoA."],
  ["Gluconeogénesis", "Bypasses", "¿Qué enzima convierte oxaloacetato en fosfoenolpiruvato?", "La fosfoenolpiruvato carboxiquinasa (PEPCK)."],
  ["Gluconeogénesis", "Bypasses", "¿Qué enzima evita la reacción irreversible de PFK-1?", "La fructosa-1,6-bisfosfatasa."],
  ["Gluconeogénesis", "Bypasses", "¿Qué enzima permite liberar glucosa libre desde glucosa-6-fosfato?", "La glucosa-6-fosfatasa, en el retículo endoplásmico."],
  ["Gluconeogénesis", "Regulación", "¿Qué metabolitos inhiben fructosa-1,6-bisfosfatasa?", "AMP y fructosa-2,6-bisfosfato."],
  ["Gluconeogénesis", "Regulación", "¿Qué hormonas favorecen la gluconeogénesis hepática?", "Glucagón, adrenalina y cortisol."],
  ["Gluconeogénesis", "Regulación", "¿Qué indica ATP o citrato altos para el destino metabólico del piruvato?", "Que hay energía disponible y se favorece la gluconeogénesis."],
  ["Gluconeogénesis", "Integración", "¿Qué enzima bifuncional regula fructosa-2,6-bisfosfato?", "PFK-2/FBPasa-2."],
  ["Vía de las pentosas", "Panorama", "¿Cuál es la función principal de la vía de las pentosas fosfato?", "Producir NADPH y ribosa-5-fosfato."],
  ["Vía de las pentosas", "Panorama", "¿Dónde ocurre la vía de las pentosas fosfato?", "En el citosol."],
  ["Vía de las pentosas", "Fases", "¿Cuál fase de la vía de las pentosas es irreversible?", "La fase oxidativa."],
  ["Vía de las pentosas", "Fases", "¿Cuál fase de la vía de las pentosas es reversible?", "La fase no oxidativa de interconversión de azúcares."],
  ["Vía de las pentosas", "Fases", "¿Qué productos directos genera la fase oxidativa?", "NADPH, CO₂ y ribulosa-5-fosfato."],
  ["Vía de las pentosas", "Regulación", "¿Cuál es la enzima reguladora de la fase oxidativa?", "La glucosa-6-fosfato deshidrogenasa."],
  ["Vía de las pentosas", "NADPH", "¿Para qué usa NADPH una célula?", "Para biosíntesis reductora y para mantener glutatión reducido frente al estrés oxidativo."],
  ["Vía de las pentosas", "NADPH", "¿Qué moléculas pueden sintetizarse usando NADPH?", "Ácidos grasos, colesterol y hormonas esteroideas."],
  ["Vía de las pentosas", "Ribosa", "¿Para qué sirve la ribosa-5-fosfato?", "Para sintetizar nucleótidos, ácidos nucleicos y coenzimas como NAD⁺, FAD y CoA."],
  ["Vía de las pentosas", "Clínica", "¿Por qué una deficiencia de G6PD puede causar anemia hemolítica?", "Porque reduce NADPH y glutatión reducido, dejando al eritrocito vulnerable al daño oxidativo."],
  ["Vía de las pentosas", "Integración", "Si una célula necesita ribosa-5-fosfato pero no NADPH, ¿qué fase utiliza?", "La fase no oxidativa en sentido de formación de ribosa-5-fosfato."],
  ["Vía de las pentosas", "Integración", "Si una célula necesita NADPH pero no ribosa-5-fosfato, ¿qué hace con los carbonos?", "Usa las fases oxidativa y no oxidativa para reciclarlos hacia intermediarios glucolíticos."],
  ["Vía de las pentosas", "Tejidos", "¿Qué tejidos dependen mucho de la vía de las pentosas?", "Hígado, tejido adiposo, corteza suprarrenal, glándula mamaria lactante y eritrocitos."],
]

const fatMetabolismSeeds: readonly Seed[] = [
  ["Beta oxidación", "Fundamentos", "¿Qué es la beta oxidación?", "La degradación secuencial de ácidos grasos que libera unidades de acetil-CoA."],
  ["Beta oxidación", "Fundamentos", "¿Dónde ocurre principalmente la beta oxidación de ácidos grasos de cadena larga?", "En la matriz mitocondrial."],
  ["Beta oxidación", "Fundamentos", "¿Cuál es la forma circulante principal de los ácidos grasos no esterificados?", "Unidos a albúmina."],
  ["Beta oxidación", "Transporte", "¿Qué enzima activa un ácido graso antes de degradarlo?", "La acil-CoA sintetasa, que forma acil-CoA."],
  ["Beta oxidación", "Transporte", "¿Qué costo energético tiene la activación de un ácido graso a acil-CoA?", "Equivale a 2 enlaces de alta energía de ATP, porque ATP se convierte en AMP y PPi."],
  ["Beta oxidación", "Transporte", "¿Qué papel tiene la carnitina en el metabolismo de ácidos grasos?", "Transporta grupos acilo de cadena larga a través de la membrana mitocondrial interna."],
  ["Beta oxidación", "Transporte", "¿Qué enzima controla la entrada de acil-CoA de cadena larga a la mitocondria?", "Carnitina palmitoiltransferasa I (CPT-I)."],
  ["Beta oxidación", "Transporte", "¿Qué metabolito inhibe CPT-I y evita oxidar ácidos grasos mientras se sintetizan?", "Malonil-CoA."],
  ["Beta oxidación", "Reacciones", "¿Cuáles son las cuatro reacciones repetidas de la beta oxidación?", "Oxidación por FAD, hidratación, oxidación por NAD+ y tiólisis por CoA."],
  ["Beta oxidación", "Reacciones", "¿Qué productos se obtienen por cada vuelta de beta oxidación?", "Un acetil-CoA, un NADH y un FADH₂; salvo en la última escisión, que libera dos acetil-CoA."],
  ["Beta oxidación", "Rendimiento e integración", "¿Qué ocurre con el acetil-CoA producido por beta oxidación en condiciones de energía suficiente?", "Puede entrar al ciclo de Krebs o contribuir a la cetogénesis hepática."],
  ["Beta oxidación", "Rendimiento e integración", "¿Dónde se acortan inicialmente los ácidos grasos de cadena muy larga?", "En peroxisomas, antes de completar su oxidación en la mitocondria."],
  ["Beta oxidación", "Rendimiento e integración", "¿Cómo se procesan los ácidos grasos de número impar de carbonos?", "El último fragmento es propionil-CoA, que se convierte en succinil-CoA."],
  ["Beta oxidación", "Rendimiento e integración", "¿Qué hormonas favorecen la movilización de ácidos grasos en ayuno?", "Glucagón y adrenalina; la insulina la inhibe."],

  ["Cetogénesis", "Fundamentos", "¿Qué situación favorece la cetogénesis hepática?", "Ayuno prolongado, baja insulina o diabetes descompensada, con alta beta oxidación y exceso de acetil-CoA."],
  ["Cetogénesis", "Fundamentos", "¿En qué compartimento celular se forman los cuerpos cetónicos?", "En la matriz mitocondrial hepática."],
  ["Cetogénesis", "Síntesis", "¿Cuáles son los tres cuerpos cetónicos?", "Acetoacetato, beta-hidroxibutirato y acetona."],
  ["Cetogénesis", "Síntesis", "¿Cuál es el primer cuerpo cetónico formado en la vía?", "Acetoacetato."],
  ["Cetogénesis", "Síntesis", "¿Cuál es la enzima limitante de la cetogénesis?", "La HMG-CoA sintasa mitocondrial."],
  ["Cetogénesis", "Síntesis", "¿Qué precursor inmediato se condensa para iniciar la síntesis de cuerpos cetónicos?", "Dos moléculas de acetil-CoA, que forman acetoacetil-CoA."],
  ["Cetogénesis", "Uso y regulación", "¿Por qué el hígado produce cuerpos cetónicos pero no los usa?", "Porque carece de la enzima succinil-CoA:acetoacetato CoA transferasa (tiotransferasa)."],
  ["Cetogénesis", "Uso y regulación", "¿Qué tejidos pueden utilizar cuerpos cetónicos como combustible?", "Músculo, corazón, corteza renal y cerebro durante ayuno prolongado."],
  ["Cetogénesis", "Uso y regulación", "¿Por qué los cuerpos cetónicos pueden servir al cerebro pero los ácidos grasos de cadena larga no?", "Porque los cuerpos cetónicos atraviesan la barrera hematoencefálica con facilidad."],
  ["Cetogénesis", "Uso y regulación", "¿Qué cuerpo cetónico no puede convertirse de nuevo en acetil-CoA?", "La acetona, que se elimina sobre todo por el aliento."],
  ["Cetogénesis", "Clínica", "¿Qué es la cetonemia?", "El aumento de cuerpos cetónicos en la sangre."],
  ["Cetogénesis", "Clínica", "¿Qué trastorno ácido-base puede producir una acumulación marcada de cuerpos cetónicos?", "Acidosis metabólica con anión gap elevado."],
  ["Cetogénesis", "Clínica", "¿Cómo reduce la insulina la producción de cuerpos cetónicos?", "Inhibe la lipólisis, disminuye la llegada de ácidos grasos al hígado y reduce la beta oxidación."],
]

// Las tarjetas del tercer parcial se basan en el banco temático de opción
// múltiple existente; se mantienen separadas de la sección de repaso pre-parcial.
const partial3Seeds: readonly Seed[] = [
  ["Síntesis de ácidos grasos", "Sustratos y reacciones", "¿Qué enzima inicia la formación de malonil-CoA?", "La acetil-CoA carboxilasa convierte acetil-CoA en malonil-CoA."],
  ["Síntesis de ácidos grasos", "Sustratos y reacciones", "¿Qué productos genera la citrato liasa en el citosol?", "Acetil-CoA y oxaloacetato."],
  ["Síntesis de ácidos grasos", "Sustratos y reacciones", "¿Por qué se exporta citrato desde la mitocondria durante la lipogénesis?", "Para llevar carbonos de acetil-CoA al citosol, donde ocurre la síntesis."],
  ["Síntesis de ácidos grasos", "Sustratos y reacciones", "¿En qué compartimento ocurre la síntesis de ácidos grasos?", "En el citosol."],
  ["Síntesis de ácidos grasos", "Sustratos y reacciones", "¿Cuál es el producto principal del complejo ácido graso sintasa?", "Ácido palmítico."],
  ["Síntesis de ácidos grasos", "Sustratos y reacciones", "¿Qué vía aporta NADPH a la síntesis de ácidos grasos?", "La vía de las pentosas fosfato."],
  ["Síntesis de ácidos grasos", "Sustratos y reacciones", "¿Para qué utiliza NADPH cada ciclo de la ácido graso sintasa?", "Para dos reacciones de reducción."],
  ["Síntesis de ácidos grasos", "Sustratos y reacciones", "¿Cuál es el orden de reacciones de cada ciclo de la ácido graso sintasa?", "Condensación, reducción, deshidratación y segunda reducción."],
  ["Síntesis de ácidos grasos", "Sustratos y reacciones", "¿Qué componente del complejo sintasa transporta el grupo malonilo?", "La proteína portadora de acilo (ACP)."],
  ["Síntesis de ácidos grasos", "Regulación y destinos", "¿Qué le ocurre a la acetil-CoA carboxilasa al fosforilarse?", "Disminuye su actividad; la desfosforilación la activa."],
  ["Síntesis de ácidos grasos", "Regulación y destinos", "¿Qué hormona favorece la lipogénesis en estado alimentado?", "La insulina."],
  ["Síntesis de ácidos grasos", "Regulación y destinos", "¿Qué estado de sustratos y energía favorece la lipogénesis?", "Abundancia de acetil-CoA, glucosa y energía."],
  ["Síntesis de ácidos grasos", "Regulación y destinos", "¿Qué efecto tienen glucagón y adrenalina sobre la lipogénesis?", "La inhiben y favorecen la movilización de ácidos grasos."],
  ["Síntesis de ácidos grasos", "Regulación y destinos", "¿Cuáles son los dos ácidos grasos esenciales tratados en el temario?", "Linoleico y alfa-linolénico."],
  ["Síntesis de ácidos grasos", "Regulación y destinos", "¿Dónde puede elongarse el palmitato después de su síntesis?", "En el retículo endoplásmico liso."],
  ["Síntesis de ácidos grasos", "Regulación y destinos", "¿Qué cambio introducen las desaturasas en una cadena de ácido graso?", "Enlaces dobles o insaturaciones."],

  ["Eicosanoides", "Rutas y mediadores", "¿Cuántos carbonos caracterizan a los eicosanoides?", "Veinte carbonos."],
  ["Eicosanoides", "Rutas y mediadores", "¿Qué enzima libera ácido araquidónico de los fosfolípidos de membrana?", "La fosfolipasa A₂."],
  ["Eicosanoides", "Rutas y mediadores", "¿Qué dos familias de mediadores proceden de la vía COX?", "Prostaglandinas y tromboxanos."],
  ["Eicosanoides", "Rutas y mediadores", "¿Qué familia de mediadores procede de la vía LOX?", "Leucotrienos."],
  ["Eicosanoides", "Rutas y mediadores", "¿Cuál isoforma COX es principalmente constitutiva?", "COX-1."],
  ["Eicosanoides", "Rutas y mediadores", "¿Cuál isoforma COX es principalmente inducible durante la inflamación?", "COX-2."],
  ["Eicosanoides", "Rutas y mediadores", "¿Qué hacen los tromboxanos sobre vasos y plaquetas?", "Favorecen vasoconstricción y agregación plaquetaria."],
  ["Eicosanoides", "Rutas y mediadores", "¿Qué hace la prostaciclina sobre vasos y plaquetas?", "Favorece vasodilatación e inhibe la agregación plaquetaria."],
  ["Eicosanoides", "Rutas y mediadores", "¿Qué efectos tienen los leucotrienos en una reacción alérgica?", "Broncoconstricción, aumento de moco y mayor permeabilidad vascular."],
  ["Eicosanoides", "Fármacos y clínica", "¿Qué enzima inhiben los AINEs para reducir prostaglandinas?", "La ciclooxigenasa (COX)."],
  ["Eicosanoides", "Fármacos y clínica", "¿Qué isoformas bloquea un AINE no selectivo?", "COX-1 y COX-2."],
  ["Eicosanoides", "Fármacos y clínica", "¿Cuál es la diana preferente de un AINE selectivo de COX-2?", "La vía de prostaglandinas dependiente de COX-2."],
  ["Eicosanoides", "Fármacos y clínica", "¿Por qué un AINE no selectivo puede irritar la mucosa gástrica?", "Al inhibir COX-1 reduce prostaglandinas protectoras de la mucosa."],
  ["Eicosanoides", "Fármacos y clínica", "¿Qué fármaco del temario inhibe la vía de lipooxigenasa?", "Zileutón."],
  ["Eicosanoides", "Rutas y mediadores", "¿Cuáles son las tres familias principales de eicosanoides estudiadas?", "Prostaglandinas, tromboxanos y leucotrienos."],
  ["Eicosanoides", "Fármacos y clínica", "Si se bloquea COX, ¿qué vía del ácido araquidónico no se inhibe directamente?", "La vía LOX que produce leucotrienos."],

  ["Lipoproteínas", "Estructura y transporte", "¿Qué lípidos se ubican en el núcleo hidrófobo de una lipoproteína?", "Triglicéridos y ésteres de colesterol."],
  ["Lipoproteínas", "Estructura y transporte", "¿Qué componentes forman la superficie de una lipoproteína?", "Fosfolípidos, colesterol libre y apoproteínas."],
  ["Lipoproteínas", "Estructura y transporte", "¿Qué lipoproteína transporta triglicéridos absorbidos en el intestino?", "El quilomicrón."],
  ["Lipoproteínas", "Estructura y transporte", "¿Qué lipoproteína exporta triglicéridos sintetizados en el hígado?", "La VLDL."],
  ["Lipoproteínas", "Estructura y transporte", "¿Qué lipoproteína entrega colesterol a tejidos mediante el receptor LDL?", "La LDL."],
  ["Lipoproteínas", "Estructura y transporte", "¿Qué lipoproteína participa en el transporte reverso de colesterol?", "La HDL, desde tejidos periféricos hacia el hígado."],
  ["Lipoproteínas", "Estructura y transporte", "¿Qué es un quilomicrón remanente?", "La partícula que queda tras entregar gran parte de sus triglicéridos."],
  ["Lipoproteínas", "Enzimas y captación", "¿Dónde actúa la lipoproteína lipasa sobre quilomicrones y VLDL?", "Asociada a la superficie del endotelio capilar."],
  ["Lipoproteínas", "Enzimas y captación", "¿Qué reacción cataliza la lipoproteína lipasa?", "Hidroliza triglicéridos de quilomicrones y VLDL, liberando ácidos grasos."],
  ["Lipoproteínas", "Estructura y transporte", "¿Cuáles son las cuatro lipoproteínas principales del temario?", "Quilomicrones, VLDL, LDL y HDL."],
  ["Lipoproteínas", "Enzimas y captación", "¿Qué apoproteína de LDL reconoce su receptor celular?", "Apo B-100."],
  ["Lipoproteínas", "Enzimas y captación", "¿Cómo entra LDL a una célula después de unirse a su receptor?", "Por endocitosis mediada por receptor."],
  ["Lipoproteínas", "Enzimas y captación", "¿Dónde se libera el colesterol de una LDL internalizada?", "En los lisosomas, tras degradarse la partícula."],
  ["Lipoproteínas", "Enzimas y captación", "¿Qué célula forma una célula espumosa al acumular LDL oxidada?", "Un macrófago."],
  ["Lipoproteínas", "Enzimas y captación", "¿Qué reacción cataliza LCAT sobre HDL?", "Esterifica colesterol libre; el éster pasa al núcleo de HDL."],
  ["Lipoproteínas", "Enzimas y captación", "¿Qué apoproteína activa LCAT?", "Apo A-I."],

  ["Colesterol", "Síntesis y regulación", "¿Cuántos carbonos y anillos tiene el colesterol?", "27 carbonos y cuatro anillos."],
  ["Colesterol", "Síntesis y regulación", "Además de los anillos, ¿qué grupos estructurales se mencionan para el colesterol?", "Una cadena lateral y un grupo hidroxilo (-OH)."],
  ["Colesterol", "Derivados y función", "¿Qué función general tienen las hormonas sexuales derivadas del colesterol?", "Participan en el desarrollo y la reproducción sexual."],
  ["Colesterol", "Síntesis y regulación", "¿Cuál es el precursor inicial de la síntesis de colesterol?", "El acetil-CoA."],
  ["Colesterol", "Síntesis y regulación", "¿Qué enzima forma HMG-CoA antes de la etapa reguladora?", "La HMG-CoA sintasa."],
  ["Colesterol", "Síntesis y regulación", "¿Qué reacción cataliza la HMG-CoA reductasa?", "Convierte HMG-CoA en mevalonato."],
  ["Colesterol", "Síntesis y regulación", "¿Cuál es la diana de las estatinas?", "La HMG-CoA reductasa."],
  ["Colesterol", "Derivados y función", "¿Qué tres tipos de derivados importantes se forman a partir del colesterol?", "Sales biliares, hormonas esteroideas y vitamina D."],
  ["Colesterol", "Síntesis y regulación", "¿Qué intermediario sigue al mevalonato en el esquema resumido?", "IPP (isopentenil pirofosfato)."],
  ["Colesterol", "Síntesis y regulación", "¿Qué intermediario sigue al IPP en el esquema resumido?", "Escualeno."],
  ["Colesterol", "Síntesis y regulación", "¿Qué procesos génicos regula SREBP?", "La síntesis de colesterol y la expresión de receptores LDL."],
  ["Colesterol", "Síntesis y regulación", "¿Qué tipo de molécula reguladora es SREBP?", "Un factor de transcripción."],
  ["Colesterol", "Derivados y función", "¿Para qué sirven principalmente las sales biliares?", "Emulsionan grasas y facilitan su absorción intestinal."],
  ["Colesterol", "Derivados y función", "¿Qué intermediario inicia la síntesis de hormonas esteroideas a partir de colesterol?", "La pregnenolona."],
  ["Colesterol", "Derivados y función", "¿Qué derivado del colesterol participa en el balance de calcio y fosfato?", "La vitamina D."],
  ["Colesterol", "Derivados y función", "¿Qué familia de esteroides regula agua y electrolitos?", "Los mineralocorticoides."],
  ["Colesterol", "Derivados y función", "¿Qué familia de esteroides modula el metabolismo y la inflamación?", "Los glucocorticoides."],
]

const seeds: readonly Seed[] = [...coreSeeds, ...fatMetabolismSeeds, ...partial3Seeds]

export const bioquimicaFlashcards: Flashcard[] = seeds.map(([topic, subtopic, front, back], index) => ({
  id: `bioquimica-${topic.toLocaleLowerCase("es").normalize("NFD").replace(/[\u0300-\u036f]/g, "").replaceAll(/[^a-z0-9]+/g, "-").replaceAll(/^-|-$/g, "")}-${String(index + 1).padStart(3, "0")}`,
  subject: "Bioquímica",
  book: "Apuntes de Bioquímica",
  chapter: topic,
  topic,
  subtopic: compactSubtopics[`${topic}|${subtopic}`] || subtopic,
  front,
  back,
  tags: ["bioquimica", topic.toLocaleLowerCase("es"), subtopic.toLocaleLowerCase("es")]
}))

export default bioquimicaFlashcards
