import type { Flashcard } from "@/content/flashcards/histologia/cards"

type CardSeed = [chapter: string, topic: string, front: string, back: string]

const seeds: CardSeed[] = [
  ["Bloque 1", "Salud y enfermedad", "¿Qué es la homeostasis?", "La capacidad del organismo de mantener un estado interno estable frente a agresiones."],
  ["Bloque 1", "Salud y enfermedad", "¿Qué diferencia hay entre etiología y patogénesis?", "La etiología es la causa; la patogénesis es el mecanismo y la secuencia por los que se desarrolla la enfermedad."],
  ["Bloque 1", "Salud y enfermedad", "¿Qué es un estado subclínico?", "Una fase con cambios moleculares o fisiológicos aún no perceptibles para el paciente."],
  ["Bloque 1", "Salud y enfermedad", "¿Qué diferencia un signo de un síntoma?", "El signo es objetivo y comprobable; el síntoma es una experiencia subjetiva referida por el paciente."],
  ["Bloque 1", "Salud y enfermedad", "¿Qué es una lesión?", "Un cambio estructural o funcional producido por una condición patológica."],
  ["Bloque 1", "Salud y enfermedad", "¿Qué es una secuela?", "Un daño o alteración que permanece después de terminar la enfermedad."],
  ["Bloque 1", "Salud y enfermedad", "¿Qué es una complicación?", "Una condición adicional e inesperada que empeora el curso o pronóstico de la enfermedad."],
  ["Bloque 1", "Salud y enfermedad", "¿Qué expresa el pronóstico?", "La predicción del curso, duración y posible desenlace de una enfermedad."],
  ["Bloque 1", "Factores de enfermedad", "¿Qué son los factores intrínsecos?", "Factores propios del paciente, como genética, edad, hipoxia, inmunidad y estado nutricional."],
  ["Bloque 1", "Factores de enfermedad", "¿Qué son los factores extrínsecos?", "Agresores externos, como toxinas, microorganismos, trauma, tabaco, temperaturas extremas y radiación."],
  ["Bloque 1", "Genética celular", "¿Cuántos pares de cromosomas posee normalmente el ser humano?", "23 pares."],
  ["Bloque 1", "Genética celular", "¿Qué es un locus?", "La posición específica que ocupa un gen en un cromosoma."],
  ["Bloque 1", "Genética celular", "¿Qué permite la diferenciación celular?", "Que células con el mismo genoma expresen genes distintos y adquieran funciones especializadas."],
  ["Bloque 1", "Genética celular", "¿Qué produce la mitosis?", "Dos células hijas genéticamente equivalentes a la célula original."],
  ["Bloque 1", "Genética celular", "¿Cuál es el resultado esencial de la meiosis?", "Gametos con la mitad del número de cromosomas."],
  ["Bloque 1", "Adaptaciones celulares", "¿Qué es hipertrofia?", "Aumento del tamaño de las células y, por tanto, del órgano."],
  ["Bloque 1", "Adaptaciones celulares", "¿Qué es hiperplasia?", "Aumento del número de células."],
  ["Bloque 1", "Adaptaciones celulares", "¿Qué es atrofia?", "Reducción del tamaño de un órgano por disminución del tamaño y/o número de sus células."],
  ["Bloque 1", "Adaptaciones celulares", "¿Qué es metaplasia?", "Cambio adaptativo reversible en el que un tipo de célula madura es sustituido por otro."],
  ["Bloque 1", "Lesión celular", "¿Qué caracteriza la tumefacción turbia?", "Entrada de agua a la célula como cambio reversible temprano."],
  ["Bloque 1", "Lesión celular", "¿Qué ocurre en la degeneración hidrópica?", "Aumenta la permeabilidad de la membrana y se acumula agua en la célula."],
  ["Bloque 1", "Muerte celular", "¿Qué es apoptosis?", "Muerte celular programada que generalmente no desencadena inflamación."],
  ["Bloque 1", "Muerte celular", "¿Qué es necrosis?", "Muerte celular localizada en tejido vivo que suele provocar inflamación."],
  ["Bloque 1", "Muerte celular", "¿Qué es cariolisis?", "Disolución o desaparición del núcleo."],
  ["Bloque 1", "Muerte celular", "¿Qué es picnosis?", "Encogimiento y condensación del núcleo."],
  ["Bloque 1", "Muerte celular", "¿Qué es cariorrexis?", "Fragmentación del núcleo y dispersión de sus restos."],
  ["Bloque 1", "Muerte celular", "¿Qué caracteriza la necrosis coagulativa?", "Conservación temporal de la arquitectura tisular, usualmente después de isquemia."],
  ["Bloque 1", "Muerte celular", "¿Qué caracteriza la necrosis licuefactiva?", "Digestión del tejido muerto hasta formar material líquido o una cavidad."],
  ["Bloque 1", "Muerte celular", "¿Con qué enfermedad se asocia clásicamente la necrosis caseosa?", "Tuberculosis."],
  ["Bloque 1", "Gangrena", "¿Qué diferencia la gangrena húmeda de la seca?", "La húmeda combina isquemia e invasión bacteriana; la seca se debe principalmente a oclusión arterial."],

  ["Bloque 2", "Inflamación", "¿Cuáles son los cinco signos cardinales de inflamación aguda?", "Rubor, calor, dolor, edema y pérdida de la función."],
  ["Bloque 2", "Inflamación", "¿Qué causa el calor y el rubor en la inflamación aguda?", "La vasodilatación y el aumento del flujo sanguíneo."],
  ["Bloque 2", "Inflamación", "¿Qué mecanismo produce el edema inflamatorio?", "Aumento de la permeabilidad vascular con salida de proteínas y líquido al intersticio."],
  ["Bloque 2", "Inflamación", "¿Cuáles son los cuatro objetivos generales de la inflamación?", "Diluir, destruir, aislar e iniciar la reparación."],
  ["Bloque 2", "Inflamación", "¿Por qué infección e inflamación no son sinónimos?", "La infección exige microorganismos; la inflamación también puede responder a trauma, químicos o necrosis."],
  ["Bloque 2", "Exudado", "¿Qué es un exudado?", "Líquido rico en proteínas y células que sale de los vasos durante la inflamación."],
  ["Bloque 2", "Exudado", "¿Qué caracteriza al exudado seroso?", "Pocas células y asociación con inflamación leve."],
  ["Bloque 2", "Exudado", "¿Qué caracteriza al exudado fibrinoso?", "Abundancia de fibrinógeno y fibrina."],
  ["Bloque 2", "Exudado", "¿Qué caracteriza al exudado supurativo?", "Presencia de pus, microorganismos y abundantes células inflamatorias."],
  ["Bloque 2", "Migración leucocitaria", "¿Cuál es la secuencia general de salida de leucocitos del vaso?", "Marginación, pavimentación/adhesión, migración y diapédesis, guiadas por quimiotaxis."],
  ["Bloque 2", "Migración leucocitaria", "¿Qué es quimiotaxis?", "Movimiento dirigido de células siguiendo un gradiente químico."],
  ["Bloque 2", "Respuesta inflamatoria", "¿Cuáles son las etapas funcionales de la respuesta inflamatoria?", "Reconocimiento, reclutamiento, remoción, regulación y reparación."],
  ["Bloque 2", "Leucocitos", "¿Cuáles leucocitos son granulocitos?", "Neutrófilos, eosinófilos y basófilos."],
  ["Bloque 2", "Leucocitos", "¿Cuáles leucocitos son agranulocitos?", "Linfocitos y monocitos."],
  ["Bloque 2", "Leucocitos", "¿Qué leucocito predomina al inicio de una inflamación bacteriana aguda?", "El neutrófilo."],
  ["Bloque 2", "Leucocitos", "¿En qué procesos aumentan típicamente los eosinófilos?", "Reacciones alérgicas e infecciones parasitarias."],
  ["Bloque 2", "Leucocitos", "¿Qué mediadores almacenan los basófilos?", "Histamina y heparina."],
  ["Bloque 2", "Fagocitosis", "¿Qué células pueden fagocitar?", "Neutrófilos, monocitos/macrófagos y células dendríticas."],
  ["Bloque 2", "Fagocitosis", "¿Qué función cumple la opsonización?", "Facilita el reconocimiento y la ingestión del microorganismo por el fagocito."],
  ["Bloque 2", "Fagocitosis", "¿Qué es un fagolisosoma?", "La vesícula formada al fusionarse el fagosoma con lisosomas para destruir el material ingerido."],
  ["Bloque 2", "Macrófagos", "¿Cómo se llaman los macrófagos del hígado?", "Células de Kupffer."],
  ["Bloque 2", "Macrófagos", "¿Cómo se llaman los macrófagos residentes del tejido conectivo?", "Histiocitos."],
  ["Bloque 2", "Células gigantes", "¿Cómo se distribuyen los núcleos en una célula gigante de Langhans?", "Hacia la periferia, a menudo en forma de herradura."],
  ["Bloque 2", "Células gigantes", "¿Qué lesiones maxilares pueden contener células gigantes?", "Granuloma central de células gigantes, querubismo y quiste óseo aneurismático."],
  ["Bloque 2", "Hematología", "¿Cuál es el rango leucocitario total?", "5,000–10,000 leucocitos/mm³."],
  ["Bloque 2", "Hematología", "¿Cuál es el rango normal de neutrófilos?", "50–70 %."],
  ["Bloque 2", "Plaquetas", "¿Cuál es el rango plaquetario?", "200,000–400,000 plaquetas/µL."],
  ["Bloque 2", "Plaquetas", "¿Qué efecto tiene la aspirina sobre la función plaquetaria?", "Inhibe la ciclooxigenasa y disminuye la síntesis de tromboxano A₂."],
  ["Bloque 2", "Inflamación crónica", "¿Qué células predominan en inflamación crónica?", "Macrófagos, linfocitos y células plasmáticas."],
  ["Bloque 2", "Inflamación crónica", "¿Por qué aparece fibrosis en la inflamación crónica?", "Por destrucción tisular persistente acompañada de intentos repetidos de reparación."],

  ["Bloque 3", "Ficha clínica", "¿Qué valor médico y legal tiene la ficha clínica?", "Guía el tratamiento, revela riesgos y documenta la atención y las decisiones clínicas."],
  ["Bloque 3", "Ficha clínica", "¿Qué debe conservar el motivo de consulta?", "Las palabras del paciente, idealmente entre comillas."],
  ["Bloque 3", "Ficha clínica", "¿Qué datos deben registrarse de cada medicamento?", "Nombre comercial y genérico, dosis, frecuencia e indicación."],
  ["Bloque 3", "Medicamentos", "¿Qué fármacos antirresortivos se asocian a osteonecrosis de los maxilares?", "Bifosfonatos y denosumab."],
  ["Bloque 3", "ASA", "¿Qué describe ASA I?", "Paciente sano, sin enfermedad sistémica relevante."],
  ["Bloque 3", "ASA", "¿Qué describe ASA II?", "Paciente con enfermedad sistémica leve o factor de riesgo controlado."],
  ["Bloque 3", "ASA", "¿Qué describe ASA III?", "Paciente con enfermedad sistémica grave que limita la actividad, pero no es una amenaza constante para la vida."],
  ["Bloque 3", "ASA", "¿Qué describe ASA IV?", "Enfermedad sistémica grave que constituye una amenaza constante para la vida."],
  ["Bloque 3", "Cardiovascular", "¿Qué antecedente infeccioso se relaciona con fiebre reumática?", "Infección faríngea por estreptococo beta-hemolítico del grupo A."],
  ["Bloque 3", "Cardiovascular", "¿Qué medicamentos son anticoagulantes y cuál es antiagregante?", "Warfarina y rivaroxabán son anticoagulantes; clopidogrel es antiagregante."],
  ["Bloque 3", "Medicamentos", "¿Qué tres grupos pueden causar agrandamiento gingival?", "Bloqueadores de canales de calcio, ciclosporina y anticonvulsivantes."],
  ["Bloque 3", "Diabetes", "¿Cuáles son las tres polis clásicas de diabetes?", "Polidipsia, polifagia y poliuria."],
  ["Bloque 3", "Diabetes", "¿Qué refleja la HbA1c?", "El promedio aproximado de glucemia de los últimos tres meses."],
  ["Bloque 3", "Diabetes", "¿Qué valor de HbA1c se considera diabetes?", "6.5 % o más."],
  ["Bloque 3", "Sjögren", "¿Qué es xerostomía?", "La sensación subjetiva de boca seca referida por el paciente."],
  ["Bloque 3", "Sjögren", "¿Qué mide la sialometría?", "El volumen o flujo de saliva producido en un tiempo determinado."],
  ["Bloque 3", "Sjögren", "¿Qué autoanticuerpos se investigan en Sjögren?", "Anti-Ro/SSA, anti-La/SSB, ANA, factor reumatoide y, en algunos casos, anti-α-fodrina."],
  ["Bloque 3", "Sjögren", "¿Por qué se prefiere biopsiar glándulas salivales menores y no la parótida?", "Porque la parótida se relaciona con el nervio facial; el labio permite una muestra menos riesgosa."],
  ["Bloque 3", "Respiratorio", "¿Qué síntomas sugieren tuberculosis activa?", "Pérdida de peso, sudoración nocturna, fiebre y hemoptisis."],
  ["Bloque 3", "Respiratorio", "¿Cómo reducen los pacientes el riesgo de candidiasis por inhaladores con esteroides?", "Enjuagándose la boca o bebiendo agua después de cada uso."],
  ["Bloque 3", "Gastrointestinal", "¿Qué lesión dental puede producir el reflujo gastroesofágico?", "Erosión dental por exposición repetida al ácido."],
  ["Bloque 3", "Gastrointestinal", "¿Qué antibiótico se asocia especialmente a colitis pseudomembranosa?", "Clindamicina."],
  ["Bloque 3", "Nervioso", "¿Por qué una parestesia sin causa clara puede ser una señal de alarma?", "Porque una lesión maligna puede invadir un nervio y manifestarse inicialmente como parestesia."],
  ["Bloque 3", "Hematología", "¿Qué pruebas se consideran ante petequias o equimosis inexplicadas?", "TP, TPT, INR, tiempos de coagulación y recuento plaquetario."],

  ["Bloque 4", "Examen clínico", "¿Cómo debe realizarse la palpación extraoral?", "De forma sistemática y bidigital, comparando ambos lados y registrando cualquier masa, dolor o asimetría."],
  ["Bloque 4", "Examen clínico", "¿Qué característica ganglionar es preocupante?", "Que el ganglio sea fijo, duro o persistente."],
  ["Bloque 4", "Examen clínico", "¿Dónde aparece típicamente un quiste del conducto tirogloso?", "En la línea media del cuello, a lo largo del trayecto embrionario de la tiroides."],
  ["Bloque 4", "Examen clínico", "¿Cómo debe recorrerse la cavidad durante la palpación intraoral?", "De manera continua, ordenada y bidigital, sin saltar áreas."],
  ["Bloque 4", "Lesiones cutáneas", "¿Qué aspecto tiene la hiperplasia sebácea?", "Pápulas amarillentas con depresión central, generalmente en adultos."],
  ["Bloque 4", "Lesiones pigmentadas", "¿Qué son las efélides?", "Máculas hiperpigmentadas adquiridas que aumentan con la exposición solar."],
  ["Bloque 4", "Lesiones pigmentadas", "¿Con qué síndrome pueden asociarse múltiples máculas periorales?", "Síndrome de Peutz-Jeghers."],
  ["Bloque 4", "Lesiones pigmentadas", "¿Qué es melasma?", "Pigmentación café adquirida en áreas faciales expuestas al sol, asociada a hormonas y radiación UV."],
  ["Bloque 4", "Lesiones vasculares", "¿Qué es una telangiectasia?", "Dilatación visible de pequeños vasos sanguíneos."],
  ["Bloque 4", "Lesiones vasculares", "¿Qué es la diascopía?", "Compresión de una lesión con una lámina transparente para evaluar si palidece y sugiere origen intravascular."],
  ["Bloque 4", "Lesiones vasculares", "¿Por qué una equimosis no palidece con diascopía?", "Porque la sangre está extravasada fuera de los vasos."],
  ["Bloque 4", "Rosácea", "¿Qué es rinofima?", "Una forma avanzada de rosácea con engrosamiento nodular de la nariz."],
  ["Bloque 4", "Lesiones pigmentadas", "¿Qué es un léntigo solar?", "Mácula pigmentada adquirida por daño solar acumulado."],
  ["Bloque 4", "Lesiones cutáneas", "¿Qué aspecto típico tiene la queratosis seborreica?", "Placa pigmentada, queratósica y de apariencia adherida a la piel."],
  ["Bloque 4", "Lesiones cutáneas", "¿Con qué alteraciones pueden asociarse múltiples acrocordones?", "Obesidad, resistencia a la insulina, prediabetes o diabetes."],
  ["Bloque 4", "Lesiones cutáneas", "¿Qué sugiere la acantosis nigricans?", "Resistencia a la insulina u otra alteración metabólica cuando aparece en pliegues."],
  ["Bloque 4", "Labios", "¿Qué es queilitis exfoliativa?", "Descamación persistente del bermellón, relacionada con irritación, lamido o algunos tratamientos."],
  ["Bloque 4", "Labios", "¿Por qué es importante la queilitis actínica?", "Porque es daño solar crónico y una lesión potencialmente maligna."],
  ["Bloque 4", "Labios", "¿Qué son los gránulos de Fordyce?", "Glándulas sebáceas ectópicas visibles como puntos amarillentos y sin potencial maligno."],
  ["Bloque 4", "Lesiones vasculares", "¿Qué es un angioma cherry?", "Una proliferación vascular adquirida, roja y benigna, más frecuente con la edad."],

  ["Bloque 1", "Salud y enfermedad", "¿Qué ocurre antes de que una enfermedad produzca malestar perceptible?", "Ya se han desarrollado cambios microscópicos, bioquímicos y funcionales."],
  ["Bloque 1", "Salud y enfermedad", "¿Qué es resolución?", "El estado en el que el paciente queda libre de la enfermedad."],
  ["Bloque 1", "Salud y enfermedad", "¿Qué es diagnóstico?", "El proceso de identificar e interpretar una lesión o enfermedad."],
  ["Bloque 1", "Salud y enfermedad", "¿Qué es un síndrome?", "Un conjunto de signos, síntomas o condiciones que aparecen asociados."],
  ["Bloque 1", "Factores de enfermedad", "¿Cómo puede la microflora normal producir enfermedad?", "Una alteración del equilibrio puede modificarla y volverla patógena."],
  ["Bloque 1", "Factores de enfermedad", "¿Qué sucede en una enfermedad autoinmune?", "El sistema inmunitario identifica incorrectamente tejidos propios como extraños y los ataca."],
  ["Bloque 1", "Factores de enfermedad", "¿Cuáles son ejemplos de enfermedades autoinmunes?", "Síndrome de CREST, síndrome de Sjögren y artritis reumatoide."],
  ["Bloque 1", "Factores de enfermedad", "¿Cómo puede la anemia producir hipoxia?", "Disminuye la capacidad de la sangre para transportar oxígeno."],
  ["Bloque 1", "Factores de enfermedad", "¿Qué alteraciones nutricionales favorecen enfermedad?", "Insuficiencia proteico-calórica y deficiencias vitamínicas u hormonales."],
  ["Bloque 1", "Factores de enfermedad", "¿Cuáles son los principales agentes biológicos extrínsecos?", "Virus, bacterias y hongos."],
  ["Bloque 1", "Homeostasis", "¿Qué función cumple la inmunovigilancia?", "Reconocer y destruir células anormales antes de que formen una patología."],
  ["Bloque 1", "Homeostasis", "¿Por qué predominan algunas patologías en personas mayores?", "Porque la respuesta frente a agresores es más lenta y menos eficaz."],
  ["Bloque 1", "Genética celular", "¿Qué información contiene el ADN?", "Los programas necesarios para funcionamiento, duplicación y transmisión celular."],
  ["Bloque 1", "Genética celular", "¿Qué es un gen?", "Una unidad de herencia y segmento de ADN que controla características particulares."],
  ["Bloque 1", "Genética celular", "¿Qué es una mutación?", "Una variación genética causada por un cambio en una región del ADN."],
  ["Bloque 1", "Genética celular", "¿Qué posibles consecuencias puede tener una mutación?", "Favorables, neutras o desfavorables."],
  ["Bloque 1", "Genética celular", "¿Qué es el fenotipo?", "La apariencia y las características observables de una persona."],
  ["Bloque 1", "Genética celular", "¿Qué distingue un alelo dominante de uno recesivo?", "El dominante se expresa en presencia de otro; el recesivo puede quedar enmascarado."],
  ["Bloque 1", "Lesión celular", "¿Qué es una lesión bioquímica?", "Un cambio metabólico celular que puede preceder cambios morfológicos, signos y síntomas."],
  ["Bloque 1", "Lesión celular", "¿Qué es degeneración vacuolar?", "Acumulación de agua dentro de vacuolas celulares."],
  ["Bloque 1", "Lesión celular", "¿Qué órgano ejemplifica la acumulación intracelular de grasa?", "El hígado, donde se acumula grasa en hepatocitos."],
  ["Bloque 1", "Lesión celular", "¿Qué factores favorecen el hígado graso?", "Mala nutrición e ingesta de alcohol."],
  ["Bloque 1", "Muerte celular", "¿Cómo elimina el organismo el tejido necrótico?", "Lo reconoce y libera enzimas líticas para degradarlo."],
  ["Bloque 1", "Muerte celular", "¿Qué ocurre en la necrosis caseosa?", "Los restos necróticos permanecen porque no se absorben rápidamente."],
  ["Bloque 1", "Gangrena", "¿Qué efectos generales puede causar la necrosis?", "Pérdida de función, foco de infección, fiebre y dolor."],

  ["Bloque 2", "Inflamación", "¿Qué tres categorías de agentes activan inflamación?", "Biológicos, físicos y químicos."],
  ["Bloque 2", "Inflamación", "¿Qué agentes físicos pueden causar inflamación?", "Trauma, radiación solar y radioterapia."],
  ["Bloque 2", "Inflamación", "¿Qué agentes químicos pueden causar inflamación?", "Líquidos orgánicos, corrosivos y quimioterapia."],
  ["Bloque 2", "Inflamación", "¿Cómo se relaciona el dolor con la inflamación aguda?", "Se produce por mediadores químicos y puede agravarse por la presión tisular."],
  ["Bloque 2", "Ganglios", "¿Cómo puede la inflamación producir linfadenopatía?", "El aumento de líquido intersticial y flujo linfático agranda ganglios regionales."],
  ["Bloque 2", "Ganglios", "¿Qué diferencia orientativa existe entre un ganglio móvil y uno fijo?", "El móvil suele ser reactivo; el fijo y firme es preocupante."],
  ["Bloque 2", "Exudado", "¿Cómo se forma el exudado?", "Por separación endotelial y salida de líquido, proteínas y células desde los vasos."],
  ["Bloque 2", "Exudado", "¿Cómo contribuye el exudado a neutralizar toxinas?", "Las diluye y transporta anticuerpos, complemento y enzimas proteolíticas."],
  ["Bloque 2", "Exudado", "¿Cómo favorece el exudado la reparación?", "Deposita fibrina y aporta nutrientes y células inflamatorias."],
  ["Bloque 2", "Migración leucocitaria", "¿Qué cambios sanguíneos preceden la migración leucocitaria?", "Aumento de permeabilidad capilar y de viscosidad sanguínea."],
  ["Bloque 2", "Migración leucocitaria", "¿Qué es marginación?", "Aproximación de leucocitos hacia la pared vascular."],
  ["Bloque 2", "Migración leucocitaria", "¿Qué es pavimentación?", "Alineación y adhesión de numerosos leucocitos sobre el endotelio."],
  ["Bloque 2", "Migración leucocitaria", "¿Qué es diapédesis?", "Paso ameboide de leucocitos a través de la pared vascular."],
  ["Bloque 2", "Respuesta inflamatoria", "¿Dónde se originan los leucocitos?", "En la médula ósea."],
  ["Bloque 2", "Hematología", "¿Qué incluye una hematología completa?", "Recuento leucocitario total y fórmula diferencial."],
  ["Bloque 2", "Hematología", "¿Cuál es el rango de eosinófilos?", "1–4 %."],
  ["Bloque 2", "Hematología", "¿Cuál es el porcentaje de basófilos?", "0.5 %."],
  ["Bloque 2", "Hematología", "¿Cuál es el rango de linfocitos?", "20–40 %."],
  ["Bloque 2", "Hematología", "¿Cuál es el rango de monocitos?", "2–8 %."],
  ["Bloque 2", "Neutrófilos", "¿Cuál es la vida media aproximada del neutrófilo?", "Alrededor de seis horas."],
  ["Bloque 2", "Neutrófilos", "¿Los neutrófilos se dividen una vez en el torrente sanguíneo?", "No; una vez circulantes ya no se dividen."],
  ["Bloque 2", "Neutrófilos", "¿Qué enzima contienen los gránulos de los neutrófilos?", "Lisozima."],
  ["Bloque 2", "Fagocitosis", "¿Qué mecanismos destruyen la bacteria dentro del fagolisosoma?", "Enzimas y mecanismos oxidativos, incluido peróxido de hidrógeno."],
  ["Bloque 2", "Leucocitos", "¿Cómo migran los eosinófilos respecto de los neutrófilos?", "Responden a quimiotaxis, pero más lentamente."],
  ["Bloque 2", "Leucocitos", "¿Qué célula circulante se transforma en macrófago tisular?", "El monocito."],
  ["Bloque 2", "Macrófagos", "¿Cómo se llaman los macrófagos del pulmón?", "Macrófagos alveolares."],
  ["Bloque 2", "Macrófagos", "¿Cómo se llaman los macrófagos del tejido linfoide?", "Macrófagos linfoides."],
  ["Bloque 2", "Células gigantes", "¿Cómo se distribuyen los núcleos en células gigantes de cuerpo extraño?", "Se encuentran dispersos por el citoplasma."],
  ["Bloque 2", "Células gigantes", "¿Con qué procesos se relacionan células gigantes de Langhans?", "Tuberculosis y sarcoidosis."],
  ["Bloque 2", "Plaquetas", "¿De qué células derivan las plaquetas?", "De megacariocitos de la médula ósea."],
  ["Bloque 2", "Plaquetas", "¿Qué activa a las plaquetas en una lesión vascular?", "El contacto con la matriz subendotelial expuesta."],
  ["Bloque 2", "Plaquetas", "¿Qué es trombocitopenia?", "Disminución del número de plaquetas."],
  ["Bloque 2", "Plaquetas", "¿Qué es trombocitosis?", "Aumento del número de plaquetas."],
  ["Bloque 2", "Plaquetas", "¿Qué riesgo aparece entre 20,000 y 50,000 plaquetas?", "Tendencia al sangrado."],
  ["Bloque 2", "Plaquetas", "¿Qué puede ocurrir con menos de 20,000 plaquetas?", "Sangrado espontáneo, incluido sangrado gingival."],
  ["Bloque 2", "Inflamación crónica", "¿Qué es angiogénesis?", "Formación de nuevos vasos durante la reparación de tejido crónicamente lesionado."],
  ["Bloque 2", "Inflamación crónica", "¿Cuál es la duración aproximada de la inflamación aguda?", "Aproximadamente 7–21 días."],

  ["Bloque 3", "Ficha clínica", "¿Qué expresa el consentimiento informado?", "Que el paciente participa voluntariamente, comprende y acepta el procedimiento."],
  ["Bloque 3", "Ficha clínica", "¿Qué estudios de imagen básicos puede incluir la ficha clínica?", "Panorámica, periapicales y bitewings."],
  ["Bloque 3", "Ficha clínica", "¿Qué imágenes avanzadas pueden solicitarse ante patologías específicas?", "Resonancia, tomografía o ultrasonido."],
  ["Bloque 3", "Ficha clínica", "¿Qué diferencia una historia no estructurada de una estructurada?", "La no estructurada surge del diálogo libre; la estructurada usa preguntas predefinidas."],
  ["Bloque 3", "Ficha clínica", "¿Qué es una historia clínica mixta?", "Un formulario estructurado complementado con diálogo clínico."],
  ["Bloque 3", "Signos vitales", "¿Qué signos vitales deben registrarse?", "Presión arterial, pulso, respiración y temperatura."],
  ["Bloque 3", "ASA", "¿Qué describe ASA V?", "Paciente moribundo o en estado terminal."],
  ["Bloque 3", "Alergias", "¿Qué alergias medicamentosas deben investigarse?", "Anestésicos, aspirina, penicilina, antibióticos, sedantes, codeína y otros narcóticos."],
  ["Bloque 3", "Alergias", "¿Qué alergias no farmacológicas deben investigarse?", "Metales, látex, yodo, polen, animales y alimentos."],
  ["Bloque 3", "Cardiovascular", "¿Qué valor de presión arterial se anota como referencia?", "120/80 mmHg."],
  ["Bloque 3", "Cardiovascular", "¿Qué representa la presión sistólica?", "La presión durante el latido cardíaco."],
  ["Bloque 3", "Cardiovascular", "¿Qué representa la presión diastólica?", "La presión entre latidos."],
  ["Bloque 3", "Cardiovascular", "¿Cómo influye la presión arterial en odontología?", "Puede modificar decisiones como el uso de vasoconstrictores."],
  ["Bloque 3", "Cardiovascular", "¿Qué clasificación ASA anotan para los primeros seis meses después de un ACV?", "ASA IV."],
  ["Bloque 3", "Cardiovascular", "¿Qué clasificación ASA anotan después de seis meses de un ACV?", "ASA III."],
  ["Bloque 3", "Cardiovascular", "¿Qué secuelas de ACV deben considerarse?", "Parálisis, dificultad del habla y pérdida de motricidad."],
  ["Bloque 3", "Cardiovascular", "¿Qué pueden representar radiopacidades cervicales en C3–C4?", "Placas ateromatosas carotídeas."],
  ["Bloque 3", "Medicamentos", "¿Cuáles son ejemplos de bifosfonatos?", "Alendronato, risedronato, ibandronato y zoledronato."],
  ["Bloque 3", "Diabetes", "¿Cuál es la glucemia preprandial?", "80–110 mg/dL."],
  ["Bloque 3", "Diabetes", "¿Cuál es la glucemia posprandial?", "Menor de 140 mg/dL."],
  ["Bloque 3", "Diabetes", "¿Cuál es el rango de HbA1c para prediabetes?", "5.7–6.4 %."],
  ["Bloque 3", "Diabetes", "¿Por qué la diabetes puede dificultar el control de infecciones?", "Puede alterar la función de los neutrófilos."],
  ["Bloque 3", "Xerostomía", "¿Qué medicamentos pueden favorecer boca seca?", "Antidepresivos y antihistamínicos, entre otros."],
  ["Bloque 3", "Xerostomía", "¿Qué riesgos orales aumenta la boca seca?", "Candidiasis y caries."],
  ["Bloque 3", "Sjögren", "¿Qué diferencia Sjögren primario de secundario?", "El primario aparece aislado; el secundario se asocia a enfermedad del colágeno."],
  ["Bloque 3", "Sjögren", "¿Qué pruebas evalúan signos oculares de Sjögren?", "Test de Schirmer y rosa de Bengala."],
  ["Bloque 3", "Sjögren", "¿Cuántas glándulas salivales menores se obtienen aproximadamente en biopsia?", "Cuatro o cinco glándulas del labio inferior."],
  ["Bloque 3", "Sjögren", "¿Qué es sialografía?", "Radiografía con contraste para observar conductos y glándulas salivales."],
  ["Bloque 3", "Sjögren", "¿Qué evalúa la centellografía salival?", "La función glandular."],
  ["Bloque 3", "Sjögren", "¿Cómo puede estimularse una sialometría?", "Con un agente ácido antes de recoger y medir la saliva."],
  ["Bloque 3", "Respiratorio", "¿Qué conducta corresponde ante gripe o catarro activo?", "Posponer el tratamiento dental electivo."],
  ["Bloque 3", "Respiratorio", "¿Qué diferencia existe entre VIH y sida?", "Una prueba positiva para VIH no equivale por sí sola a sida."],
  ["Bloque 3", "Respiratorio", "¿Cuáles son ejemplos de enfermedades oportunistas?", "Sarcoma de Kaposi, tuberculosis y candidiasis pseudomembranosa."],
  ["Bloque 3", "Respiratorio", "¿Qué maniobra puede aumentar el dolor de una sinusitis?", "Inclinarse hacia delante."],
  ["Bloque 3", "Gastrointestinal", "¿Qué fármacos pueden agravar gastritis o úlcera?", "Aspirina y otros AINE."],
  ["Bloque 3", "Gastrointestinal", "¿Qué puede causar un sangrado gastrointestinal crónico?", "Anemia y palidez de mucosas."],
  ["Bloque 3", "Hepático", "¿Por qué la hepatitis o ictericia importan para la prescripción?", "Pueden alterar el metabolismo de fármacos y la coagulación."],
  ["Bloque 3", "Genitourinario", "¿Por qué debe conocerse la función renal?", "Porque determina la excreción de muchos medicamentos."],
  ["Bloque 3", "Genitourinario", "¿Qué síntomas orientan a enfermedad renal?", "Edema de tobillos o párpados, molestias al orinar y dolor lumbar."],
  ["Bloque 3", "Neurológico", "¿Qué debe investigarse en un paciente con convulsiones?", "Tratamiento, horario de medicación y factores de ansiedad."],
  ["Bloque 3", "Hematología", "¿Cómo puede la anemia afectar la cicatrización?", "La menor oxigenación tisular puede retrasarla."],
  ["Bloque 3", "Hematología", "¿Qué sustancias pueden prolongar el sangrado?", "Ginkgo biloba, ajo y hormonas."],
  ["Bloque 3", "Hematología", "¿Cuáles son los rangos de hemoglobina?", "Hombres 14–18 g/dL; mujeres 12–16 g/dL."],
  ["Bloque 3", "Hematología", "¿Cuáles son los rangos de hematocrito?", "Hombres 41–53 %; mujeres 36–46 %."],

  ["Bloque 4", "Preparación clínica", "¿Qué debe verificarse antes del examen clínico?", "Instrumental esterilizado, radiografía panorámica y estudios necesarios."],
  ["Bloque 4", "Preparación clínica", "¿Qué instrumentos básicos se preparan para el examen?", "Sonda periodontal, espejos, bajalenguas, explorador, gasa, pinza y equipo de protección."],
  ["Bloque 4", "Preparación clínica", "¿Qué signos se miden antes del examen?", "Signos vitales con oxímetro y esfigmomanómetro."],
  ["Bloque 4", "Preparación clínica", "¿Cuándo deben reconsiderarse bitewings?", "Cuando faltan dientes posteriores o coronas impiden su utilidad."],
  ["Bloque 4", "Examen clínico", "¿Qué tercios faciales se palpan extraoralmente?", "Superior, medio e inferior."],
  ["Bloque 4", "Quiste epidermoide", "¿Cómo se presenta el quiste epidermoide o sebáceo?", "Como crecimiento lento, asintomático, cubierto por piel normal y revestido por epitelio."],
  ["Bloque 4", "Quiste epidermoide", "¿En qué zonas y edades aparece con mayor frecuencia?", "Cuello, cara o pecho; principalmente tercera y cuarta décadas."],
  ["Bloque 4", "Quiste epidermoide", "¿Cuál es su tratamiento?", "Escisión quirúrgica y evaluación histopatológica."],
  ["Bloque 4", "Lesiones cutáneas", "¿En qué grupo etario predomina la hiperplasia sebácea?", "Adultos de mediana y tercera edad."],
  ["Bloque 4", "Lesiones pigmentadas", "¿Qué es una mácula?", "Un cambio de color plano, sin elevación."],
  ["Bloque 4", "Lesiones pigmentadas", "¿Qué factores se asocian al melasma?", "Exposición solar, embarazo y anticonceptivos."],
  ["Bloque 4", "Lesiones vasculares", "¿Con qué enfermedades puede asociarse una telangiectasia?", "Telangiectasia hemorrágica hereditaria y síndrome de CREST."],
  ["Bloque 4", "Lesiones vasculares", "¿Qué son petequias?", "Lesiones puntiformes por extravasación de sangre."],
  ["Bloque 4", "Lesiones vasculares", "¿Qué esfuerzos pueden producir petequias?", "Tos o vómito intenso."],
  ["Bloque 4", "Rosácea", "¿Qué factores pueden exacerbar rosácea?", "Luz UV, temperatura, ejercicio, alcohol, tabaco, café y estrés."],
  ["Bloque 4", "Lesiones pigmentadas", "¿En quiénes es más frecuente el léntigo solar?", "En personas mayores y áreas expuestas al sol."],
  ["Bloque 4", "Lesiones cutáneas", "¿A partir de qué edad es frecuente la queratosis seborreica?", "Después de los 50 años."],
  ["Bloque 4", "Cuello", "¿Cómo se facilita la palpación del esternocleidomastoideo?", "Pidiendo al paciente que gire la cabeza."],
  ["Bloque 4", "Cuello", "¿Desde dónde desciende embrionariamente la tiroides?", "Desde el foramen ciego de la lengua hacia el cuello."],
  ["Bloque 4", "Cuello", "¿Qué tres aspectos se buscan al palpar el cuello?", "Masa, dolor y molestia o asimetría."],
  ["Bloque 4", "Lesiones cutáneas", "¿Por qué puede sangrar un acrocordón?", "Porque posee un eje vascular."],
  ["Bloque 4", "Lesiones cutáneas", "¿Dónde aparecen típicamente los acrocordones?", "En cuello y axilas."],
  ["Bloque 4", "Lesiones cutáneas", "¿Dónde aparece la acantosis nigricans?", "En pliegues como cuello, axilas e ingles."],
  ["Bloque 4", "Labios", "¿Qué tratamiento puede causar queilitis exfoliativa?", "Isotretinoína para acné."],
  ["Bloque 4", "Labios", "¿Qué caracteriza una fisura labial?", "Una grieta, a menudo medial, que se reabre al hablar o reír."],
  ["Bloque 4", "Labios", "¿Qué signo clínico aparece en queilitis actínica?", "Pérdida de la delimitación normal del bermellón."],
  ["Bloque 4", "Labios", "¿Cuándo debe biopsiarse una queilitis actínica?", "Cuando presenta ulceración u otros cambios sospechosos."],
  ["Bloque 4", "Lesiones pigmentadas", "¿Cómo se presenta la mácula melanótica labial?", "Como lesión pigmentada plana, generalmente única."],
  ["Bloque 4", "Lesiones vasculares", "¿Qué otros nombres recibe el angioma cherry?", "Angioma senil o hemangioma del adulto."],
  ["Bloque 4", "Lesiones vasculares", "¿Cuál es el manejo habitual del angioma cherry?", "Diagnóstico clínico y tratamiento principalmente estético."]
]

export const semiologiaFlashcards: Flashcard[] = seeds.map(
  ([chapter, topic, front, back], index) => ({
    id: `semio-${String(index + 1).padStart(3, "0")}`,
    subject: "Semiología",
    book: "Semiología clínica",
    chapter,
    topic,
    subtopic: topic,
    front,
    back,
    tags: ["Semiología", chapter, topic]
  })
)

export default semiologiaFlashcards
