import type { Flashcard } from "./cards"

const CHAPTER = "Artículo · Hemostasia y trombosis"

type Seed = readonly [
  subtopic: string,
  front: string,
  back: string
]

const H = "Hemorragia y conceptos generales"
const N = "Secuencia de la hemostasia normal"
const EA = "Endotelio antitrombótico"
const EP = "Endotelio protrombótico"
const PG = "Plaquetas y gránulos"
const PA = "Adhesión plaquetaria"
const PV = "Activación plaquetaria"
const AG = "Agregación y tapón estable"
const PE = "Interacción plaqueta-endotelio"
const CC = "Cascada de coagulación"
const PR = "Pruebas de coagulación"
const TP = "Trombina y receptores PAR"
const AN = "Anticoagulantes naturales"
const FI = "Fibrinólisis"
const VT = "Trombosis y tríada de Virchow"
const FA = "Flujo anormal y trombosis"

const seeds: Seed[] = [
  [H, "¿Qué alteración puede producir hemorragias petequiales puntiformes?", "Trombocitopenia."],
  [H, "¿Por qué una hemorragia relativamente pequeña puede ser mortal en el cerebro?", "Por su localización intracraneal."],
  [H, "¿Qué consecuencia frecuente tiene la pérdida externa crónica o recurrente de sangre?", "Anemia ferropénica."],
  [H, "¿Por qué la pérdida externa crónica de sangre causa ferropenia?", "Porque se pierde el hierro contenido en la hemoglobina."],
  [H, "¿Por qué un hematoma interno no suele causar ferropenia?", "Porque el hierro de los eritrocitos fagocitados se recicla eficientemente."],
  [H, "¿Qué mantiene la hemostasia normal dentro de vasos sanos?", "La sangre fluida y libre de coágulos."],
  [H, "¿Qué forma rápidamente la hemostasia normal tras una lesión vascular?", "Un tapón hemostático localizado."],
  [H, "¿Cuál es la contraparte patológica de la hemostasia?", "La trombosis."],
  [H, "¿Qué es la trombosis?", "La formación de un trombo dentro de vasos intactos."],
  [H, "¿Qué tres elementos participan tanto en hemostasia como en trombosis?", "Pared vascular, plaquetas y cascada de coagulación."],

  [N, "¿Cuál es la primera respuesta a una lesión vascular?", "Vasoconstricción arteriolar transitoria."],
  [N, "¿Qué mecanismo inicia la vasoconstricción tras una lesión vascular?", "Reflejos neurógenos."],
  [N, "¿Qué mediador endotelial refuerza la vasoconstricción inicial?", "Endotelina."],
  [N, "¿Qué tipo de mediador es la endotelina?", "Un potente vasoconstrictor derivado del endotelio."],
  [N, "¿Por qué la vasoconstricción inicial no basta para detener la hemorragia?", "Porque es transitoria y el sangrado reaparecería sin plaquetas y coagulación."],
  [N, "¿Qué expone la lesión endotelial para iniciar la adhesión plaquetaria?", "La matriz extracelular subendotelial trombogénica."],
  [N, "¿Qué tres procesos plaquetarios provoca la exposición de la matriz subendotelial?", "Adhesión, activación y agregación."],
  [N, "¿Cómo se llama la formación del tapón plaquetario inicial?", "Hemostasia primaria."],
  [N, "¿Qué otro nombre recibe el factor tisular?", "Factor III o tromboplastina."],
  [N, "¿Qué clase de molécula es el factor tisular?", "Una glucoproteína procoagulante unida a membrana."],
  [N, "¿Qué células sintetizan el factor tisular descrito en el texto?", "Células endoteliales."],
  [N, "¿Con qué factor actúa el factor tisular para iniciar la coagulación?", "Factor VII."],
  [N, "¿Cuál es el principal desencadenante in vivo de la cascada de coagulación?", "El factor tisular expuesto junto con el factor VII."],
  [N, "¿En qué activación culmina la cascada de coagulación?", "En la activación de trombina."],
  [N, "¿Qué hace la trombina al fibrinógeno durante la hemostasia?", "Lo escinde para formar fibrina insoluble."],
  [N, "¿Qué efecto tiene la trombina sobre las plaquetas?", "Las activa potentemente y refuerza el tapón."],
  [N, "¿Cómo se llama la formación del coágulo estable de fibrina?", "Hemostasia secundaria."],
  [N, "¿Qué limita el coágulo al sitio de lesión cuando se controla el sangrado?", "Mecanismos contrarreguladores anticoagulantes y fibrinolíticos."],
  [N, "¿Qué activador fibrinolítico ejemplifica la contrarregulación hemostática?", "El activador tisular del plasminógeno, t-PA."],

  [EA, "¿Qué determina si un trombo se forma, progresa o se disuelve?", "El balance entre actividades antitrombóticas y protrombóticas del endotelio."],
  [EA, "¿Qué tres efectos generales tiene el endotelio normal sobre la hemostasia?", "Inhibe plaquetas, inhibe coagulación y promueve fibrinólisis."],
  [EA, "¿Cómo impide físicamente el endotelio intacto la activación hemostática?", "Separa plaquetas y factores plasmáticos de la matriz subendotelial trombogénica."],
  [EA, "¿Se adhieren las plaquetas no activadas al endotelio normal?", "No."],
  [EA, "¿Qué dos mediadores endoteliales dificultan la adhesión de plaquetas activadas?", "Prostaciclina (PGI2) y óxido nítrico."],
  [EA, "¿Qué efecto vascular comparten PGI2 y óxido nítrico?", "Vasodilatación."],
  [EA, "¿Qué efecto plaquetario comparten PGI2 y óxido nítrico?", "Inhibición de la agregación plaquetaria."],
  [EA, "¿Qué estímulos pueden aumentar la síntesis endotelial de PGI2 y NO durante la coagulación?", "Trombina y citocinas, entre otros."],
  [EA, "¿Qué enzima endotelial degrada ADP?", "Adenosina difosfatasa."],
  [EA, "¿Cómo inhibe la adenosina difosfatasa la agregación plaquetaria?", "Degrada el ADP que activa y recluta plaquetas."],
  [EA, "¿Qué tres sistemas endoteliales inhiben factores de coagulación?", "Moléculas tipo heparina, trombomodulina y TFPI."],
  [EA, "¿Cómo actúan las moléculas endoteliales tipo heparina?", "Como cofactores que potencian la acción de antitrombina III."],
  [EA, "¿Qué proteína plasmática es potenciada por moléculas tipo heparina?", "Antitrombina III."],
  [EA, "¿Qué enzima central inactiva la antitrombina III?", "Trombina."],
  [EA, "¿Qué otros factores puede inactivar antitrombina III?", "IXa, Xa, XIa y XIIa."],
  [EA, "¿A qué se une la trombomodulina?", "A la trombina."],
  [EA, "¿Qué cambia la trombomodulina al unirse a trombina?", "La especificidad de sustrato de la trombina."],
  [EA, "¿Qué hace la trombina unida a trombomodulina en vez de escindir fibrinógeno?", "Activa proteína C."],
  [EA, "¿Qué factores inactiva la proteína C activada?", "Va y VIIIa."],
  [EA, "¿Qué cofactor necesita la proteína C activada?", "Proteína S."],
  [EA, "¿Qué células sintetizan proteína S según el texto?", "Células endoteliales."],
  [EA, "¿Qué complejos inhibe directamente TFPI?", "Factor tisular-factor VIIa y factor Xa."],
  [EA, "¿Qué sintetiza el endotelio para convertir plasminógeno en plasmina?", "t-PA."],
  [EA, "¿Qué hace la plasmina con la fibrina?", "La escinde y degrada el trombo."],

  [EP, "¿Qué puede activar al endotelio además del trauma?", "Patógenos, fuerzas hemodinámicas y mediadores proinflamatorios."],
  [EP, "¿Cómo favorece plaquetas la pérdida de integridad endotelial?", "Expone colágeno y vWF subendoteliales."],
  [EP, "¿Qué citocinas inducen factor tisular en endotelio?", "TNF e IL-1."],
  [EP, "¿Qué producto bacteriano puede inducir factor tisular endotelial?", "Endotoxina."],
  [EP, "¿Qué anticoagulante endotelial disminuye durante la activación?", "Trombomodulina."],
  [EP, "¿Qué factores activados se unen al endotelio activado para aumentar su actividad catalítica?", "IXa y Xa."],
  [EP, "¿Qué secretan las células endoteliales activadas para limitar fibrinólisis?", "Inhibidores del activador del plasminógeno (PAI)."],
  [EP, "¿Qué efecto neto tiene la secreción endotelial de PAI?", "Favorece trombosis."],
  [EP, "¿Qué cambio general sufre el endotelio tras lesión o activación?", "Pasa de un fenotipo anticoagulante a uno procoagulante."],
  [EP, "¿Qué molécula actúa como puente entre pared vascular denudada y plaqueta?", "Factor de von Willebrand."],

  [PG, "¿Qué son las plaquetas?", "Fragmentos celulares anucleados derivados de megacariocitos medulares."],
  [PG, "¿Qué defecto vascular sella el tapón plaquetario?", "La discontinuidad de la pared vascular."],
  [PG, "¿Qué superficie proporcionan las plaquetas durante la coagulación?", "Una superficie que recluta y concentra factores activados."],
  [PG, "¿De qué familia son varios receptores glucoproteicos funcionales de las plaquetas?", "De la familia de las integrinas."],
  [PG, "¿Qué dos tipos de gránulos citoplasmáticos tienen las plaquetas?", "Gránulos alfa y cuerpos densos delta."],
  [PG, "¿Qué molécula de adhesión expresan las membranas de gránulos alfa?", "P-selectina."],
  [PG, "¿Qué proteínas adhesivas contienen los gránulos alfa?", "Fibrinógeno y fibronectina."],
  [PG, "¿Qué factores de coagulación contienen los gránulos alfa?", "Factores V y VIII."],
  [PG, "¿Qué quimiocina de unión a heparina contienen los gránulos alfa?", "Factor plaquetario 4."],
  [PG, "¿Qué factores de crecimiento contienen los gránulos alfa?", "PDGF y TGF-beta."],
  [PG, "¿Qué nucleótidos contienen los cuerpos densos?", "ADP y ATP."],
  [PG, "¿Qué ion importante para coagulación contienen los cuerpos densos?", "Calcio ionizado."],
  [PG, "¿Qué aminas y catecolamina contienen los cuerpos densos?", "Histamina, serotonina y epinefrina."],

  [PA, "¿Qué componente de la matriz es el más importante para la adhesión plaquetaria?", "Colágeno."],
  [PA, "¿De qué dos moléculas depende principalmente la adhesión plaquetaria?", "vWF y GpIb."],
  [PA, "¿Qué le ocurre al vWF bajo estrés de cizallamiento?", "Se extiende por un cambio conformacional."],
  [PA, "¿Qué dos estructuras une simultáneamente el vWF extendido?", "Colágeno de la matriz y GpIb plaquetaria."],
  [PA, "¿Qué fija al vWF a la matriz subendotelial?", "Su interacción con colágeno."],
  [PA, "¿Qué receptor plaquetario se une con fuerza a vWF?", "GpIb."],
  [PA, "¿Qué enfermedad hemorrágica causa la deficiencia de vWF?", "Enfermedad de von Willebrand."],
  [PA, "¿Qué enfermedad hemorrágica causa la deficiencia de GpIb?", "Síndrome de Bernard-Soulier."],
  [PA, "¿Qué molécula falta en la enfermedad de von Willebrand según la figura?", "vWF."],
  [PA, "¿Qué receptor falta en el síndrome de Bernard-Soulier?", "GpIb."],

  [PV, "¿Qué desencadena la activación plaquetaria?", "La adhesión a la matriz subendotelial."],
  [PV, "¿Qué dos cambios principales definen la activación plaquetaria?", "Cambio irreversible de forma y reacción de liberación granular."],
  [PV, "¿Qué gránulos libera la plaqueta activada?", "Gránulos alfa y cuerpos densos delta."],
  [PV, "¿Qué dos componentes liberados por cuerpos densos son especialmente importantes?", "Calcio y ADP."],
  [PV, "¿Por qué es importante el calcio liberado por plaquetas?", "Es necesario para varios factores de coagulación."],
  [PV, "¿Qué hace el ADP liberado por plaquetas?", "Activa potentemente plaquetas en reposo."],
  [PV, "¿Qué eicosanoide sintetizan las plaquetas activadas?", "Tromboxano A2."],
  [PV, "¿Qué efecto tiene TxA2 sobre plaquetas vecinas?", "Las activa y favorece su agregación."],
  [PV, "¿Cómo cambia la forma plaquetaria durante la activación?", "De disco liso a esfera con prolongaciones largas y espiculadas."],
  [PV, "¿Qué ventaja funcional aporta el cambio de forma plaquetaria?", "Favorece agregación y aumenta la superficie para factores de coagulación."],
  [PV, "¿Qué fosfolípidos aumentan en la superficie de la plaqueta activada?", "Fosfolípidos con carga negativa."],
  [PV, "¿Qué se une a los fosfolípidos negativos de la plaqueta activada?", "Calcio y factores de coagulación."],
  [PV, "¿Qué receptor cambia de conformación durante la activación plaquetaria?", "GpIIb/IIIa."],
  [PV, "¿Qué permite el cambio conformacional de GpIIb/IIIa?", "La unión de fibrinógeno."],

  [AG, "¿Qué proceso sigue a la adhesión y activación plaquetarias?", "Agregación plaquetaria."],
  [AG, "¿Qué mediador plaquetario estimula tanto activación como agregación?", "TxA2."],
  [AG, "¿Cómo conecta el fibrinógeno a plaquetas adyacentes?", "Se une a receptores GpIIb/IIIa de distintas plaquetas."],
  [AG, "¿Qué deficiencia hereditaria impide la agregación plaquetaria?", "Deficiencia de GpIIb/IIIa."],
  [AG, "¿Cómo se llama la enfermedad por deficiencia de GpIIb/IIIa?", "Trombastenia de Glanzmann."],
  [AG, "¿Qué manifestación produce la trombastenia de Glanzmann?", "Sangrado con incapacidad de agregación plaquetaria."],
  [AG, "¿Qué receptor es blanco de fármacos antiagregantes por su papel central en agregación?", "GpIIb/IIIa."],
  [AG, "¿Qué receptor plaquetario activa la trombina para reforzar agregación?", "Un receptor activado por proteasa, PAR."],
  [AG, "¿Con qué mediadores coopera trombina-PAR para aumentar agregación?", "ADP y TxA2."],
  [AG, "¿Qué proceso sigue a la activación adicional de plaquetas por trombina?", "Contracción plaquetaria."],
  [AG, "¿Qué produce la contracción plaquetaria?", "Una masa de plaquetas fusionada irreversiblemente."],
  [AG, "¿Qué convierte el tapón primario en un tapón secundario definitivo?", "Trombina, contracción plaquetaria y depósito de fibrina."],
  [AG, "¿Cómo estabiliza trombina el tapón mediante fibrina?", "Convierte fibrinógeno en fibrina que cementa el tapón."],
  [AG, "¿Qué células sanguíneas pueden quedar atrapadas en el tapón secundario?", "Eritrocitos y leucocitos."],
  [AG, "¿Cómo se adhieren leucocitos a plaquetas dentro del trombo?", "Mediante P-selectina."],
  [AG, "¿Qué respuesta acompañante favorecen los leucocitos del tapón?", "La respuesta inflamatoria asociada a trombosis."],
  [AG, "¿Cómo favorece trombina la inflamación además de activar plaquetas?", "Estimula adhesión de neutrófilos y monocitos y genera productos quimiotácticos de fibrina."],

  [PE, "¿Qué sintetiza el endotelio normal para oponerse a TxA2?", "PGI2."],
  [PE, "¿Qué célula sintetiza TxA2 durante la hemostasia?", "La plaqueta activada."],
  [PE, "¿Qué efecto vascular tiene TxA2?", "Vasoconstricción potente."],
  [PE, "¿Qué mediador predomina en vasos normales: PGI2 o TxA2?", "PGI2."],
  [PE, "¿Qué efecto tiene el predominio de PGI2 en vasos normales?", "Impide la agregación plaquetaria."],
  [PE, "¿Cómo altera una lesión endotelial el equilibrio PGI2-TxA2?", "Disminuye PGI2 y favorece agregación y producción de TxA2."],
  [PE, "¿Qué enzima inhibe irreversiblemente la aspirina?", "Ciclooxigenasa."],
  [PE, "¿Por qué la aspirina bloquea permanentemente TxA2 en plaquetas?", "Porque las plaquetas no pueden sintetizar proteínas nuevas."],
  [PE, "¿Por qué el endotelio supera la inhibición de PGI2 causada por aspirina?", "Porque puede resintetizar ciclooxigenasa."],
  [PE, "¿Qué utilidad clínica deriva del bloqueo plaquetario de TxA2 por aspirina?", "Disminuir el riesgo de trombosis coronaria."],

  [CC, "¿Qué lugar ocupa la cascada de coagulación en el sistema hemostático?", "Es el tercer brazo del sistema."],
  [CC, "¿Qué tipo de reacciones forman la cascada de coagulación?", "Reacciones enzimáticas sucesivas y amplificadoras."],
  [CC, "¿Cómo se activa un proenzima de coagulación?", "Por proteólisis."],
  [CC, "¿Qué hace cada factor activado en la secuencia?", "Proteoliza el siguiente proenzima."],
  [CC, "¿Qué producto final forma la cascada después de activar trombina?", "Fibrina."],
  [CC, "¿Qué monómeros genera trombina a partir de fibrinógeno?", "Monómeros de fibrina."],
  [CC, "¿Qué forman los monómeros de fibrina al polimerizar?", "Un gel insoluble."],
  [CC, "¿Qué engloba el gel de fibrina del tapón secundario?", "Plaquetas y otras células circulantes."],
  [CC, "¿Qué factor entrecruza y estabiliza los polímeros de fibrina?", "Factor XIIIa."],
  [CC, "¿Qué activa al factor XIII?", "Trombina."],
  [CC, "¿Qué tres componentes integran cada complejo de la cascada?", "Enzima activa, sustrato proenzimático y cofactor acelerador."],
  [CC, "¿Sobre qué superficie se ensamblan los complejos de coagulación?", "Una superficie fosfolipídica de plaquetas o endotelio."],
  [CC, "¿Qué ion mantiene unidos los componentes de los complejos de coagulación?", "Calcio."],
  [CC, "¿Por qué los quelantes de calcio impiden coagulación?", "Porque el calcio es esencial para ensamblar los complejos de factores."],
  [CC, "¿Qué factores necesitan gamma-carboxilación para unirse a calcio?", "II, VII, IX y X."],
  [CC, "¿Qué aminoácido recibe grupos gamma-carboxilo en factores II, VII, IX y X?", "Residuos de ácido glutámico."],
  [CC, "¿Qué cofactor requiere la gamma-carboxilación de factores de coagulación?", "Vitamina K."],
  [CC, "¿Qué fármaco antagoniza la vitamina K según el texto?", "Coumadin."],
  [CC, "¿En qué factor convergen las vías intrínseca y extrínseca?", "Factor X."],
  [CC, "¿Qué activa experimentalmente la vía intrínseca?", "Contacto del factor XII con una superficie cargada negativamente."],
  [CC, "¿Qué factor inicia la vía intrínseca en las pruebas de laboratorio?", "Factor XII o factor de Hageman."],
  [CC, "¿Qué vía es más relevante fisiológicamente tras daño vascular?", "La vía extrínseca."],
  [CC, "¿Qué activa la vía extrínseca?", "Factor tisular expuesto en el sitio de lesión."],
  [CC, "¿Por qué la separación entre vías intrínseca y extrínseca es en parte artificial?", "Porque refleja pruebas in vitro y existen conexiones entre ambas vías."],
  [CC, "¿Qué factores pueden activar al factor IX?", "XIa o VIIa."],
  [CC, "¿Qué activador de factor IX predomina en laboratorio?", "Factor XIa."],
  [CC, "¿Qué activador de factor IX parece predominar in vivo?", "Factor VIIa."],
  [CC, "¿Qué complejo convierte factor X en Xa por la vía extrínseca?", "VIIa, factor tisular, fosfolípidos y calcio."],
  [CC, "¿Qué complejo convierte protrombina en trombina?", "Xa, factor Va, fosfolípidos y calcio."],
  [CC, "¿Qué número corresponde a la protrombina?", "Factor II."],
  [CC, "¿Qué número corresponde a la trombina?", "Factor IIa."],
  [CC, "¿Qué número corresponde al fibrinógeno?", "Factor I."],
  [CC, "¿Qué número corresponde a la fibrina activada en el esquema?", "Factor Ia."],

  [PR, "¿Qué vía evalúa principalmente el tiempo de protrombina (PT)?", "La vía extrínseca."],
  [PR, "¿Qué factores evalúa el PT?", "VII, X, II, V y fibrinógeno."],
  [PR, "¿Qué se añade primero al plasma citratado para medir PT?", "Fosfolípidos y factor tisular."],
  [PR, "¿Qué se añade después para iniciar la coagulación en el PT?", "Calcio."],
  [PR, "¿Qué hace el citrato de sodio en la muestra?", "Quela calcio y evita coagulación espontánea."],
  [PR, "¿Cuál es el tiempo normal aproximado del PT indicado en el texto?", "11 a 13 segundos."],
  [PR, "¿Qué factor dependiente de vitamina K tiene la vida media más corta?", "Factor VII."],
  [PR, "¿Cuál es la vida media aproximada del factor VII?", "Unas 7 horas."],
  [PR, "¿Qué tratamiento se monitoriza con PT?", "Antagonistas de vitamina K como coumadin."],
  [PR, "¿Qué vía evalúa principalmente el tiempo parcial de tromboplastina (PTT)?", "La vía intrínseca."],
  [PR, "¿Qué factores evalúa el PTT?", "XII, XI, IX, VIII, X, V, II y fibrinógeno."],
  [PR, "¿Qué activador se añade para iniciar el PTT?", "Un activador negativo del factor XII, como vidrio molido."],
  [PR, "¿Qué otros componentes se añaden al plasma para medir PTT?", "Fosfolípidos y después calcio."],
  [PR, "¿Cuál es el tiempo normal aproximado del PTT indicado en el texto?", "28 a 35 segundos."],
  [PR, "¿A qué anticoagulante es sensible el PTT?", "Heparina."],
  [PR, "¿Qué tratamiento se monitoriza con PTT?", "Tratamiento con heparina."],

  [TP, "¿Qué familia de receptores media muchos efectos celulares de trombina?", "Receptores activados por proteasa (PAR)."],
  [TP, "¿Qué arquitectura tienen los receptores PAR?", "Siete dominios transmembrana."],
  [TP, "¿En qué células se encuentran receptores PAR?", "Plaquetas, endotelio, monocitos y linfocitos T."],
  [TP, "¿Cómo activa trombina a un receptor PAR?", "Escinde su dominio extracelular y provoca un cambio conformacional."],
  [TP, "¿Qué proteínas activa el cambio conformacional de PAR?", "Proteínas G asociadas."],
  [TP, "¿Por qué la activación de PAR por trombina es muy potente?", "Porque es un proceso catalítico."],
  [TP, "¿Qué efecto leucocitario puede provocar trombina mediante PAR?", "Aumentar las propiedades adhesivas de leucocitos."],
  [TP, "¿Qué mediadores produce el endotelio activado por trombina según la figura?", "t-PA, NO, PGI2 y PDGF."],
  [TP, "¿Qué células activa trombina además de plaquetas y endotelio?", "Monocitos y linfocitos; también favorece adhesión de neutrófilos."],
  [TP, "¿Cómo amplifica trombina la cascada además de formar fibrina?", "Activa factores adicionales mediante bucles de retroalimentación positiva."],

  [AN, "¿Qué tres categorías generales limitan naturalmente la coagulación?", "Antitrombinas, proteínas C/S y TFPI."],
  [AN, "¿Qué serinproteasas inhibe antitrombina III además de trombina?", "IXa, Xa, XIa y XIIa."],
  [AN, "¿Qué activa funcionalmente a antitrombina III?", "Su unión a moléculas endoteliales tipo heparina."],
  [AN, "¿Qué fundamento explica la utilidad clínica de heparina?", "Potencia la inactivación de trombina y otras proteasas por antitrombina III."],
  [AN, "¿De qué vitamina dependen proteínas C y S?", "Vitamina K."],
  [AN, "¿Cómo actúan juntas proteínas C y S?", "Proteína S funciona como cofactor de proteína C activada."],
  [AN, "¿Qué cofactores procoagulantes inactiva el complejo C/S?", "Va y VIIIa."],
  [AN, "¿Qué complejo endotelial activa proteína C?", "Trombina unida a trombomodulina."],
  [AN, "¿Qué factor activado inactiva TFPI?", "Factor Xa."],
  [AN, "¿Qué complejo iniciador inactiva TFPI?", "Factor tisular-factor VIIa."],
  [AN, "¿Cómo se restringe espacialmente la activación de factores?", "Al limitarla a superficies fosfolipídicas expuestas."],
  [AN, "¿Cómo convierte trombomodulina a trombina en anticoagulante?", "Redirige su actividad hacia la activación de proteína C."],

  [FI, "¿Qué enzima realiza principalmente la fibrinólisis?", "Plasmina."],
  [FI, "¿Qué dos efectos tiene plasmina sobre fibrina?", "La degrada e interfiere con su polimerización."],
  [FI, "¿Qué son los FSP?", "Productos de escisión o degradación de fibrina."],
  [FI, "¿Qué efecto anticoagulante tienen los productos de degradación de fibrina?", "Un efecto anticoagulante débil."],
  [FI, "¿Qué producto de fibrina es especialmente útil como marcador de trombosis?", "Dímero D."],
  [FI, "¿En qué estados trombóticos pueden elevarse los dímeros D?", "CID, trombosis venosa profunda y tromboembolismo pulmonar."],
  [FI, "¿De qué precursor se genera plasmina?", "Plasminógeno."],
  [FI, "¿Qué naturaleza tiene el plasminógeno circulante?", "Precursor plasmático inactivo."],
  [FI, "¿Qué factor de coagulación puede activar plasminógeno?", "Factor XII."],
  [FI, "¿Cuál es el activador más importante del plasminógeno?", "t-PA."],
  [FI, "¿Qué células sintetizan principalmente t-PA?", "Células endoteliales."],
  [FI, "¿Cuándo es más activo t-PA?", "Cuando está unido a fibrina."],
  [FI, "¿Qué ventaja produce la afinidad de t-PA por fibrina?", "Limita su acción a sitios de trombosis reciente."],
  [FI, "¿Qué otro activador fisiológico del plasminógeno existe en plasma y tejidos?", "Activador tipo uroquinasa, u-PA."],
  [FI, "¿Dónde puede activar plasmina el u-PA?", "En la fase líquida."],
  [FI, "¿Qué producto bacteriano puede activar plasminógeno?", "Estreptoquinasa."],
  [FI, "¿Qué uso clínico tiene estreptoquinasa?", "Lisis de coágulos en algunas enfermedades trombóticas."],
  [FI, "¿Qué inhibidor neutraliza rápidamente plasmina libre?", "Alfa-2-antiplasmina."],
  [FI, "¿Por qué se inactiva rápidamente la plasmina libre?", "Para evitar lisis indiscriminada de trombos por todo el cuerpo."],
  [FI, "¿Qué bloquean los inhibidores del activador del plasminógeno?", "La fibrinólisis."],
  [FI, "¿Qué efecto global tienen los PAI sobre coagulación?", "Efecto procoagulante."],
  [FI, "¿Qué citocina aumenta especialmente la producción de PAI?", "Interferón gamma."],
  [FI, "¿A qué complicación de inflamación grave puede contribuir el aumento de PAI?", "Trombosis intravascular."],

  [VT, "¿Cuáles son los tres componentes de la tríada de Virchow?", "Lesión endotelial, flujo anormal e hipercoagulabilidad."],
  [VT, "¿Qué alteraciones del flujo incluye la tríada de Virchow?", "Estasis o turbulencia."],
  [VT, "¿Cuál es el factor más importante de la tríada de Virchow según la figura?", "Integridad o lesión endotelial."],
  [VT, "¿En qué territorios es especialmente importante la lesión endotelial para trombosis?", "Corazón y arterias."],
  [VT, "¿Por qué el flujo alto normalmente dificulta trombosis arterial o cardíaca?", "Impide adhesión plaquetaria y diluye factores de coagulación."],
  [VT, "¿Dónde pueden formarse trombos murales tras infarto?", "En las cámaras cardíacas."],
  [VT, "¿Qué lesión aterosclerótica favorece trombosis arterial?", "Placa ulcerada."],
  [VT, "¿Qué lesiones vasculares traumáticas o inflamatorias favorecen trombosis?", "Sitios de lesión vascular y vasculitis."],
  [VT, "¿Qué tres efectos protrombóticos produce la pérdida abierta de endotelio?", "Expone matriz, libera factor tisular y reduce PGI2 y activadores del plasminógeno."],
  [VT, "¿Es necesaria la denudación endotelial para favorecer trombosis?", "No; basta una disfunción del equilibrio hemostático endotelial."],
  [VT, "¿Qué produce en exceso el endotelio disfuncional?", "Moléculas de adhesión plaquetaria, factor tisular y PAI."],
  [VT, "¿Qué produce en menor cantidad el endotelio disfuncional?", "Trombomodulina, PGI2 y t-PA."],
  [VT, "¿Qué agresiones pueden causar disfunción endotelial?", "Hipertensión, flujo turbulento, productos bacterianos, radiación, alteraciones metabólicas y humo."],
  [VT, "¿Qué alteraciones metabólicas se citan como causas de disfunción endotelial?", "Homocistinuria e hipercolesterolemia."],

  [FA, "¿Cómo favorece turbulencia la trombosis arterial y cardíaca?", "Lesiona o disfunciona endotelio y crea contracorrientes y bolsas de estasis."],
  [FA, "¿Cuál es el principal papel de la estasis en trombosis?", "Es un factor mayor de trombosis venosa."],
  [FA, "¿Dónde circulan normalmente plaquetas y células en flujo laminar?", "En el centro de la luz vascular."],
  [FA, "¿Qué separa a las células sanguíneas del endotelio en flujo laminar?", "Una capa periférica de plasma de movimiento más lento."],
  [FA, "¿Qué efecto tienen estasis y turbulencia sobre el endotelio?", "Activación endotelial y aumento de actividad procoagulante."],
  [FA, "¿Cómo influye el flujo en la expresión génica endotelial?", "Cambios inducidos por flujo aumentan actividad procoagulante."],
  [FA, "¿Cómo favorece estasis el contacto celular con endotelio?", "Permite que plaquetas y leucocitos alcancen la pared durante flujo lento."],
  [FA, "¿Cómo afecta estasis la eliminación de factores activados?", "Retrasa su lavado."],
  [FA, "¿Cómo afecta estasis la llegada de inhibidores de coagulación?", "Impide o reduce su afluencia."],
  [FA, "¿Cómo favorece una placa aterosclerótica ulcerada la trombosis por dos mecanismos?", "Expone matriz subendotelial y causa turbulencia."],
  [FA, "¿Por qué un aneurisma favorece trombosis?", "Crea estasis local."],
  [FA, "¿Cómo favorece un infarto agudo trombos murales?", "Genera miocardio focalmente no contráctil y estasis local."],
  [FA, "¿Cómo favorece un infarto antiguo trombos murales?", "El remodelado puede formar un aneurisma con estasis."],
  [FA, "¿Qué combinación hace a la aurícula izquierda un sitio de estasis profunda?", "Estenosis mitral, dilatación auricular y fibrilación auricular."],
  [FA, "¿Cómo favorece policitemia la trombosis?", "La hiperviscosidad aumenta resistencia al flujo y estasis de vasos pequeños."],
  [FA, "¿Cómo favorece anemia falciforme la trombosis?", "Eritrocitos deformados ocluyen vasos y generan estasis."],
]

export const articuloHemostasiaFlashcards: Flashcard[] =
  seeds.map(([subtopic, front, back], index) => ({
    id: `histo-art-hemostasia-${String(index + 1).padStart(4, "0")}`,
    subject: "Histología",
    book: "Robbins Basic Pathology, 9.ª ed.",
    chapter: CHAPTER,
    topic: "Hemostasia y trombosis",
    subtopic,
    front,
    back,
    tags: ["Artículo", "Hemostasia", subtopic]
  }))
