import type { Flashcard } from "./cards"

type CardPair = readonly [front: string, back: string]

type CardGroup = {
  topic: string
  subtopic: string
  cards: readonly CardPair[]
}

const groups: CardGroup[] = [
  {
    topic: "Fundamentos del sistema tegumentario",
    subtopic: "Fundamentos tegumentarios",
    cards: [
      ["¿Qué estructuras constituyen el sistema tegumentario?", "La piel y sus derivados."],
      ["¿Qué otros nombres recibe la piel?", "Cutis o tegumento."],
      ["¿Qué proporción de la masa corporal total constituye la piel?", "Aproximadamente 15-20%."],
      ["¿Cuáles son los dos estratos principales de la piel?", "Epidermis y dermis."],
      ["¿Qué tipo de epitelio forma la epidermis?", "Epitelio plano estratificado queratinizado."],
      ["¿De qué capa germinal deriva la epidermis?", "Del ectodermo."],
      ["¿Qué tejido forma la dermis?", "Tejido conjuntivo denso."],
      ["¿De qué capa germinal deriva la dermis?", "Del mesodermo."],
      ["¿Qué funciones mecánicas aporta la dermis?", "Sostén, resistencia y espesor."],
      ["¿Dónde se encuentra la hipodermis respecto de la dermis?", "A mayor profundidad."],
      ["¿A qué estructura anatómica equivale la hipodermis?", "A la fascia subcutánea."],
      ["¿Cómo se organiza el tejido adiposo de la hipodermis?", "En lobulillos separados por tabiques de tejido conjuntivo."],
      ["¿Qué anexos cutáneos enumera el texto?", "Folículos pilosos y pelo, glándulas sudoríparas, glándulas sebáceas, uñas y glándulas mamarias."],
      ["¿Qué tres tipos de agentes bloquea la función de barrera de la piel?", "Agentes físicos, químicos y biológicos."],
      ["¿Qué tres barreras específicas proporciona la piel?", "Mecánica, de permeabilidad y ultravioleta."],
      ["¿Cómo participa la piel en la inmunidad?", "Procesa antígenos y transmite información inmunitaria a células efectoras."],
      ["¿Cómo participa la piel en la homeostasis?", "Regula la temperatura corporal y la pérdida de agua."],
      ["¿Qué información transmite la piel al sistema nervioso?", "Información sensitiva del medio externo."],
      ["¿Qué actividad endocrina destacada realiza la piel?", "Convierte precursores en vitamina D activa."],
      ["¿Cómo interviene la piel en la excreción?", "Mediante secreciones sudoríparas, sebáceas y apocrinas."],
      ["¿Qué propiedad cutánea permite administrar fármacos con parches?", "La absorción de sustancias liposolubles."],
      ["Mencione un fármaco o sustancia administrable por vía transdérmica según el texto.", "Nicotina, hormonas esteroideas o medicamentos contra el mareo."],
      ["¿Qué mantiene el espesor normal de una epidermis que crece continuamente?", "La descamación."],
      ["¿Cuál es el intervalo aproximado del espesor total de la piel?", "Desde menos de 1 mm hasta más de 5 mm."],
      ["¿Qué determina la clasificación histológica de piel gruesa o delgada?", "El espesor de la epidermis, no el espesor total de la piel."],
    ]
  },
  {
    topic: "Fundamentos del sistema tegumentario",
    subtopic: "Piel gruesa y delgada",
    cards: [
      ["¿Dónde se encuentra la piel gruesa?", "En las palmas de las manos y las plantas de los pies."],
      ["¿La piel gruesa contiene folículos pilosos?", "No; es piel sin pelo."],
      ["¿Qué condición mecánica explica la epidermis gruesa de palmas y plantas?", "La fricción intensa."],
      ["¿Cómo es la epidermis de la piel delgada?", "Más delgada que la de palmas y plantas."],
      ["¿La piel delgada suele contener folículos pilosos?", "Sí, en casi toda su extensión."],
      ["¿Dónde se encuentra anatómicamente la piel total más gruesa?", "En la parte superior del dorso, por el gran espesor de la dermis."],
      ["¿La epidermis del dorso corresponde a piel gruesa histológica?", "No; es comparable a la epidermis de la piel delgada."],
      ["¿Qué sitio presenta una piel total especialmente delgada?", "El párpado."],
      ["¿Cuál es la diferencia epidérmica principal entre piel gruesa y delgada?", "El espesor del estrato córneo."],
      ["¿Qué estrato epidérmico solo se observa bien en piel gruesa?", "El estrato lúcido."],
      ["¿Qué estructuras epidérmicas forman las huellas dactilares y plantares?", "Las crestas interpapilares dispuestas en patrones únicos."],
      ["¿Cómo se llama el estudio de los patrones de crestas cutáneas?", "Dermatoglifia."],
      ["¿Por qué la piel gruesa produce más células córneas por unidad de tiempo?", "Porque su superficie basal y su estrato germinal son más extensos."],
      ["¿Dónde son especialmente prominentes las crestas y papilas dérmicas?", "En las superficies palmares y plantares."],
    ]
  },
  {
    topic: "Estratos de la piel",
    subtopic: "Estratos epidérmicos",
    cards: [
      ["¿Cuántos estratos bien definidos tiene la epidermis habitual?", "Cuatro."],
      ["¿Cuántos estratos tiene la epidermis de la piel gruesa?", "Cinco."],
      ["Enumere los estratos epidérmicos de profundo a superficial.", "Basal, espinoso, granuloso, lúcido y córneo."],
      ["¿Qué estrato también se denomina germinal?", "El estrato basal."],
      ["¿Por qué el estrato basal se denomina germinal?", "Porque contiene células madre con actividad mitótica."],
      ["¿Qué estrato también se denomina capa espinosa?", "El estrato espinoso."],
      ["¿Qué rasgo da nombre al estrato espinoso?", "Las proyecciones cortas entre células contiguas."],
      ["¿Qué estrato contiene abundantes gránulos intensamente teñidos?", "El estrato granuloso."],
      ["¿A qué tipo de piel se limita el estrato lúcido?", "A la piel gruesa."],
      ["¿De qué estrato se considera una subdivisión el estrato lúcido?", "Del estrato córneo."],
      ["¿Qué células forman el estrato córneo?", "Células queratinizadas o cornificadas."],
      ["¿Qué forma especial de muerte celular representa la diferenciación epidérmica terminal?", "Una forma especializada de apoptosis."],
      ["¿En qué estrato aparece morfología nuclear apoptótica típica?", "En el estrato granuloso."],
      ["¿Qué proceso apoptótico habitual no ocurre durante la cornificación?", "La fragmentación celular."],
      ["¿Qué sucede finalmente con las células cornificadas?", "Se descaman de la superficie cutánea."],
    ]
  },
  {
    topic: "Estratos de la piel",
    subtopic: "Estrato basal",
    cards: [
      ["¿Cuántas capas celulares forman el estrato basal?", "Una sola capa."],
      ["¿Sobre qué estructura se apoya el estrato basal?", "Sobre la membrana basal."],
      ["¿Qué células origina el estrato basal por mitosis?", "Nuevos queratinocitos."],
      ["¿Qué forma tienen las células basales?", "Cúbica o cilíndrica baja."],
      ["¿Por qué los núcleos del estrato basal están muy juntos?", "Porque las células tienen poco citoplasma."],
      ["¿Qué explica la intensa basofilia del estrato basal?", "Núcleos apiñados y citoplasma basófilo."],
      ["¿De dónde procede la melanina de los queratinocitos basales?", "De melanocitos vecinos."],
      ["¿Qué unión conecta las células basales entre sí y con queratinocitos?", "Desmosomas."],
      ["¿Qué unión fija las células basales a la membrana basal?", "Hemidesmosomas."],
      ["¿Qué ocurre con los queratinocitos recién formados en el estrato basal?", "Migran al estrato espinoso e inician su ascenso."],
      ["¿Qué filamentos empiezan a sintetizar los queratinocitos basales?", "Filamentos intermedios de queratina."],
      ["¿Qué queratinas marcan a las células basales según la figura 15-7?", "Queratinas 5 y 14."],
      ["¿Qué marcador nuclear se asocia con células madre basales según la figura 15-7?", "p63."],
      ["¿Qué integrina se menciona como marcador de células basales?", "Integrina α6β1."],
    ]
  },
  {
    topic: "Estratos de la piel",
    subtopic: "Estrato espinoso",
    cards: [
      ["¿Qué estructura produce el aspecto espinoso de los queratinocitos?", "Evaginaciones citoplasmáticas unidas por desmosomas."],
      ["¿Cómo se observan en conjunto las uniones del estrato espinoso?", "Como puentes intercelulares."],
      ["¿Qué síntesis continúa mientras el queratinocito atraviesa el estrato espinoso?", "La síntesis de filamentos de queratina."],
      ["¿Cómo se llaman los haces de queratina visibles con microscopía óptica?", "Tonofibrillas."],
      ["¿Por qué el citoplasma del queratinocito se vuelve eosinófilo en el estrato espinoso?", "Por la acumulación de tonofibrillas."],
      ["¿Qué orgánulos aparecen en la parte superior del estrato espinoso?", "Gránulos de queratohialina y cuerpos laminares."],
      ["¿Qué queratinas se expresan durante la diferenciación espinosa?", "Queratinas 1 y 10."],
      ["¿Qué función mecánica tienen los desmosomas del estrato espinoso?", "Mantener unidos los queratinocitos frente al estrés."],
    ]
  },
  {
    topic: "Estratos de la piel",
    subtopic: "Estrato granuloso",
    cards: [
      ["¿Cuál es la capa más superficial de la porción no queratinizada de la epidermis?", "El estrato granuloso."],
      ["¿Qué espesor celular tiene el estrato granuloso?", "De una a tres células."],
      ["¿Qué gránulos caracterizan al estrato granuloso?", "Gránulos de queratohialina."],
      ["¿Cómo se reconocen los gránulos de queratohialina con H&E?", "Por su intensa basofilia."],
      ["¿Qué aminoácidos abundan en las proteínas de los gránulos de queratohialina?", "Cistina e histidina."],
      ["¿De qué proteína son precursoras esas proteínas granulares?", "De la filagrina."],
      ["¿Qué función tiene la filagrina?", "Aglomera filamentos de queratina."],
      ["¿Qué otra proteína de los gránulos promueve la agregación de queratina?", "Tricohialina."],
      ["¿Qué proceso inicia la liberación de filagrina y tricohialina?", "La conversión de células granulares en cornificadas."],
      ["¿Cuánto tarda la queratinización al pasar del granuloso al córneo?", "Aproximadamente 2-6 horas."],
      ["¿Qué estructuras celulares se desintegran durante la cornificación?", "El núcleo y los demás orgánulos."],
      ["¿Qué sucede con la membrana plasmática durante la cornificación?", "Se engrosa."],
    ]
  },
  {
    topic: "Estratos de la piel",
    subtopic: "Estratos lúcido y córneo",
    cards: [
      ["¿Cómo se observa el estrato lúcido con microscopía óptica?", "Refringente y poco teñido."],
      ["¿Qué tipo de células contiene el estrato lúcido?", "Células eosinófilas con queratinización muy avanzada."],
      ["¿Qué ocurre con el núcleo y los orgánulos en el estrato lúcido?", "Se destruyen y desaparecen."],
      ["¿Cómo son las células del estrato córneo?", "Planas, anucleadas y desecadas."],
      ["¿De qué están llenas las células del estrato córneo?", "De filamentos de queratina."],
      ["¿Qué células son las más diferenciadas de la epidermis?", "Las del estrato córneo."],
      ["¿Qué capa externa recubre las células córneas profundas?", "Una capa extracelular de lípidos."],
      ["¿Qué función cumple esa capa lipídica extracelular?", "Forma el componente principal de la barrera contra el agua."],
      ["¿Qué estrato epidérmico presenta el espesor más variable?", "El estrato córneo."],
      ["¿Qué ocurre con el estrato córneo en zonas de fricción intensa?", "Se engruesa y forma callos."],
      ["¿Cuántas capas celulares tiene en promedio el estrato córneo humano?", "Aproximadamente 16-20."],
      ["¿Qué pH presenta la superficie del estrato córneo?", "Aproximadamente 4.5-6."],
      ["¿Cómo cambia el pH desde el granuloso hacia la superficie?", "Desciende de casi neutro a ácido."],
    ]
  },
  {
    topic: "Dermis e hipodermis",
    subtopic: "Unión dermoepidérmica",
    cards: [
      ["¿Cómo es el contorno de la unión dermoepidérmica?", "Muy irregular, salvo en la piel más delgada."],
      ["¿Qué son las papilas dérmicas?", "Evaginaciones digitiformes de tejido conjuntivo hacia la epidermis."],
      ["¿Qué son las crestas epidérmicas o interpapilares?", "Proyecciones epidérmicas que se hunden en la dermis."],
      ["¿Qué aspecto tienen las papilas dérmicas en un corte paralelo a la superficie?", "Islotes circulares de tejido conjuntivo dentro del epitelio."],
      ["¿Qué ocurre con papilas y crestas en zonas de gran estrés mecánico?", "Se hacen más largas, profundas y juntas."],
      ["¿Qué ventaja aporta el entrelazamiento de papilas y crestas?", "Aumenta la interfaz y fortalece la adhesión."],
      ["¿Qué estructuras aumentan la superficie basal de las células epidérmicas?", "Protuberancias citoplasmáticas irregulares."],
      ["¿Qué filamentos unen los hemidesmosomas a la membrana basal?", "Filamentos intermedios."],
      ["¿Qué filamentos conectan las adhesiones focales con la membrana basal?", "Filamentos de actina."],
    ]
  },
  {
    topic: "Dermis e hipodermis",
    subtopic: "Dermis papilar y reticular",
    cards: [
      ["¿Cuáles son las dos capas de la dermis?", "Papilar y reticular."],
      ["¿Dónde se encuentra la dermis papilar?", "Justo debajo de la epidermis."],
      ["¿Qué tejido forma la dermis papilar?", "Tejido conjuntivo laxo."],
      ["¿Qué tipos de colágeno predominan en la dermis papilar?", "Tipos I y III."],
      ["¿Cómo son las fibras colágenas de la dermis papilar?", "Delgadas."],
      ["¿Cómo son las fibras elásticas de la dermis papilar?", "Filiformes y organizadas en una red irregular."],
      ["¿Qué estructuras vasculares contiene la dermis papilar?", "Vasos que irrigan la epidermis sin penetrarla."],
      ["¿Dónde se concentran vasos y terminaciones sensitivas superficiales?", "En las papilas dérmicas."],
      ["¿Dónde se encuentra la dermis reticular?", "Profunda a la dermis papilar."],
      ["¿Cuál capa dérmica es más gruesa?", "La dermis reticular."],
      ["¿Cuál capa dérmica contiene menos células?", "La dermis reticular."],
      ["¿Qué colágeno predomina en la dermis reticular?", "Colágeno tipo I."],
      ["¿Cómo son los haces de colágeno de la dermis reticular?", "Gruesos e irregulares."],
      ["¿Cómo son las fibras elásticas de la dermis reticular?", "Más gruesas que las de la dermis papilar."],
      ["¿Qué son las líneas de Langer?", "Líneas regulares de tensión determinadas por la orientación de colágeno y fibras elásticas."],
      ["¿Cómo deben orientarse las incisiones respecto de las líneas de Langer?", "Paralelas a ellas."],
      ["¿Qué beneficio tiene una incisión paralela a las líneas de Langer?", "Produce cicatrices menos prominentes."],
      ["¿Dónde forma el músculo liso una red laxa en la dermis reticular?", "Aréolas, pene, escroto y periné."],
    ]
  },
  {
    topic: "Dermis e hipodermis",
    subtopic: "Hipodermis y músculos cutáneos",
    cards: [
      ["¿Qué es el panículo adiposo?", "Una capa de tejido adiposo profunda a la dermis reticular."],
      ["¿Qué funciones cumple el panículo adiposo?", "Reserva energética y aislamiento térmico."],
      ["¿Qué tejidos constituyen la hipodermis?", "Panículo adiposo y tejido conjuntivo laxo asociado."],
      ["¿Dónde se originan los músculos erectores del pelo?", "En la hipodermis o dermis profunda."],
      ["¿Qué conecta el músculo erector del pelo?", "El folículo piloso profundo con la dermis superficial."],
      ["¿Qué produce su contracción en humanos?", "Erección del pelo y piel de gallina."],
      ["¿Qué es el panículo carnoso?", "Una capa de músculo estriado bajo la fascia subcutánea."],
      ["¿Dónde persiste bien definido el panículo carnoso humano?", "Cuello, cara y cuero cabelludo."],
      ["¿Qué músculos humanos derivan del panículo carnoso?", "Platisma y músculos de la expresión facial."],
    ]
  },
  {
    topic: "Células de la epidermis",
    subtopic: "Tipos celulares epidérmicos",
    cards: [
      ["¿Cuáles son los cuatro tipos celulares de la epidermis?", "Queratinocitos, melanocitos, células de Langerhans y células de Merkel."],
      ["¿Qué porcentaje aproximado de células epidérmicas son queratinocitos?", "85%."],
      ["¿Qué porcentaje aproximado son melanocitos?", "5%."],
      ["¿Qué porcentaje aproximado son células de Langerhans?", "2-5%."],
      ["¿Qué porcentaje aproximado son células de Merkel según el texto?", "6-10%."],
      ["¿Cuál es la función principal de los queratinocitos?", "Separar el organismo del medio externo."],
      ["¿Cuál es la función principal de los melanocitos?", "Producir pigmento."],
      ["¿Cuál es la función principal de las células de Langerhans?", "Presentar antígenos."],
      ["¿Cuál es la función principal de las células de Merkel?", "Actuar como mecanorreceptores."],
    ]
  },
  {
    topic: "Queratinocitos y barrera epidérmica",
    subtopic: "Diferenciación de queratinocitos",
    cards: [
      ["¿Dónde se originan los queratinocitos?", "En el estrato basal."],
      ["¿Cuáles son las dos actividades esenciales del queratinocito?", "Producir queratinas y formar la barrera epidérmica contra el agua."],
      ["¿Qué son las citoqueratinas?", "Proteínas estructurales que forman filamentos intermedios."],
      ["¿Qué proporción del queratinocito maduro puede corresponder a queratina?", "Casi 85%."],
      ["¿Qué diámetro tienen los filamentos intermedios de queratina basales?", "7-9 nm."],
      ["¿Por qué es basófilo el queratinocito inmaduro?", "Por sus abundantes ribosomas libres."],
      ["¿Cómo se denominan con frecuencia los filamentos intermedios de queratina?", "Tonofilamentos."],
      ["¿Qué proteínas de queratohialina agregan tonofilamentos en tonofibrillas?", "Filagrina y tricohialina."],
      ["¿Qué marcador indica el inicio de la fase final de apoptosis queratinocítica?", "La expresión de filagrina y aparición de gránulos de queratohialina."],
      ["¿Qué tipo de queratina forma la epidermis?", "Queratina blanda."],
      ["¿Qué tipo de queratina forma pelo y uñas?", "Queratina dura."],
      ["¿Cuáles son los tres procesos que mantienen el equilibrio epidérmico?", "Mitosis basal, diferenciación/muerte programada y exfoliación."],
      ["¿Cuánto tarda el tránsito por los estratos espinoso y granuloso?", "Unos 31 días."],
      ["¿Cuánto tarda el tránsito por el estrato córneo?", "Unos 14 días."],
      ["¿Cuánto dura aproximadamente la renovación epidérmica total?", "Unos 47 días."],
      ["¿Cada cuánto se produce y exfolia una capa córnea?", "Aproximadamente cada 22.4 horas."],
      ["¿Cuánto tarda la renovación epidérmica en psoriasis?", "Aproximadamente 8-10 días."],
      ["¿Qué cambios epidérmicos acompañan la psoriasis?", "Mayor grosor y menor muerte celular."],
      ["¿Cómo suele presentarse clínicamente la psoriasis?", "Placas rojas elevadas y pruriginosas con escamas blanco-plateadas."],
    ]
  },
  {
    topic: "Queratinocitos y barrera epidérmica",
    subtopic: "Descamación y gradiente de pH",
    cards: [
      ["¿Qué proceso elimina queratinocitos de la superficie?", "La descamación o exfoliación."],
      ["¿Qué uniones deben degradarse para permitir la descamación?", "Los desmosomas."],
      ["¿Qué enzimas escinden proteínas desmosómicas según el pH?", "Las serina-peptidasas relacionadas con calicreína (KLK)."],
      ["¿Qué KLK menciona el texto?", "KLK5, KLK7 y KLK14."],
      ["¿Qué inhibidor bloquea las KLK a pH neutro?", "LEKTI."],
      ["¿Qué significa LEKTI?", "Inhibidor linfoepitelial de tipo Kazal."],
      ["¿Qué ocurre con LEKTI y KLK al acidificarse el estrato córneo?", "Se disocian y las KLK quedan activas."],
      ["¿Qué efecto tienen las KLK activas en capas superficiales?", "Degradan desmosomas y liberan corneocitos."],
      ["¿Qué gen codifica LEKTI?", "SPINK5."],
      ["¿Qué síndrome causa un SPINK5 defectuoso?", "Síndrome de Netherton."],
      ["¿Qué defecto funcional caracteriza al síndrome de Netherton?", "Disminución de la barrera cutánea."],
      ["¿Qué dos manifestaciones cutáneas menciona el texto para Netherton?", "Eritrodermia y descamación."],
    ]
  },
  {
    topic: "Queratinocitos y barrera epidérmica",
    subtopic: "Cuerpos laminares",
    cards: [
      ["¿Qué son los cuerpos laminares?", "Vesículas epidérmicas membranosas con lípidos y enzimas."],
      ["¿En qué células aparecen los cuerpos laminares?", "En queratinocitos espinosos y granulosos."],
      ["¿Dónde se forman los cuerpos laminares?", "En el aparato de Golgi."],
      ["¿Qué forma presentan los cuerpos laminares?", "Tubular u ovoide."],
      ["¿En qué epitelio son exclusivos los cuerpos laminares?", "En la epidermis de mamíferos."],
      ["Mencione tres lípidos o precursores contenidos en cuerpos laminares.", "Glucoesfingolípidos, fosfolípidos y ceramidas."],
      ["¿Dónde liberan su contenido los cuerpos laminares?", "Entre el estrato granuloso y el córneo."],
      ["¿Cómo liberan su contenido?", "Por exocitosis."],
      ["¿Qué estructura forma la organización de sus láminas lipídicas?", "La barrera epidérmica intercelular contra el agua."],
      ["¿Qué funciones adicionales tienen los cuerpos laminares?", "Cornificación, descamación y defensa antimicrobiana."],
      ["¿Qué ocurre con la permeabilidad al agua en deficiencia de ácidos grasos esenciales?", "Aumenta."],
      ["¿Qué consecuencia grave puede causar la destrucción extensa de la barrera, como en quemaduras?", "Deshidratación potencialmente mortal."],
    ]
  },
  {
    topic: "Queratinocitos y barrera epidérmica",
    subtopic: "Envolturas celular y lipídica",
    cards: [
      ["¿Cuáles son los dos elementos estructurales de la barrera contra el agua?", "Envoltura celular y envoltura lipídica."],
      ["¿Dónde se localiza la envoltura celular?", "En la cara interna de la membrana plasmática."],
      ["¿Qué espesor tiene la envoltura celular?", "Aproximadamente 15 nm."],
      ["¿Qué función principal tiene la envoltura celular?", "Aportar resistencia mecánica."],
      ["¿En qué sitios aumenta el espesor de la envoltura celular?", "Labio, palma y planta."],
      ["¿Qué enlaces forman la envoltura celular?", "Enlaces cruzados entre proteínas ricas en prolina."],
      ["¿Cuál es la principal proteína estructural de la envoltura celular?", "Loricrina."],
      ["¿Qué porcentaje aproximado de su masa proteica representa la loricrina?", "Casi 80%."],
      ["Mencione tres proteínas adicionales de la envoltura celular.", "Involucrina, filagrina y desmoplaquina."],
      ["¿Dónde se localiza la envoltura lipídica?", "En la superficie externa de la membrana plasmática."],
      ["¿Qué espesor tiene la envoltura lipídica?", "Aproximadamente 5 nm."],
      ["¿Qué lípidos predominan en la envoltura lipídica?", "Ceramidas, colesterol y ácidos grasos libres."],
      ["¿Cuál es su componente lipídico más importante según el texto?", "La capa monomolecular de acilglucosilceramida."],
      ["¿Qué efecto superficial produce la acilglucosilceramida?", "Una cubierta impermeable similar al teflón."],
      ["¿Qué funciones de señalización tienen las ceramidas?", "Favorecen diferenciación y apoptosis y reducen proliferación."],
    ]
  },
  {
    topic: "Células de la epidermis",
    subtopic: "Melanocitos y melanogénesis",
    cards: [
      ["¿De dónde derivan los melanocitos?", "De la cresta neural."],
      ["¿En qué estrato se ubican los melanocitos epidérmicos?", "En el estrato basal."],
      ["¿Qué es la unidad melanoepidérmica?", "La asociación funcional de un melanocito con un grupo de queratinocitos."],
      ["¿Con cuántos queratinocitos se asocia aproximadamente un melanocito?", "Con cerca de 36."],
      ["¿La relación melanocitos/queratinocitos cambia entre grupos étnicos?", "No; es esencialmente constante."],
      ["¿Qué factores modifican esa relación?", "La edad y factores ambientales como la exposición solar."],
      ["¿Dónde residen melanoblastos indiferenciados en adultos?", "En la protuberancia folicular."],
      ["¿Qué factor de transcripción activa MITF?", "Pax3."],
      ["¿Qué función tiene MITF?", "Es decisivo para desarrollo y diferenciación de melanocitos."],
      ["¿Qué forma tiene el melanocito epidérmico?", "Dendrítica."],
      ["¿Los melanocitos forman desmosomas con queratinocitos?", "No."],
      ["¿Cómo se observa un melanocito en H&E?", "Núcleo alargado rodeado de citoplasma claro."],
      ["¿Cuál es la función principal de la melanina?", "Proteger el ADN frente a radiación ultravioleta."],
      ["¿De qué aminoácido se sintetiza la melanina?", "De tirosina."],
      ["¿Qué enzima convierte tirosina en DOPA?", "Tirosinasa."],
      ["¿Dónde comienzan las reacciones de síntesis de melanina?", "En premelanosomas."],
      ["¿De qué orgánulo derivan los premelanosomas?", "Del aparato de Golgi."],
      ["¿Qué hormona estimula la síntesis de melanina?", "MSH."],
      ["¿Qué receptor melanocítico se une a MSH?", "MC1R."],
      ["¿Qué efecto tiene la señal de MSH sobre la tirosinasa?", "Aumenta su actividad."],
      ["¿Cómo se observa un melanosoma maduro con MET?", "Como un gránulo electrodenso."],
      ["¿Dónde se concentran los premelanosomas?", "Cerca del aparato de Golgi."],
      ["¿Dónde se acumulan los melanosomas maduros?", "En los extremos de las prolongaciones melanocíticas."],
      ["¿Qué es la donación pigmentaria?", "La transferencia de melanosomas del melanocito al queratinocito."],
      ["¿Qué mecanismo utiliza el queratinocito para recibir melanosomas?", "Fagocita el extremo de la prolongación melanocítica."],
      ["¿Por qué la donación pigmentaria es secreción citocrina?", "Porque transfiere melanosomas junto con algo de citoplasma."],
      ["¿Dónde se distribuyen los melanosomas dentro del queratinocito?", "Sobre el núcleo, formando una sombrilla protectora."],
      ["¿Cómo se degradan los melanosomas?", "Por macroautofagia."],
      ["¿Cómo es la degradación de melanina en piel oscura?", "Más lenta."],
      ["¿Cómo es la degradación de melanina en piel clara?", "Más rápida."],
    ]
  },
  {
    topic: "Células de la epidermis",
    subtopic: "Color de la piel",
    cards: [
      ["¿Cuál es el principal determinante del color de la piel?", "El contenido y destino de la melanina."],
      ["¿Qué diferencia pigmentaria principal existe entre piel clara y oscura?", "La velocidad de degradación y distribución de melanosomas."],
      ["¿Hasta qué estrato pueden persistir melanosomas en piel oscura?", "Hasta el estrato córneo."],
      ["¿Qué es la eumelanina?", "Pigmento café a negro."],
      ["¿Qué es la feomelanina?", "Pigmento rojo amarillento."],
      ["¿Qué efecto tiene la radiación ultravioleta sobre melanocitos y melanina?", "Aumenta los melanocitos y acelera la producción de melanina."],
      ["¿Qué trastorno endocrino puede aumentar la pigmentación cutánea?", "Enfermedad de Addison."],
      ["¿Qué defecto enzimático causa el albinismo descrito?", "Falta de tirosinasa."],
      ["¿Qué producen los melanocitos albinos?", "Premelanosomas, pero no melanina."],
      ["¿Qué genes relaciona el texto con el encanecimiento?", "Bcl2 y MITF."],
      ["¿Qué función tiene Bcl2 en células madre melanocíticas?", "Mantener su población y evitar apoptosis."],
      ["¿Qué ocurre si disminuye la expresión de Bcl2?", "Mueren melanoblastos y disminuyen melanocitos."],
      ["¿Qué pigmento sanguíneo da un tono rojo a la piel?", "Oxihemoglobina."],
      ["¿Qué pigmento dietario da un tono naranja?", "Caroteno."],
      ["¿Qué color aporta la hemosiderina?", "Pardo dorado."],
      ["¿Qué color aporta la bilirrubina?", "Pardo amarillento."],
      ["¿Cómo se denomina la coloración amarilla por acumulación de bilirrubina?", "Ictericia."],
    ]
  },
  {
    topic: "Células de la epidermis",
    subtopic: "Células de Langerhans",
    cards: [
      ["¿Qué función inmunitaria tienen las células de Langerhans?", "Captar, procesar y presentar antígenos cutáneos."],
      ["¿De qué progenitores derivan las células de Langerhans?", "De progenitores linfoides comunes de médula ósea."],
      ["¿Cómo llegan las células de Langerhans a la epidermis?", "A través de la circulación."],
      ["¿A qué sistema celular pertenecen?", "Al sistema fagocítico mononuclear."],
      ["¿Qué función cumplen en la epidermis?", "Inmunovigilancia."],
      ["¿Cómo muestrean las capas externas sin romper la barrera?", "Extienden prolongaciones a través de uniones estrechas."],
      ["¿A dónde migran después de procesar un antígeno?", "A un ganglio linfático regional."],
      ["¿Qué respuesta pueden iniciar en el ganglio?", "Tolerancia o activación inmunitaria adaptativa."],
      ["¿Qué efecto tiene la radiación UV sobre estas células?", "Las agota y reduce la presentación antigénica."],
      ["¿Cuál es la relación aproximada de Langerhans con otras células epidérmicas?", "1:53."],
      ["¿En qué estrato se visualizan mejor con técnicas especiales?", "En el estrato espinoso."],
      ["¿Qué marcador permite inmunoteñirlas?", "CD1a."],
      ["¿Cómo es su núcleo?", "Irregular y con múltiples escotaduras."],
      ["¿Qué gránulos característicos poseen?", "Gránulos de Birbeck."],
      ["¿Qué forma tienen los gránulos de Birbeck?", "Raqueta de tenis."],
      ["¿Qué moléculas MHC expresan?", "MHC I y MHC II."],
      ["¿A qué linfocitos presentan antígeno mediante MHC I y II?", "T CD8+ y T CD4+, respectivamente."],
      ["¿En qué tipo de hipersensibilidad cutánea participan?", "Hipersensibilidad retardada."],
      ["¿Qué enfermedad maligna deriva de células de Langerhans?", "Histiocitosis de células de Langerhans o histiocitosis X."],
    ]
  },
  {
    topic: "Células de la epidermis",
    subtopic: "Células de Merkel",
    cards: [
      ["¿En qué estrato se localizan las células de Merkel?", "En el estrato basal."],
      ["¿Dónde son especialmente abundantes?", "En zonas de percepción fina, como las yemas de los dedos."],
      ["¿Cómo se unen a queratinocitos contiguos?", "Mediante desmosomas."],
      ["¿Qué filamentos contienen las células de Merkel?", "Filamentos intermedios de queratina."],
      ["¿Cómo es el núcleo de una célula de Merkel?", "Lobulado."],
      ["¿Qué gránulos caracterizan su citoplasma?", "Gránulos de neurosecreción de centro denso."],
      ["¿Con qué fibras nerviosas se relacionan?", "Con fibras mielínicas aferentes."],
      ["¿Qué pierde la terminación nerviosa antes de atravesar la membrana basal?", "Su cubierta de células de Schwann."],
      ["¿Qué es el disco receptor?", "La expansión terminal en placa de la fibra aferente."],
      ["¿Qué forma el corpúsculo de Merkel?", "Una célula de Merkel y su terminación nerviosa aferente."],
      ["¿Qué tipo de receptor es el corpúsculo de Merkel?", "Mecanorreceptor sensitivo."],
      ["¿Cómo se comporta el carcinoma de células de Merkel?", "Crece rápido y metastatiza tempranamente por vasos linfáticos."],
      ["¿Dónde aparece con mayor frecuencia ese carcinoma?", "En piel expuesta al sol, sobre todo cabeza, cuello y miembros."],
    ]
  },
  {
    topic: "Inervación cutánea",
    subtopic: "Terminaciones nerviosas libres",
    cards: [
      ["¿Cuáles son los receptores neuronales más abundantes de la epidermis?", "Las terminaciones nerviosas libres."],
      ["¿Hasta qué estrato llegan las terminaciones libres?", "Hasta el estrato granuloso."],
      ["¿Por qué se denominan terminaciones libres?", "Porque carecen de cápsula conjuntiva y cubierta de Schwann."],
      ["¿Qué modalidades detectan las terminaciones libres?", "Tacto fino, calor, frío y dolor."],
      ["¿Existe una diferencia morfológica evidente entre sus modalidades?", "No."],
      ["¿Qué estructura rodean las redes de terminaciones dérmicas libres?", "La mayoría de los folículos pilosos."],
      ["¿A qué parte del folículo se fijan?", "A la vaina radicular externa."],
      ["¿Qué estímulo detectan las terminaciones alrededor del folículo?", "El movimiento del pelo."],
    ]
  },
  {
    topic: "Inervación cutánea",
    subtopic: "Receptores encapsulados",
    cards: [
      ["¿Qué detectan los corpúsculos de Pacini?", "Cambios de presión y vibración."],
      ["¿Dónde se encuentran los corpúsculos de Pacini?", "En dermis profunda e hipodermis, especialmente en los dedos."],
      ["¿Qué tamaño pueden alcanzar los corpúsculos de Pacini?", "Más de 1 mm."],
      ["¿Qué aspecto histológico tiene un corpúsculo de Pacini?", "Laminillas concéntricas como una cebolla cortada."],
      ["¿Qué ocupa el centro del corpúsculo de Pacini?", "Una terminación axónica."],
      ["¿Qué células forman el núcleo interno de Pacini?", "Células de Schwann aplanadas."],
      ["¿Qué contienen los espacios entre laminillas externas?", "Líquido semejante a linfa, pocas fibrillas y capilares."],
      ["¿Cómo transforma Pacini la presión en señal?", "El desplazamiento laminar despolariza el axón."],
      ["¿Qué detectan los corpúsculos de Meissner?", "Tacto leve y estímulos de baja frecuencia."],
      ["¿Dónde se encuentran los corpúsculos de Meissner?", "En papilas dérmicas de piel lampiña."],
      ["Mencione sitios ricos en corpúsculos de Meissner.", "Labios, palmas, plantas y dedos."],
      ["¿Cómo se orientan respecto de la superficie cutánea?", "Perpendiculares a ella."],
      ["¿Qué células forman sus láminas irregulares?", "Células de Schwann aplanadas."],
      ["¿Qué detectan los corpúsculos de Ruffini?", "Estiramiento y tensión de la piel."],
      ["¿Cómo es la forma de un corpúsculo de Ruffini?", "Alargada y fusiforme."],
      ["¿Qué atraviesa la cápsula de Ruffini?", "Fibras de colágeno del tejido conjuntivo circundante."],
      ["¿Qué sucede con la fibra nerviosa al entrar en Ruffini?", "Pierde mielina y se ramifica en una arborización densa."],
      ["¿Qué estímulo activa Ruffini?", "El desplazamiento mecánico continuo de fibras colágenas."],
      ["¿Qué receptor encapsulado funciona como receptor de frío según la figura 15-12?", "El bulbo terminal de Krause."],
    ]
  },
  {
    topic: "Anexos cutáneos",
    subtopic: "Fundamentos de anexos cutáneos",
    cards: [
      ["¿De qué estructura embrionaria derivan los anexos cutáneos?", "De brotes profundos del epitelio epidérmico."],
      ["¿Qué producto genera el folículo piloso?", "El pelo."],
      ["¿Qué producto genera la glándula sebácea?", "Sebo."],
      ["¿Qué producto genera la glándula ecrina?", "Sudor acuoso."],
      ["¿Cómo es el producto de la glándula apocrina?", "Sudor rico en carbohidratos, lípidos y proteínas."],
      ["¿Qué anexos participan en termorregulación?", "Pelos y glándulas sudoríparas."],
      ["¿Qué anexo aporta células madre para reparación cutánea?", "Principalmente el folículo piloso."],
    ]
  },
  {
    topic: "Folículos pilosos y pelo",
    subtopic: "Folículo piloso",
    cards: [
      ["¿Qué es un folículo piloso?", "Una invaginación epidérmica donde se forma un pelo."],
      ["¿Dónde están ausentes los folículos pilosos?", "Palmas, plantas, labios y piel periorificial urinaria y genital."],
      ["¿Qué hormonas influyen mucho en la distribución del pelo?", "Hormonas sexuales."],
      ["¿Qué determina el color del pelo?", "El contenido y tipo de melanina."],
      ["¿Qué determina el aspecto histológico del folículo?", "Si está en crecimiento o reposo."],
      ["¿Cuáles son las cuatro regiones del folículo piloso?", "Infundíbulo, istmo, protuberancia y segmento inferior."],
      ["¿Desde dónde hasta dónde se extiende el infundíbulo?", "Desde el orificio superficial hasta el conducto sebáceo."],
      ["¿Qué sustancia atraviesa el infundíbulo?", "Sebo."],
      ["¿Desde dónde hasta dónde se extiende el istmo?", "Desde el infundíbulo hasta la inserción del erector del pelo."],
      ["¿Dónde se localiza la protuberancia folicular?", "Cerca de la inserción del músculo erector."],
      ["¿Qué contiene la protuberancia folicular?", "Células madre epidérmicas."],
      ["¿Qué expansión forma la base del segmento inferior?", "El bulbo piloso."],
      ["¿Qué invagina la base del bulbo?", "Una papila dérmica vascularizada."],
      ["¿Qué es la matriz del pelo?", "Las células del bulbo que rodean la papila dérmica."],
      ["¿Qué células son responsables del crecimiento del pelo?", "Las células matriciales en división rápida."],
      ["¿Qué aportan los melanocitos de la matriz?", "Melanosomas al pelo en desarrollo."],
      ["¿En qué se diferencian las células matriciales?", "En pelo y vaina radicular interna."],
      ["¿Cuáles son las tres capas de la vaina radicular interna?", "Henle, Huxley y cutícula propia."],
      ["¿Cómo es la capa de Henle?", "Una capa externa de células cúbicas."],
      ["¿Cómo es la capa de Huxley?", "Una o dos capas de células aplanadas."],
      ["¿Qué contacta la cutícula de la vaina interna?", "El tallo del pelo."],
      ["¿Qué separa el folículo de la dermis?", "La membrana vítrea."],
      ["¿Qué tejido rodea externamente el folículo?", "Una vaina de tejido conjuntivo denso irregular."],
    ]
  },
  {
    topic: "Folículos pilosos y pelo",
    subtopic: "Células madre foliculares",
    cards: [
      ["¿Qué capacidad tienen las células madre de la protuberancia?", "Autorrenovación y diferenciación en linajes epidérmicos."],
      ["¿Qué estructuras producen normalmente las células madre foliculares?", "Folículo piloso y glándulas sebáceas."],
      ["¿Contribuyen normalmente a la población basal de la epidermis?", "No."],
      ["¿Qué ocurre con ellas cuando se lesiona la epidermis?", "Se reprograman y migran hacia la herida."],
      ["¿Qué función cumplen en una herida superficial?", "Participan en la formación inicial de la nueva epidermis."],
      ["¿Qué dirección siguen normalmente hacia el folículo?", "Descienden desde la protuberancia hacia la matriz."],
      ["¿Qué dirección siguen hacia la glándula sebácea?", "Ascienden desde la protuberancia."],
    ]
  },
  {
    topic: "Folículos pilosos y pelo",
    subtopic: "Tallo del pelo",
    cards: [
      ["¿Dónde ocurre la queratinización del pelo?", "En la zona queratógena del tercio inferior del folículo."],
      ["¿Qué expulsan las células corticales al queratinizarse?", "Sus orgánulos."],
      ["¿Cómo emerge el pelo del folículo?", "Completamente queratinizado con queratina dura."],
      ["¿Qué tipo de queratina tiene la vaina radicular interna?", "Queratina blanda."],
      ["¿Dónde se desintegra la vaina radicular interna?", "A la altura del istmo."],
      ["¿Cuáles son las tres capas del tallo piloso?", "Médula, corteza y cutícula."],
      ["¿Qué forma la médula del pelo?", "La porción central."],
      ["¿En qué pelos está presente la médula?", "Solo en pelos gruesos."],
      ["¿Qué tipo de queratina contiene la médula?", "Queratina blanda."],
      ["¿Qué proporción de la masa del pelo forma la corteza?", "Alrededor de 80%."],
      ["¿Qué tipo de queratina contiene la corteza?", "Queratina dura."],
      ["¿Qué son las KAP?", "Proteínas asociadas con la queratina."],
      ["¿Qué enlace vuelve rígido el tallo piloso?", "Enlaces disulfuro entre proteínas ricas en azufre."],
      ["¿Qué propiedades determina la corteza?", "Textura, elasticidad y color."],
      ["¿Qué es la cutícula del pelo?", "La capa externa de células planas superpuestas y queratinizadas."],
      ["¿Qué función tiene la cutícula?", "Protege del daño y determina la porosidad."],
    ]
  },
  {
    topic: "Folículos pilosos y pelo",
    subtopic: "Ciclo y tipos de pelo",
    cards: [
      ["¿El crecimiento del pelo es continuo?", "No; es cíclico."],
      ["¿Cuáles son las tres fases del ciclo piloso?", "Anágena, catágena y telógena."],
      ["¿Qué ocurre en la fase anágena?", "Crecimiento activo."],
      ["¿Qué ocurre en la fase catágena?", "Se detiene la división y el folículo involuciona."],
      ["¿Qué ocurre en la fase telógena?", "Reposo prolongado y pérdida final del pelo."],
      ["¿Qué sucede con la papila dérmica durante catágeno?", "Se retrae."],
      ["¿Qué porcentaje del cabello normal está en anágeno?", "Más de 80%."],
      ["¿Cuánto se acorta el folículo en telógeno?", "Hasta la mitad o menos de su longitud."],
      ["¿Qué es el pelo claviforme?", "El pelo telógeno con extremo proximal en forma de clava."],
      ["¿Qué diferencia al pelo terminal del vello?", "Es largo, grueso y producido por folículos grandes."],
      ["¿Cómo es el vello?", "Corto, delgado y producido por folículos pequeños."],
      ["¿Cuál es la velocidad promedio de crecimiento del pelo?", "0.4 mm/día o 1.2 cm/mes."],
      ["¿Qué ocurre con crecimiento y grosor del pelo con la edad?", "Disminuyen."],
      ["¿Qué causa el pelo gris?", "Disminución de la producción de melanina."],
      ["¿Qué cambio folicular ocurre en la calvicie?", "Folículos terminales se miniaturizan a folículos vellosos."],
      ["¿El cuero cabelludo calvo carece por completo de folículos?", "No; conserva folículos vellosos pequeños."],
      ["¿En qué fase es más susceptible el pelo a eliminación con láser?", "En anágeno."],
      ["¿Por qué se requieren varias sesiones de láser?", "Porque los folículos entran en anágeno en momentos distintos."],
    ]
  },
  {
    topic: "Glándulas cutáneas",
    subtopic: "Glándulas sebáceas",
    cards: [
      ["¿Con qué estructura se asocia la mayoría de glándulas sebáceas?", "Con folículos pilosos."],
      ["¿Dónde faltan glándulas sebáceas?", "En palmas y plantas."],
      ["¿Qué cuatro componentes forman la unidad pilosebácea?", "Folículo, pelo, músculo erector y glándula sebácea."],
      ["¿Dónde existe la mayor densidad de glándulas sebáceas?", "En el rostro."],
      ["¿Qué glándulas sebáceas palpebrales desembocan sin folículo?", "Glándulas de Zeis y de Meibomio."],
      ["¿Qué otras zonas tienen glándulas sebáceas sin folículo?", "Aréolas y bermellón de los labios."],
      ["¿De qué estructura fetal brotan las glándulas sebáceas?", "De la vaina radicular externa del folículo."],
      ["¿Qué secreción fetal ayudan a formar?", "Vernix caseosa."],
      ["¿Qué hormonas aumentan la actividad sebácea?", "Andrógenos."],
      ["¿Qué hormonas inhiben la producción de sebo?", "Estrógenos."],
      ["¿Cómo cambia la actividad sebácea en la pubertad?", "Aumenta."],
      ["¿Qué son los sebocitos?", "Células epiteliales terminalmente diferenciadas que producen sebo."],
      ["¿Qué tipo de secreción produce el sebo?", "Holocrina."],
      ["¿Qué ocurre con el sebocito durante la secreción holocrina?", "Se llena de lípidos, muere y se elimina completo."],
      ["¿Dónde se vierte el sebo?", "En el infundíbulo del folículo."],
      ["¿Qué células reemplazan los sebocitos perdidos?", "Células basales periféricas mitóticas."],
      ["¿Qué orgánulo aumenta cuando el sebocito sintetiza lípidos?", "Retículo endoplasmático liso."],
      ["¿Cuánto tarda la producción de sebo desde mitosis hasta secreción?", "Unos ocho días."],
      ["¿Qué componentes predominan en el sebo?", "Triglicéridos, diglicéridos y ácidos grasos libres."],
      ["¿Qué porcentaje del sebo forman esos lípidos principales?", "Aproximadamente 57%."],
      ["¿Qué porcentaje corresponde a ésteres cerosos?", "Aproximadamente 26%."],
      ["¿Qué porcentaje corresponde a escualeno?", "Aproximadamente 12%."],
      ["¿Por qué el sebo puede actuar como firma química individual?", "Por variaciones genéticas en su composición."],
      ["¿Cuáles son los tres eventos fundamentales del acné vulgar?", "Seborrea, queratinización folicular anómala y proliferación de P. acnes."],
      ["¿Dónde se retiene el sebo en el acné?", "En el istmo del folículo piloso."],
    ]
  },
  {
    topic: "Glándulas cutáneas",
    subtopic: "Glándulas sudoríparas ecrinas",
    cards: [
      ["¿Cuántas glándulas sudoríparas tiene aproximadamente el ser humano?", "Cerca de cuatro millones."],
      ["¿Cuáles son los dos tipos de glándulas sudoríparas?", "Ecrinas y apocrinas."],
      ["¿Cómo se distribuyen las glándulas ecrinas?", "Por casi toda la superficie corporal."],
      ["¿Dónde faltan glándulas ecrinas?", "Labios, lechos ungueales y ciertas partes de genitales externos."],
      ["¿Dónde es mayor la densidad de glándulas ecrinas?", "Palmas, plantas, axilas, frente y tórax."],
      ["¿Se asocian directamente las glándulas ecrinas con folículos?", "No."],
      ["¿Qué tipo morfológico de glándula es la ecrina?", "Tubular simple enrollada de fondo ciego."],
      ["¿Cuáles son los dos segmentos de una glándula ecrina?", "Secretor y canalicular."],
      ["¿Dónde se encuentra el segmento secretor ecrino?", "Dermis profunda o hipodermis superficial."],
      ["¿Dónde desemboca el conducto ecrino?", "Directamente en la superficie epidérmica."],
      ["¿Cuál es la función principal de las glándulas ecrinas?", "Termorregulación por evaporación."],
      ["¿Qué función tienen en palmas y plantas?", "Aumentar la fuerza de agarre."],
      ["¿A qué se parece la secreción primaria ecrina?", "A un ultrafiltrado de sangre."],
      ["¿Qué ocurre con sodio y agua en el conducto ecrino?", "Se reabsorben parcialmente."],
      ["¿Cómo es el sudor ecrino final?", "Hipotónico y bajo en proteínas."],
      ["¿Qué solutos contiene el sudor ecrino?", "NaCl, urea, ácido úrico y amonio."],
      ["¿Qué función adicional cumple la glándula ecrina?", "Excreción parcial."],
      ["¿Cuánta agua se pierde normalmente por evaporación pulmonar y cutánea?", "Unos 600 mL al día."],
      ["¿Dónde inicia la sudoración termorreguladora?", "Frente y cuero cabelludo."],
      ["¿Qué zonas sudan primero por tensión emocional?", "Palmas, plantas y axilas."],
      ["¿Qué neurotransmisión controla la sudoración termorreguladora?", "Colinérgica."],
      ["¿Cuáles son los tres tipos celulares del adenómero ecrino?", "Células claras, oscuras y mioepiteliales."],
      ["¿Cómo se organiza el epitelio secretor ecrino?", "Como epitelio seudoestratificado; todas las células tocan la basal."],
      ["¿Qué sustancia abunda en las células claras?", "Glucógeno."],
      ["¿Qué componente del sudor producen las células claras?", "El componente acuoso."],
      ["¿Qué orgánulos abundan en células claras?", "Mitocondrias y REL."],
      ["¿Qué estructuras amplían su membrana?", "Pliegues laterales, apicales y basales."],
      ["¿Qué caracteriza a las células oscuras?", "RER, Golgi y gránulos secretores abundantes."],
      ["¿Qué secretan las células oscuras?", "Glucoproteínas."],
      ["¿Dónde vierten principalmente su producto las células claras?", "En canalículos intercelulares."],
      ["¿Dónde se ubican las células mioepiteliales ecrinas?", "En la base del segmento secretor."],
      ["¿Qué filamentos abundan en células mioepiteliales?", "Filamentos de actina."],
      ["¿Qué efecto tiene su contracción?", "Expulsa rápidamente el sudor."],
      ["¿Qué epitelio reviste el conducto ecrino dérmico?", "Epitelio cúbico estratificado."],
      ["¿Tiene células mioepiteliales el conducto ecrino?", "No."],
      ["¿Cómo se compara el diámetro del conducto con el adenómero?", "Es menor."],
      ["¿Cómo se denomina clínicamente la porción dérmica del conducto?", "Siringe."],
      ["¿Cómo se denomina la porción intraepidérmica?", "Acrosiringio."],
      ["¿Qué tumor benigno deriva de la siringe?", "Siringoma."],
      ["¿Qué tumor deriva del acrosiringio?", "Poroma; su maligno es porocarcinoma ecrino."],
    ]
  },
  {
    topic: "Glándulas cutáneas",
    subtopic: "Glándulas sudoríparas apocrinas",
    cards: [
      ["¿Dónde se localizan las glándulas apocrinas?", "Axila, aréola, pezón, región perianal y genitales externos."],
      ["¿Qué glándulas del oído son apocrinas modificadas?", "Glándulas ceruminosas."],
      ["¿Qué glándulas de las pestañas son apocrinas?", "Glándulas de Moll."],
      ["¿De qué brote embrionario derivan las apocrinas?", "Del mismo brote epidérmico que el folículo piloso."],
      ["¿Dónde desemboca el conducto apocrino?", "En el folículo piloso."],
      ["¿Cómo es la glándula apocrina morfológicamente?", "Tubular enrollada, a veces ramificada."],
      ["¿Dónde está su porción secretora?", "Dermis profunda o hipodermis superficial."],
      ["¿Cuál es la diferencia histológica más evidente frente a ecrina?", "La luz apocrina es mucho más amplia."],
      ["¿Dónde almacena la apocrina su producto?", "En la luz."],
      ["¿Qué epitelio forma el adenómero apocrino?", "Epitelio simple."],
      ["¿Cuántos tipos de células secretoras tiene?", "Uno."],
      ["¿Cómo es el citoplasma de las células secretoras apocrinas?", "Eosinófilo."],
      ["¿Qué aspecto presenta a menudo su superficie apical?", "Una protrusión vesiculosa."],
      ["¿La secreción apocrina humana se libera por decapitación celular?", "No; es merocrina por exocitosis."],
      ["¿Qué pigmento residual contienen estas células?", "Lipofuscina."],
      ["¿Contiene células mioepiteliales la porción secretora?", "Sí."],
      ["¿Qué función tienen sus células mioepiteliales?", "Facilitar la expulsión de la secreción."],
      ["¿Qué epitelio reviste el conducto apocrino?", "Epitelio cúbico estratificado."],
      ["¿Se modifica la secreción en el conducto apocrino?", "No; no hay resorción."],
      ["¿Qué contiene la secreción apocrina?", "Proteínas, carbohidratos, amonio, lípidos y compuestos orgánicos."],
      ["¿Cómo es la secreción axilar recién emitida?", "Lechosa, viscosa e inodora."],
      ["¿Qué produce el olor acre de la secreción axilar?", "La acción bacteriana sobre la secreción."],
      ["¿Cuándo se vuelven funcionales las glándulas apocrinas?", "En la pubertad."],
      ["¿De qué depende su desarrollo?", "De hormonas sexuales."],
      ["¿Qué neurotransmisor estimula las glándulas apocrinas?", "Noradrenalina."],
      ["¿Qué división nerviosa las inerva?", "La simpática."],
      ["¿Responden las glándulas apocrinas al calor?", "No."],
      ["¿Ante qué estímulos participan en sudoración?", "Estrés, temor, dolor y estimulación sexual."],
      ["¿Qué neurotransmisor estimula las glándulas ecrinas?", "Acetilcolina."],
      ["¿Cómo se describe la inervación ecrina?", "Funcionalmente colinérgica, anatómicamente simpática."],
    ]
  },
  {
    topic: "Uñas",
    subtopic: "Placa y aparato ungueal",
    cards: [
      ["¿Qué son las placas ungueales?", "Células queratinizadas con queratina dura."],
      ["¿A qué estructura se unen firmemente las placas ungueales?", "Al lecho ungueal."],
      ["¿Con qué estratos es continuo el lecho ungueal?", "Basal y espinoso."],
      ["¿Qué es la raíz ungueal?", "La porción proximal oculta bajo un pliegue epidérmico."],
      ["¿Qué contiene la matriz ungueal?", "Células madre, epiteliales, melanocitos, Merkel y Langerhans."],
      ["¿Qué producen las células madre de la matriz?", "La queratina de la uña."],
      ["¿Qué tipo de queratina forma la uña?", "Queratina dura."],
      ["¿Por qué es dura la queratina ungueal?", "Por su alto contenido de azufre y filamentos muy juntos."],
      ["¿La queratina ungueal se descama?", "No."],
      ["¿Aparecen gránulos de queratohialina al formarse la uña?", "No."],
      ["¿Qué impulsa el crecimiento de la uña?", "La adición continua de células y queratina en la raíz."],
      ["¿A qué velocidad crecen las uñas de las manos?", "2-3 mm al mes."],
      ["¿A qué velocidad crecen las uñas de los pies?", "Aproximadamente 1 mm al mes."],
      ["¿Cuánto tarda el reemplazo completo de una uña de la mano?", "Unos seis meses."],
      ["¿Cuánto tarda el reemplazo completo de una uña del pie?", "Unos 18 meses."],
      ["¿Qué es la lúnula?", "El área blanca semilunar que marca la matriz distal."],
      ["¿Por qué es blanca la lúnula?", "Por células matriciales gruesas, opacas y parcialmente queratinizadas."],
      ["¿Qué es el eponiquio?", "El borde o cutícula que cubre la raíz ungueal."],
      ["¿Qué es el hiponiquio?", "La epidermis engrosada que fija el borde libre de la uña."],
    ]
  },
  {
    topic: "Correlaciones clínicas",
    subtopic: "Cáncer cutáneo",
    cards: [
      ["¿Cuál es la causa general más importante de cáncer cutáneo mencionada?", "Exposición UV prolongada sin protección."],
      ["¿Cuál es el cáncer cutáneo más frecuente?", "Carcinoma basocelular."],
      ["¿A qué células se parece histológicamente el carcinoma basocelular?", "A células del estrato basal."],
      ["¿Cómo suele crecer el carcinoma basocelular?", "Lentamente."],
      ["¿El carcinoma basocelular suele metastatizar?", "No."],
      ["¿De qué nicho suele originarse el carcinoma basocelular?", "De la protuberancia de la vaina radicular externa."],
      ["¿Cuál es el segundo cáncer cutáneo más frecuente?", "Carcinoma epidermoide."],
      ["¿Qué aspecto clínico puede tener el carcinoma epidermoide?", "Placa o nódulo indoloro rodeado de inflamación."],
      ["¿Qué caracteriza al carcinoma epidermoide in situ?", "Células muy atípicas en todos los niveles epidérmicos."],
      ["¿Qué permite la metástasis del carcinoma epidermoide?", "La fragmentación de la membrana basal."],
      ["¿Cuál es la forma más grave de cáncer cutáneo si no se detecta temprano?", "Melanoma maligno."],
      ["¿De qué células deriva el melanoma?", "De melanocitos."],
      ["¿Qué es un melanoma in situ?", "Uno confinado a la epidermis."],
      ["¿Cómo crece el melanoma en fase radial?", "Hacia arriba, abajo y periféricamente."],
      ["¿La fase radial temprana suele metastatizar?", "No."],
      ["¿Qué ocurre en la fase vertical del melanoma?", "Forma nódulos que crecen perpendicularmente y suelen metastatizar."],
      ["¿Qué significa la A de la regla ABCD?", "Asimetría."],
      ["¿Qué significa la B de la regla ABCD?", "Borde irregular."],
      ["¿Qué significa la C de la regla ABCD?", "Color variable."],
      ["¿Qué significa la D de la regla ABCD?", "Diámetro mayor de 6 mm sospechoso."],
      ["¿Cuál es el tratamiento de elección para melanoma localizado?", "Cirugía."],
    ]
  },
  {
    topic: "Correlaciones clínicas",
    subtopic: "Cirugía de Mohs",
    cards: [
      ["¿Qué es la cirugía micrográfica de Mohs?", "Una técnica guiada por microscopía para extirpar cáncer cutáneo."],
      ["¿Qué tipo de cortes utiliza durante la cirugía?", "Cortes congelados."],
      ["¿Qué porcentaje del margen quirúrgico puede visualizarse en el primer corte?", "El 100%."],
      ["¿Qué orientación tienen los cortes de Mohs?", "Horizontal o en face."],
      ["¿Qué orientación tienen los cortes convencionales?", "Vertical."],
      ["¿Por qué se marcan los bordes con colores?", "Para localizar con precisión tumor residual."],
      ["¿Qué ventaja tisular ofrece Mohs?", "Conserva más tejido sano."],
      ["¿En qué zonas es especialmente útil?", "Rostro, manos, pies y genitales."],
      ["¿Para qué patrón tumoral funciona mejor?", "Tumores contiguos."],
      ["¿Qué carcinomas suelen ser susceptibles a Mohs?", "Basocelular y epidermoide."],
      ["¿Qué doble función cumple el cirujano en Mohs?", "Cirujano y patólogo."],
    ]
  },
  {
    topic: "Correlaciones clínicas",
    subtopic: "Sudoración y enfermedad",
    cards: [
      ["¿Qué hallazgo en sudor puede indicar fibrosis quística?", "Sodio y cloruro elevados."],
      ["¿Cuánto pueden elevarse sodio y cloruro en fibrosis quística?", "De dos a cinco veces lo normal."],
      ["¿Qué aumenta en el sudor durante la uremia?", "La urea."],
      ["¿Qué es la escarcha urémica?", "Cristales de urea sobre la piel tras evaporarse el sudor."],
      ["¿Qué es la hiperhidrosis?", "Producción de sudor excesiva para las necesidades termorreguladoras."],
      ["¿La hiperhidrosis primaria depende necesariamente de calor?", "No; puede ocurrir en reposo y ser impredecible."],
      ["Mencione un tratamiento de hiperhidrosis del texto.", "Anticolinérgicos, simpatectomía, láser o toxina botulínica."],
    ]
  },
  {
    topic: "Correlaciones clínicas",
    subtopic: "Reparación cutánea",
    cards: [
      ["¿Cuándo ocurre cicatrización por primera intención?", "En heridas limpias con bordes aproximados por sutura."],
      ["¿Cuándo ocurre cicatrización por segunda intención?", "En heridas con bordes separados y pérdida extensa de tejido."],
      ["¿Qué tejido abunda en la segunda intención?", "Tejido de granulación."],
      ["¿Cuál es el primer paso de reparación dérmica enumerado?", "Formación de un coágulo sanguíneo."],
      ["¿Qué células eliminan gran parte del colágeno dañado?", "Macrófagos."],
      ["¿Qué células depositan y remodelan matriz extracelular?", "Fibroblastos."],
      ["¿Qué células contraen la herida?", "Miofibroblastos."],
      ["¿Por qué la primera intención deja menos cicatriz?", "Porque reduce el área que debe repararse."],
      ["¿Qué orientación de incisión reduce la cicatriz?", "Paralela a los haces de colágeno o líneas de tensión."],
      ["¿Qué células inician la reparación epidérmica?", "Queratinocitos basales de piel intacta vecina."],
      ["¿Cuándo aumenta mucho la mitosis basal tras una herida?", "Durante las primeras 24 horas."],
      ["¿Qué es la costra?", "El coágulo sanguíneo deshidratado."],
      ["¿Por dónde migran los queratinocitos en reparación?", "Por debajo de la costra."],
      ["¿Cuándo comienza la migración queratinocítica?", "Entre 8 y 18 horas tras la lesión."],
      ["¿Qué velocidad puede alcanzar esa migración?", "Hasta 0.5 mm/día."],
      ["¿Dónde ocurren proliferación y diferenciación durante reepitelización?", "Detrás del frente migratorio."],
      ["¿Por qué la costra se desprende desde la periferia?", "Porque la epidermis nueva se queratiniza y exfolia debajo."],
      ["¿Qué estructura aporta células si se pierde todo el espesor epidérmico?", "La protuberancia de folículos pilosos conservados."],
      ["¿Qué lesión impide la reepitelización espontánea adecuada?", "Destrucción de todas las estructuras epiteliales, como quemadura de tercer grado."],
      ["¿Qué tratamiento requiere una pérdida epitelial masiva?", "Injerto epidérmico."],
    ]
  },
  {
    topic: "Histología 101 e identificación",
    subtopic: "Identificación histológica",
    cards: [
      ["Una superficie con estrato córneo muy grueso, estrato lúcido y sin pelo corresponde a…", "Piel gruesa."],
      ["Una epidermis delgada con folículos pilosos corresponde a…", "Piel delgada."],
      ["Una capa monocelular basófila sobre la membrana basal corresponde a…", "Estrato basal."],
      ["Queratinocitos con puentes intercelulares visibles identifican el…", "Estrato espinoso."],
      ["Una banda de células aplanadas con gránulos basófilos identifica el…", "Estrato granuloso."],
      ["Una banda clara refringente exclusiva de piel gruesa identifica el…", "Estrato lúcido."],
      ["Células planas anucleadas llenas de queratina identifican el…", "Estrato córneo."],
      ["Tejido conjuntivo laxo celular justo bajo epidermis identifica la…", "Dermis papilar."],
      ["Haces gruesos de colágeno tipo I identifican la…", "Dermis reticular."],
      ["Una célula basal clara y dendrítica con melanosomas corresponde a…", "Melanocito."],
      ["Una célula espinosa dendrítica con gránulos de Birbeck corresponde a…", "Célula de Langerhans."],
      ["Una célula basal con gránulos densos y disco nervioso corresponde a…", "Célula de Merkel."],
      ["Una estructura laminar en cebolla en dermis profunda corresponde a…", "Corpúsculo de Pacini."],
      ["Un receptor ovalado en una papila dérmica corresponde a…", "Corpúsculo de Meissner."],
      ["Una invaginación epidérmica con bulbo y papila dérmica corresponde a…", "Folículo piloso."],
      ["Lobulillos pálidos asociados a un folículo corresponden a…", "Glándula sebácea."],
      ["Un túbulo enrollado con luz pequeña y células claras/oscuras corresponde a…", "Adenómero ecrino."],
      ["Un túbulo de epitelio cúbico estratificado, luz pequeña y sin mioepiteliales corresponde a…", "Conducto ecrino."],
      ["Una glándula tubular con luz muy amplia cerca de un folículo corresponde a…", "Glándula apocrina."],
      ["Una placa de queratina dura sobre un lecho epitelial corresponde a…", "Uña."],
    ]
  }
]

export const cap15Flashcards: Flashcard[] = groups.flatMap(
  group => group.cards.map(([front, back], index) => ({
    id: `histo-cap15-${group.subtopic
      .normalize("NFD")
      .replace(/[\u0300-\u036f]/g, "")
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "")}-${String(index + 1).padStart(4, "0")}`,
    subject: "Histología",
    book: "Ross",
    chapter: "Capítulo 15",
    topic: group.topic,
    subtopic: group.subtopic,
    front,
    back,
    tags: ["Capítulo 15", group.subtopic]
  }))
)
