import type { Flashcard } from "./cards"

type Group = { topic: string; subtopic: string; cards: readonly (readonly [string, string])[] }

// Banco manual basado en Ross, capítulo 17. Las pistas son concretas y cada tarjeta
// contiene una sola unidad recuperable, para evitar tarjetas de definición vacía.
const groups: readonly Group[] = [
  { topic: "Fundamentos del tubo digestivo", subtopic: "Pared y sistema nervioso entérico", cards: [
    ["¿Cuáles son las cuatro capas generales de la pared del tubo digestivo?", "Mucosa, submucosa, muscular externa y serosa o adventicia."],
    ["¿Qué tres componentes forman la mucosa digestiva?", "Epitelio, lámina propia y muscular de la mucosa."],
    ["¿Qué tejido predomina en la submucosa digestiva?", "Tejido conjuntivo denso irregular."],
    ["¿Qué plexo se localiza en la submucosa?", "El plexo submucoso de Meissner."],
    ["¿Qué regula principalmente el plexo submucoso de Meissner?", "Secreción, flujo sanguíneo local y muscular de la mucosa."],
    ["¿Entre qué capas está el plexo mientérico de Auerbach?", "Entre la capa circular interna y la longitudinal externa."],
    ["¿Qué función predomina en el plexo mientérico de Auerbach?", "La coordinación de la motilidad."],
    ["¿Qué contracción mezcla quimo sin propulsarlo netamente?", "La segmentación."],
    ["¿Qué capa muscular genera principalmente segmentación?", "La capa circular interna."],
    ["¿Qué movimiento desplaza el contenido hacia distal?", "El peristaltismo."],
    ["¿Qué capas actúan coordinadamente en el peristaltismo?", "La circular interna y la longitudinal externa."],
    ["¿Para qué sirve la muscular de la mucosa?", "Para producir movimientos locales de la mucosa."],
    ["¿Qué capa externa posee mesotelio?", "La serosa."],
    ["¿Cuándo una pared digestiva posee adventicia?", "Cuando está fijada a estructuras vecinas y no cubierta por peritoneo."],
    ["¿Qué cubierta externa predomina en el esófago torácico?", "La adventicia."],
    ["¿Qué estructura ileal puede extenderse a la submucosa?", "Las placas de Peyer."],
    ["¿Qué tres niveles aumentan la superficie del intestino delgado?", "Pliegues circulares, vellosidades y microvellosidades."],
    ["¿Qué recubre las microvellosidades y contiene enzimas digestivas terminales?", "El glucocáliz."],
    ["¿Qué esfínter limita el reflujo del colon hacia el íleon?", "El esfínter ileocecal."],
    ["¿Qué causa la ausencia de inervación normal del esfínter pilórico?", "Estenosis pilórica hipertrófica con vómito proyectil no bilioso."],
  ]},
  { topic: "Esófago", subtopic: "Epitelio, músculo y glándulas", cards: [
    ["¿Qué epitelio reviste el esófago normal?", "Plano estratificado no queratinizado."],
    ["¿Qué función explica el epitelio plano estratificado del esófago?", "Resistir la abrasión del bolo alimenticio."],
    ["¿Cómo se ve habitualmente la luz esofágica vacía en corte transversal?", "Estrellada o ramificada por pliegues longitudinales."],
    ["¿Qué permiten los pliegues longitudinales esofágicos?", "La distensión durante el paso del bolo."],
    ["¿Qué tejido inmunitario puede encontrarse en la lámina propia esofágica?", "Tejido linfático difuso."],
    ["¿Cómo se orienta la muscular de la mucosa del esófago?", "Principalmente en sentido longitudinal."],
    ["¿Dónde se localizan las glándulas esofágicas propias?", "En la submucosa."],
    ["¿Qué tipo de glándulas son las esofágicas propias?", "Compuestas tubuloacinares."],
    ["¿Qué epitelio reviste sus conductos?", "Plano estratificado."],
    ["¿Qué característica tiene su moco?", "Es viscoso y ligeramente ácido."],
    ["¿Qué función tiene el moco de las glándulas esofágicas propias?", "Lubricar y proteger la mucosa."],
    ["¿Dónde están las glándulas cardiales esofágicas?", "En la lámina propia, cerca de los extremos esofágicos."],
    ["¿Qué tipo de moco secretan las glándulas cardiales esofágicas?", "Moco neutro protector."],
    ["¿Qué protege el moco cardial del extremo distal?", "La mucosa frente al reflujo gástrico."],
    ["¿Cómo cambia el músculo de la muscular externa a lo largo del esófago?", "Estriado arriba, mixto en el tercio medio y liso abajo."],
    ["¿De dónde vienen las fibras motoras del músculo estriado esofágico?", "Del núcleo ambiguo a través del vago."],
    ["¿De dónde vienen las fibras parasimpáticas del músculo liso esofágico distal?", "Del núcleo motor dorsal del vago."],
    ["¿Qué cubierta tiene la corta porción abdominal del esófago?", "Serosa."],
    ["¿Qué cambio epitelial ocurre en la unión gastroesofágica normal?", "De plano estratificado a cilíndrico simple."],
    ["¿Qué metaplasia puede provocar el reflujo crónico en esófago distal?", "Metaplasia a epitelio cilíndrico, como en Barrett."],
  ]},
  { topic: "Estómago", subtopic: "Mucosa, regiones y protección", cards: [
    ["¿Cuáles son las regiones anatómicas del estómago?", "Cardias, fondo, cuerpo y antro-píloro."],
    ["¿Qué tres regiones histológicas se reconocen por sus glándulas?", "Cardial, fúndica y pilórica."],
    ["¿Qué zonas contienen glándulas fúndicas?", "Fondo y cuerpo."],
    ["¿Qué zonas tienen glándulas predominantemente mucosas?", "Cardias y píloro."],
    ["¿Qué capas forman las rugas gástricas?", "Mucosa y submucosa."],
    ["¿Qué sucede con las rugas al llenarse el estómago?", "Se aplanan."],
    ["¿Qué epitelio cubre la superficie y las fovéolas gástricas?", "Cilíndrico simple de células mucosas superficiales."],
    ["¿Dónde desembocan las glándulas gástricas?", "En el fondo de las fovéolas."],
    ["¿Cómo difieren las fovéolas de fondo/cuerpo y píloro?", "Son cortas en fondo/cuerpo y profundas en píloro."],
    ["¿Qué dos componentes forman la barrera mucosa gástrica?", "Moco viscoso y bicarbonato."],
    ["¿Qué pH se mantiene cerca del epitelio bajo el moco gástrico?", "Casi neutro."],
    ["¿Qué prostaglandina favorece moco, bicarbonato y vasodilatación mucosa?", "Prostaglandina E2."],
    ["¿Por qué los AINE favorecen lesión gástrica?", "Porque reducen las prostaglandinas protectoras."],
    ["¿Qué gasotransmisor aumenta el flujo sanguíneo mucoso?", "Óxido nítrico."],
    ["¿Qué sustancias pueden absorberse en pequeña cantidad en el estómago?", "Agua, sales y compuestos liposolubles como alcohol y aspirina."],
    ["¿Qué capa adicional tiene la muscular externa gástrica?", "Una capa oblicua interna."],
    ["¿Qué cubre la superficie externa del estómago?", "Serosa."],
    ["¿Con qué estructuras se continúa la serosa gástrica?", "Con los epiplones mayor y menor."],
  ]},
  { topic: "Estómago", subtopic: "Glándulas fúndicas", cards: [
    ["¿Qué tipo de glándula es una glándula fúndica?", "Tubular simple ramificada."],
    ["¿Desde dónde hasta dónde se extiende una glándula fúndica?", "Desde la base de una fovéola hasta la muscular de la mucosa."],
    ["¿Dónde se ubica el nicho de células madre de una glándula fúndica?", "En el istmo."],
    ["¿Qué células integran una glándula fúndica?", "Mucosas del cuello, parietales, principales, enteroendocrinas y células madre."],
    ["¿Qué célula secreta HCl?", "La célula parietal u oxíntica."],
    ["¿Qué célula secreta factor intrínseco?", "La célula parietal."],
    ["¿Qué célula secreta pepsinógeno?", "La célula principal."],
    ["¿Qué otra secreción produce la célula principal?", "Lipasa gástrica en pequeña cantidad."],
    ["¿Dónde predominan las células parietales?", "En el cuello y la mitad superior de la glándula."],
    ["¿Dónde predominan las células principales?", "En la base de la glándula."],
    ["¿Qué aspecto tienen las células parietales en H&E?", "Citoplasma intensamente eosinófilo."],
    ["¿Qué aspecto basal tienen las células principales?", "Basofilia marcada por abundante RER."],
    ["¿Qué estructuras amplían la superficie secretora de una célula parietal activa?", "Canalículos intracelulares con microvellosidades."],
    ["¿Qué compartimento disminuye durante la secreción activa de HCl?", "El sistema tubulovesicular."],
    ["¿Qué bomba expulsa H+ a la luz gástrica?", "La H+/K+-ATPasa."],
    ["¿Qué enzima permite generar H+ y HCO3− en la célula parietal?", "Anhidrasa carbónica."],
    ["¿Qué ion acompaña al H+ para formar HCl?", "Cloruro."],
    ["¿Qué tres estímulos aumentan la secreción ácida parietal?", "Gastrina, histamina y acetilcolina."],
    ["¿Qué receptor recibe la histamina en la célula parietal?", "H2."],
    ["¿Qué receptor muscarínico media el estímulo colinérgico?", "M3."],
    ["¿Qué pH favorece la activación de pepsinógeno a pepsina?", "Menor de 5."],
    ["¿Qué hace la pepsina con proteínas?", "Hidroliza enlaces peptídicos internos."],
    ["¿Qué propiedad defensiva adicional tiene el HCl?", "Es bacteriostático."],
    ["¿Qué moco es más alcalino: el superficial o el del cuello?", "El de las células mucosas superficiales."],
    ["¿Qué células actúan como precursoras de células mucosas superficiales?", "Las células mucosas del cuello."],
    ["¿Dónde se absorbe la vitamina B12 unida a factor intrínseco?", "En el íleon distal."],
    ["¿Qué anemia resulta de destruir células parietales por autoinmunidad?", "Anemia perniciosa."],
    ["¿Qué medicamento bloquea directamente la bomba H+/K+-ATPasa?", "Un inhibidor de la bomba de protones."],
  ]},
  { topic: "Estómago", subtopic: "Hormonas, renovación y clínica", cards: [
    ["¿Qué célula antral secreta gastrina?", "La célula G."],
    ["¿Qué efecto tiene la gastrina sobre el estómago?", "Estimula secreción ácida."],
    ["¿Qué célula secreta somatostatina gástrica?", "La célula D."],
    ["¿Qué efecto tiene somatostatina sobre gastrina y HCl?", "Los inhibe."],
    ["¿Qué mediador paracrino estimula HCl desde células enteroendocrinas?", "Histamina."],
    ["¿Qué hormona del fondo se relaciona con hambre?", "Grelina."],
    ["¿Qué hormona duodenal contrae vesícula biliar y frena vaciamiento gástrico?", "Colecistoquinina."],
    ["¿Qué hormona duodenal estimula bicarbonato pancreático e inhibe HCl?", "Secretina."],
    ["¿Qué hormona intestinal estimula insulina tras ingerir glucosa?", "GIP."],
    ["¿Qué hormona participa en la motilidad intestinal interdigestiva?", "Motilina."],
    ["¿Qué hormona de células L incrementa insulina e inhibe vaciamiento gástrico?", "GLP-1."],
    ["¿Qué hormona de células L favorece absorción colónica de agua y electrolitos?", "PYY."],
    ["¿Qué hormona se eleva en el síndrome de Zollinger-Ellison?", "Gastrina."],
    ["¿Qué tipo de tumor causa Zollinger-Ellison?", "Gastrinoma duodenal o pancreático."],
    ["¿Qué combinación sugiere gastrinoma?", "Úlceras recurrentes, diarrea y esteatorrea por exceso ácido."],
    ["¿Qué bacteria usa ureasa para formar una nube protectora de amoníaco?", "Helicobacter pylori."],
    ["¿Cuánto viven las células mucosas superficiales gástricas?", "Aproximadamente 3 a 5 días."],
    ["¿Cuánto viven células principales y enteroendocrinas gástricas?", "Aproximadamente 60 a 90 días."],
    ["¿Qué células fúndicas viven aproximadamente 150 a 200 días?", "Las células parietales."],
    ["¿Qué dirección siguen las células del istmo destinadas a superficie?", "Migran hacia arriba, hacia la fovéola."],
    ["¿Qué dirección siguen las células del istmo destinadas a la porción profunda?", "Migran hacia abajo, hacia la base glandular."],
  ]},
  { topic: "Intestino delgado", subtopic: "Vellosidades y absorción", cards: [
    ["¿Qué estructura es una proyección de mucosa hacia la luz intestinal?", "La vellosidad."],
    ["¿Qué estructura es una invaginación tubular entre vellosidades?", "La cripta o glándula de Lieberkühn."],
    ["¿Qué epitelio cubre una vellosidad intestinal?", "Cilíndrico simple."],
    ["¿Qué célula es la principal responsable de absorción intestinal?", "El enterocito."],
    ["¿Qué forma el borde estriado del enterocito?", "Microvellosidades apicales."],
    ["¿Qué filamentos forman el núcleo de una microvellosidad?", "Filamentos de actina."],
    ["¿Qué proteína ancla filamentos de actina de la microvellosidad?", "Villin."],
    ["¿Qué proteína motora participa en el anclaje de microvellosidades?", "Miosina I."],
    ["¿A qué red citoplasmática se fijan los haces de actina microvellosos?", "A la red terminal."],
    ["¿Qué uniones controlan el paso paracelular entre enterocitos?", "Las zónulas ocluyentes."],
    ["¿En qué segmentos hay mayor permeabilidad paracelular?", "Duodeno y yeyuno."],
    ["¿Qué tipo de absorción se beneficia de esa permeabilidad yeyunal?", "Arrastre por solvente."],
    ["¿Qué organelo participa en la resíntesis de lípidos en enterocitos?", "El retículo endoplásmico liso."],
    ["¿Qué vaso recibe aminoácidos y monosacáridos de una vellosidad?", "Los capilares sanguíneos."],
    ["¿Qué vaso recibe quilomicrones de una vellosidad?", "El quilífero central."],
    ["¿Dónde está el quilífero central?", "En la lámina propia de la vellosidad."],
    ["¿Qué fibras acortan vellosidades y ayudan a vaciar el quilífero?", "Fibras de músculo liso de la muscular de la mucosa."],
    ["¿Qué célula intestinal secreta mucina?", "La célula caliciforme."],
    ["¿Cómo cambia la cantidad de células caliciformes hacia el íleon?", "Aumenta progresivamente."],
    ["¿Qué segmento tiene vellosidades más largas?", "El yeyuno."],
    ["¿Qué segmento presenta plicas circulares más desarrolladas?", "El yeyuno."],
    ["¿Qué segmento suele tener las placas de Peyer más notorias?", "El íleon."],
  ]},
  { topic: "Intestino delgado", subtopic: "Criptas, inmunidad y segmentos", cards: [
    ["¿Dónde se ubican las células de Paneth?", "En la base de las criptas intestinales."],
    ["¿Qué aspecto tienen los gránulos de Paneth con H&E?", "Eosinófilos intensos y refringentes."],
    ["¿Qué sustancias antimicrobianas liberan células de Paneth?", "Lisozima y defensinas alfa."],
    ["¿Qué célula cubre placas de Peyer y transporta antígenos?", "La célula M."],
    ["¿Qué rasgo apical diferencia célula M de enterocito?", "Micropliegues en vez de microvellosidades largas."],
    ["¿Qué receptor apical de células M capta bacterias gramnegativas?", "GP2."],
    ["¿Qué proceso lleva antígenos por la célula M hasta su base?", "Transcitosis."],
    ["¿Qué células ocupan el receso basal de una célula M?", "Linfocitos, macrófagos y células dendríticas."],
    ["¿Dónde está el nicho de células madre del intestino delgado?", "En la mitad basal de la cripta."],
    ["¿Qué células forman el compartimento proliferativo de la cripta?", "Las células intermediarias."],
    ["¿Qué linajes pueden originar las células intermediarias?", "Absortivo o caliciforme."],
    ["¿Qué factor favorece linajes secretores intestinales?", "Math1."],
    ["¿Qué linaje aparece cuando se inhibe Math1?", "El linaje absortivo de enterocitos."],
    ["¿Hacia dónde migran enterocitos y caliciformes tras formarse?", "Hacia arriba por cripta y vellosidad."],
    ["¿Cómo terminan enterocitos y caliciformes en la punta vellosa?", "Por apoptosis y exfoliación."],
    ["¿Cuánto dura el recambio de enterocitos y caliciformes?", "Aproximadamente 4 a 6 días."],
    ["¿Qué hacen las células de Paneth en vez de ascender por la vellosidad?", "Migran hacia abajo y permanecen en la base de la cripta."],
    ["¿Cuánto viven las células de Paneth?", "Alrededor de cuatro semanas."],
    ["¿Qué inmunoglobulina predomina en la defensa mucosa intestinal?", "IgA secretora."],
    ["¿Qué forma de IgA secretan principalmente plasmocitos intestinales?", "IgA dimérica con cadena J."],
    ["¿Dónde se encuentra pIgR en un enterocito?", "En la membrana basolateral."],
    ["¿Qué se forma cuando IgA dimérica se libera con componente secretor?", "IgA secretora."],
    ["¿Qué hace la IgA secretora en la luz intestinal?", "Evita adhesión e invasión microbiana y neutraliza toxinas."],
    ["¿Qué rasgo submucoso identifica al duodeno?", "Glándulas de Brunner."],
    ["¿Qué secretan las glándulas de Brunner?", "Moco alcalino con bicarbonato."],
    ["¿Qué función tiene la secreción de Brunner?", "Neutralizar quimo ácido y favorecer enzimas pancreáticas."],
    ["¿Qué pH tiene aproximadamente la secreción de Brunner?", "Entre 8.1 y 9.3."],
  ]},
  { topic: "Intestino grueso", subtopic: "Colon y lámina propia", cards: [
    ["¿Qué órganos incluye el intestino grueso?", "Ciego, apéndice, colon, recto y conducto anal."],
    ["¿Qué falta en la mucosa normal del colon?", "Vellosidades y pliegues circulares."],
    ["¿Cómo son las criptas del colon?", "Tubulares, rectas, largas y no ramificadas."],
    ["¿Cuál es la función principal del colon?", "Reabsorber agua y electrólitos y eliminar desechos."],
    ["¿Qué célula reabsorbe agua y electrólitos en colon?", "La célula absortiva cilíndrica."],
    ["¿Qué bomba es abundante en la membrana lateral de células absortivas colónicas?", "Na+/K+-ATPasa."],
    ["¿Qué tipo celular es mucho más abundante en colon que en intestino delgado?", "La célula caliciforme."],
    ["¿Para qué sirve el moco colónico continuo?", "Lubricar el contenido que se vuelve más sólido."],
    ["¿Qué tipo celular suele estar ausente del epitelio colónico humano?", "La célula de Paneth."],
    ["¿Qué proporción aproximada de absortivas a caliciformes hay en colon?", "Aproximadamente 4:1."],
    ["¿Cómo cambia esa proporción cerca del recto?", "Se aproxima a 1:1 por aumento de caliciformes."],
    ["¿Dónde está el nicho de células madre de una cripta colónica?", "En su tercio basal."],
    ["¿Cuánto tardan aproximadamente en renovarse absortivas y caliciformes colónicas?", "Cerca de 6 días."],
    ["¿Dónde se exfolian células colónicas seniles?", "En el punto medio entre criptas contiguas."],
    ["¿Qué capa se interpone entre epitelio y capilares venosos absortivos del colon?", "La meseta de colágeno."],
    ["¿Qué función tiene la meseta de colágeno?", "Regular el paso de agua y electrólitos al compartimento vascular."],
    ["¿Qué estructura fibroblástica rodea criptas colónicas?", "La vaina fibroblástica pericríptica."],
    ["¿Qué tejido inmunitario está muy desarrollado en colon?", "GALT."],
    ["¿Por qué un adenoma confinado a mucosa metastatiza lentamente?", "Porque la lámina propia tiene acceso linfático limitado."],
    ["¿Qué hallazgo puede aumentar en colitis ulcerosa activa?", "Vasos linfáticos en la lámina propia por linfangiogénesis."],
  ]},
  { topic: "Intestino grueso", subtopic: "Tenias, apéndice y canal anal", cards: [
    ["¿Qué son las tenias del colon?", "Tres bandas longitudinales gruesas de músculo liso."],
    ["¿Qué son las haustras?", "Saculaciones colónicas entre las tenias."],
    ["¿Qué son los apéndices omentales?", "Proyecciones adiposas de la serosa colónica."],
    ["¿Qué tipo de contracción del colon no propulsa el contenido?", "Segmentación."],
    ["¿Qué movimiento colónico vacía masivamente el colon distal?", "Peristaltismo masivo."],
    ["¿Con qué frecuencia suele ocurrir peristaltismo masivo en sanos?", "Aproximadamente una vez al día."],
    ["¿Qué diferencia muscular tiene el apéndice frente al colon?", "Tiene capa longitudinal externa continua, no tenias."],
    ["¿Qué rasgo histológico identifica al apéndice?", "Nódulos linfáticos abundantes que alcanzan submucosa."],
    ["¿Qué suele iniciar la apendicitis?", "Obstrucción luminal con moco o materia fecal."],
    ["¿Qué tumor enteroendocrino es frecuente en apéndice?", "Carcinoide."],
    ["¿Qué pliegues caracterizan el recto superior?", "Pliegues rectales transversos."],
    ["¿Qué pliegues longitudinales posee el canal anal superior?", "Columnas anales."],
    ["¿Cómo se llaman las depresiones entre columnas anales?", "Senos anales."],
    ["¿Qué epitelio cubre la zona colorrectal del canal anal?", "Cilíndrico simple."],
    ["¿Qué epitelio caracteriza la zona de transición anal?", "Cilíndrico o cúbico estratificado."],
    ["¿Qué epitelio cubre la zona escamosa anal?", "Plano estratificado continuo con piel perianal."],
    ["¿Qué secretan las glándulas anales?", "Moco."],
    ["¿Qué complicación pueden originar las glándulas anales?", "Fístulas anales."],
    ["¿Qué son las hemorroides internas?", "Dilataciones de venas submucosas del plexo rectal."],
    ["¿Qué condición favorece hemorroides internas?", "Hipertensión portal."],
    ["¿Qué forma el esfínter anal interno?", "Engrosamiento de músculo liso circular."],
    ["¿Qué forma el esfínter anal externo?", "Músculo estriado del periné."],
  ]},
  { topic: "Intestino delgado", subtopic: "Detalles celulares y digestión", cards: [
    ["¿Qué células de las criptas secretan fluido que equilibra la absorción de las vellosidades?", "Las células secretoras de las glándulas intestinales."],
    ["¿Qué hace el glucocáliz del enterocito además de recubrir microvellosidades?", "Contiene enzimas para la digestión final de carbohidratos y proteínas."],
    ["¿Qué estructuras aumentan la membrana lateral de los enterocitos para transporte?", "Pliegues y especializaciones laterales."],
    ["¿Qué células presentan gránulos secretores concentrados cerca de su base?", "Las células enteroendocrinas."],
    ["¿Qué tipo de célula enteroendocrina alcanza directamente la luz intestinal?", "La célula enteroendocrina abierta."],
    ["¿Qué diferencia una célula enteroendocrina cerrada de una abierta?", "La cerrada no alcanza la luz intestinal."],
    ["¿Qué hormona secretan células I ante lípidos y aminoácidos en duodeno?", "Colecistoquinina."],
    ["¿Qué hormona secretan células S en respuesta al quimo ácido?", "Secretina."],
    ["¿Qué hormona secretan las células K de duodeno y yeyuno?", "GIP."],
    ["¿Qué hormona secretan células Mo de duodeno y yeyuno?", "Motilina."],
    ["¿Qué hormona secretan células L de íleon y colon que aumenta insulina?", "GLP-1."],
    ["¿Qué hormona de células L inhibe la secreción ácida y el vaciamiento gástrico?", "PYY."],
    ["¿Qué célula intestinal contiene granos eosinófilos apicales ricos en sustancias antimicrobianas?", "La célula de Paneth."],
    ["¿Por qué las células de Paneth no son una población migratoria de la vellosidad?", "Porque permanecen en la base de la cripta hasta ser reemplazadas."],
    ["¿Qué hace una célula M con un antígeno intacto de la luz?", "Lo transporta al receso basal para células presentadoras de antígeno."],
    ["¿Qué recubre pobremente la superficie de una célula M en comparación con un enterocito?", "El glucocáliz."],
    ["¿Qué resultado inmunitario produce el muestreo antigénico por células M?", "Activación de una respuesta en el GALT."],
    ["¿Qué células de la lámina propia procesan antígenos antes de activar linfocitos?", "Macrófagos y otras células presentadoras de antígeno."],
    ["¿Qué proporción aproximada de la mucosa digestiva está ocupada por organización inmunitaria laxa según el texto?", "Alrededor de una cuarta parte."],
    ["¿Qué inmunoglobulina polimérica, además de IgA, puede llegar a la mucosa por transcitosis?", "IgM."],
    ["¿Qué hace el componente secretor con la IgA en la luz?", "Permanece unido al dímero y forma IgA secretora."],
    ["¿Qué efecto puede tener IgA secretora sobre bacterias adherentes?", "Enmascara sitios de adhesión y favorece aglomeración microbiana."],
    ["¿Qué mecanismo intestinal permite que aminoácidos lleguen a sangre y lípidos a linfa?", "Capilares sanguíneos para solutos hidrosolubles y quilífero para quilomicrones."],
    ["¿Qué segmento recibe el quimo gástrico antes de que actúen plenamente enzimas pancreáticas?", "El duodeno."],
    ["¿Qué rasgo hace especialmente alcalina la secreción de Brunner?", "Su contenido de bicarbonato y glucoproteínas alcalinas."],
  ]},
  { topic: "Intestino grueso", subtopic: "Detalles de pared y correlaciones", cards: [
    ["¿Qué capa longitudinal externa se condensa para formar tenias?", "La capa longitudinal de la muscular externa."],
    ["¿En qué partes del intestino grueso no hay tenias?", "Recto, canal anal y apéndice."],
    ["¿Qué estructura externa del colon contiene tejido adiposo y está cubierta por serosa?", "El apéndice omental."],
    ["¿Qué rasgo de la superficie mucosa colónica puede formar pliegues semilunares?", "Las contracciones de la muscular externa."],
    ["¿Qué tipo de célula colónica puede dividirse aun tras adquirir características caliciformes?", "La célula caliciforme en la región profunda de la cripta."],
    ["¿Cómo se ve una célula caliciforme agotada en la superficie colónica?", "Alta y delgada, con pocos gránulos de mucinógeno centroapicales."],
    ["¿Qué ocurre con el número de células absortivas hacia la profundidad de una cripta colónica?", "Disminuye mientras aumentan las caliciformes."],
    ["¿Qué enzimas digestivas se han comprobado en el glucocáliz colónico?", "No se ha comprobado que contenga enzimas digestivas."],
    ["¿Cuánto mide aproximadamente la meseta de colágeno en colon humano normal?", "Alrededor de 5 micrómetros."],
    ["¿Qué cambio de la meseta de colágeno puede verse en pólipos hiperplásicos?", "Puede engrosarse hasta tres veces."],
    ["¿Qué destino pueden adoptar fibroblastos pericrípticos al alcanzar superficie?", "Características morfológicas e histoquímicas de macrófagos."],
    ["¿Por qué el GALT está más desarrollado en colon que en segmentos proximales?", "Por la abundancia y diversidad de microorganismos y metabolitos luminales."],
    ["¿Hacia dónde drena finalmente la linfa de la pared colónica?", "Hacia nódulos linfáticos regionales."],
    ["¿Qué marcador se usa para estudiar endotelio linfático en colon?", "D2-40."],
    ["¿Qué lesión neoplásica intraepitelial protruye hacia la luz colónica?", "Un pólipo adenomatoso."],
    ["¿Qué examen permite detectar muchos pólipos de recto y colon sigmoide?", "Rectosigmoidoscopia."],
    ["¿Qué gen supresor se pierde tempranamente en la secuencia clásica de cáncer colorrectal?", "APC."],
    ["¿Qué protooncogén suele mutar para convertir un pólipo en adenoma benigno?", "K-Ras."],
    ["¿Qué genes supresores adicionales se asocian con adenocarcinoma invasor?", "p53 y DCC."],
    ["¿Qué tipo histológico constituye la mayoría de cánceres colorrectales?", "Adenocarcinoma."],
    ["¿Qué síntomas pueden alertar sobre cáncer colorrectal temprano?", "Cambio del hábito intestinal, sangrado rectal, cólicos, diarrea o estreñimiento persistente."],
    ["¿Qué capa externa tiene el colon donde contacta directamente estructuras retroperitoneales?", "Adventicia."],
    ["¿Qué capa externa tiene el resto peritoneal del colon?", "Serosa."],
    ["¿Qué vaso rectal participa en las hemorroides internas?", "El plexo venoso rectal de la submucosa."],
    ["¿Qué ocurre con la muscular de la mucosa al llegar a la zona de transición anal?", "Desaparece progresivamente."],
  ]},
  { topic: "Estómago", subtopic: "Células y casos integradores", cards: [
    ["¿Qué célula predomina en el cuello de la glándula fúndica y libera moco soluble?", "La célula mucosa del cuello."],
    ["¿Qué célula tiene canalículos y sistema tubulovesicular para regular secreción?", "La célula parietal."],
    ["¿Qué célula tiene RER basal y gránulos apicales de zimógeno?", "La célula principal."],
    ["¿Qué estímulo nervioso aumenta HCl por receptor M3?", "Acetilcolina vagal."],
    ["¿Qué sustancia inhibe la secreción ácida al reducir gastrina?", "Somatostatina."],
    ["¿Qué proceso activa al pepsinógeno secretado por células principales?", "La acidificación de la luz por HCl."],
    ["¿Qué vitamina queda comprometida primero de forma funcional en anemia perniciosa?", "Vitamina B12."],
    ["¿Qué epitelio cubre inmediatamente las fovéolas, no las glándulas profundas?", "Células mucosas superficiales cilíndricas simples."],
    ["¿Qué diferencia una glándula pilórica de una fúndica en una lámina?", "La pilórica tiene fovéolas profundas y glándulas más mucosas; la fúndica, parietales y principales."],
    ["¿Qué hormona eleva HCl desde células G sin ser secretada por una célula parietal?", "Gastrina."],
    ["¿Qué efecto tiene histamina liberada localmente en mucosa gástrica?", "Estimula receptores H2 de células parietales."],
    ["¿Qué alteración de Helicobacter pylori favorece su supervivencia en medio ácido?", "Producción de ureasa y amoníaco protector."],
    ["¿Qué célula del estómago presenta abundantes mitocondrias por la energía de secreción ácida?", "La célula parietal."],
    ["¿Qué consecuencia directa tiene bloquear H+/K+-ATPasa?", "Se reduce la secreción de ácido clorhídrico."],
    ["¿Qué células gástricas migran hacia superficie con recambio muy rápido?", "Las células mucosas superficiales."],
    ["¿Qué célula secretora gástrica puede originar un tumor neuroendocrino?", "Una célula enteroendocrina."],
    ["¿Qué síntoma endocrino puede producir exceso de serotonina de carcinoide?", "Rubor, diarrea o broncoconstricción."],
    ["¿Qué estructura mucosa permite que un estómago vacío se distienda sin desgarrarse?", "Las rugas formadas por mucosa y submucosa."],
    ["¿Qué capa muscular estomacal contribuye a la mezcla vigorosa del quimo?", "La capa oblicua interna."],
    ["¿Qué molécula protectora aumenta al estimular PGE2 la mucosa gástrica?", "Bicarbonato secretado hacia la capa de moco."],
  ]},
  { topic: "Capítulo 17", subtopic: "Repaso de detalles examinables", cards: [
    ["¿Qué capa contiene el plexo de Meissner pero no el de Auerbach?", "La submucosa."],
    ["¿Qué plexo se encuentra entre músculo circular y longitudinal, no en submucosa?", "El plexo de Auerbach."],
    ["¿Qué células parietales pueden ser binucleadas?", "Las células oxínticas de las glándulas fúndicas."],
    ["¿Qué célula gástrica tiene gránulos de zimógeno apicales?", "La célula principal."],
    ["¿Qué capa gástrica contiene las fovéolas, pero no las rugas completas?", "La mucosa."],
    ["¿Qué región gástrica secreta predominantemente moco y contiene células G?", "El antro pilórico."],
    ["¿Qué célula participa en absorción intestinal pero no secreta moco?", "El enterocito."],
    ["¿Qué célula secreta moco intestinal pero no posee borde estriado predominante?", "La célula caliciforme."],
    ["¿Qué estructura absorbe lípidos desde la vellosidad en vez de llevarlos primero a sangre portal?", "El quilífero central."],
    ["¿Qué célula de cripta libera defensinas sin ser una célula enteroendocrina?", "La célula de Paneth."],
    ["¿Qué superficie apical de célula M facilita captar antígenos en placas de Peyer?", "Los micropliegues apicales."],
    ["¿Qué segmento presenta Brunner en submucosa, no placas de Peyer extensas?", "El duodeno."],
    ["¿Qué segmento presenta placas de Peyer extensas, no glándulas de Brunner?", "El íleon."],
    ["¿Qué rasgo colónico permite absorber agua sin digerir nutrientes?", "Células absortivas con Na+/K+-ATPasa lateral abundante."],
    ["¿Qué capa de colágeno especial del colon se ubica bajo epitelio y regula transporte hídrico?", "La meseta de colágeno."],
    ["¿Qué estructura externa adiposa no debe confundirse con una tenia?", "Un apéndice omental."],
    ["¿Qué hallazgo macroscópico se forma entre tenias en colon?", "Haustras."],
    ["¿Qué parte del intestino grueso posee tenias y cuál no?", "Ciego y colon sí; recto, canal anal y apéndice no."],
    ["¿Qué zona anal conserva epitelio cilíndrico simple como el recto?", "La zona colorrectal."],
    ["¿Qué zona anal marca el cambio hacia epitelio escamoso?", "La zona de transición anal."],
    ["¿Qué esfínter es involuntario por ser músculo liso?", "El esfínter anal interno."],
    ["¿Qué esfínter es voluntario por estar compuesto de músculo estriado?", "El esfínter anal externo."],
  ]},
  { topic: "Capítulo 17", subtopic: "Identificación histológica", cards: [
    ["¿Qué combinación identifica duodeno en un corte?", "Vellosidades, criptas y glándulas de Brunner submucosas."],
    ["¿Qué combinación identifica yeyuno en un corte?", "Vellosidades largas y plicas prominentes sin Brunner."],
    ["¿Qué combinación identifica íleon en un corte?", "Vellosidades con placas de Peyer prominentes."],
    ["¿Qué combinación identifica colon en un corte?", "Sin vellosidades, criptas rectas profundas y muchas caliciformes."],
    ["¿Qué combinación identifica apéndice en un corte?", "Criptas colónicas, nódulos linfoides abundantes y muscular longitudinal continua."],
    ["¿Qué combinación identifica esófago en un corte?", "Epitelio plano estratificado no queratinizado y glándulas submucosas."],
    ["¿Qué combinación identifica estómago fúndico?", "Fovéolas cortas y glándulas con células parietales eosinófilas y principales basófilas."],
    ["¿Qué hallazgo separa de inmediato colon e intestino delgado?", "La ausencia de vellosidades en colon."],
    ["¿Qué hallazgo separa apéndice y colon?", "El apéndice no tiene tenias y tiene más nódulos linfáticos."],
    ["¿Qué hallazgo separa recto y colon?", "En recto la capa longitudinal es continua, sin tenias."],
  ]}
]

const slug = (value: string) => value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")

const subtopicFor = (group: Group, index: number) => {
  const sections: Record<string, readonly (readonly [number, string])[]> = {
    "Pared y sistema nervioso entérico": [[6, "Mucosa y submucosa"], [15, "Muscular externa y plexos"], [Infinity, "Serosa, adventicia y esfínteres"]],
    "Epitelio, músculo y glándulas": [[6, "Mucosa esofágica"], [14, "Glándulas esofágicas"], [Infinity, "Muscular externa y unión gastroesofágica"]],
    "Mucosa, regiones y protección": [[9, "Regiones y fovéolas"], [16, "Barrera mucosa"], [Infinity, "Pared gástrica"]],
    "Glándulas fúndicas": [[11, "Tipos celulares"], [23, "Secreción ácida y pepsina"], [Infinity, "Factor intrínseco y farmacología"]],
    "Hormonas, renovación y clínica": [[12, "Regulación enteroendocrina"], [18, "Clínica gástrica"], [Infinity, "Renovación epitelial"]],
    "Vellosidades y absorción": [[10, "Vellosidades y microvellosidades"], [18, "Absorción y transporte"], [Infinity, "Diferencias regionales"]],
    "Criptas, inmunidad y segmentos": [[8, "Células de Paneth y M"], [18, "Renovación de criptas"], [23, "IgA y GALT"], [Infinity, "Duodeno y glándulas de Brunner"]],
    "Colon y lámina propia": [[10, "Mucosa y células colónicas"], [14, "Renovación de criptas"], [Infinity, "Lámina propia y drenaje"]],
    "Tenias, apéndice y canal anal": [[6, "Tenias y haustras"], [10, "Ciego y apéndice"], [16, "Recto y canal anal"], [Infinity, "Esfínteres y hemorroides"]],
    "Detalles celulares y digestión": [[12, "Digestión y enteroendocrinas"], [18, "GALT y células M"], [Infinity, "Absorción intestinal"]],
    "Detalles de pared y correlaciones": [[10, "Mucosa y meseta de colágeno"], [16, "Linfáticos y pólipos"], [Infinity, "Cáncer y clínica colónica"]],
    "Células y casos integradores": [[8, "Células y secreción"], [14, "Regulación y Helicobacter"], [Infinity, "Protección y renovación"]],
    "Repaso de detalles examinables": [[7, "Pared y estómago"], [14, "Intestino delgado"], [18, "Colon y apéndice"], [Infinity, "Canal anal"]]
  }
  return sections[group.subtopic]?.find(([limit]) => index < limit)?.[1] ?? group.subtopic
}

export const cap17RebuiltFlashcards: Flashcard[] = groups.flatMap(group =>
  group.cards.map(([front, back], index) => {
    const subtopic = subtopicFor(group, index)
    return {
      id: `histo-cap17-${slug(subtopic)}-${String(index + 1).padStart(3, "0")}`,
      subject: "Histología", book: "Ross", chapter: "Capítulo 17", topic: group.topic, subtopic,
      front, back, tags: ["Capítulo 17", subtopic]
    }
  })
)
