import type { Flashcard } from "./cards"

type Fact = readonly [label: string, detail: string]
type Group = { topic: string; subtopic: string; facts: readonly Fact[] }

const groups: readonly Group[] = [
  { topic: "Hígado", subtopic: "Fundamentos del hígado", facts: [
    ["masa glandular hepática", "Es la masa glandular más grande del organismo y pesa cerca de 1500 g en el adulto."],
    ["ubicación del hígado", "Ocupa principalmente el cuadrante superior derecho y se extiende parcialmente al izquierdo."],
    ["cápsula de Glisson", "Cápsula de tejido conjuntivo que recubre el hígado y se continúa con el estroma portal."],
    ["superficie desnuda hepática", "Zona de adherencia al diafragma que carece de peritoneo visceral."],
    ["lóbulos anatómicos", "Lóbulos derecho, izquierdo, cuadrado y caudado definidos por rasgos externos."],
    ["segmentación funcional", "División quirúrgica basada en la distribución independiente de vasos y conductos biliares."],
  ]},
  { topic: "Hígado", subtopic: "Desarrollo y funciones generales", facts: [
    ["origen embrionario hepático", "Divertículo hepático endodérmico que surge del intestino anterior, en la región duodenal."],
    ["origen de los hepatocitos", "Proliferación de células endodérmicas del divertículo hepático."],
    ["origen del colédoco", "El tallo que conecta el divertículo hepático con el duodeno se transforma en el conducto biliar común."],
    ["origen de vesícula y conducto cístico", "Una evaginación del divertículo hepático forma la vesícula biliar y su conducto."],
    ["función exocrina hepática", "Producción de bilis y su liberación hacia el duodeno."],
    ["funciones metabólicas hepáticas", "Síntesis, almacenamiento, transformación y detoxificación de numerosas moléculas."],
  ]},
  { topic: "Fisiología hepática", subtopic: "Proteínas plasmáticas y lipoproteínas", facts: [
    ["síntesis de albúmina", "El hígado produce albúmina, proteína esencial para conservar la presión oncótica plasmática."],
    ["proteínas de coagulación hepáticas", "Incluyen protrombina y fibrinógeno, además de otros factores plasmáticos."],
    ["proteínas transportadoras hepáticas", "Haptoglobina, transferrina y hemopexina son glucoproteínas sintetizadas por el hígado."],
    ["función de VLDL", "Transporta triglicéridos desde el hígado hacia otros órganos."],
    ["función de LDL", "Lleva colesterol desde el hígado hacia los tejidos periféricos."],
    ["función de HDL", "Transporta colesterol desde los tejidos periféricos de regreso al hígado."],
  ]},
  { topic: "Fisiología hepática", subtopic: "Vitaminas y minerales", facts: [
    ["reserva hepática de vitamina A", "Se almacena como ésteres de retinilo principalmente en las células estrelladas hepáticas."],
    ["liberación de vitamina A", "El retinol sale unido a proteína fijadora de retinol, también sintetizada por el hígado."],
    ["conversión hepática de vitamina D", "El hígado transforma vitamina D3 en 25-hidroxicolecalciferol; el riñón completa su activación."],
    ["vitamina E", "El alfa-tocoferol actúa como antioxidante y su secreción hepática se relaciona con VLDL y alfa-TTP."],
    ["vitamina K", "Es necesaria para sintetizar protrombina y otros factores; su déficit favorece hemorragia."],
    ["almacenamiento de hierro", "El hierro se conserva en ferritina y hemosiderina; el exceso puede producir hemocromatosis."],
  ]},
  { topic: "Fisiología hepática", subtopic: "Cobre y enfermedad de Wilson", facts: [
    ["transporte portal del cobre", "Llega al hígado unido principalmente a albúmina e histidina."],
    ["función de ATP7B", "Incorpora cobre a la apoceruloplasmina y facilita su excreción por la bilis."],
    ["enfermedad de Wilson", "Trastorno autosómico recesivo por mutaciones de ATP7B."],
    ["ceruloplasmina en Wilson", "Suele estar disminuida porque el cobre no se incorpora adecuadamente a la apoceruloplasmina."],
    ["acumulación de cobre en Wilson", "El cobre se acumula primero en hígado y después puede afectar encéfalo y otros tejidos."],
    ["tratamiento de Wilson", "Quelación o zinc para reducir cobre; el trasplante puede ser necesario en daño hepático grave."],
  ]},
  { topic: "Fisiología hepática", subtopic: "Detoxificación y metabolismo", facts: [
    ["fase I de detoxificación", "Oxidación, hidroxilación o carboxilación mediante citocromos P450 del REL y mitocondrias."],
    ["fase II de detoxificación", "Conjugación con moléculas como ácido glucurónico, glicina o taurina para aumentar solubilidad."],
    ["respuesta del REL a fármacos", "Alcohol, fenobarbital y otros compuestos pueden inducir hipertrofia del REL hepatocitario."],
    ["glucógeno hepático", "Después de comer, glucosa-6-fosfato puede almacenarse como glucógeno; en ayuno ocurre glucogenólisis."],
    ["cuerpos cetónicos", "El hígado los produce a partir de ácidos grasos, pero no puede utilizarlos como combustible."],
    ["amonio y urea", "La desaminación genera amonio, que el hígado convierte en urea para su eliminación."],
  ]},
  { topic: "Fisiología hepática", subtopic: "Bilis y función endocrina", facts: [
    ["ácidos biliares primarios", "Ácido cólico y ácido quenodesoxicólico, sintetizados por hepatocitos a partir de colesterol."],
    ["ácidos biliares secundarios", "Ácidos desoxicólico y litocólico, formados por acción de la microbiota intestinal."],
    ["circulación enterohepática", "Cerca del 90% de las sales biliares se reabsorbe en intestino delgado y vuelve al hígado."],
    ["bilirrubina conjugada", "Se excreta como glucurónidos en la bilis y no participa en el reciclaje de sales biliares."],
    ["producción diaria de bilis", "El hígado produce aproximadamente un litro de bilis al día."],
    ["funciones endocrinas hepáticas", "Convierte T4 en T3, produce IGF-1 y degrada hormonas como insulina y glucagón."],
  ]},
  { topic: "Hígado", subtopic: "Irrigación hepática", facts: [
    ["aporte de la vena porta", "Proporciona alrededor del 75% del flujo hepático con sangre venosa rica en nutrientes."],
    ["aporte de la arteria hepática", "Aporta cerca del 25% del flujo con sangre oxigenada procedente del tronco celíaco."],
    ["mezcla sanguínea hepática", "La sangre portal y arterial se mezcla en los sinusoides antes de alcanzar los hepatocitos."],
    ["contenido de la sangre portal", "Nutrientes y tóxicos intestinales, productos eritrocitarios y secreciones endocrinas digestivas."],
    ["dirección del flujo sanguíneo", "Desde ramas portales periféricas hacia la vena central de cada lobulillo."],
    ["drenaje venoso", "Venas centrales a sublobulillares, luego venas hepáticas y finalmente vena cava inferior."],
  ]},
  { topic: "Hígado", subtopic: "Lobulillo hepático clásico", facts: [
    ["forma del lobulillo clásico", "Unidad aproximadamente hexagonal con una vena central y espacios portales en sus vértices."],
    ["placas de hepatocitos", "Cordones radiales de una célula de espesor en el adulto, separados por sinusoides."],
    ["placas hepáticas infantiles", "Pueden conservar dos células de espesor hasta aproximadamente los seis años."],
    ["tríada portal", "Rama de vena porta, rama de arteria hepática y conducto biliar; suele acompañarse de linfáticos."],
    ["tejido conjuntivo interlobulillar humano", "Es escaso y hace menos definidos los límites lobulillares que en el hígado porcino."],
    ["espacio de Mall", "Espacio entre el estroma portal y hepatocitos periféricos donde se origina parte de la linfa."],
  ]},
  { topic: "Hígado", subtopic: "Lobulillo portal y ácino hepático", facts: [
    ["lobulillo portal", "Unidad triangular centrada en un conducto biliar y delimitada por tres venas centrales próximas."],
    ["utilidad del lobulillo portal", "Destaca la función exocrina y el territorio que drena bilis a un mismo conducto."],
    ["forma del ácino hepático", "Unidad romboidal cuya dimensión corta sigue ramas portales terminales y la larga une venas centrales."],
    ["utilidad del ácino", "Correlaciona mejor perfusión, actividad metabólica y patrones de lesión."],
    ["zona 1 del ácino", "Zona periportal que recibe primero oxígeno, nutrientes y sustancias tóxicas."],
    ["zona 3 del ácino", "Zona centrolobulillar que recibe menos oxígeno y es la primera en sufrir necrosis isquémica."],
  ]},
  { topic: "Hígado", subtopic: "Zonas acinares y lesión", facts: [
    ["regeneración de la zona 1", "Es la primera zona en regenerarse y la última en morir cuando disminuye la perfusión."],
    ["obstrucción biliar y zona 1", "Los cambios por obstrucción biliar aparecen primero en la región periportal."],
    ["acumulación grasa y zona 3", "La región centrolobulillar suele ser la primera en acumular lípidos."],
    ["toxinas y zona 3", "La zona 3 responde tarde a toxinas y estasis biliar, pero es vulnerable a metabolitos generados por P450."],
    ["insuficiencia cardíaca congestiva", "La hipoperfusión puede causar necrosis centrolobulillar y vacuolas lipídicas."],
    ["sobredosis de paracetamol", "Agota glutatión y permite que NAPQI lesione sobre todo hepatocitos de la zona 3."],
  ]},
  { topic: "Hígado", subtopic: "Sinusoides y células de Kupffer", facts: [
    ["endotelio sinusoidal", "Endotelio discontinuo con fenestras sin diafragma, grandes espacios y lámina basal incompleta o ausente."],
    ["función de las fenestras", "Facilitan intercambio entre plasma sinusoidal y microvellosidades hepatocitarias del espacio de Disse."],
    ["células de Kupffer", "Macrófagos derivados de monocitos que forman parte del revestimiento sinusoidal."],
    ["unión de Kupffer al endotelio", "No establecen uniones con las células endoteliales vecinas."],
    ["función eritrofagocítica", "Eliminan eritrocitos envejecidos y pueden acumular ferritina y hemosiderina."],
    ["Kupffer tras esplenectomía", "Adquieren mayor importancia en la eliminación de eritrocitos cuando falta el bazo."],
  ]},
  { topic: "Hígado", subtopic: "Espacio de Disse y células estrelladas", facts: [
    ["espacio de Disse", "Espacio perisinusoidal entre hepatocitos y endotelio o células de Kupffer."],
    ["microvellosidades hepatocitarias", "Se proyectan hacia Disse y pueden multiplicar unas seis veces el área de intercambio."],
    ["secreciones hacia sangre", "Todas las secreciones hepatocitarias excepto la bilis atraviesan el espacio de Disse."],
    ["hematopoyesis en Disse", "Ocurre durante la vida fetal y puede reaparecer en adultos con anemia crónica."],
    ["células de Ito", "Células estrelladas mesenquimatosas perisinusoidales que almacenan vitamina A."],
    ["activación de células de Ito", "En lesión crónica pierden lípidos, adquieren fenotipo miofibroblástico y producen colágeno I y III."],
  ]},
  { topic: "Hígado", subtopic: "Fibrosis y linfa hepática", facts: [
    ["marcadores de células estrelladas activadas", "Desmina y alfa-actina de músculo liso."],
    ["contracción de células estrelladas", "Aumenta la resistencia sinusoidal y contribuye a hipertensión portal."],
    ["origen principal de linfa hepática", "Plasma que entra al espacio de Disse y se dirige hacia espacios de Mall."],
    ["dirección de la linfa hepática", "Hacia los espacios portales, en la misma dirección general que la bilis."],
    ["drenaje linfático mayoritario", "Cerca del 80% de la linfa hepática alcanza el conducto torácico."],
    ["importancia cuantitativa de la linfa hepática", "El hígado aporta una fracción principal de la linfa que circula por el conducto torácico."],
  ]},
  { topic: "Hepatocitos", subtopic: "Morfología del hepatocito", facts: [
    ["proporción de hepatocitos", "Constituyen cerca del 80% de la población celular del hígado."],
    ["tamaño y forma", "Células poligonales de aproximadamente 20 a 30 micrómetros."],
    ["núcleo hepatocitario", "Grande, esférico y central; muchas células adultas son binucleadas o tetraploides."],
    ["vida media del hepatocito", "Aproximadamente cinco meses, con gran capacidad regenerativa."],
    ["polaridad basal", "Las superficies basales miran hacia sinusoides y espacio de Disse."],
    ["polaridad apical", "Las superficies laterales contiguas forman los canalículos biliares."],
  ]},
  { topic: "Hepatocitos", subtopic: "Orgánulos e inclusiones", facts: [
    ["mitocondrias hepatocitarias", "Cada célula contiene aproximadamente 800 a 1000 mitocondrias."],
    ["glucógeno", "Inclusión citoplasmática PAS positiva cuya cantidad varía con el estado nutricional."],
    ["gotas lipídicas", "Se demuestran con colorantes liposolubles y aumentan por alcohol o tóxicos."],
    ["peroxisomas", "Existen unos 200 a 300 por hepatocito y participan en oxidación, gluconeogénesis y metabolismo de purinas."],
    ["catalasa", "Enzima peroxisómica que degrada peróxido de hidrógeno en agua y oxígeno."],
    ["lisosomas peribiliares", "Contienen lipofuscina, organelos parcialmente digeridos, figuras de mielina e hierro."],
  ]},
  { topic: "Hepatocitos", subtopic: "REL, Golgi y peroxisomas", facts: [
    ["papel del REL", "Detoxificación, conjugación, síntesis de colesterol y metabolismo de lípidos y lipoproteínas."],
    ["oxidación peroxisómica del alcohol", "Una parte importante del etanol puede convertirse en acetaldehído en peroxisomas."],
    ["aparatos de Golgi", "Puede haber hasta 50 dictiosomas por hepatocito, cada uno con varias cisternas."],
    ["Golgi pericanalicular", "Se relaciona con productos dirigidos hacia la bilis."],
    ["Golgi sinusoidal", "Contiene precursores de VLDL, otras lipoproteínas y productos endocrinos."],
    ["lisosomas en colestasis", "Aumentan cuando se acumulan productos biliares y también en hepatitis viral o anemia."],
  ]},
  { topic: "Árbol biliar", subtopic: "Canalículos y conductos de Hering", facts: [
    ["canalículo biliar", "Conducto de aproximadamente 0.5 micrómetros formado por surcos enfrentados de dos hepatocitos."],
    ["aislamiento del canalículo", "Uniones ocluyentes evitan que la bilis escape hacia el espacio intercelular y la sangre."],
    ["superficie canalicular", "Posee microvellosidades y enzimas como ATPasa y fosfatasa alcalina, compatibles con secreción activa."],
    ["conducto de Hering", "Segmento de transición revestido parcialmente por hepatocitos y parcialmente por colangiocitos cúbicos."],
    ["nicho progenitor de Hering", "Puede originar hepatocitos y colangiocitos después de una lesión importante."],
    ["lesión del conducto de Hering", "Puede producir colestasis intrahepática."],
  ]},
  { topic: "Árbol biliar", subtopic: "Colangiocitos y conductos", facts: [
    ["colangiocitos", "Células cúbicas pequeñas en ductulillos que se hacen cilíndricas al aumentar el calibre."],
    ["cilio primario del colangiocito", "Sensor apical no móvil que detecta cambios del flujo biliar."],
    ["ductulillo biliar intrahepático", "Segmento revestido por completo por colangiocitos, a diferencia del conducto de Hering."],
    ["conductos interlobulillares", "Se ubican en tríadas portales y miden aproximadamente 15 a 40 micrómetros."],
    ["conductos hepáticos", "Los conductos intrahepáticos convergen en conductos hepáticos derecho e izquierdo y después en el común."],
    ["conductos de Luschka", "Restos embrionarios cerca del cuello vesicular que suelen comunicarse con el conducto cístico."],
  ]},
  { topic: "Árbol biliar", subtopic: "Conductos extrahepáticos y esfínteres", facts: [
    ["conducto hepático común", "Mide cerca de 3 cm y posee las capas gastrointestinales excepto muscular de la mucosa."],
    ["válvula espiral de Heister", "Pliegue del conducto cístico que regula pasivamente el flujo, sin ser un esfínter histológico."],
    ["conducto colédoco", "Mide aproximadamente 7 cm y conduce bilis hacia la ampolla hepatopancreática."],
    ["esfínter de Boyden", "Músculo circular del colédoco que regula el ingreso de bilis a la ampolla."],
    ["esfínter de Oddi", "Deriva de la muscular externa duodenal y controla la ampolla hepatopancreática."],
    ["ampolla de Vater", "Región donde desembocan el colédoco y el conducto pancreático principal antes de abrirse al duodeno."],
  ]},
  { topic: "Vesícula biliar", subtopic: "Organización de la vesícula", facts: [
    ["capacidad vesicular", "Órgano piriforme distensible que almacena alrededor de 50 mL."],
    ["concentración de la bilis", "Elimina cerca del 90% del agua y puede concentrar la bilis hasta diez veces."],
    ["pliegues mucosos", "Son profundos cuando la vesícula está vacía y se aplanan con la distensión."],
    ["epitelio vesicular", "Epitelio cilíndrico simple de colangiocitos con microvellosidades cortas."],
    ["ausencia de capas", "La vesícula no posee muscular de la mucosa ni submucosa."],
    ["capa muscular", "Fascículos de músculo liso orientados irregularmente entre colágeno y fibras elásticas."],
  ]},
  { topic: "Vesícula biliar", subtopic: "Mucosa, cubierta y clínica vesicular", facts: [
    ["lámina propia vesicular", "Contiene capilares fenestrados, vénulas y células inmunitarias, pero carece de linfáticos."],
    ["glándulas mucosas vesiculares", "Se concentran en el cuello y aumentan durante inflamación crónica."],
    ["superficie adherida al hígado", "Está cubierta por adventicia."],
    ["superficie libre vesicular", "Está cubierta por serosa."],
    ["senos de Rokitansky-Aschoff", "Divertículos profundos de mucosa que atraviesan la muscular por hiperplasia o herniación patológica."],
    ["estimulación de vaciamiento", "La presencia de grasas en duodeno induce hormonas que contraen la vesícula y relajan la salida biliar."],
  ]},
  { topic: "Vesícula biliar", subtopic: "Concentración de la bilis", facts: [
    ["transporte de electrolitos", "Na+, Cl− y HCO3− pasan hacia espacios intercelulares laterales del epitelio vesicular."],
    ["movimiento del agua", "Sigue osmóticamente a los electrolitos mediante acuaporinas como AQP1 y AQP8."],
    ["pliegues laterales celulares", "Amplían la superficie para transporte de agua y electrolitos."],
    ["mitocondrias epiteliales", "Son abundantes en regiones apical y basal para sostener transporte activo."],
    ["destino del líquido absorbido", "La presión hidrostática lo impulsa hacia la lámina propia y capilares fenestrados."],
    ["producto de la absorción", "El líquido que abandona la luz es aproximadamente isotónico aunque la bilis se concentra."],
  ]},
  { topic: "Páncreas", subtopic: "Fundamentos del páncreas", facts: [
    ["ubicación pancreática", "La cabeza ocupa la curva duodenal, el cuerpo cruza la línea media y la cola llega al hilio esplénico."],
    ["conducto de Wirsung", "Conducto pancreático principal que recorre la glándula y suele unirse al colédoco."],
    ["conducto de Santorini", "Conducto accesorio que desemboca en la papila menor y refleja el origen embrionario doble."],
    ["cápsula pancreática", "Capa delgada de tejido conjuntivo laxo que envía tabiques y divide lobulillos poco definidos."],
    ["porción exocrina", "Acinos serosos y conductos que producen enzimas digestivas y bicarbonato."],
    ["porción endocrina", "Islotes de Langerhans que secretan hormonas a capilares fenestrados."],
  ]},
  { topic: "Páncreas exocrino", subtopic: "Acinos pancreáticos", facts: [
    ["tipo de adenómero", "Acinos serosos o tubuloacinosos de células piramidales con muy poco tejido conjuntivo periacinar."],
    ["basofilia basal acinar", "Se debe al abundante retículo endoplásmico rugoso para síntesis de enzimas."],
    ["gránulos de cimógeno", "Se concentran en el polo apical y son más numerosos durante el ayuno."],
    ["células centroacinares", "Células pálidas y planas que señalan el inicio del conducto intercalar dentro del acino."],
    ["rasgo diferencial pancreático", "Es la única glándula con células centroacinares visibles dentro de sus acinos."],
    ["activación de cimógenos", "La enteropeptidasa activa tripsinógeno y la tripsina activa otros precursores proteolíticos."],
  ]},
  { topic: "Páncreas exocrino", subtopic: "Enzimas y conductos pancreáticos", facts: [
    ["endopeptidasas pancreáticas", "Tripsinógeno y quimotripsinógeno se convierten en enzimas que cortan enlaces internos."],
    ["exopeptidasas pancreáticas", "Procarboxipeptidasas y proaminopeptidasas liberan aminoácidos desde extremos peptídicos."],
    ["otras enzimas pancreáticas", "Alfa-amilasa, lipasas, desoxirribonucleasa y ribonucleasa."],
    ["secuencia ductal", "Centroacinar, intercalar de Boll, colector intralobulillar, interlobulillar y conducto principal."],
    ["conductos estriados", "No existen en el páncreas, diferencia útil frente a glándulas salivales."],
    ["epitelio de conductos grandes", "Se vuelve cilíndrico bajo y puede incluir células caliciformes y enteroendocrinas."],
  ]},
  { topic: "Páncreas exocrino", subtopic: "Secreción pancreática", facts: [
    ["volumen diario pancreático", "El páncreas produce alrededor de un litro de líquido exocrino al día."],
    ["secreción acinar", "Volumen pequeño rico en proteínas y enzimas digestivas."],
    ["secreción de conductos de Boll", "Volumen abundante, rico en sodio y bicarbonato y pobre en enzimas."],
    ["función del bicarbonato", "Neutraliza el ácido gástrico y establece un pH favorable para enzimas pancreáticas."],
    ["secretina", "Péptido de 27 aminoácidos que estimula secreción ductal abundante rica en bicarbonato."],
    ["colecistocinina", "Péptido de 33 aminoácidos que estimula células acinares para liberar proenzimas."],
  ]},
  { topic: "Páncreas endocrino", subtopic: "Islotes de Langerhans", facts: [
    ["cantidad de islotes", "Hay entre uno y tres millones, equivalentes a cerca del 1 al 2% de la masa pancreática."],
    ["distribución de islotes", "Son más numerosos en la cola del páncreas."],
    ["aspecto con H&E", "Agrupaciones celulares pálidas entre acinos exocrinos más intensamente teñidos."],
    ["organización insular", "Cordones celulares cortos e irregulares alrededor de una extensa red de capilares fenestrados."],
    ["perfusión insular", "Reciben aproximadamente 10 a 15% del flujo pancreático pese a su pequeña masa."],
    ["inicio del desarrollo endocrino", "Las células endocrinas definitivas aparecen aproximadamente entre semanas 9 y 12."],
  ]},
  { topic: "Páncreas endocrino", subtopic: "Células A, B y D", facts: [
    ["células B", "Constituyen 60 a 70%, suelen ocupar el centro y producen insulina."],
    ["gránulos de células B", "Miden cerca de 300 nm y muestran un centro cristalino angular denso con halo claro."],
    ["células A", "Constituyen 15 a 20%, suelen ser periféricas y producen glucagón."],
    ["gránulos de células A", "Miden cerca de 250 nm y tienen centro denso excéntrico con halo claro."],
    ["células D", "Constituyen 5 a 10%, suelen ser periféricas y secretan somatostatina."],
    ["gránulos de células D", "Miden 300 a 350 nm y poseen contenido homogéneo de densidad baja o intermedia."],
  ]},
  { topic: "Páncreas endocrino", subtopic: "Células insulares minoritarias", facts: [
    ["células PP o F", "Producen polipéptido pancreático, que inhibe secreción pancreática y actividad biliar y digestiva."],
    ["células D1", "Secretan péptido intestinal vasoactivo, relacionado con secreción y motilidad intestinal."],
    ["células EC", "Pueden producir secretina, motilina y sustancia P."],
    ["células épsilon", "Secretan grelina, hormona que estimula el apetito."],
    ["gastrinoma", "Tumor endocrino que produce gastrina y puede causar síndrome de Zollinger-Ellison."],
    ["proporción minoritaria", "Las células distintas de A, B y D representan en conjunto alrededor del 5% del islote."],
  ]},
  { topic: "Páncreas endocrino", subtopic: "Acciones de insulina y glucagón", facts: [
    ["captación de glucosa por insulina", "Favorece translocación de GLUT4 en músculo y tejido adiposo."],
    ["almacenamiento de glucógeno", "La insulina activa glucógeno sintasa e inhibe glucógeno fosforilasa."],
    ["efecto lipídico de insulina", "Estimula lipoproteína lipasa, captación de ácidos grasos y lipogénesis."],
    ["efecto proteico de insulina", "Aumenta captación de aminoácidos y síntesis proteica mediante vías como mTOR."],
    ["acción del glucagón", "Eleva glucemia mediante gluconeogénesis y glucogenólisis hepáticas."],
    ["somatostatina insular", "Inhibe secreción tanto de insulina y glucagón como del páncreas exocrino."],
  ]},
  { topic: "Páncreas endocrino", subtopic: "Regulación de los islotes", facts: [
    ["umbral estimulante de insulina", "Glucemia por encima de unos 70 mg/dL favorece secreción de insulina."],
    ["otros estímulos de células B", "Aminoácidos, ácidos grasos y hormonas digestivas como gastrina, CCK y secretina."],
    ["estimulación de glucagón", "Glucemia inferior a unos 70 mg/dL y concentraciones bajas de ácidos grasos."],
    ["control paracrino", "CCK y glucagón pueden estimular células B, mientras insulina inhibe células A."],
    ["parasimpático", "Puede aumentar secreción tanto de insulina como de glucagón."],
    ["simpático", "Tiende a aumentar glucagón e inhibir insulina."],
  ]},
  { topic: "Páncreas endocrino", subtopic: "Síntesis de insulina y péptido C", facts: [
    ["preproinsulina", "Cadena inicial de unos 110 aminoácidos con un péptido señal de 24 aminoácidos."],
    ["proinsulina", "Producto del RER después de retirar el péptido señal; se transporta al aparato de Golgi."],
    ["insulina madura", "Dos cadenas, A de 21 aminoácidos y B de 30, unidas por puentes disulfuro."],
    ["formación de péptido C", "Proteasas tipo catepsina eliminan el segmento conector durante el procesamiento en Golgi y gránulos."],
    ["secreción equimolar", "Insulina y péptido C se liberan en cantidades equivalentes."],
    ["utilidad del péptido C", "Evalúa secreción endógena de células B porque dura más y se elimina por riñón."],
  ]},
  { topic: "Páncreas endocrino", subtopic: "Perfusión insuloacinar y correlación clínica", facts: [
    ["flujo insular humano", "Es probable que la sangre alcance primero células A y D periféricas antes que células B centrales."],
    ["sistema porta insuloacinar", "Capilares eferentes del islote forman redes alrededor de acinos exocrinos."],
    ["estímulos exocrinos insulares", "Insulina, VIP y CCK estimulan secreción exocrina."],
    ["inhibidores exocrinos insulares", "Glucagón, polipéptido pancreático y somatostatina inhiben secreción exocrina."],
    ["diabetes mellitus", "La insuficiencia de insulina produce hiperglucemia, glucosuria y complicaciones sistémicas."],
    ["insulina y enfermedad de Alzheimer", "Se ha relacionado resistencia o reducción de señal de insulina cerebral con neurodegeneración."],
  ]},
]

const slug = (value: string) => value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")

export const cap18Flashcards: Flashcard[] = groups.flatMap(group =>
  group.facts.flatMap(([label, detail], index) => {
    const base = `histo-cap18-${slug(group.subtopic)}-${String(index + 1).padStart(3, "0")}`
    const common = {
      subject: "Histología",
      book: "Ross",
      chapter: "Capítulo 18",
      topic: group.topic,
      subtopic: group.subtopic,
      tags: ["Capítulo 18", group.subtopic]
    }

    return [
      { ...common, id: `${base}-a`, front: `En ${group.subtopic.toLowerCase()}, ¿qué caracteriza a ${label}?`, back: detail },
      { ...common, id: `${base}-b`, front: `En ${group.subtopic.toLowerCase()}, ¿qué concepto corresponde a esta descripción: ${detail}`, back: label }
    ]
  })
)
