import type { Flashcard } from "./cards"

type Fact = readonly [label: string, detail: string]
type Group = { topic: string; subtopic: string; facts: readonly Fact[] }

const groups: readonly Group[] = [
  { topic: "Tubo digestivo", subtopic: "Organización general de la pared", facts: [
    ["capas del tubo digestivo", "Mucosa, submucosa, muscular externa y serosa o adventicia, desde la luz hacia afuera."],
    ["componentes de la mucosa", "Epitelio, lámina propia y muscular de la mucosa."],
    ["funciones principales de la mucosa", "Protección, absorción y secreción."],
    ["composición de la submucosa", "Tejido conjuntivo denso irregular con vasos, linfáticos, nervios y, en ciertos segmentos, glándulas."],
    ["organización habitual de la muscular externa", "Una capa circular interna y una longitudinal externa de músculo liso."],
    ["serosa", "Mesotelio y una capa delgada de tejido conjuntivo; corresponde al peritoneo visceral."],
    ["adventicia", "Tejido conjuntivo sin mesotelio que fija el órgano a estructuras vecinas."],
    ["glándulas mucosas", "Glándulas situadas en la lámina propia de la mucosa."],
    ["glándulas submucosas", "Glándulas cuyos adenómeros se encuentran en la submucosa y cuyos conductos atraviesan la mucosa."],
    ["glándulas extramurales", "Hígado y páncreas, cuyos conductos llevan secreciones al duodeno."],
  ]},
  { topic: "Tubo digestivo", subtopic: "Amplificación, mucosa y motilidad", facts: [
    ["pliegues circulares", "Elevaciones permanentes con un centro de submucosa que aumentan la superficie del intestino delgado."],
    ["vellosidades intestinales", "Proyecciones de la mucosa con un centro de lámina propia."],
    ["microvellosidades", "Proyecciones apicales de enterocitos que producen la mayor amplificación de la superficie absortiva."],
    ["glucocáliz enterocitario", "Cubierta apical que contiene enzimas terminales para la digestión de nutrientes."],
    ["capilares de la lámina propia", "Capilares fenestrados que reciben la mayoría de los nutrientes hidrosolubles absorbidos."],
    ["vasos linfáticos mucosos", "Vía de transporte para lípidos y algunas proteínas absorbidas."],
    ["GALT", "Tejido linfático asociado al intestino que protege la mucosa frente a antígenos luminales."],
    ["placas de Peyer", "Agregados de nódulos linfáticos del íleon, especialmente en su lado antimesentérico."],
    ["muscular de la mucosa", "Músculo liso circular interno y longitudinal externo que mueve localmente la mucosa, independientemente del peristaltismo."],
    ["contracción circular", "Constricción de la luz que mezcla el contenido y participa en su propulsión."],
    ["contracción longitudinal", "Acortamiento del segmento digestivo que ayuda a propulsar el contenido."],
  ]},
  { topic: "Sistema nervioso entérico", subtopic: "Plexos y esfínteres", facts: [
    ["plexo de Meissner", "Plexo submucoso que regula principalmente secreción, flujo sanguíneo y actividad de la muscular de la mucosa."],
    ["plexo de Auerbach", "Plexo mientérico situado entre las capas circular y longitudinal de la muscular externa."],
    ["esfínter faringoesofágico", "Evita la entrada de aire en el esófago."],
    ["esfínter esofágico inferior", "Barrera fisiológica contra el reflujo, apoyada por el diafragma."],
    ["esfínter pilórico", "Controla el paso del quimo al duodeno."],
    ["relajación pilórica", "Depende de neuronas que producen óxido nítrico mediante óxido nítrico sintasa."],
    ["esfínter ileocecal", "Impide el reflujo del contenido colónico rico en bacterias hacia el íleon."],
    ["esfínter anal interno", "Evita que las heces ingresen al conducto anal cuando este no está distendido."],
    ["músculo esofágico superior", "Músculo estriado, una excepción a la organización lisa habitual de la muscular externa."],
    ["capa oblicua gástrica", "Tercera disposición de músculo liso que ayuda a mezclar el contenido del estómago."],
    ["tenias del colon", "Tres bandas engrosadas de músculo longitudinal externo del colon."],
  ]},
  { topic: "Esófago", subtopic: "Mucosa y organización", facts: [
    ["longitud aproximada del esófago", "Unos 25 cm."],
    ["luz esofágica colapsada", "Presenta un contorno irregular o ramificado debido a pliegues longitudinales."],
    ["epitelio esofágico", "Epitelio plano estratificado no queratinizado que resiste la abrasión."],
    ["gránulos de queratohialina esofágicos", "Pueden aparecer ocasionalmente en las células superficiales, aunque el epitelio suele no estar queratinizado."],
    ["lámina propia esofágica", "Tejido conjuntivo con vasos, infiltración linfocítica difusa y nódulos cerca de conductos glandulares."],
    ["muscular de la mucosa esofágica", "Predomina músculo liso longitudinal y comienza cerca del cartílago cricoides."],
    ["submucosa esofágica", "Contiene vasos, plexo de Meissner y glándulas esofágicas propiamente dichas."],
    ["tercio superior de la muscular externa esofágica", "Músculo estriado."],
    ["tercio medio de la muscular externa esofágica", "Mezcla de músculo estriado y liso."],
    ["tercio inferior de la muscular externa esofágica", "Músculo liso."],
    ["cubierta externa predominante del esófago", "Adventicia que se continúa con el tejido conjuntivo circundante."],
    ["segmento abdominal del esófago", "Segmento libre de apenas 1 a 2 cm cubierto por serosa."],
  ]},
  { topic: "Esófago", subtopic: "Glándulas e inervación", facts: [
    ["glándulas esofágicas propiamente dichas", "Glándulas tubuloacinares compuestas de la submucosa, más concentradas en la mitad superior."],
    ["secreción de las glándulas esofágicas propias", "Moco viscoso ligeramente ácido que lubrica la pared."],
    ["conductos de glándulas esofágicas propias", "Conductos revestidos por epitelio estratificado que atraviesan la mucosa."],
    ["glándulas cardíacas esofágicas", "Glándulas de la lámina propia ubicadas principalmente en los extremos inicial y terminal."],
    ["secreción de las glándulas cardíacas esofágicas", "Moco neutro que protege la mucosa frente al contenido gástrico refluido."],
    ["inervación del músculo esofágico estriado", "Fibras somáticas del nervio vago originadas en el núcleo ambiguo."],
    ["inervación del músculo esofágico liso", "Fibras viscerales vagales originadas en el núcleo motor dorsal."],
    ["contracción esofágica coordinada", "Onda peristáltica que lleva el bolo desde la faringe hasta el estómago."],
  ]},
  { topic: "Estómago", subtopic: "Regiones, pliegues y mucosa superficial", facts: [
    ["función mecánica del estómago", "Mezcla el alimento con el jugo gástrico y produce quimo."],
    ["regiones histológicas gástricas", "Cardíaca, fúndica y pilórica, definidas por el tipo de glándula."],
    ["pliegues gástricos", "Elevaciones de mucosa y submucosa que desaparecen al distenderse el estómago."],
    ["función de los pliegues gástricos", "Permitir la expansión del estómago, no aumentar permanentemente su área."],
    ["áreas mamiliformes", "Pequeñas elevaciones separadas por surcos que aumentan ligeramente la superficie secretora."],
    ["fovéolas gástricas", "Invaginaciones del epitelio superficial en cuya base desembocan las glándulas."],
    ["epitelio superficial gástrico", "Epitelio cilíndrico simple compuesto por células mucosas superficiales."],
    ["célula mucosa superficial", "Célula cilíndrica con copa apical de mucinógeno y núcleo y Golgi ubicados por debajo."],
    ["moco visible gástrico", "Capa viscosa rica en bicarbonato y potasio que protege el epitelio."],
    ["bicarbonato superficial", "Queda atrapado en el moco y mantiene un microambiente relativamente neutro junto a las células."],
    ["absorción gástrica", "Es limitada, pero incluye agua, sales y algunos compuestos liposolubles."],
  ]},
  { topic: "Estómago", subtopic: "Barrera y citoprotección gástrica", facts: [
    ["primera línea de defensa gástrica", "La barrera física y química de moco y bicarbonato."],
    ["segunda línea de defensa gástrica", "Flujo sanguíneo mucoso regulado por prostaglandinas, óxido nítrico y neuropéptidos."],
    ["acción citoprotectora de PGE2", "Estimula bicarbonato, mantiene el espesor del moco y produce vasodilatación."],
    ["acción citoprotectora del óxido nítrico", "Mantiene el flujo sanguíneo de la mucosa."],
    ["efecto de AINE sobre la mucosa", "Inhiben prostaglandinas y pueden alterar la barrera hidrófoba, favoreciendo lesión."],
    ["citoprotección gástrica", "Conjunto de mecanismos que conservan la integridad mucosa pese al ácido y las enzimas."],
    ["restitución epitelial gástrica", "Migración rápida de células vecinas para cerrar lesiones superficiales."],
    ["flujo sanguíneo mucoso", "Retira el ácido difundido y aporta bicarbonato, oxígeno y nutrientes para reparación."],
  ]},
  { topic: "Estómago", subtopic: "Glándulas fúndicas", facts: [
    ["glándula fúndica", "Glándula tubular simple ramificada que se extiende desde una fovéola hasta la muscular de la mucosa."],
    ["partes de la glándula fúndica", "Istmo corto, cuello largo y base más corta y ancha."],
    ["nicho de células madre fúndicas", "El istmo glandular."],
    ["volumen diario de jugo gástrico", "Aproximadamente 2 litros."],
    ["concentración de HCl gástrico", "Cerca de 150 a 160 mmol/L, con pH menor de 1 a 2."],
    ["funciones del HCl", "Activa pepsinógeno, crea el pH para pepsina y ejerce efecto bacteriostático."],
    ["pepsinógeno", "Proenzima secretada por células principales que se activa a pH menor de 5."],
    ["pepsina", "Endopeptidasa que rompe enlaces peptídicos internos."],
    ["factor intrínseco", "Glucoproteína de 44 kDa de la célula parietal que permite absorber vitamina B12 en el íleon distal."],
    ["ureasa de Helicobacter pylori", "Genera amoníaco y crea alrededor de la bacteria un ambiente menos ácido."],
  ]},
  { topic: "Estómago", subtopic: "Células de las glándulas fúndicas", facts: [
    ["célula mucosa del cuello", "Célula del cuello glandular que produce un moco soluble menos alcalino y responde al vago."],
    ["vida de la célula mucosa del cuello", "Aproximadamente 6 días."],
    ["célula principal", "Célula basófila en su base por RER y con gránulos apicales de pepsinógeno."],
    ["secreciones de la célula principal", "Pepsinógeno y una lipasa gástrica débil."],
    ["célula parietal", "Célula grande eosinófila, a veces binucleada, abundante en cuello y porción superior o media."],
    ["canalículos intracelulares parietales", "Invaginaciones apicales con microvellosidades donde se secreta el ácido."],
    ["sistema tubulovesicular parietal", "Reservorio intracelular de bombas H+/K+-ATPasa en la célula inactiva."],
    ["cambio parietal durante activación", "Aumentan las microvellosidades canaliculares y disminuye el sistema tubulovesicular."],
    ["abundancia de mitocondrias parietales", "Proporciona ATP para el transporte activo de protones."],
    ["receptores estimuladores de la célula parietal", "Receptores para gastrina, histamina H2 y acetilcolina M2, según el texto."],
    ["célula enteroendocrina fúndica", "Célula dispersa con gránulos densos basales que libera mensajeros a la lámina propia."],
  ]},
  { topic: "Estómago", subtopic: "Secreción de ácido y clínica gástrica", facts: [
    ["anhidrasa carbónica parietal", "Forma ácido carbónico, que se disocia en H+ y bicarbonato."],
    ["H+/K+-ATPasa", "Intercambia protones citoplasmáticos por potasio en la membrana canalicular."],
    ["canales de cloro parietales", "Permiten que Cl− alcance el canalículo y se combine con H+ para formar HCl."],
    ["marea alcalina posprandial", "Aumento transitorio de bicarbonato en sangre por su salida basolateral desde células parietales."],
    ["gastrinoma", "Tumor secretor de gastrina localizado con frecuencia en duodeno o islotes pancreáticos."],
    ["síndrome de Zollinger-Ellison", "Hipergastrinemia con exceso de HCl, úlceras, dolor, diarrea y esteatorrea."],
    ["tratamiento ácido en Zollinger-Ellison", "Inhibidores de la bomba de protones, además de resección tumoral cuando es posible."],
    ["aclorhidria autoinmunitaria", "Destrucción de mucosa y células parietales con pérdida de ácido y factor intrínseco."],
    ["anemia perniciosa", "Deficiencia de vitamina B12 secundaria a falta de factor intrínseco."],
    ["efecto de bloqueadores H2", "Reducen tanto la secreción ácida como la de factor intrínseco."],
    ["efecto de inhibidores de bomba de protones", "Bloquean la H+/K+-ATPasa sin inhibir directamente la secreción de factor intrínseco."],
  ]},
  { topic: "Estómago", subtopic: "Sistema enteroendocrino", facts: [
    ["sistema neuroendocrino difuso", "Población dispersa de células endocrinas gastrointestinales con gránulos de centro denso."],
    ["cromogranina A", "Proteína relacionada con la biogénesis de gránulos secretores neuroendocrinos."],
    ["cromogranina B", "Proteína que participa en clasificación y empaquetamiento de hormonas en gránulos."],
    ["célula enteroendocrina abierta", "Alcanza la luz y posee microvellosidades apicales que detectan su contenido."],
    ["célula enteroendocrina cerrada", "No alcanza la luz y recibe estímulos indirectos neurales o paracrinos."],
    ["señal endocrina", "Mensajero que viaja por sangre hacia un blanco distante."],
    ["señal paracrina", "Mensajero que actúa localmente sobre células cercanas."],
    ["señal neurocrina", "Mensajero liberado por una terminación nerviosa."],
    ["tumor carcinoide serotoninérgico", "Tumor neuroendocrino que puede causar diarrea, rubor, broncoconstricción y lesión valvular derecha."],
    ["sitio gastrointestinal frecuente de tumor neuroendocrino", "El apéndice."],
  ]},
  { topic: "Estómago", subtopic: "Hormonas gastrointestinales", facts: [
    ["gastrina", "Hormona de células G gástricas que estimula la secreción de ácido."],
    ["grelina", "Hormona gástrica que estimula hormona de crecimiento, apetito y hambre y modifica el metabolismo lipídico."],
    ["colecistocinina", "Hormona de duodeno y yeyuno que contrae la vesícula, estimula enzimas pancreáticas e inhibe vaciamiento gástrico."],
    ["secretina", "Hormona duodenal que estimula bicarbonato pancreático e inhibe la secreción ácida gástrica."],
    ["GIP", "Hormona de duodeno y yeyuno que estimula insulina e inhibe secreción ácida."],
    ["motilina", "Hormona de duodeno y yeyuno que promueve motilidad gástrica e intestinal."],
    ["péptido YY", "Hormona de íleon y colon que favorece absorción colónica e inhibe ácido, vaciamiento y consumo de alimento."],
    ["GLP-1", "Hormona de íleon y colon que estimula insulina e inhibe secreción ácida y vaciamiento gástrico."],
    ["somatostatina", "Hormona de células D que inhibe gastrina, ácido y otras hormonas gastrointestinales."],
    ["histamina gástrica", "Señal paracrina que activa receptores H2 y estimula ácido."],
    ["VIP", "Neurotransmisor que estimula secreción intestinal y pancreática e inhibe músculo liso y esfínteres."],
  ]},
  { topic: "Estómago", subtopic: "Cardias, píloro y renovación", facts: [
    ["glándulas cardíacas", "Glándulas tubulares tortuosas, a veces ramificadas, predominantemente mucosas y asociadas a fovéolas poco profundas."],
    ["función de las glándulas cardíacas", "Proteger la mucosa y el extremo esofágico mediante moco."],
    ["glándulas pilóricas", "Glándulas tubulares enrolladas y ramificadas, de luz amplia, con células mucosas y enteroendocrinas."],
    ["fovéolas pilóricas", "Invaginaciones profundas que ocupan aproximadamente la mitad de la mucosa."],
    ["renovación de células mucosas superficiales", "Cada 3 a 5 días."],
    ["vida de células parietales", "Aproximadamente 150 a 200 días."],
    ["vida de células principales y enteroendocrinas", "Aproximadamente 60 a 90 días."],
    ["lámina propia gástrica", "Escaso tejido conjuntivo entre glándulas, con fibras reticulares y células inmunitarias."],
    ["muscular de la mucosa gástrica", "Dos capas delgadas, a veces una tercera, con fascículos que penetran la lámina propia."],
    ["muscular externa gástrica", "Disposición tradicional longitudinal externa, circular media y oblicua interna, aunque los fascículos pueden ser irregulares."],
  ]},
  { topic: "Intestino delgado", subtopic: "Organización y superficie", facts: [
    ["longitud del intestino delgado", "Más de 6 metros."],
    ["duodeno", "Segmento más corto y ancho, de unos 25 cm."],
    ["yeyuno", "Porción proximal de aproximadamente 2.5 m que representa los dos quintos del intestino móvil."],
    ["íleon", "Porción distal de aproximadamente 3.5 m que representa los tres quintos y termina en la válvula ileocecal."],
    ["inicio de pliegues circulares", "A unos 5 a 6 cm del píloro."],
    ["máxima prominencia de pliegues circulares", "Duodeno distal y yeyuno proximal."],
    ["disminución de pliegues circulares", "Se reducen progresivamente y casi desaparecen hacia la mitad del íleon."],
    ["altura de vellosidades", "Aproximadamente 0.5 a 1.5 mm."],
    ["centro de la vellosidad", "Lámina propia con capilares fenestrados, vaso quilífero y fascículos de músculo liso."],
    ["vaso quilífero central", "Capilar linfático ciego de la vellosidad que recibe quilomicrones."],
    ["movimiento de vellosidades", "Contracción del músculo liso procedente de la muscular de la mucosa que ayuda al flujo linfático."],
    ["criptas de Lieberkühn", "Glándulas tubulares simples que llegan hasta la muscular de la mucosa y se abren entre vellosidades."],
  ]},
  { topic: "Intestino delgado", subtopic: "Enterocitos y transporte", facts: [
    ["enterocito", "Célula cilíndrica absortiva con miles de microvellosidades apicales."],
    ["aumento superficial enterocitario", "Las microvellosidades pueden amplificar la superficie hasta unas 600 veces."],
    ["armazón de la microvellosidad", "Filamentos de actina asociados con villina y miosina I."],
    ["red terminal", "Red apical de actina unida a la zónula adherente."],
    ["contracción de la red terminal", "Separa microvellosidades y ayuda a cerrar brechas cuando se exfolian células."],
    ["uniones del duodeno y yeyuno", "Son relativamente permeables y permiten arrastre por solvente paracelular."],
    ["uniones del íleon y colon", "Son más herméticas y favorecen transporte transcelular activo."],
    ["Na+/K+-ATPasa enterocitaria", "Bomba de la membrana lateral que mantiene el gradiente para absorción de sodio y nutrientes."],
    ["pliegues laterales enterocitarios", "Aumentan la superficie disponible para transporte de agua y electrólitos."],
    ["secreción de las criptas", "Agua y electrólitos que equilibran la absorción producida en las vellosidades."],
  ]},
  { topic: "Intestino delgado", subtopic: "Células de la mucosa intestinal", facts: [
    ["célula caliciforme", "Célula secretora con teca apical de mucinógeno, núcleo basal y Golgi prominente."],
    ["gradiente de células caliciformes", "Su número aumenta desde el duodeno hacia el íleon."],
    ["célula de Paneth", "Célula de la base de la cripta con citoplasma basal basófilo y grandes gránulos apicales eosinófilos."],
    ["productos de células de Paneth", "Lisozima, defensinas alfa, glucoproteínas, proteína rica en arginina y zinc."],
    ["función de células de Paneth", "Regular la microbiota y proteger el nicho de las criptas; también pueden fagocitar."],
    ["célula M", "Célula epitelial sobre GALT que capta y transloca antígenos luminales intactos."],
    ["bolsillo basolateral de la célula M", "Depresión con células dendríticas, macrófagos y linfocitos T y B."],
    ["superficie apical de la célula M", "Micropliegues, glucocáliz delgado y receptor GP2."],
    ["receptor GP2", "Receptor de célula M que une macromoléculas y ciertas bacterias gramnegativas como E. coli."],
    ["célula intermedia", "Progenitora mitótica de la mitad basal de la cripta que amplifica los linajes epiteliales."],
    ["factor Math1", "Factor de transcripción alto en células destinadas a linajes secretores; su inhibición favorece enterocitos."],
  ]},
  { topic: "Intestino delgado", subtopic: "Digestión y absorción", facts: [
    ["enteropeptidasa", "Enzima del borde en cepillo que convierte tripsinógeno en tripsina."],
    ["tripsina activada", "Activa más tripsinógeno y otros cimógenos pancreáticos."],
    ["absorción de glucosa y galactosa", "Cotransporte con sodio mediante SGLT1."],
    ["absorción de fructosa", "Difusión facilitada principalmente mediante GLUT5."],
    ["salida basolateral de monosacáridos", "Mediante GLUT2 hacia capilares portales."],
    ["deficiencia de lactasa", "Produce fermentación, gas, distensión y diarrea osmótica."],
    ["función de sales biliares", "Emulsionar lípidos y facilitar la formación de micelas."],
    ["procesamiento de ácidos grasos largos", "Se reesterifican en REL, forman quilomicrones en Golgi y salen hacia vasos quilíferos."],
    ["absorción de ácidos grasos cortos y medianos", "Pasan directamente a capilares portales junto con glicerol."],
    ["productos finales de digestión proteica", "Aproximadamente 30% aminoácidos libres y 70% oligopéptidos."],
    ["absorción de aminoácidos", "Cotransportadores apicales dependientes de sodio."],
    ["absorción de dipéptidos y tripéptidos", "Cotransporte con protones mediante PepT1, seguido de hidrólisis citoplasmática."],
    ["enfermedad de Hartnup", "Demuestra que el transporte de aminoácidos libres es distinto al de péptidos."],
  ]},
  { topic: "Intestino delgado", subtopic: "Inmunidad mucosa", facts: [
    ["proporción inmunitaria de la mucosa", "El GALT representa cerca de una cuarta parte de la capa mucosa."],
    ["IgA dimérica intestinal", "Anticuerpo producido por plasmocitos y unido por cadena J."],
    ["pIgR", "Receptor de 75 kDa producido por enterocitos que transloca IgA dimérica hacia la luz."],
    ["componente secretor", "Fragmento del pIgR que queda unido a la IgA después de su escisión apical."],
    ["función de la IgA secretora", "Bloquear adherencia e invasión microbiana mediante aglutinación y enmascaramiento de sitios de unión."],
    ["IgM secretora", "Puede atravesar el epitelio por un mecanismo semejante al de IgA."],
    ["IgE mucosa", "Se une a mastocitos y participa en respuestas frente a parásitos y alérgenos."],
    ["placa de Peyer", "Agregado linfoide ileal cubierto por epitelio asociado a folículo con células M."],
  ]},
  { topic: "Intestino delgado", subtopic: "Submucosa, motilidad y renovación", facts: [
    ["glándulas de Brunner", "Glándulas tubulares ramificadas de la submucosa duodenal."],
    ["pH de la secreción de Brunner", "Aproximadamente 8.1 a 9.3."],
    ["productos de glándulas de Brunner", "Glucoproteínas neutras o alcalinas y bicarbonato."],
    ["función de glándulas de Brunner", "Neutralizar el quimo y crear el pH adecuado para enzimas pancreáticas."],
    ["desembocadura de conductos de Brunner", "En las criptas de Lieberkühn."],
    ["segmentación intestinal", "Contracciones locales circulares no propulsivas que mezclan el quimo y lo acercan a la mucosa."],
    ["peristaltismo intestinal", "Contracciones coordinadas circulares y longitudinales que desplazan el contenido distalmente."],
    ["renovación de enterocitos y caliciformes", "Aproximadamente cada 4 a 6 días."],
    ["vida de una célula de Paneth", "Cerca de 4 semanas; migra hacia la base de la cripta."],
    ["migración de células absortivas", "Desde la cripta hacia la punta de la vellosidad, donde se exfolian."],
  ]},
  { topic: "Intestino grueso", subtopic: "Organización de la mucosa colónica", facts: [
    ["segmentos del intestino grueso", "Ciego y apéndice, colon, recto y conducto anal."],
    ["superficie mucosa colónica", "Lisa, sin vellosidades ni pliegues circulares."],
    ["criptas colónicas", "Glándulas rectas no ramificadas que ocupan todo el espesor de la mucosa."],
    ["funciones del colon", "Absorción de agua y electrólitos y eliminación de residuos."],
    ["célula absortiva colónica", "Célula semejante al enterocito, especializada en transporte de agua y electrólitos."],
    ["células caliciformes colónicas", "Son más numerosas que en intestino delgado y forman una película continua de moco."],
    ["relación absortivas:caliciformes", "Aproximadamente 4:1 en la mayor parte del colon y cercana a 1:1 en el recto."],
    ["glucocáliz colónico", "Se renueva cada 16 a 24 horas y carece de enzimas digestivas."],
    ["células de Paneth en colon humano", "Por lo general están ausentes."],
    ["renovación del epitelio colónico", "Las células madre del tercio basal producen células que se exfolian alrededor de 5 días después."],
    ["vida de células enteroendocrinas colónicas", "Aproximadamente 4 semanas."],
  ]},
  { topic: "Intestino grueso", subtopic: "Lámina propia, muscular y serosa", facts: [
    ["tabla de colágeno colónica", "Capa de colágeno y proteoglucanos de unos 5 µm entre la lámina basal epitelial y capilares fenestrados."],
    ["función de la tabla de colágeno", "Regular el paso de agua y electrólitos hacia la red vascular."],
    ["cambio de tabla de colágeno en pólipos", "Puede engrosarse hasta unas tres veces."],
    ["vaina fibroblástica pericríptica", "Fibroblastos que se dividen en la base y migran hacia la superficie junto con el epitelio."],
    ["linfáticos de la lámina propia colónica central", "Están ausentes entre las glándulas; los vasos comienzan cerca de sus bases."],
    ["drenaje linfático colónico", "Red basal hacia muscular de la mucosa, submucosa, muscular externa y ganglios regionales."],
    ["tenias colónicas", "Tres bandas longitudinales ausentes en recto, conducto anal y apéndice."],
    ["haustras", "Sacculaciones formadas por diferencias entre tenias y músculo longitudinal intermedio."],
    ["apéndices epiploicos", "Proyecciones adiposas de la serosa del colon."],
    ["segmentación colónica", "Contracción local no propulsiva que mezcla y compacta el contenido."],
    ["peristaltismo en masa", "Movimiento propulsivo infrecuente, aproximadamente una vez al día, que lleva contenido distalmente."],
  ]},
  { topic: "Intestino grueso", subtopic: "Apéndice, recto y conducto anal", facts: [
    ["muscular externa del apéndice", "Capa longitudinal uniforme, sin tenias."],
    ["rasgo histológico del apéndice", "Numerosos nódulos linfáticos que pueden extenderse hasta la submucosa."],
    ["cambio apendicular con la edad", "El tejido linfático puede ser reemplazado progresivamente por tejido cicatricial."],
    ["mecanismo frecuente de apendicitis", "Obstrucción luminal con acumulación de moco y contenido fecal."],
    ["mucosa rectal", "Similar a la del colon distal, con abundantes células caliciformes y pliegues transversales."],
    ["longitud del conducto anal", "Aproximadamente 4 cm."],
    ["zona colorrectal anal", "Tercio superior con epitelio cilíndrico simple."],
    ["zona de transición anal", "Tercio medio con epitelio estratificado cilíndrico o cúbico."],
    ["zona escamosa anal", "Tercio inferior con epitelio plano estratificado continuo con la piel."],
    ["glándulas anales", "Glándulas tubulares rectas y ramificadas productoras de moco cuyos conductos pueden originar fístulas."],
    ["glándulas perianales", "Grandes glándulas apocrinas de la piel alrededor del ano."],
    ["plexo venoso anal", "Red asociada con la arteria rectal superior que puede dilatarse y formar hemorroides internas."],
    ["desaparición de la muscular de la mucosa", "Ocurre alrededor de la zona de transición anal."],
    ["esfínter anal interno", "Engrosamiento de músculo liso circular."],
    ["esfínter anal externo", "Músculo estriado del periné bajo control voluntario."],
  ]},
  { topic: "Correlaciones clínicas", subtopic: "Inflamación y cáncer colorrectal", facts: [
    ["marcador D2-40", "Sialoglucoproteína de 40 kDa utilizada para identificar endotelio linfático."],
    ["linfáticos en colitis ulcerosa activa", "Aumentan por linfangiogénesis en la lámina propia y disminuyen con una buena respuesta terapéutica."],
    ["metástasis de pólipo mucoso", "Es poco probable mientras el tumor permanezca por encima de la muscular de la mucosa, donde faltan linfáticos centrales."],
    ["localización frecuente de pólipos adenomatosos", "Aproximadamente la mitad se encuentra en recto y colon sigmoide."],
    ["origen de cáncer colorrectal", "Cerca del 98% son adenocarcinomas que suelen comenzar como pólipos glandulares benignos."],
    ["factores epidemiológicos colorrectales", "Dieta baja en fibra, alta en grasa y edad frecuente entre 60 y 79 años."],
    ["pérdida de APC", "Evento temprano que favorece la formación de un pólipo."],
    ["activación de K-Ras", "Favorece la progresión hacia adenoma benigno."],
    ["pérdida de p53 y DCC", "Se asocia con transformación e invasión maligna."],
    ["vía alternativa colorrectal", "Defectos de reparación de errores de apareamiento del ADN."],
    ["histología de adenocarcinoma colorrectal", "Glándulas irregulares con células oscuras y, a veces, abundante producción de moco."],
    ["síntomas de cáncer colorrectal", "Cambio del hábito intestinal, estreñimiento o diarrea, cólicos y sangrado."],
  ]},
]

const slug = (value: string) => value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")

export const cap17Flashcards: Flashcard[] = groups.flatMap(group =>
  group.facts.flatMap(([label, detail], index) => {
    const base = `histo-cap17-${slug(group.subtopic)}-${String(index + 1).padStart(3, "0")}`
    const common = {
      subject: "Histología",
      book: "Ross",
      chapter: "Capítulo 17",
      topic: group.topic,
      subtopic: group.subtopic,
      tags: ["Capítulo 17", group.subtopic]
    }

    return [
      { ...common, id: `${base}-a`, front: `En ${group.subtopic.toLowerCase()}, ¿qué caracteriza a ${label}?`, back: detail },
      { ...common, id: `${base}-b`, front: `En ${group.subtopic.toLowerCase()}, ¿qué concepto corresponde a esta descripción: ${detail}`, back: label }
    ]
  })
)
