import type { Flashcard } from "./cards"

type Pair = readonly [string, string]
type Group = { topic: string; subtopic: string; cards: readonly Pair[] }

// Reescritura manual basada en Ross, cap. 18. Cada pista está redactada como
// una pregunta independiente y el subtema existe desde la fuente de datos.
const groups: readonly Group[] = [
  { topic: "Hígado", subtopic: "Fundamentos y desarrollo", cards: [
    ["¿Qué órgano es la masa glandular más grande del organismo?", "El hígado."],
    ["¿Cuál es el peso aproximado del hígado adulto?", "Alrededor de 1 500 g."],
    ["¿Qué cápsula fibrosa rodea el hígado?", "La cápsula de Glisson."],
    ["¿Qué zona hepática carece de peritoneo visceral por adherirse al diafragma?", "La superficie desnuda."],
    ["¿Qué lóbulos anatómicos grandes se distinguen en el hígado?", "El derecho y el izquierdo."],
    ["¿Qué dos lóbulos anatómicos pequeños también se reconocen?", "El cuadrado y el caudado."],
    ["¿En qué se basa la segmentación funcional útil para cirugía hepática?", "En irrigación y drenaje biliar independientes."],
    ["¿De qué capa germinal procede el divertículo hepático?", "Del endodermo."],
    ["¿De qué región del intestino anterior surge el divertículo hepático?", "De la región que formará el duodeno."],
    ["¿Qué células derivan del divertículo hepático embrionario?", "Los hepatocitos."],
    ["¿En qué disposición se organizan inicialmente los hepatocitos embrionarios?", "En cordones hepáticos."],
    ["¿En qué se transforma el pedículo original del divertículo hepático?", "En el conducto colédoco."],
    ["¿Qué estructura embrionaria origina la vesícula biliar y el conducto cístico?", "El divertículo cístico que brota del colédoco."],
    ["¿Qué función exocrina distingue al hígado?", "La producción de bilis."],
    ["¿Qué función hepática mantiene la glucemia entre comidas?", "Almacenar, liberar y producir glucosa según necesidad."],
  ]},
  { topic: "Fisiología hepática", subtopic: "Proteínas y lipoproteínas", cards: [
    ["¿Qué proteína hepática mantiene gran parte de la presión oncótica plasmática?", "La albúmina."],
    ["¿Qué dos proteínas de coagulación sintetiza el hígado de forma importante?", "Protrombina y fibrinógeno."],
    ["¿Qué proteína hepática transporta hierro en plasma?", "La transferrina."],
    ["¿Qué proteína hepática transporta hemoglobina libre?", "La haptoglobina."],
    ["¿Qué proteína hepática transporta hemo libre?", "La hemopexina."],
    ["¿Qué lipoproteína transporta principalmente triglicéridos desde hígado a tejidos?", "VLDL."],
    ["¿Qué lipoproteína lleva colesterol desde hígado hacia tejidos periféricos?", "LDL."],
    ["¿Qué lipoproteína devuelve colesterol desde tejidos al hígado?", "HDL."],
    ["¿Dónde se producen los quilomicrones?", "En el intestino delgado."],
    ["¿Qué componente de una lipoproteína se sintetiza en el REL hepatocitario?", "El componente lipídico."],
    ["¿Qué componente de una lipoproteína se sintetiza en el RER hepatocitario?", "El componente proteico."],
    ["¿Qué apolipoproteína contribuye a la secreción de VLDL hepática?", "Apolipoproteína B-100."],
    ["¿Qué organelo empaqueta partículas lipoproteínicas antes de su secreción?", "El aparato de Golgi."],
    ["¿Hacia qué espacio libera el hepatocito lipoproteínas a la sangre?", "Hacia el espacio perisinusoidal."],
    ["¿Qué hormonas pueden regular la secreción de lipoproteínas hepáticas?", "Estrógenos y hormonas tiroideas."],
  ]},
  { topic: "Fisiología hepática", subtopic: "Vitaminas, hierro y cobre", cards: [
    ["¿En qué células hepáticas se almacenan ésteres de retinilo?", "En las células estrelladas hepáticas."],
    ["¿Qué proteína une retinol para liberarlo desde el hígado a la sangre?", "La proteína fijadora de retinol, RBP."],
    ["¿Qué manifestación visual puede causar déficit de vitamina A?", "Ceguera nocturna."],
    ["¿Qué metabolito circulante de vitamina D forma el hígado?", "25-hidroxicolecalciferol."],
    ["¿Qué órgano convierte 25-hidroxicolecalciferol en calcitriol?", "El riñón."],
    ["¿Dónde se almacena principalmente vitamina D, no en el hígado?", "En músculo esquelético y tejido adiposo."],
    ["¿Qué enfermedad ósea se asocia con déficit de vitamina D?", "Raquitismo."],
    ["¿Qué forma de vitamina E predomina en el organismo?", "Alfa-tocoferol."],
    ["¿Qué función química tiene el alfa-tocoferol?", "Actúa como antioxidante que interrumpe cadenas de radicales libres."],
    ["¿Qué proteína hepática transfiere alfa-tocoferol?", "La proteína de transferencia de tocoferol alfa, α-TTP."],
    ["¿Qué vitamina es necesaria para sintetizar protrombina y otros factores?", "Vitamina K."],
    ["¿Qué alteración causa el déficit de vitamina K?", "Hipoprotrombinemia con tendencia hemorrágica."],
    ["¿En qué formas se almacena hierro en el hígado?", "Ferritina y hemosiderina."],
    ["¿Qué transportador hepático incorpora cobre a apoceruloplasmina y permite excreción biliar?", "ATP7B."],
    ["¿Qué enfermedad autosómica recesiva resulta de mutaciones de ATP7B?", "Enfermedad de Wilson."],
    ["¿Cómo suele estar la ceruloplasmina en enfermedad de Wilson?", "Disminuida."],
    ["¿Dónde se acumula inicialmente cobre en Wilson?", "En el hígado."],
  ]},
  { topic: "Fisiología hepática", subtopic: "Metabolismo y bilis", cards: [
    ["¿Qué fase de detoxificación usa citocromos P450 para oxidar compuestos?", "La fase I."],
    ["¿Qué fase de detoxificación aumenta solubilidad al conjugar compuestos?", "La fase II."],
    ["¿Qué organelo aumenta con uso crónico de fenobarbital o alcohol?", "El retículo endoplásmico liso."],
    ["¿Qué producto tóxico de la desaminación convierte el hígado en urea?", "Amonio."],
    ["¿Qué combustible fabrica el hígado a partir de ácidos grasos pero no utiliza?", "Cuerpos cetónicos."],
    ["¿Qué dos ácidos biliares primarios sintetizan hepatocitos desde colesterol?", "Ácido cólico y ácido quenodesoxicólico."],
    ["¿Qué ácidos biliares secundarios produce la microbiota intestinal?", "Ácido desoxicólico y litocólico."],
    ["¿Qué proporción aproximada de sales biliares retorna al hígado por circulación enterohepática?", "Cerca del 90%."],
    ["¿Qué producto conjugado de hemoglobina se excreta en bilis y da color a heces?", "Glucurónido de bilirrubina."],
    ["¿Qué puede causar incapacidad de conjugar o secretar bilirrubina?", "Ictericia."],
    ["¿Cuánto volumen de bilis secreta aproximadamente un hígado adulto al día?", "Alrededor de un litro."],
    ["¿Qué dos funciones principales tiene la bilis?", "Facilitar absorción de grasas y excretar productos como colesterol y bilirrubina."],
    ["¿Qué hormonas digestivas aumentan flujo biliar?", "CCK, gastrina y motilina."],
    ["¿Qué efecto tienen estrógenos sobre secreción biliar hepática?", "La disminuyen."],
    ["¿Qué efecto parasimpático facilita la salida de bilis?", "Contrae vesícula y relaja esfínter de Oddi."],
  ]},
  { topic: "Hígado", subtopic: "Irrigación y lobulillos", cards: [
    ["¿Qué vaso aporta cerca del 75% del flujo sanguíneo hepático?", "La vena porta."],
    ["¿Qué vaso aporta sangre oxigenada al hígado?", "La arteria hepática."],
    ["¿Dónde se mezclan sangre portal y arterial dentro del hígado?", "En los sinusoides."],
    ["¿Hacia dónde fluye sangre dentro de un lobulillo clásico?", "Desde la periferia portal hacia la vena central."],
    ["¿Qué tres estructuras forman una tríada portal?", "Rama portal, rama arterial hepática y conducto biliar."],
    ["¿Qué vaso ocupa el centro del lobulillo hepático clásico?", "La vena central."],
    ["¿Qué forma geométrica se usa para describir el lobulillo clásico?", "Hexagonal."],
    ["¿Cómo se disponen las placas de hepatocitos en el lobulillo adulto?", "En cordones radiales de una célula de espesor."],
    ["¿Qué unidad triangular se centra en un conducto biliar?", "El lobulillo portal."],
    ["¿Qué unidad funcional correlaciona mejor con perfusión y lesión hipóxica?", "El ácino hepático."],
    ["¿Qué zona del ácino recibe primero oxígeno y nutrientes?", "La zona 1 periportal."],
    ["¿Qué zona del ácino recibe menos oxígeno?", "La zona 3 centrolobulillar."],
    ["¿Qué zona sufre primero necrosis por isquemia?", "La zona 3."],
    ["¿Qué zona suele acumular primero lípidos en hígado graso?", "La zona 3."],
    ["¿Qué zona manifiesta primero cambios por obstrucción biliar?", "La zona 1."],
    ["¿Qué lesión zonal provoca sobredosis de paracetamol?", "Necrosis de zona 3."],
  ]},
  { topic: "Hígado", subtopic: "Sinusoides, Disse y fibrosis", cards: [
    ["¿Qué tipo de endotelio recubre sinusoides hepáticos?", "Endotelio discontinuo fenestrado."],
    ["¿Qué característica tiene la lámina basal de un sinusoide hepático?", "Es incompleta o ausente."],
    ["¿Qué células son los macrófagos residentes del sinusoide?", "Las células de Kupffer."],
    ["¿Qué material pueden acumular células de Kupffer tras fagocitar eritrocitos?", "Ferritina y hemosiderina."],
    ["¿Qué espacio queda entre endotelio sinusoidal y hepatocitos?", "El espacio de Disse."],
    ["¿Qué estructuras hepatocitarias protruyen al espacio de Disse?", "Microvellosidades."],
    ["¿Qué células perisinusoidales almacenan vitamina A?", "Las células estrelladas de Ito."],
    ["¿Qué cambio sufren las células de Ito en lesión hepática crónica?", "Se vuelven miofibroblásticas y producen colágeno."],
    ["¿Qué tipos de colágeno producen células estrelladas activadas?", "Principalmente tipos I y III."],
    ["¿Qué efecto hemodinámico tiene contracción de células estrelladas activadas?", "Aumenta resistencia sinusoidal e hipertensión portal."],
    ["¿Qué marcadores expresan células estrelladas activadas?", "Desmina y alfa-actina de músculo liso."],
    ["¿Dónde se origina gran parte de la linfa hepática?", "En el espacio de Disse."],
    ["¿Hacia qué espacio porta se dirige la linfa formada en Disse?", "Hacia el espacio de Mall."],
    ["¿Qué proporción aproximada de linfa hepática llega al conducto torácico?", "Cerca del 80%."],
  ]},
  { topic: "Hepatocitos", subtopic: "Morfología y organelos", cards: [
    ["¿Qué proporción aproximada de células hepáticas son hepatocitos?", "Cerca del 80%."],
    ["¿Qué forma tienen los hepatocitos?", "Poligonal."],
    ["¿Qué rasgo nuclear puede verse en hepatocitos adultos?", "Binucleación o tetraploidía."],
    ["¿Qué cara del hepatocito se orienta hacia el espacio de Disse?", "La superficie sinusoidal o basal."],
    ["¿Qué cara del hepatocito forma canalículos con la célula vecina?", "La superficie canalicular apical."],
    ["¿Qué inclusión hepatocitaria es PAS positiva y varía con nutrición?", "Glucógeno."],
    ["¿Qué organelo contiene catalasa y degrada peróxido de hidrógeno?", "El peroxisoma."],
    ["¿Qué organelo participa en síntesis de colesterol y detoxificación?", "El retículo endoplásmico liso."],
    ["¿Qué organelo se asocia con empaquetar productos dirigidos a bilis?", "Golgi pericanalicular."],
    ["¿Qué pigmento de desgaste puede verse en lisosomas peribiliares?", "Lipofuscina."],
    ["¿Qué efecto tienen alcohol y tóxicos sobre gotas lipídicas hepatocitarias?", "Pueden aumentarlas."],
  ]},
  { topic: "Árbol biliar", subtopic: "Canalículos y conductos intrahepáticos", cards: [
    ["¿Entre qué células se forma un canalículo biliar?", "Entre dos hepatocitos contiguos."],
    ["¿Qué uniones impiden que la bilis de un canalículo pase a sangre?", "Uniones ocluyentes."],
    ["¿Qué estructura transicional tiene parte hepatocitaria y parte colangiocitaria?", "El conducto de Hering."],
    ["¿Qué potencial progenitor tiene el conducto de Hering después de lesión grave?", "Puede originar hepatocitos y colangiocitos."],
    ["¿Qué estructura está revestida por completo por colangiocitos?", "El conductillo biliar intrahepático."],
    ["¿Cómo cambian los colangiocitos cuando aumenta el calibre ductal?", "De cúbicos a más cilíndricos."],
    ["¿Qué sensor apical poseen colangiocitos para detectar flujo biliar?", "Un cilio primario no móvil."],
    ["¿Dónde están los conductos biliares interlobulillares?", "En las tríadas portales."],
    ["¿Qué conductos se unen para formar el conducto hepático común?", "Los conductos hepáticos derecho e izquierdo."],
    ["¿Qué conductos embrionarios aberrantes pueden verse cerca del cuello vesicular?", "Los conductos de Luschka."],
  ]},
  { topic: "Árbol biliar", subtopic: "Vías extrahepáticas y flujo biliar", cards: [
    ["¿Qué conducto une la vesícula biliar con el conducto hepático común?", "El conducto cístico."],
    ["¿Qué pliegues mucosos caracterizan el conducto cístico?", "La válvula espiral de Heister."],
    ["¿Qué conducto se forma al unirse conducto hepático común y conducto cístico?", "El colédoco."],
    ["¿Qué conducto se une al pancreático principal antes de entrar al duodeno?", "El colédoco."],
    ["¿Qué estructura se forma con colédoco y conducto de Wirsung?", "La ampolla hepatopancreática de Vater."],
    ["¿Qué esfínter regula el paso desde colédoco a ampolla?", "El esfínter del colédoco o de Boyden."],
    ["¿Qué esfínter rodea la ampolla hepatopancreática?", "El esfínter de Oddi."],
    ["¿Qué ocurre con la bilis si se contrae el esfínter de Boyden?", "Retrocede hacia la vesícula biliar."],
    ["¿Qué capa del tubo digestivo no tiene el conducto hepático común?", "Muscular de la mucosa."],
    ["¿Qué evita el esfínter de Oddi además de regular secreción?", "El reflujo duodenal hacia conductos biliar y pancreático."],
    ["¿Qué estímulo autonómico eleva el flujo biliar?", "La estimulación parasimpática."],
    ["¿Qué estímulo simpático altera directamente vasos hepáticos?", "Aumenta resistencia vascular y reduce volumen sanguíneo hepático."],
  ]},
  { topic: "Vesícula biliar", subtopic: "Pared y concentración de bilis", cards: [
    ["¿Qué forma tiene la vesícula biliar?", "De pera y distensible."],
    ["¿Cuánto volumen de bilis puede contener aproximadamente?", "Unos 50 mL."],
    ["¿Qué dos funciones principales tiene la vesícula biliar?", "Almacenar y concentrar la bilis."],
    ["¿Qué porcentaje aproximado del agua de la bilis puede extraer?", "Cerca del 90%."],
    ["¿Cuánto puede aumentar la concentración de sales biliares al concentrarse?", "Hasta diez veces."],
    ["¿Qué epitelio recubre la mucosa vesicular?", "Cilíndrico simple."],
    ["¿Qué especialización apical corta poseen colangiocitos vesiculares?", "Microvellosidades."],
    ["¿Qué bomba lateral permite reabsorción de electrolitos en vesícula?", "Na+/K+-ATPasa."],
    ["¿Qué dos acuaporinas expresa la vesícula biliar?", "AQP1 y AQP8."],
    ["¿Qué capa falta en la pared vesicular además de submucosa?", "Muscular de la mucosa."],
    ["¿Cómo se disponen los haces de músculo liso vesicular?", "En orientación aleatoria, no en capas definidas."],
    ["¿Qué cubierta tiene la cara vesicular adherida al hígado?", "Adventicia."],
    ["¿Qué cubierta tiene la cara vesicular no adherida al hígado?", "Serosa."],
    ["¿Qué divertículos mucosos profundos atraviesan muscular vesicular?", "Senos de Rokitansky-Aschoff."],
    ["¿Qué favorecen los senos de Rokitansky-Aschoff?", "Inflamación crónica y formación de cálculos."],
    ["¿Qué hormona contrae la vesícula ante grasa en duodeno?", "Colecistoquinina."],
  ]},
  { topic: "Páncreas exocrino", subtopic: "Acinos y conductos", cards: [
    ["¿Qué partes anatómicas tiene el páncreas?", "Cabeza, cuerpo y cola."],
    ["¿Dónde se ubica la cabeza pancreática?", "En la curvatura en C del duodeno."],
    ["¿Hacia qué órgano se dirige la cola pancreática?", "Hacia el hilio esplénico."],
    ["¿Qué tipo de glándula es el páncreas exocrino?", "Una glándula serosa acinar o tubuloacinar."],
    ["¿Qué glándula salival se parece histológicamente al páncreas exocrino?", "La parótida."],
    ["¿Qué rasgo permite distinguir páncreas de parótida?", "Células centroacinares e islotes de Langerhans."],
    ["¿Qué aspecto tiene la base de una célula acinar pancreática?", "Basófila por RER abundante."],
    ["¿Qué contiene el polo apical de una célula acinar?", "Gránulos eosinófilos de zimógeno."],
    ["¿Qué son las células centroacinares?", "Células del inicio del conducto intercalado ubicadas dentro del acino."],
    ["¿Cómo se tiñen las células centroacinares en H&E?", "Muy pálidamente."],
    ["¿Qué carecen de forma característica las células centroacinares?", "RER y gránulos de secreción."],
    ["¿Cómo se llama el conducto intercalado pancreático?", "Conducto de Boll."],
    ["¿Qué conductos drenan los conductos de Boll?", "Conductos colectores intralobulillares."],
    ["¿Qué falta en el sistema de conductos pancreático a diferencia de salivales?", "Conductos estriados."],
    ["¿Qué conducto principal recorre toda la glándula?", "Conducto pancreático principal de Wirsung."],
    ["¿Qué conducto accesorio puede abrirse en papila menor?", "Conducto de Santorini."],
  ]},
  { topic: "Páncreas exocrino", subtopic: "Enzimas y regulación", cards: [
    ["¿Qué proenzima pancreática se activa primero en intestino?", "Tripsinógeno."],
    ["¿Qué enzima del glucocáliz activa tripsinógeno?", "Enterocinasa."],
    ["¿Qué enzima activa otras proenzimas pancreáticas?", "Tripsina."],
    ["¿Qué digieren tripsinógeno y quimiotripsinógeno ya activados?", "Proteínas."],
    ["¿Qué enzima pancreática digiere enlaces glucosídicos de carbohidratos?", "Alfa-amilasa."],
    ["¿Qué enzimas pancreáticas rompen enlaces éster de triglicéridos?", "Lipasas."],
    ["¿Qué enzimas pancreáticas digieren ácidos nucleicos?", "Ribonucleasa y desoxirribonucleasa."],
    ["¿Qué secreta principalmente un acino pancreático?", "Un pequeño volumen rico en proenzimas."],
    ["¿Qué secretan principalmente conductos de Boll?", "Un gran volumen rico en sodio y bicarbonato."],
    ["¿Qué hormona estimula secreción ductal rica en bicarbonato?", "Secretina."],
    ["¿Qué hormona estimula que acinos liberen proenzimas?", "Colecistoquinina."],
    ["¿Qué efecto tiene bicarbonato pancreático en duodeno?", "Neutraliza quimo ácido y favorece actividad enzimática."],
    ["¿Qué fibras autonómicas estimulan actividad acinar y centroacinar?", "Parasimpáticas."],
    ["¿Qué fibras regulan especialmente flujo sanguíneo pancreático?", "Simpáticas."],
  ]},
  { topic: "Páncreas endocrino", subtopic: "Islotes de Langerhans", cards: [
    ["¿Qué componente pancreático secreta hormonas a sangre?", "Los islotes de Langerhans."],
    ["¿Qué porcentaje de masa pancreática constituyen aproximadamente los islotes?", "Entre 1 y 2%."],
    ["¿Dónde son más abundantes los islotes pancreáticos?", "En la cola del páncreas."],
    ["¿Cómo se ven los islotes en H&E respecto de acinos?", "Como grupos celulares más pálidos."],
    ["¿Cómo se organizan las células endocrinas de un islote?", "En cordones cortos irregulares."],
    ["¿Qué tipo de capilar rodea cordones insulares?", "Capilares fenestrados."],
    ["¿Qué proporción del flujo pancreático reciben islotes pese a su masa pequeña?", "Alrededor de 10 a 15%."],
    ["¿Cuándo aparecen células endocrinas definitivas del islote?", "Entre semanas 9 y 12 de gestación."],
    ["¿Qué células producen insulina?", "Las células B o beta."],
    ["¿Qué células producen glucagón?", "Las células A o alfa."],
    ["¿Qué células producen somatostatina?", "Las células D o delta."],
    ["¿Qué proporción aproximada son células B?", "60 a 70%."],
    ["¿Qué proporción aproximada son células A?", "15 a 20%."],
    ["¿Qué proporción aproximada son células D?", "5 a 10%."],
    ["¿Qué morfología ultraestructural tienen gránulos beta?", "Centro cristalino angular denso con halo claro."],
    ["¿Qué morfología ultraestructural tienen gránulos alfa?", "Centro denso excéntrico con halo claro."],
  ]},
  { topic: "Páncreas endocrino", subtopic: "Hormonas y regulación insular", cards: [
    ["¿Qué hormona favorece entrada de glucosa por GLUT4 en músculo y adiposo?", "Insulina."],
    ["¿Qué enzima activa insulina para formar glucógeno?", "Glucógeno sintasa."],
    ["¿Qué enzima inhibe insulina para frenar glucogenólisis?", "Glucógeno fosforilasa."],
    ["¿Qué efecto tiene insulina sobre lipogénesis?", "La estimula."],
    ["¿Qué efecto tiene insulina sobre captación de aminoácidos?", "La aumenta y favorece síntesis proteica."],
    ["¿Qué dos procesos hepáticos estimula glucagón para elevar glucemia?", "Glucogenólisis y gluconeogénesis."],
    ["¿Qué hormona inhibe dentro del islote tanto insulina como glucagón?", "Somatostatina."],
    ["¿A partir de qué glucemia aproximada se estimula secreción de insulina?", "Por encima de 70 mg/dL."],
    ["¿Qué estímulos no glucídicos favorecen secreción de insulina?", "Aminoácidos, ácidos grasos y hormonas digestivas."],
    ["¿Qué glucemia estimula secreción de glucagón?", "Una glucemia inferior a unos 70 mg/dL."],
    ["¿Qué efecto tiene la insulina sobre células alfa?", "Inhibe su secreción de glucagón."],
    ["¿Qué efecto tiene el simpático sobre insulina y glucagón?", "Inhibe insulina y aumenta glucagón."],
    ["¿Qué efecto tiene el parasimpático sobre secreción insular?", "Puede aumentar insulina y glucagón."],
    ["¿Qué célula insular produce polipéptido pancreático?", "La célula PP o F."],
    ["¿Qué hormona secretan células épsilon?", "Grelina."],
    ["¿Qué efecto tiene polipéptido pancreático sobre páncreas exocrino?", "Lo inhibe."],
  ]},
  { topic: "Páncreas endocrino", subtopic: "Síntesis de insulina y clínica", cards: [
    ["¿Cuál es el precursor inicial de insulina sintetizado en RER?", "Preproinsulina."],
    ["¿Qué se retira de preproinsulina para formar proinsulina?", "El péptido señal."],
    ["¿Cuántos aminoácidos tiene la cadena A de insulina madura?", "21."],
    ["¿Cuántos aminoácidos tiene la cadena B de insulina madura?", "30."],
    ["¿Qué une las cadenas A y B de la insulina madura?", "Puentes disulfuro."],
    ["¿Qué fragmento se elimina de proinsulina durante maduración?", "Péptido C."],
    ["¿Cómo se liberan insulina y péptido C desde una célula beta?", "En cantidades equimolares."],
    ["¿Por qué péptido C sirve para evaluar secreción endógena?", "Dura más en circulación y se elimina por riñón."],
    ["¿Qué complicación metabólica principal produce insuficiencia de insulina?", "Hiperglucemia."],
    ["¿Qué hallazgo urinario puede acompañar hiperglucemia marcada?", "Glucosuria."],
    ["¿Qué sistema vascular lleva hormonas de islotes a acinos cercanos?", "El sistema porta insuloacinar."],
    ["¿Qué hormona insular estimula secreción exocrina pancreática?", "Insulina."],
    ["¿Qué hormonas insulares inhiben secreción exocrina?", "Glucagón, somatostatina y polipéptido pancreático."],
    ["¿Qué relación se ha propuesto entre señalización cerebral de insulina y Alzheimer?", "Resistencia o disminución de señal de insulina puede contribuir a neurodegeneración."],
  ]},
]

const slug = (value: string) => value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")

export const cap18RebuiltFlashcards: Flashcard[] = groups.flatMap(group =>
  group.cards.map(([front, back], index) => ({
    id: `histo-cap18-${slug(group.subtopic)}-${String(index + 1).padStart(3, "0")}`,
    subject: "Histología", book: "Ross", chapter: "Capítulo 18", topic: group.topic, subtopic: group.subtopic,
    front, back, tags: ["Capítulo 18", group.subtopic]
  }))
)
