import type { Flashcard } from "./cards"

type Pair = readonly [string, string]
type Group = { topic: string; subtopic: string; cards: readonly Pair[] }

// Capítulo 19 se reconstruye desde Ross con el patrón explícito de caps. 16–18.
const groups: readonly Group[] = [
  { topic: "Fundamentos respiratorios", subtopic: "Organización y acondicionamiento", cards: [
    ["¿Cuáles son las tres funciones generales del sistema respiratorio?", "Conducción del aire, filtración o acondicionamiento e intercambio gaseoso."],
    ["¿Dónde ocurre principalmente el intercambio gaseoso pulmonar?", "En los alvéolos."],
    ["¿Qué estructuras forman la porción conductora?", "Cavidades nasales, faringe, laringe, tráquea, bronquios y bronquiolos terminales."],
    ["¿Qué estructuras forman la porción respiratoria?", "Bronquiolos respiratorios, conductos alveolares, sacos alveolares y alvéolos."],
    ["¿Qué segmento es el último de la porción conductora?", "El bronquiolo terminal."],
    ["¿Qué segmento es el primero de la porción respiratoria?", "El bronquiolo respiratorio."],
    ["¿Por qué el bronquiolo respiratorio participa en intercambio gaseoso?", "Porque ya presenta alvéolos en su pared."],
    ["¿De qué estructura endodérmica se desarrolla el epitelio de vías respiratorias?", "Del divertículo laringotraqueal del intestino anterior."],
    ["¿De dónde derivan cartílago y músculo liso de la vía respiratoria?", "Del mesénquima torácico esplácnico."],
    ["¿Qué tres procesos acondicionan el aire inspirado en cavidades nasales?", "Calentamiento, humidificación y eliminación de partículas."],
    ["¿Qué estructura nasal retiene primero partículas grandes del aire inspirado?", "Las vibrisas del vestíbulo nasal."],
    ["¿Hacia dónde desplaza el aparato mucociliar las secreciones atrapadas?", "Hacia la faringe para ser deglutidas."],
  ]},
  { topic: "Cavidades nasales", subtopic: "Vestíbulo y región respiratoria", cards: [
    ["¿Qué epitelio reviste el vestíbulo nasal inmediatamente tras la narina?", "Epitelio plano estratificado continuo con la piel."],
    ["¿Qué región nasal ocupa los dos tercios inferiores de la cavidad?", "La región respiratoria."],
    ["¿Qué epitelio cubre la región respiratoria nasal?", "Epitelio cilíndrico seudoestratificado ciliado."],
    ["¿Qué tipo celular es más abundante en el epitelio respiratorio?", "La célula ciliada."],
    ["¿Qué célula respiratoria produce el moco superficial?", "La célula caliciforme."],
    ["¿Qué células renuevan el epitelio respiratorio después de lesión?", "Las células basales."],
    ["¿Qué función tienen los cornetes nasales sobre el aire?", "Aumentan superficie y turbulencia para acondicionarlo."],
    ["¿Qué célula respiratoria tiene función neuroendocrina y secreta aminas o péptidos?", "La célula de gránulos pequeños o de Kulchitsky."],
    ["¿Qué tipo de secreción producen glándulas seromucosas nasales?", "Moco y líquido seroso que humedecen el aire y atrapan partículas."],
    ["¿Qué tipo de vasos explican la capacidad de calentar aire en mucosa nasal?", "Plexos venosos abundantes de la lámina propia."],
  ]},
  { topic: "Cavidades nasales", subtopic: "Región olfatoria y senos", cards: [
    ["¿Qué región nasal ocupa el tercio superior de cada cavidad?", "La región olfatoria."],
    ["¿Qué tipo de neurona es la célula receptora olfatoria?", "Una neurona bipolar."],
    ["¿Dónde terminan las dendritas de las neuronas olfatorias?", "En una vesícula olfatoria con cilios no móviles."],
    ["¿Qué células dan soporte físico y metabólico a neuronas olfatorias?", "Las células de sostén."],
    ["¿Qué células reemplazan neuronas receptoras olfatorias?", "Las células basales olfatorias."],
    ["¿Qué glándulas serosas disuelven sustancias odoríferas?", "Las glándulas de Bowman."],
    ["¿Qué tipo de epitelio reviste la mayoría de los senos paranasales?", "Epitelio respiratorio más delgado y con menos células caliciformes."],
    ["¿Qué función cumple el moco y los cilios en senos paranasales?", "Dirigir secreciones hacia las cavidades nasales."],
  ]},
  { topic: "Cavidades nasales", subtopic: "Defensa, olfacción y clínica", cards: [
    ["¿Qué células de la región respiratoria nasal detectan sustancias irritantes mediante microvellosidades romas?", "Las células en cepillo."],
    ["¿Con qué nervio craneal hacen contacto las células en cepillo de la mucosa nasal?", "Con terminaciones del nervio trigémino (V)."],
    ["¿Qué reflejo puede desencadenar una partícula que irrita receptores sensitivos de la mucosa nasal?", "El estornudo."],
    ["¿Qué ocurre primero en el reflejo del estornudo antes de expulsar el aire?", "Una inspiración rápida llena los pulmones de aire."],
    ["¿Qué estructuras laríngeas se cierran transitoriamente durante el estornudo?", "Cuerdas vocales, pliegues vestibulares y epiglotis."],
    ["¿Qué población de linfocitos predomina en la inmunidad local de mucosa respiratoria nasal?", "Linfocitos T gamma/delta."],
    ["¿Por qué una alergia nasal puede obstruir el paso de aire?", "Porque los vasos se congestionan, trasudan líquido y la mucosa se edematiza."],
    ["¿Qué cambio microscópico ayuda a reconocer mucosa olfatoria en una lámina?", "Nervios olfatorios y glándulas de Bowman en la lámina propia."],
    ["¿Qué moléculas secretan las células de soporte para transportar odorantes hacia sus receptores?", "Proteínas fijadoras de sustancias odoríferas u OBP."],
    ["¿Qué segundo mensajero inicia la apertura de canales de Na+ y Ca2+ en la transducción olfatoria?", "AMP cíclico."],
    ["¿Qué evento eléctrico produce la entrada de Na+ y Ca2+ en la neurona olfatoria?", "Despolarización y generación de un potencial de acción."],
    ["¿Qué hueso atraviesan los fascículos axónicos olfatorios para llegar al bulbo?", "La lámina cribosa del etmoides."],
    ["¿Qué déficit puede aparecer tras cortar axones olfatorios en un traumatismo craneal?", "Anosmia."],
    ["¿Qué efecto tienen las glándulas de Bowman además de disolver odorantes?", "Eliminan restos de olores previos y permiten percibir nuevos estímulos."],
    ["¿Qué gas se produce en altas concentraciones en senos paranasales y ayuda a defensa local?", "Óxido nítrico."],
    ["¿Qué efecto pulmonar del óxido nítrico procedente de senos favorece el intercambio gaseoso?", "Relaja músculo liso vascular y reduce resistencia vascular pulmonar."],
  ]},
  { topic: "Faringe y laringe", subtopic: "Organización y pliegues laríngeos", cards: [
    ["¿Qué regiones comunica la faringe con la laringe y el esófago?", "Las cavidades nasal y bucal."],
    ["¿Qué dos sistemas comparten la faringe?", "El respiratorio y el digestivo."],
    ["¿Qué parte de la faringe comunica con el oído medio por trompas auditivas?", "La nasofaringe."],
    ["¿Cómo se llama la concentración linfática en la unión superior y posterior de la faringe?", "Amígdala faríngea."],
    ["¿Entre qué dos segmentos se localiza la laringe?", "Entre la bucofaringe y la tráquea."],
    ["¿Qué dos funciones principales cumple la laringe?", "Conducir aire y producir fonación."],
    ["¿Qué dos tipos de cartílago forman el esqueleto laríngeo?", "Cartílago hialino y cartílago elástico."],
    ["¿Qué par de pliegues laríngeos es móvil y participa directamente en fonación?", "Los pliegues vocales verdaderos."],
    ["¿Qué par de pliegues laríngeos se sitúa por encima de los vocales?", "Los pliegues vestibulares o cuerdas vocales falsas."],
    ["¿Cómo se llama el espacio entre pliegues vestibulares y vocales?", "El ventrículo laríngeo."],
    ["¿Cómo se llama la abertura de la laringe delimitada lateralmente por pliegues vocales?", "La hendidura glótica o glotis."],
    ["¿Qué dos elementos internos de un pliegue vocal permiten ajustar su tensión?", "El ligamento vocal y el músculo vocal esquelético."],
    ["¿Qué efecto tiene aumentar la tensión de los pliegues vocales sobre el tono?", "Produce un tono más alto."],
    ["¿Qué tono originan pliegues vocales más relajados?", "Un tono más profundo."],
    ["¿Por qué los pliegues ventriculares no son las cuerdas de la fonación?", "Porque no poseen músculo intrínseco que module su tensión."],
    ["¿Qué función acústica aportan pliegues ventriculares y ventrículo?", "Contribuyen a la resonancia."],
  ]},
  { topic: "Faringe y laringe", subtopic: "Revestimiento y correlación clínica", cards: [
    ["¿Qué epitelio reviste la superficie luminal de los pliegues vocales?", "Epitelio plano estratificado no queratinizado."],
    ["¿Por qué los pliegues vocales requieren epitelio plano estratificado?", "Para resistir abrasión por la corriente de aire rápida."],
    ["¿Qué epitelio cubre la mayor parte restante de la laringe?", "Epitelio cilíndrico seudoestratificado ciliado."],
    ["¿Qué tipo de glándulas se encuentran en el tejido conjuntivo laríngeo?", "Glándulas mucoserosas mixtas."],
    ["¿Qué región subepitelial del pliegue vocal es poco vascularizada y sin linfáticos?", "El espacio de Reinke."],
    ["¿Qué epitelio puede aparecer en zonas de laringe expuestas al estrés mecánico?", "Epitelio plano estratificado por metaplasia escamosa."],
    ["¿Cómo se llama la inflamación aguda de la laringe con disfonía o afonía?", "Laringitis aguda."],
    ["¿Qué exposición sostenida es causa frecuente de laringitis crónica?", "Humo de tabaco, polvo o aire contaminado."],
    ["¿Qué alteración epitelial adaptativa produce irritación crónica de vías respiratorias?", "Metaplasia cilíndrica a escamosa."],
    ["¿Una célula ciliada madura se transforma directamente en célula escamosa durante metaplasia?", "No; células basales proliferan y originan el nuevo epitelio diferenciado."],
    ["¿Por qué el epitelio metaplásico escamoso es funcionalmente desfavorable?", "Resiste mejor lesión, pero pierde eficacia mucociliar."],
    ["¿Qué hábito favorece pérdida progresiva del movimiento ciliar y metaplasia escamosa?", "El tabaquismo."],
    ["¿Qué tipo de carcinoma puede originarse en epitelio escamoso metaplásico persistente?", "Carcinoma epidermoide."],
  ]},
  { topic: "Tráquea", subtopic: "Capas y sostén de la pared", cards: [
    ["¿Qué estructura mantiene abierta la luz de la tráquea durante la espiración?", "Los anillos de cartílago hialino en forma de C."],
    ["¿Qué órgano se ubica inmediatamente detrás de la tráquea?", "El esófago."],
    ["¿Cuáles son las cuatro capas de la pared traqueal?", "Mucosa, submucosa, capa cartilaginosa y adventicia."],
    ["¿Qué componentes forman la mucosa traqueal?", "Epitelio seudoestratificado ciliado y lámina propia rica en fibras elásticas."],
    ["¿Qué tipo de tejido predomina en la submucosa de la tráquea?", "Tejido conjuntivo relativamente laxo."],
    ["¿Qué capa fija la tráquea a estructuras del cuello y mediastino?", "La adventicia."],
    ["¿Dónde se ubica la brecha de los anillos cartilaginosos traqueales?", "En la pared posterior, junto al esófago."],
    ["¿Qué músculo liso une los extremos libres posteriores de los anillos traqueales?", "El músculo traqueal."],
    ["¿Qué componente permite flexibilidad entre anillos traqueales?", "Tejido fibroelástico asociado con músculo liso."],
    ["¿Qué cambio puede experimentar el cartílago traqueal con la edad?", "Reemplazo parcial por tejido óseo."],
    ["¿Qué capa marca el límite entre lámina propia y submucosa traqueal?", "La membrana elástica."],
    ["¿Qué capa puede verse engrosada en fumadores con tos crónica y en asma?", "La membrana basal aparente del epitelio respiratorio."],
    ["¿Qué estructura inmunitaria se encuentra de manera difusa y nodular en pared traqueal?", "Tejido linfático asociado a bronquios, BALT."],
    ["¿Dónde son especialmente abundantes glándulas traqueales seromucosas?", "En la región posterior sin cartílago."],
  ]},
  { topic: "Tráquea", subtopic: "Epitelio y depuración mucociliar", cards: [
    ["¿Cuáles son los tres tipos celulares principales del epitelio traqueal?", "Células ciliadas, células caliciformes mucosas y células basales."],
    ["¿Cuál es la célula más abundante del epitelio traqueal?", "La célula cilíndrica ciliada."],
    ["¿Cuántos cilios puede poseer aproximadamente una célula ciliada traqueal?", "Alrededor de 250."],
    ["¿Qué estructura genera la línea oscura bajo los cilios en una preparación histológica?", "Los cuerpos basales alineados."],
    ["¿En qué dirección desplazan los cilios traqueales la capa mucosa?", "Desde vías aéreas distales hacia la faringe."],
    ["¿Qué sustancias almacenan las células caliciformes antes de secretar moco?", "Gránulos de mucinógeno."],
    ["¿Qué ocurre con el número de células mucosas durante irritación crónica?", "Aumenta."],
    ["¿Qué rasgo ultraestructural identifica una célula en cepillo traqueal?", "Microvellosidades romas y contacto sináptico con una fibra aferente."],
    ["¿Qué función sensorial tienen las células en cepillo respiratorias?", "Quimiorrecepción y detección sensorial general."],
    ["¿Qué otro nombre reciben las células granulares pequeñas respiratorias?", "Células de Kulchitsky."],
    ["¿A qué grupo funcional equivalen las células de Kulchitsky en el tubo digestivo?", "A células enteroendocrinas."],
    ["¿Qué sustancias pueden secretar células granulares pequeñas?", "Catecolaminas o péptidos como serotonina, calcitonina y bombesina."],
    ["¿Qué estructuras forman las células granulares pequeñas agrupadas con fibras nerviosas?", "Corpúsculos neuroepiteliales."],
    ["¿Qué células actúan como reserva para reponer epitelio traqueal?", "Las células basales."],
  ]},
  { topic: "Bronquios", subtopic: "Ramificación y pared bronquial", cards: [
    ["¿Cuál bronquio principal es más corto y amplio?", "El bronquio principal derecho."],
    ["¿En cuántos bronquios lobulares se divide el bronquio principal derecho?", "En tres."],
    ["¿En cuántos bronquios lobulares se divide el bronquio principal izquierdo?", "En dos."],
    ["¿Qué bronquios reciben también el nombre de terciarios?", "Los bronquios segmentarios."],
    ["¿Qué forma un bronquio segmentario junto con el parénquima que depende de él?", "Un segmento broncopulmonar."],
    ["¿Por qué un segmento broncopulmonar puede resecarse quirúrgicamente de forma relativamente independiente?", "Porque posee irrigación y tabiques conjuntivos propios."],
    ["¿Qué reemplaza los anillos cartilaginosos cuando un bronquio entra al pulmón?", "Placas cartilaginosas irregulares."],
    ["¿Qué combinación histológica identifica a un bronquio intrapulmonar?", "Placas de cartílago y una capa circular de músculo liso."],
    ["¿Qué sucede con las placas cartilaginosas al reducirse el calibre bronquial?", "Se hacen más pequeñas y menos abundantes hasta desaparecer."],
    ["¿A partir de qué cambio de diámetro se denomina bronquiolo a la vía aérea?", "Cuando ya no hay placas cartilaginosas, alrededor de 1 mm."],
    ["¿Cuáles son las cinco capas de la pared de un bronquio intrapulmonar?", "Mucosa, muscular, submucosa, cartílago y adventicia."],
    ["¿Qué capa regula activamente el diámetro de un bronquio?", "La capa de músculo liso."],
    ["¿Cómo cambia la altura epitelial al disminuir el calibre de los bronquios?", "Disminuye progresivamente."],
    ["¿Qué contienen los bronquios mayores en su submucosa además de tejido conjuntivo?", "Glándulas y tejido adiposo."],
  ]},
  { topic: "Bronquiolos", subtopic: "Estructura y células club", cards: [
    ["¿Qué diámetro máximo define a un bronquiolo?", "Un milímetro o menos."],
    ["¿Qué dos estructuras faltan por completo en bronquiolos normales?", "Placas cartilaginosas y glándulas subepiteliales."],
    ["¿Qué epitelio tienen inicialmente los bronquiolos grandes?", "Cilíndrico seudoestratificado ciliado."],
    ["¿Qué epitelio predomina en bronquiolos terminales?", "Cúbico simple."],
    ["¿Qué células desaparecen normalmente antes de llegar al bronquiolo terminal?", "Las células caliciformes."],
    ["¿Qué capa permanece relativamente gruesa en la pared de todos los bronquiolos?", "La capa de músculo liso."],
    ["¿Cuál es el bronquiolo más distal que todavía pertenece solo a la vía conductora?", "El bronquiolo terminal."],
    ["¿Qué células no ciliadas, de ápice abombado, aparecen entre células ciliadas terminales?", "Las células club o de Clara."],
    ["¿Qué ocurre con la proporción de células club al avanzar hacia el extremo distal del bronquiolo?", "Aumenta mientras disminuyen las células ciliadas."],
    ["¿Qué característica apical permite reconocer una célula club?", "Una prominencia redondeada en forma de cúpula, sin cilios."],
    ["¿Qué secreción lipoproteica de la célula club evita adhesión luminal cuando se colapsa la vía aérea?", "Surfactante bronquiolar."],
    ["¿Qué proteína secretora de 16 kDa se usa como marcador de lesión de células club?", "CC16."],
    ["¿Cómo cambia la CC16 del líquido bronquial cuando se lesionan células club?", "Disminuye."],
    ["¿Qué orgánulo apical está muy desarrollado en célula club y se asocia con detoxificación?", "El retículo endoplasmático liso."],
    ["¿Qué manifestación epitelial es frecuente en asma bronquiolar?", "Más células caliciformes, membrana basal engrosada y músculo liso hiperplásico."],
  ]},
  { topic: "Bronquiolos", subtopic: "Porción respiratoria y asma", cards: [
    ["¿Qué estructura marca el inicio de la porción respiratoria del árbol bronquial?", "El bronquiolo respiratorio."],
    ["¿Por qué el bronquiolo respiratorio es una zona de transición?", "Porque conduce aire y también intercambia gases mediante alvéolos de su pared."],
    ["¿Qué estructuras nacen de los bronquiolos respiratorios?", "Conductos alveolares."],
    ["¿Cómo están delimitados los conductos alveolares?", "Casi solo por aberturas de alvéolos a lo largo de su trayecto."],
    ["¿Qué son los sacos alveolares?", "Espacios terminales rodeados por grupos de alvéolos."],
    ["¿Qué integra un acino pulmonar?", "Un bronquiolo terminal, sus bronquiolos respiratorios y los alvéolos que reciben aire de ellos."],
    ["¿Cuál es la unidad funcional más pequeña del pulmón?", "La unidad bronquiolar respiratoria."],
    ["¿Qué dos mecanismos causan la obstrucción recurrente del flujo de aire en asma?", "Inflamación bronquiolar y broncoespasmo por constricción del músculo liso."],
    ["¿Qué célula inflamatoria es especialmente típica en pared bronquiolar asmática?", "El eosinófilo."],
    ["¿Qué cambio de la lámina reticular contribuye al engrosamiento de membrana basal en asma?", "Mayor depósito de colágeno."],
    ["¿Qué clase de fármaco revierte rápidamente el broncoespasmo?", "Agonistas beta-adrenérgicos broncodilatadores."],
    ["¿Qué tipo de tratamiento controla inflamación asmática a largo plazo?", "Corticoesteroides inhalados."],
    ["¿Qué mediadores lipídicos reducen los modificadores de leucotrienos?", "Los leucotrienos."],
  ]},
  { topic: "Alvéolos", subtopic: "Tabiques y neumocitos", cards: [
    ["¿Qué estructura separa dos espacios aéreos alveolares contiguos?", "El tabique interalveolar."],
    ["¿Qué contiene el tabique interalveolar que permite intercambio con sangre?", "Una red de capilares sanguíneos."],
    ["¿Qué tipo celular cubre alrededor del 95% de la superficie alveolar?", "El neumocito tipo I."],
    ["¿Qué tipo celular cubre poca superficie alveolar pero es más numeroso como célula?", "El neumocito tipo II."],
    ["¿Qué propiedad hace al neumocito tipo I apto para difusión gaseosa?", "Su citoplasma extremadamente delgado y plano."],
    ["¿Los neumocitos tipo I se dividen para reparar el epitelio?", "No; son reemplazados por progenie de neumocitos tipo II."],
    ["¿Qué orgánulos característicos contienen los neumocitos tipo II?", "Cuerpos laminares."],
    ["¿Qué secretan los neumocitos tipo II hacia la luz alveolar?", "Surfactante pulmonar."],
    ["¿Qué cambio celular señala reparación tras lesión alveolar?", "Hiperplasia de neumocitos tipo II."],
    ["¿Qué células originan tanto neumocitos tipo I como tipo II durante reparación?", "Los neumocitos tipo II."],
    ["¿Qué célula alveolar escasa vigila químicamente la calidad del aire?", "La célula en cepillo."],
    ["¿Qué fosfolípido es el principal responsable de reducir tensión superficial del surfactante?", "Dipalmitoilfosfatidilcolina, DPPC."],
    ["¿Qué evitaría el surfactante durante la espiración?", "El colapso de los alvéolos."],
    ["¿En qué semana gestacional aproximadamente comienza producción fetal suficiente de surfactante?", "Después de la semana 35."],
    ["¿Qué síndrome aparece en prematuros por déficit de surfactante?", "Síndrome de dificultad respiratoria neonatal."],
  ]},
  { topic: "Alvéolos", subtopic: "Barrera hematogaseosa y defensa", cards: [
    ["¿Qué componentes forman la parte más delgada de la barrera hematogaseosa?", "Surfactante, neumocito I, lámina basal fusionada y endotelio capilar."],
    ["¿Dónde ocurre la mayor parte del intercambio gaseoso del tabique interalveolar?", "En su porción delgada."],
    ["¿Qué característica define la porción gruesa del tabique interalveolar?", "Tejido conjuntivo entre las láminas basales."],
    ["¿Por qué es importante la porción gruesa del tabique?", "Puede acumular líquido tisular antes de que alcance el alvéolo."],
    ["¿Qué vasos drenan líquido acumulado en porciones gruesas del tabique?", "Vasos linfáticos del tejido conjuntivo bronquiolar terminal."],
    ["¿Qué células reciben el nombre de células del polvo?", "Los macrófagos alveolares."],
    ["¿Cuál es el origen de los macrófagos alveolares?", "Monocitos de la sangre."],
    ["¿Qué destino pueden tener macrófagos alveolares cargados de partículas?", "Subir con moco al árbol bronquial y eliminarse por deglución o expectoración."],
    ["¿Qué pigmento contienen macrófagos que fagocitaron eritrocitos en congestión pulmonar?", "Hemosiderina."],
    ["¿Qué nombre reciben macrófagos con hemosiderina en insuficiencia ventricular izquierda?", "Células de la insuficiencia cardíaca."],
    ["¿Qué contaminante pigmenta macrófagos septales en fumadores y habitantes urbanos?", "Carbono o pigmento antracótico."],
    ["¿Qué bacilo puede sobrevivir fagocitado dentro de macrófagos alveolares?", "Mycobacterium tuberculosis."],
    ["¿Qué poros comunican alvéolos vecinos y permiten ventilación colateral?", "Los poros de Kohn."],
    ["¿En qué contexto los poros de Kohn ayudan a ventilar alvéolos distales?", "Cuando una obstrucción bloquea la vía aérea normal."],
  ]},
  { topic: "Pulmón", subtopic: "Irrigación, linfáticos e inervación", cards: [
    ["¿Qué dos circulaciones tiene el pulmón?", "La pulmonar y la bronquial."],
    ["¿Qué circulación irriga capilares de tabiques interalveolares?", "La circulación pulmonar."],
    ["¿De qué cavidad cardíaca sale la arteria pulmonar?", "Del ventrículo derecho."],
    ["¿A qué cavidad cardíaca devuelven sangre oxigenada las venas pulmonares?", "A la aurícula izquierda."],
    ["¿Qué tejidos irrigan las arterias bronquiales?", "Paredes de bronquios y bronquiolos, y tejido conjuntivo pulmonar, no los alvéolos."],
    ["¿Dónde se anastomosan aproximadamente las circulaciones bronquial y pulmonar?", "En la transición entre porción conductora y respiratoria."],
    ["¿Qué región drenan principalmente las venas bronquiales?", "Tejido conjuntivo de la región hiliar."],
    ["¿Qué dos territorios drena el sistema linfático pulmonar doble?", "Parénquima que sigue vías aéreas y superficie pulmonar en pleura visceral."],
    ["¿Qué epitelio recubre la pleura visceral?", "Mesotelio plano simple."],
    ["¿Qué divisiones del sistema nervioso autónomo inervan el pulmón?", "Simpática y parasimpática."],
    ["¿Qué controlan los nervios autónomos en la pared de vías respiratorias?", "El calibre por músculo liso y la secreción glandular."],
  ]},
  { topic: "Correlación clínica", subtopic: "Rinitis, fibrosis quística y EPOC", cards: [
    ["¿Cómo se denomina inflamación de la mucosa nasal?", "Rinitis."],
    ["¿Qué extensión de rinitis afecta también senos paranasales?", "Rinosinusitis."],
    ["¿Qué células abundan especialmente en rinitis alérgica?", "Eosinófilos, plasmocitos y mastocitos."],
    ["¿Qué inmunoglobulina se une a mastocitos en rinitis alérgica?", "IgE."],
    ["¿Qué mediadores liberados por mastocitos causan rinorrea y congestión?", "Histamina y leucotrienos."],
    ["¿Qué gen está mutado en fibrosis quística?", "CFTR, localizado en cromosoma 7."],
    ["¿Qué tipo de herencia presenta fibrosis quística?", "Autosómica recesiva."],
    ["¿Qué transporte se altera directamente en epitelio bronquial de fibrosis quística?", "La secreción de cloruro hacia la luz."],
    ["¿Cómo cambia la reabsorción de sodio y agua en fibrosis quística?", "Aumenta, deshidratando el moco."],
    ["¿Por qué aumenta el riesgo de infecciones respiratorias en fibrosis quística?", "El moco viscoso obstruye vías y falla la depuración mucociliar."],
    ["¿Qué caracteriza anatómicamente al enfisema?", "Agrandamiento permanente de espacios distales al bronquiolo terminal con destrucción de pared alveolar."],
    ["¿Qué superficie funcional disminuye cuando se destruyen tabiques en enfisema?", "La superficie de intercambio gaseoso."],
    ["¿Cuál es la causa más frecuente de enfisema?", "Tabaquismo."],
    ["¿Qué déficit hereditario favorece una forma grave de enfisema?", "Deficiencia de alfa-1-antitripsina."],
    ["¿Qué llena inicialmente los alvéolos en neumonía bacteriana temprana?", "Exudado rico en proteínas con microorganismos."],
    ["¿Qué células predominan en el exudado de hepatización roja?", "Neutrófilos y eritrocitos."],
    ["¿Por qué el pulmón se ve firme y rojo en hepatización roja?", "Los alvéolos se llenan de exudado y los capilares están congestionados."],
    ["¿Qué células eliminan neutrófilos fragmentados durante hepatización gris?", "Macrófagos."],
  ]},
]

const slug = (value: string) => value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")

export const cap19RebuiltFlashcards: Flashcard[] = groups.flatMap(group =>
  group.cards.map(([front, back], index) => ({
    id: `histo-cap19-${slug(group.subtopic)}-${String(index + 1).padStart(3, "0")}`,
    subject: "Histología", book: "Ross", chapter: "Capítulo 19", topic: group.topic, subtopic: group.subtopic,
    front, back, tags: ["Capítulo 19", group.subtopic]
  }))
)
