import type { Flashcard } from "./cards"
import { cap16ExtraFlashcards } from "./cap16Extra"

type Pair = readonly [string, string]
type Group = { topic: string; subtopic: string; cards: readonly Pair[] }

const groups: Group[] = [
  { topic: "Fundamentos del sistema digestivo", subtopic: "Fundamentos digestivos", cards: [
    ["¿Qué componentes forman el sistema digestivo?", "El tubo digestivo y sus órganos asociados."],
    ["¿Cuáles son los principales órganos asociados al tubo digestivo?", "Lengua, dientes, glándulas salivales, páncreas, hígado y vesícula biliar."],
    ["¿Cuáles son las cuatro funciones generales del sistema digestivo?", "Transporte, secreción, digestión y absorción, y excreción."],
    ["¿Cómo se considera la luz del tubo digestivo respecto del cuerpo?", "Física y funcionalmente exterior al cuerpo."],
    ["¿Qué superficie media entre la luz digestiva y el medio interno?", "La mucosa digestiva."],
    ["¿Qué cuatro funciones cumple la mucosa digestiva?", "Secreción, absorción, barrera y protección inmunitaria."],
    ["¿Cuánto material se ingiere aproximadamente cada día?", "Cerca de 2 L de agua y alimentos."],
    ["¿Cuánto pueden sumar los jugos digestivos secretados al día?", "Cerca de 7 L."],
    ["¿Dónde se absorbe la mayor parte de los líquidos y nutrientes?", "En el intestino delgado."],
    ["¿Qué componentes pueden encontrarse en las heces además de alimento no digerido?", "Moco, bacterias, células descamadas y pigmentos biliares."],
  ]},
  { topic: "Cavidad bucal", subtopic: "Organización de la cavidad bucal", cards: [
    ["¿Qué estructuras principales incluye la cavidad bucal?", "Lengua, dientes y periodonto, glándulas salivales y amígdalas."],
    ["¿En qué dos espacios se divide la cavidad bucal?", "Vestíbulo y cavidad bucal propiamente dicha."],
    ["¿Dónde se encuentra el vestíbulo bucal?", "Entre labios y mejillas por fuera, y dientes por dentro."],
    ["¿Qué limita superiormente la cavidad bucal propiamente dicha?", "El paladar duro y el paladar blando."],
    ["¿Qué la limita inferiormente?", "La lengua y el piso de la boca."],
    ["¿Qué estructura comunica posteriormente con la cavidad bucal?", "La entrada a la bucofaringe."],
    ["¿Dónde desemboca el conducto parotídeo de Stensen?", "En la papila parótida frente al segundo molar superior."],
    ["¿Dónde desemboca el conducto submandibular de Wharton?", "En la carúncula sublingual, a cada lado del frenillo."],
    ["¿Cómo desembocan los conductos de la glándula sublingual?", "Algunos al conducto submandibular y otros directamente al piso de la boca."],
    ["¿Dónde se encuentran las glándulas salivales menores?", "En la submucosa de la cavidad bucal."],
    ["¿Cómo se denominan las glándulas salivales menores?", "Según su ubicación: bucales, labiales, linguales y palatinas."],
    ["¿Qué es el anillo de Waldeyer?", "El anillo protector de tejido amigdalino alrededor de las entradas bucal y nasal."],
    ["¿Qué amígdalas forman el anillo de Waldeyer?", "Palatinas, tubáricas, faríngea y linguales."],
  ]},
  { topic: "Cavidad bucal", subtopic: "Mucosa bucal", cards: [
    ["¿Cuáles son los tres tipos de mucosa bucal?", "Masticatoria, de revestimiento y especializada."],
    ["¿Dónde se encuentra la mucosa masticatoria?", "En encías y paladar duro."],
    ["¿Qué epitelio presenta la mucosa masticatoria?", "Plano estratificado queratinizado o paraqueratinizado."],
    ["¿Qué diferencia al epitelio paraqueratinizado?", "Sus células superficiales conservan núcleos picnóticos."],
    ["¿Qué estrato falta en el epitelio queratinizado de la mucosa masticatoria?", "El estrato lúcido."],
    ["¿Qué capas presenta la lámina propia de la mucosa masticatoria?", "Una capa papilar laxa y una reticular más densa."],
    ["¿Por qué no hay submucosa en el rafe palatino y la encía?", "La lámina propia se fusiona con el periostio."],
    ["¿Qué contiene la submucosa anterior del paladar duro?", "Tejido adiposo."],
    ["¿Qué contiene la submucosa posterior del paladar duro?", "Glándulas mucosas."],
    ["¿Dónde se encuentra la mucosa de revestimiento?", "Labios, mejillas, mucosa alveolar, piso bucal, lengua ventral y paladar blando."],
    ["¿Cómo es usualmente el epitelio de la mucosa de revestimiento?", "Plano estratificado no queratinizado."],
    ["¿Cuáles son sus tres estratos?", "Basal, espinoso y superficial."],
    ["¿Qué sitio de mucosa de revestimiento sí está queratinizado?", "El borde bermellón del labio."],
    ["¿Cómo son sus papilas frente a las de la mucosa masticatoria?", "Menos abundantes y más cortas, para permitir movilidad."],
    ["¿Dónde se restringe la mucosa especializada?", "A la superficie dorsal de la lengua."],
    ["¿Qué son los gránulos de Fordyce?", "Glándulas sebáceas ectópicas sin folículo piloso en la mucosa bucal."],
    ["¿Qué ventaja tiene la administración transmucosa bucal?", "Evita el tubo digestivo, la circulación portal y el primer paso hepático."],
    ["¿Dónde se coloca un fármaco sublingual?", "Debajo de la lengua."],
    ["¿Dónde se coloca un fármaco por vía bucal?", "Entre la mejilla y la encía."],
  ]},
  { topic: "Lengua", subtopic: "Organización lingual", cards: [
    ["¿Qué tipo de órgano es la lengua?", "Un órgano muscular que se proyecta en la cavidad bucal."],
    ["¿Qué distingue a los músculos linguales extrínsecos?", "Tienen al menos una inserción fuera de la lengua."],
    ["¿Qué distingue a los músculos linguales intrínsecos?", "Están confinados por completo dentro de la lengua."],
    ["¿Cómo se orientan los fascículos de músculo estriado lingual?", "En tres planos aproximadamente perpendiculares."],
    ["¿Qué permite esa organización tridimensional?", "Movimientos muy flexibles y precisos."],
    ["¿Qué divide el surco terminal?", "Los dos tercios anteriores del tercio posterior de la lengua."],
    ["¿Hacia dónde apunta el vértice del surco terminal?", "Hacia atrás."],
    ["¿Qué es el foramen ciego lingual?", "Un remanente del origen embrionario de la glándula tiroides."],
    ["¿Qué causa el relieve irregular de la base de la lengua?", "Las amígdalas linguales en la lámina propia."],
    ["¿Qué nervio da la inervación motora lingual principal?", "El nervio hipogloso, NC XII."],
    ["¿Qué nervio lleva sensibilidad general de los dos tercios anteriores?", "El nervio lingual, rama de V3."],
    ["¿Qué nervio lleva el gusto de los dos tercios anteriores?", "La cuerda del tímpano del facial, NC VII."],
    ["¿Qué nervio lleva sensibilidad general y gusto del tercio posterior?", "El glosofaríngeo, NC IX."],
  ]},
  { topic: "Lengua", subtopic: "Papilas linguales", cards: [
    ["¿Cuáles son los cuatro tipos de papilas linguales?", "Filiformes, fungiformes, caliciformes y foliadas."],
    ["¿Cuáles son las papilas más pequeñas y abundantes?", "Las filiformes."],
    ["¿Qué epitelio recubre las papilas filiformes?", "Plano estratificado muy queratinizado."],
    ["¿Qué función tienen las papilas filiformes?", "Exclusivamente mecánica."],
    ["¿Las papilas filiformes poseen botones gustativos?", "No."],
    ["¿Hacia dónde apuntan los extremos de las papilas filiformes?", "Hacia atrás."],
    ["¿Qué forma tienen las papilas fungiformes?", "Forma de hongo."],
    ["¿Dónde abundan las papilas fungiformes?", "Cerca de la punta de la lengua."],
    ["¿Por qué se ven como puntos rojos?", "Por su centro conjuntivo muy vascular y epitelio superficial delgado."],
    ["¿Dónde están los botones gustativos de las fungiformes?", "En el epitelio de su superficie dorsal."],
    ["¿Cuántas papilas caliciformes posee normalmente la lengua humana?", "Entre 8 y 12."],
    ["¿Dónde se sitúan las papilas caliciformes?", "Justo por delante del surco terminal, formando una V."],
    ["¿Dónde están sus botones gustativos?", "En las paredes laterales que miran al surco."],
    ["¿Qué glándulas desembocan en los surcos caliciformes?", "Las glándulas serosas de Von Ebner."],
    ["¿Qué función tiene la secreción de Von Ebner?", "Lava el surco para permitir nuevos estímulos gustativos."],
    ["¿Dónde se encuentran las papilas foliadas?", "En los bordes laterales de la lengua."],
    ["¿Cómo se organizan las papilas foliadas?", "Como crestas paralelas separadas por hendiduras profundas."],
    ["¿En qué grupo etario son más evidentes las papilas foliadas?", "En personas jóvenes."],
    ["¿Dónde se ubican sus botones gustativos?", "En las paredes enfrentadas de papilas contiguas."],
  ]},
  { topic: "Lengua", subtopic: "Botones gustativos", cards: [
    ["¿Cómo se ven los botones gustativos con microscopía óptica?", "Como estructuras ovaladas pálidas que atraviesan el epitelio."],
    ["¿Cómo se llama su abertura superficial?", "Poro gustativo."],
    ["¿Qué tres tipos celulares contienen?", "Células neuroepiteliales, de soporte y basales."],
    ["¿Cuál es el tipo celular más numeroso?", "La célula neuroepitelial sensorial."],
    ["¿Qué proyectan las células sensoriales hacia el poro gustativo?", "Microvellosidades."],
    ["¿Qué unión sella las células cerca del polo apical?", "Zónulas ocluyentes."],
    ["¿Con qué establecen sinapsis las células neuroepiteliales?", "Con fibras nerviosas aferentes gustativas."],
    ["¿Cuánto dura aproximadamente una célula neuroepitelial gustativa?", "Unos 10 días."],
    ["¿Las células de soporte forman sinapsis nerviosas?", "No."],
    ["¿Qué células renuevan el botón gustativo?", "Las células basales."],
    ["¿Dónde más existen botones gustativos fuera de las papilas?", "Arco palatogloso, paladar blando, epiglotis y pared posterior faríngea."],
    ["¿Cuáles son los cinco sabores básicos?", "Dulce, salado, amargo, ácido y umami."],
  ]},
  { topic: "Lengua", subtopic: "Transducción gustativa", cards: [
    ["¿Qué sabores usan receptores acoplados a proteína G?", "Amargo, dulce y umami."],
    ["¿Qué sabores actúan principalmente mediante canales iónicos?", "Salado y ácido."],
    ["¿Qué familia receptora detecta el sabor amargo?", "T2R."],
    ["¿Cuántos tipos de receptores amargos menciona el texto?", "Aproximadamente 30."],
    ["¿Qué enzima activa la proteína G en la vía amarga?", "Fosfolipasa C."],
    ["¿Qué segundo mensajero aumenta en la vía amarga?", "IP3."],
    ["¿Qué subunidades forman el receptor del sabor dulce?", "T1R2 y T1R3."],
    ["¿Qué subunidades forman el receptor umami?", "T1R1 y T1R3."],
    ["¿Qué aminoácido se asocia especialmente con umami?", "L-glutamato."],
    ["¿Qué ion entra directamente para producir el sabor salado?", "Na+."],
    ["¿Qué ion genera el sabor ácido?", "H+."],
    ["¿Qué efecto tiene H+ sobre canales de K+?", "Los bloquea y despolariza la célula."],
    ["¿Qué porcentaje aproximado de la población son superdegustadores?", "Alrededor del 25%."],
    ["¿Qué caracteriza a los superdegustadores?", "Muchas papilas, alta densidad de botones y gran sensibilidad a PTC/PROP."],
    ["¿Qué causa la hipogeusia en el síndrome de Riley-Day?", "Falta de desarrollo de papilas fungiformes y botones gustativos."],
  ]},
  { topic: "Dientes", subtopic: "Organización y denticiones", cards: [
    ["¿Cuántos dientes permanentes posee normalmente el adulto?", "32."],
    ["¿Cuántos dientes deciduales posee el niño?", "20."],
    ["¿Qué es la corona clínica?", "La porción del diente visible en la cavidad bucal."],
    ["¿Qué es la corona anatómica?", "Toda la porción cubierta por esmalte."],
    ["¿Qué tres tejidos mineralizados tiene el diente?", "Esmalte, dentina y cemento."],
    ["¿Cuál forma el núcleo blando central?", "La pulpa dental."],
    ["¿Qué reemplaza a los molares deciduales?", "Los premolares permanentes."],
    ["¿Los molares permanentes tienen precursores deciduales?", "No."],
    ["¿Cuántos dientes permanentes hay por cuadrante?", "Ocho."],
    ["¿Cuántos dientes deciduales hay por cuadrante?", "Cinco."],
    ["¿Qué sistema dental emplea dos dígitos?", "El sistema internacional."],
    ["¿Qué indica el primer dígito internacional?", "El cuadrante."],
    ["¿Qué indica el segundo dígito internacional?", "La posición desde la línea media."],
    ["¿Qué sistema numera los permanentes del 1 al 32?", "El sistema americano o universal."],
    ["¿Qué suma dan dientes permanentes opuestos en el sistema universal?", "33."],
  ]},
  { topic: "Dientes", subtopic: "Desarrollo dentario", cards: [
    ["¿De qué origen embrionario procede el órgano adamantino?", "Del epitelio ectodérmico bucal."],
    ["¿De qué origen proceden los odontoblastos?", "De células de la cresta neural del ectomesénquima."],
    ["¿Qué banda epitelial inicia el desarrollo dental?", "La lámina dental."],
    ["¿Cuáles son las tres etapas morfológicas tempranas del germen dental?", "Yema, casquete y campana."],
    ["¿Qué representa la etapa de yema?", "Un brote redondeado de epitelio hacia el mesénquima."],
    ["¿Qué caracteriza la etapa de casquete?", "La aparición de una concavidad en el órgano adamantino."],
    ["¿Qué cuatro capas tiene el órgano adamantino en campana?", "Epitelio externo, epitelio interno, estrato intermedio y retículo estrellado."],
    ["¿Qué origina el epitelio interno del esmalte?", "Los ameloblastos."],
    ["¿Qué origina la papila dental?", "Dentina y pulpa dental."],
    ["¿Qué origina el saco dental?", "Las estructuras del periodonto."],
    ["¿Qué tejido mineralizado se deposita primero?", "La dentina."],
    ["¿Sobre qué se deposita inicialmente la matriz del esmalte?", "Sobre la dentina recién formada."],
    ["¿Qué sucede con la lámina dental antes de la dentinogénesis y amelogénesis?", "Se degenera y separa el primordio del epitelio bucal."],
    ["¿Cómo cambia el foramen apical después de la erupción?", "Se estrecha."],
  ]},
  { topic: "Esmalte", subtopic: "Estructura del esmalte", cards: [
    ["¿Qué célula produce el esmalte?", "El ameloblasto."],
    ["¿Qué proceso forma el esmalte?", "La amelogénesis."],
    ["¿Cuál es el tejido más duro del cuerpo?", "El esmalte maduro."],
    ["¿Qué proporción aproximada del esmalte maduro es mineral?", "Cerca del 96%."],
    ["¿Qué mineral predomina en el esmalte?", "Hidroxiapatita cálcica."],
    ["¿Tiene células el esmalte maduro?", "No; es acelular."],
    ["¿Puede regenerarse el esmalte después de la erupción?", "No, porque desaparecen los ameloblastos."],
    ["¿Qué unidades estructurales paralelas forman el esmalte?", "Los bastones o prismas de esmalte."],
    ["¿Desde dónde hasta dónde se extiende un bastón?", "Desde la unión amelodentinaria hasta la superficie."],
    ["¿Qué forma tiene el bastón en corte transversal?", "De ojo de cerradura, con cabeza y cola."],
    ["¿Dónde son más largos los bastones?", "En el vértice de la corona, donde el esmalte es más grueso."],
    ["¿Qué registran las direcciones de los bastones?", "La trayectoria previa de los ameloblastos secretores."],
    ["¿Qué son las estrías de Retzius?", "Líneas incrementales del esmalte."],
    ["¿Qué torna al esmalte más resistente a la desmineralización ácida?", "La incorporación de fluoruro a la hidroxiapatita."],
  ]},
  { topic: "Esmalte", subtopic: "Amelogénesis", cards: [
    ["¿Cuáles son las dos etapas principales de la amelogénesis?", "Secreción de matriz y maduración."],
    ["¿Qué hacen los ameloblastos secretores?", "Producen matriz adamantina parcialmente mineralizada."],
    ["¿Qué prolongación apical posee el ameloblasto secretor?", "El proceso de Tomes."],
    ["¿Qué organelos abundan en el ameloblasto secretor?", "RER, Golgi y gránulos de secreción."],
    ["¿Qué mantiene la orientación de los ameloblastos al desplazarse?", "Complejos de unión apicales y basales."],
    ["¿Qué enzima del estrato intermedio participa en calcificación?", "Fosfatasa alcalina."],
    ["¿Qué hacen los ameloblastos de maduración?", "Retiran matriz orgánica y regulan el transporte de calcio y fosfato."],
    ["¿Qué cambio cíclico experimentan los ameloblastos de maduración?", "Modulación entre borde estriado y borde liso."],
    ["¿Qué porcentaje aproximado presenta borde estriado?", "70%."],
    ["¿Qué porcentaje aproximado presenta borde liso?", "30%."],
    ["¿Qué secreta el borde estriado?", "Iones bicarbonato."],
    ["¿Qué bomba contiene el borde estriado?", "Ca2+-ATPasa de membrana plasmática, PMCA."],
    ["¿Qué hacen los ameloblastos de borde liso?", "Secretan enzimas y reabsorben matriz orgánica degradada."],
    ["¿Qué reemplaza al estrato intermedio durante la maduración?", "Una capa papilar vascular reorganizada."],
    ["¿Qué función tienen las amelogeninas?", "Mantener el espacio entre bastones durante el desarrollo inicial."],
    ["¿Qué función se atribuye a las ameloblastinas?", "Guiar mineralización, elongación cristalina y unión entre bastones."],
    ["¿Qué sucede con las enamelinas durante la maduración?", "Sufren escisión proteolítica; fragmentos permanecen en el esmalte."],
    ["¿Qué proteína inicia la nucleación cerca de la unión amelodentinaria?", "La tuftelina."],
    ["¿Qué proteínas permanecen en el esmalte maduro?", "Enamelinas y tuftelinas."],
    ["¿Qué proteínas se eliminan durante la maduración?", "Amelogeninas y ameloblastinas."],
  ]},
  { topic: "Cemento y dentina", subtopic: "Cemento", cards: [
    ["¿Qué parte del diente cubre el cemento?", "La raíz, desde el cuello hasta el ápice."],
    ["¿Qué célula produce el cemento?", "El cementoblasto."],
    ["¿Cómo se llama la matriz no mineralizada del cemento?", "Cementoide."],
    ["¿En qué se convierte un cementoblasto atrapado?", "En cementocito."],
    ["¿Qué porcentaje aproximado del cemento es mineral?", "65%."],
    ["¿Es vascular el cemento?", "No; es avascular."],
    ["¿Cómo se distribuyen sus lagunas?", "Irregularmente."],
    ["¿Sus canalículos forman una red anastomosada?", "No."],
    ["¿Qué tejido mineralizado concentra más fluoruro?", "El cemento."],
    ["¿Qué fibras fijan el cemento al hueso alveolar?", "Fibras de Sharpey del ligamento periodontal."],
    ["¿Cómo están las fibras de Sharpey dentro del cemento?", "Mineralizadas."],
    ["¿Cómo están dentro del ligamento periodontal?", "No mineralizadas."],
    ["¿El cemento se remodela durante la ortodoncia?", "No; se remodela el hueso alveolar."],
  ]},
  { topic: "Cemento y dentina", subtopic: "Dentina", cards: [
    ["¿Qué tejido constituye la mayor parte del diente?", "La dentina."],
    ["¿Dónde se ubica la dentina?", "Debajo del esmalte y del cemento."],
    ["¿Qué proporción aproximada de la dentina es hidroxiapatita?", "70%."],
    ["¿Qué célula secreta dentina?", "El odontoblasto."],
    ["¿Dónde están los cuerpos de los odontoblastos?", "En la periferia de la pulpa dental."],
    ["¿Cómo se llaman los conductos que contienen prolongaciones odontoblásticas?", "Túbulos dentinarios."],
    ["¿Hasta dónde se extienden los túbulos dentinarios?", "Hasta la unión amelodentinaria o cementodentinaria."],
    ["¿Qué es la predentina?", "La matriz orgánica de dentina recién secretada y aún no mineralizada."],
    ["¿Cuál es la región dentinaria más mineralizada?", "La dentina peritubular."],
    ["¿Qué ocupa el espacio entre túbulos?", "La dentina intertubular."],
    ["¿Qué líneas finas reflejan el crecimiento rítmico de la dentina?", "Líneas incrementales de Von Ebner."],
    ["¿Cómo se llaman las líneas incrementales acentuadas?", "Líneas de Owen."],
    ["¿Qué línea registra el nacimiento?", "La línea neonatal."],
    ["¿Qué utilidad tienen las líneas dentinarias?", "Registrar eventos del desarrollo y servir en medicina forense."],
    ["¿Qué proteína dentinaria inicia mineralización y controla el cristal?", "Fosfoproteína de la dentina, DPP."],
    ["¿Qué otra proteína es exclusiva de la predentina?", "Sialoproteína de la dentina, DSP."],
    ["¿Puede producirse dentina durante toda la vida?", "Sí."],
    ["¿Cómo se llama la dentina más externa?", "Dentina del manto."],
    ["¿Qué células producen las fibras de Von Korff de la dentina del manto?", "Células subodontoblásticas."],
    ["¿Qué ocurre con el volumen de la cavidad pulpar con la edad?", "Disminuye por el depósito continuo de dentina."],
  ]},
  { topic: "Pulpa y periodonto", subtopic: "Pulpa dental", cards: [
    ["¿Qué tipo de tejido forma la pulpa dental?", "Tejido conjuntivo laxo de aspecto embrionario."],
    ["¿Qué contiene la pulpa?", "Odontoblastos, fibroblastos, vasos, nervios y células inmunitarias."],
    ["¿Qué reviste periféricamente la cavidad pulpar?", "La capa de odontoblastos."],
    ["¿Por dónde ingresan vasos y nervios a la pulpa?", "Por el foramen apical."],
    ["¿Qué tejido limita la cavidad pulpar?", "La dentina."],
    ["¿Qué forma adopta la cavidad pulpar?", "La forma general del diente."],
    ["¿Qué tipo de fibras nerviosas predominan en la pulpa?", "Fibras sensitivas para dolor y fibras autónomas vasomotoras."],
    ["¿Dónde forman redes los vasos y nervios pulpares?", "Debajo y dentro de la capa de odontoblastos."],
  ]},
  { topic: "Pulpa y periodonto", subtopic: "Periodonto y encía", cards: [
    ["¿Qué tejidos integran el periodonto?", "Cemento, ligamento periodontal, hueso alveolar y encía."],
    ["¿Qué tejido fija el diente al alvéolo?", "El ligamento periodontal."],
    ["¿Qué tipo de tejido es el ligamento periodontal?", "Tejido conjuntivo denso especializado."],
    ["¿Qué colágeno predomina en sus haces?", "Colágeno tipo I."],
    ["¿Qué célula mantiene las fibras periodontales?", "El fibroblasto."],
    ["¿Qué funciones cumple el ligamento periodontal?", "Adhesión, soporte, remodelación, propiocepción y erupción."],
    ["¿Qué permite cierto movimiento fisiológico del diente?", "La suspensión por fibras periodontales."],
    ["¿Qué sucede al hueso alveolar durante ortodoncia?", "Se resorbe en presión y se deposita en tensión."],
    ["¿Qué es la mucosa gingival?", "La porción de mucosa masticatoria que rodea el diente."],
    ["¿Qué es el epitelio de unión?", "El epitelio gingival adherido firmemente a la superficie dental."],
    ["¿Qué estructura forma el espacio entre diente y encía libre?", "El surco gingival."],
    ["¿Qué unión fija el epitelio de unión al diente?", "Hemidesmosomas y una lámina basal interna."],
  ]},
  { topic: "Glándulas salivales", subtopic: "Acinos y células mioepiteliales", cards: [
    ["¿Qué es una sialona?", "La unidad funcional formada por acino, conducto intercalado y conducto estriado."],
    ["¿Qué es el acino salival?", "La porción secretora de la sialona."],
    ["¿Qué tres tipos de unidades secretoras existen?", "Serosas, mucosas y mixtas."],
    ["¿Qué secretan las células serosas?", "Una secreción acuosa rica en proteínas y enzimas."],
    ["¿Cómo es el núcleo de una célula serosa?", "Redondo y situado hacia la base."],
    ["¿Por qué la base serosa es basófila?", "Por su abundante RER."],
    ["¿Qué secretan las células mucosas?", "Mucinas glucoproteicas."],
    ["¿Cómo es el núcleo de una célula mucosa?", "Aplanado contra la base."],
    ["¿Cómo se tiñe el citoplasma mucoso con H&E?", "Pálido o espumoso."],
    ["¿Qué son las semilunas serosas?", "Casquetes serosos en acinos mixtos vistos tras fijación convencional."],
    ["¿Son estructuras naturales las semilunas serosas?", "No; son artefactos de fijación."],
    ["¿Qué produce el artefacto de semiluna?", "La expansión del mucinógeno desplaza las células serosas."],
    ["¿Dónde se ubican las células mioepiteliales?", "Entre las células secretoras o ductales y la lámina basal."],
    ["¿Qué forma tienen alrededor de los acinos?", "Estrellada, como una cesta."],
    ["¿Qué función cumplen las células mioepiteliales?", "Se contraen y ayudan a expulsar la secreción."],
    ["¿Qué filamentos contienen?", "Actina y miosina."],
  ]},
  { topic: "Glándulas salivales", subtopic: "Conductos salivales", cards: [
    ["¿Cuáles son los tres segmentos del sistema de conductos?", "Intercalado, estriado y excretor."],
    ["¿Qué epitelio reviste el conducto intercalado?", "Cúbico simple."],
    ["¿Qué ion secreta el conducto intercalado?", "HCO3−."],
    ["¿Qué ion absorbe el conducto intercalado?", "Cl−."],
    ["¿En qué tipo de glándula están mejor desarrollados los intercalados?", "En glándulas serosas."],
    ["¿Qué epitelio reviste inicialmente el conducto estriado?", "Cúbico simple que se vuelve cilíndrico simple."],
    ["¿Qué produce las estrías basales?", "Pliegues basales con mitocondrias alargadas."],
    ["¿Qué ion reabsorbe el conducto estriado?", "Na+."],
    ["¿Qué iones secreta el conducto estriado?", "K+ y HCO3−."],
    ["¿Por qué la saliva se vuelve hipotónica?", "Se reabsorbe más Na+ que el K+ secretado."],
    ["¿Qué ocurre con la saliva cuando el flujo es muy rápido?", "Aumenta Na+ y disminuye K+ por menor modificación ductal."],
    ["¿Los conductos estriados son intra o interlobulillares?", "Intralobulillares."],
    ["¿Dónde discurren los conductos excretores?", "En tejido conjuntivo interlobulillar e interlobular."],
    ["¿Cómo cambia el epitelio del conducto excretor al aumentar su calibre?", "De cúbico simple a seudoestratificado o estratificado y finalmente plano estratificado."],
  ]},
  { topic: "Glándulas salivales", subtopic: "Glándulas salivales mayores", cards: [
    ["¿Cuál es la glándula salival mayor más grande?", "La parótida."],
    ["¿Qué tipo de acinos tiene la parótida?", "Solo serosos."],
    ["¿Qué rasgo histológico ayuda a reconocer la parótida?", "Abundante tejido adiposo entre acinos serosos."],
    ["¿Cómo son sus conductos intercalados?", "Largos y numerosos."],
    ["¿Qué nervio atraviesa la parótida?", "El nervio facial, NC VII."],
    ["¿Qué tipo de glándula es la submandibular?", "Mixta con predominio seroso."],
    ["¿Cómo son sus intercalados frente a la parótida?", "Menos abundantes."],
    ["¿Qué tipo de glándula es la sublingual?", "Mixta con predominio mucoso."],
    ["¿Cuál es la menor de las glándulas salivales mayores?", "La sublingual."],
    ["¿Son comunes los acinos serosos puros en la sublingual?", "No, son muy raros."],
    ["¿Cómo son sus conductos intercalados y estriados?", "Cortos, difíciles de ver y a veces ausentes."],
    ["¿Qué forma pueden tener sus unidades mucosas?", "Tubular más que acinar."],
    ["¿Qué glándula muestra más semilunas serosas?", "La sublingual en preparados convencionales."],
  ]},
  { topic: "Glándulas salivales", subtopic: "Saliva", cards: [
    ["¿Qué secreciones componen la saliva?", "Las de glándulas mayores y menores, con aportes menores del surco gingival y mucosa."],
    ["¿Cuánta saliva se produce aproximadamente al día?", "Alrededor de 1200 mL."],
    ["¿Cuáles son sus componentes generales?", "Agua, proteínas, glucoproteínas y electrólitos."],
    ["¿Qué ion está unas siete veces más concentrado que en sangre?", "K+."],
    ["¿Cómo se compara el Na+ salival con el sanguíneo?", "Es aproximadamente una décima parte."],
    ["¿Cómo se compara el bicarbonato salival con el sanguíneo?", "Es casi tres veces mayor."],
    ["¿Cuáles son las principales enzimas salivales?", "Amilasa alfa y lisozima."],
    ["¿Qué hace la amilasa alfa?", "Inicia la digestión de hidratos de carbono."],
    ["¿Qué hace la lisozima?", "Degrada ácido murámico de paredes bacterianas."],
    ["¿Qué función tiene el bicarbonato?", "Amortigua el contenido de la cavidad bucal."],
    ["¿Qué iones salivales favorecen mineralización y reparación del esmalte?", "Calcio y fosfato."],
    ["¿Qué es la película adquirida?", "Una cubierta proteica salival protectora sobre los dientes."],
    ["¿Dónde se sintetiza la IgA salival?", "En plasmocitos del tejido conjuntivo glandular."],
    ["¿Qué une los dos monómeros de IgA dimérica?", "La cadena J."],
    ["¿Qué receptor transporta IgA dimérica a través de la célula glandular?", "El receptor de inmunoglobulina polimérica, pIgR."],
    ["¿Qué forma el componente secretor de la sIgA?", "La porción extracelular escindida del pIgR."],
    ["¿Qué consecuencias dentales produce la xerostomía?", "Mayor riesgo de caries y deterioro de la mucosa."],
  ]},
  { topic: "Correlaciones clínicas", subtopic: "Clínica e identificación", cards: [
    ["¿Qué causa la caries dental?", "Desmineralización ácida del esmalte por bacterias que metabolizan restos alimentarios."],
    ["¿Qué tejido dental no puede repararse biológicamente?", "El esmalte."],
    ["¿Qué tejido dental continúa secretándose durante toda la vida?", "La dentina."],
    ["¿Qué tumor salival benigno es el más frecuente?", "Adenoma pleomorfo."],
    ["¿Qué porcentaje aproximado de tumores salivales representa?", "65%."],
    ["¿Qué porcentaje aproximado de tumores salivales son benignos?", "80%."],
    ["¿En qué glándula se originan la mayoría de tumores salivales?", "En la parótida."],
    ["¿Cuál es el sitio más frecuente de tumor de glándula salival menor?", "El paladar."],
    ["¿Qué células producen el estroma de aspecto conjuntivo del adenoma pleomorfo?", "Células mioepiteliales."],
    ["¿Qué complicación neurológica puede seguir a una parotidectomía?", "Disfunción del nervio facial."],
    ["¿Qué papila queratinizada sin botones gustativos se reconoce en lengua?", "La filiforme."],
    ["¿Qué papila grande rodeada por un surco tiene botones laterales?", "La caliciforme."],
    ["¿Qué glándula muestra acinos serosos y adipocitos?", "La parótida."],
    ["¿Qué glándula muestra predominio mucoso y semilunas?", "La sublingual."],
    ["¿Qué conducto se reconoce por estrías basales?", "El conducto estriado."],
    ["¿Qué tejido se reconoce por túbulos con prolongaciones odontoblásticas?", "La dentina."],
  ]},
]

const slug = (value: string) => value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")

const cap16CoreFlashcards: Flashcard[] = groups.flatMap(group =>
  group.cards.map(([front, back], index) => ({
    id: `histo-cap16-${slug(group.subtopic)}-${String(index + 1).padStart(4, "0")}`,
    subject: "Histología", book: "Ross", chapter: "Capítulo 16",
    topic: group.topic, subtopic: group.subtopic, front, back,
    tags: ["Capítulo 16", group.subtopic]
  }))
)

export const cap16Flashcards: Flashcard[] = [
  ...cap16CoreFlashcards,
  ...cap16ExtraFlashcards
]
