import type { Flashcard } from "./cards"

type Pair = readonly [string, string]
const details: { topic: string; subtopic: string; cards: readonly Pair[] }[] = [
  { topic: "Cavidad bucal", subtopic: "Mucosa bucal", cards: [
    ["¿Qué secreta el revestimiento digestivo en sitios específicos?", "Enzimas, ácido clorhídrico, mucina y anticuerpos."],
    ["¿Qué materiales reciclables absorbe la mucosa digestiva?", "Componentes biliares y colesterol."],
    ["¿Qué células de la mucosa bucal participan en defensa además del epitelio?", "Neutrófilos migratorios."],
    ["¿Qué defensinas expresa el epitelio bucal?", "Defensinas beta."],
    ["¿Qué defensinas expresan los neutrófilos bucales?", "Defensinas alfa."],
    ["¿Qué inmunoglobulina protege la superficie bucal?", "IgA secretora."],
    ["¿Qué situaciones favorecen infecciones bucales según el texto?", "Inmunodeficiencia y tratamiento antibiótico."],
    ["¿Qué células comparte el epitelio bucal con la epidermis?", "Queratinocitos, Langerhans, melanocitos y Merkel."],
    ["¿Qué contiene la lámina propia de la mucosa bucal?", "Vasos, nervios y terminaciones sensitivas."],
    ["¿Qué receptores encapsulados pueden hallarse en papilas de mucosa masticatoria?", "Corpúsculos de Meissner."],
    ["¿Qué une la submucosa de revestimiento al músculo subyacente?", "Bandas amplias y elásticas de colágeno."],
    ["¿Qué vasos de mayor calibre contiene la submucosa bucal?", "Vasos sanguíneos, linfáticos y nervios."],
    ["¿Qué cubre la mucosa de revestimiento en labios y mejillas?", "Músculo estriado."],
    ["¿Qué cubre en la mucosa alveolar?", "Hueso."],
    ["¿Qué cubre en el paladar blando?", "Músculo y glándulas."],
    ["¿Qué causa el color rojo del borde bermellón?", "Capilares muy cercanos bajo un epitelio delgado."],
    ["¿Por qué el borde bermellón es muy sensible?", "Por abundantes terminaciones nerviosas en papilas conjuntivas profundas."],
    ["¿Qué diferencia histológica ayuda a reconocer mucosa alveolar?", "Papilas numerosas y profundas."],
  ]},
  { topic: "Lengua", subtopic: "Organización lingual", cards: [
    ["¿Qué tejido puede encontrarse entre fascículos musculares linguales?", "Tejido adiposo."],
    ["¿Dónde están las amígdalas linguales respecto del surco terminal?", "Detrás del surco terminal."],
    ["¿Qué organización linfática presentan las amígdalas linguales?", "Tejido difuso y nódulos con centros germinativos."],
    ["¿Qué estructuras epiteliales se invaginan en las amígdalas linguales?", "Criptas."],
    ["¿Por qué puede ser difícil distinguir su epitelio?", "Por la intensa infiltración de linfocitos."],
    ["¿Qué glándulas pueden verse dentro de la amígdala lingual?", "Glándulas salivales linguales mucosas."],
    ["¿Qué nervios llevan sensibilidad general detrás del surco terminal?", "Glosofaríngeo IX y vago X."],
    ["¿Qué sistema inerva vasos y glándulas de la lengua?", "El sistema nervioso autónomo simpático y parasimpático."],
    ["¿Qué representan las células ganglionares dentro de la lengua?", "Neuronas parasimpáticas posganglionares para glándulas linguales."],
    ["¿Dónde están los somas simpáticos posganglionares para la lengua?", "En el ganglio cervical superior."],
  ]},
  { topic: "Lengua", subtopic: "Transducción gustativa", cards: [
    ["¿Qué significa que una sustancia sea sápida?", "Que posee sabor y estimula receptores gustativos."],
    ["¿Dónde se sitúan los receptores del gusto en la célula sensorial?", "En su superficie apical."],
    ["¿Cada célula gustativa expresa todas las clases de receptores?", "No; expresa selectivamente una clase."],
    ["¿Por qué amargo y dulce viajan por fibras diferentes aunque compartan cascada?", "Porque activan células receptoras distintas."],
    ["¿Qué abre la despolarización gustativa tras la entrada de Na+?", "Canales de Ca2+ activados por voltaje."],
    ["¿Qué provoca el aumento de Ca2+ en la célula gustativa?", "Liberación de neurotransmisor."],
    ["¿Qué canales específicos de H+ participan en el sabor ácido?", "PKD1L3 y PKD2L1."],
    ["¿Qué canales de Na+ participan en sabores ácido y salado?", "Canales sensibles a la amilorida."],
    ["¿Son iguales a los canales de Na+ voltaje-dependientes neuronales?", "No."],
    ["¿Qué alimentos menciona el texto como ricos en umami?", "Espárragos, tomates, quesos y carne."],
    ["¿Qué aditivo estimula intensamente receptores umami?", "Glutamato monosódico."],
    ["¿Qué región responde más a dulce?", "La punta de la lengua."],
    ["¿Qué región responde más a salado?", "Los lados próximos a la punta."],
    ["¿Qué región responde más a ácido?", "La región posterolateral."],
    ["¿Qué papilas responden especialmente a amargo y umami?", "Las caliciformes."],
    ["¿Por qué el mapa clásico del gusto es una simplificación?", "Toda la lengua puede detectar todas las cualidades."],
    ["¿Qué proporción aproximada de la población es no degustadora?", "Alrededor del 25%."],
    ["¿Cómo responden los no degustadores a PTC/PROP?", "No perciben su sabor amargo."],
    ["¿Qué gen está mutado en disautonomía familiar tipo I?", "DYS o IKBKAP, en el cromosoma 9."],
    ["¿Qué patrón hereditario tiene el síndrome de Riley-Day?", "Autosómico recesivo."],
  ]},
  { topic: "Dientes", subtopic: "Organización y denticiones", cards: [
    ["¿Cuántos dientes deciduales hay en cada maxilar?", "Diez."],
    ["¿Cuál suele ser el primer diente decidual en erupcionar?", "El incisivo central mandibular."],
    ["¿A qué edad suele erupcionar el primer diente decidual?", "Alrededor de los 6 meses."],
    ["¿Cuándo erupciona aproximadamente el incisivo lateral decidual?", "Alrededor de los 8 meses."],
    ["¿Cuándo erupciona aproximadamente el canino decidual?", "Hacia los 15 meses."],
    ["¿Cuándo erupciona el primer molar decidual?", "Entre 10 y 19 meses."],
    ["¿Cuándo erupciona el segundo molar decidual?", "Entre 20 y 31 meses."],
    ["¿Entre qué edades se reemplaza la dentición decidual?", "Aproximadamente entre 6 y 12-13 años."],
    ["¿Cuándo emerge el incisivo central permanente?", "Entre 7 y 8 años."],
    ["¿Cuándo emerge el incisivo lateral permanente?", "Entre 8 y 9 años."],
    ["¿Cuándo emerge el canino permanente?", "Entre 10 y 12 años."],
    ["¿Cuándo emergen los premolares?", "Entre 10 y 12 años."],
    ["¿Cuándo suele aparecer el primer molar permanente?", "Alrededor de los 6 años."],
    ["¿Cuándo aparece el segundo molar permanente?", "En los primeros años de la adolescencia."],
    ["¿Cuándo aparece el tercer molar?", "En adolescencia tardía o después de los 20 años."],
    ["¿Cuántas raíces suelen tener incisivos, caninos y premolares?", "Una."],
    ["¿Qué premolar suele tener dos raíces?", "El primer premolar maxilar."],
    ["¿Cuántas raíces suelen tener los molares mandibulares?", "Dos."],
    ["¿Cuántas raíces suelen tener los molares maxilares?", "Tres."],
    ["¿Qué sistema de notación dental es el más usado mundialmente?", "El sistema de Palmer."],
    ["¿Qué usa Palmer para dientes deciduales?", "Letras mayúsculas."],
    ["¿Qué usa Palmer para dientes permanentes?", "Números arábigos."],
    ["¿Qué números designan cuadrantes permanentes en el sistema internacional?", "1 a 4."],
    ["¿Qué números designan cuadrantes deciduales en el sistema internacional?", "5 a 8."],
    ["¿Qué letras usa el sistema universal para deciduales?", "A hasta T."],
  ]},
  { topic: "Esmalte", subtopic: "Estructura del esmalte", cards: [
    ["¿Cuál es el intervalo mineral del esmalte según el texto?", "96-98% de hidroxiapatita."],
    ["¿Cuál es el espesor máximo aproximado del esmalte en una cúspide?", "2.5 mm."],
    ["¿Dónde termina la capa de esmalte?", "En el cuello, en la unión cemento-esmalte."],
    ["¿Qué dimensiones aproximadas tiene un bastón de esmalte?", "4 µm de ancho y 8 µm de alto."],
    ["¿Hacia dónde se orienta la cabeza del bastón?", "Hacia la superficie."],
    ["¿Hacia dónde se orienta la cola del bastón?", "Hacia la profundidad y la raíz."],
    ["¿Cómo se orientan los cristales en la cabeza del bastón?", "Paralelos a su eje longitudinal."],
    ["¿Cómo se orientan los cristales en la cola?", "Más oblicuamente."],
    ["¿Qué llena los límites entre bastones?", "Cristales de esmalte."],
    ["¿Qué reflejan las estrías de Retzius?", "El crecimiento rítmico del esmalte."],
    ["¿Dónde aparece una línea neonatal de hipomineralización en esmalte?", "En dientes deciduales."],
    ["¿Qué cambio registra la línea neonatal?", "La transición nutricional prenatal-posnatal."],
    ["¿Por qué el esmalte erupcionado no es totalmente estático?", "La saliva influye en su mantenimiento y remineralización."],
    ["¿Qué componentes salivales mantienen el esmalte?", "Minerales, enzimas y anticuerpos."],
    ["¿Qué ocurre con la matriz orgánica al madurar el esmalte?", "La mayor parte se elimina."],
  ]},
  { topic: "Esmalte", subtopic: "Amelogénesis", cards: [
    ["¿Qué superficie del órgano adamantino forma el epitelio externo?", "La superficie convexa."],
    ["¿Qué superficie forma el epitelio interno?", "La superficie cóncava."],
    ["¿Dónde se ubica el estrato intermedio?", "Inmediatamente por dentro del epitelio interno."],
    ["¿Qué aspecto tienen las células del retículo estrellado?", "Estrellado y ampliamente separado."],
    ["¿Qué forma adoptan los preodontoblastos junto al epitelio interno?", "Cilíndrica, con aspecto epitelial."],
    ["¿Qué células colaboran con ameloblastos en producción de esmalte?", "Las del estrato intermedio."],
    ["¿Qué aparato sintetiza la matriz proteica adamantina?", "RER, aparato de Golgi y gránulos de secreción."],
    ["¿Hasta cuándo secretan matriz los ameloblastos secretores?", "Hasta alcanzar el espesor definitivo del esmalte."],
    ["¿Dónde está el proceso de Tomes?", "En el polo apical del ameloblasto secretor."],
    ["¿Qué causa eosinofilia en la base del ameloblasto secretor?", "Mitocondrias y filamentos de actina de la red terminal proximal."],
    ["¿Dónde se encuentra el núcleo del ameloblasto secretor?", "Junto a las mitocondrias, hacia la región basal."],
    ["¿Qué mueve al ameloblasto sobre el esmalte en desarrollo?", "Filamentos de actina unidos a complejos de unión."],
    ["¿Qué separa inicialmente al órgano adamantino de vasos contiguos?", "Una lámina basal."],
    ["¿Qué significa modulación ameloblástica?", "Alternancia cíclica entre borde estriado y liso."],
    ["¿Qué células colapsan para formar la capa papilar?", "Estrato intermedio, retículo estrellado y epitelio externo."],
    ["¿Qué invade la capa papilar reorganizada?", "Vasos sanguíneos."],
    ["¿Por qué abundan mitocondrias en ameloblastos maduros y células papilares?", "Porque funcionan como epitelio de transporte activo."],
    ["¿Durante qué etapas se producen ameloblastinas?", "Desde secreción inicial hasta maduración final."],
    ["¿Dónde se retienen fragmentos de enamelina?", "En la superficie de cristales del esmalte maduro."],
    ["¿Con qué estructura se asocian las tuftelinas?", "Penachos adamantinos hipomineralizados."],
    ["¿Cuándo degeneran los ameloblastos?", "Al completarse el esmalte, cerca de la erupción."],
  ]},
  { topic: "Cemento y dentina", subtopic: "Dentina", cards: [
    ["¿Qué organelos muestran la actividad secretora del odontoblasto?", "RER abundante y aparato de Golgi grande."],
    ["¿Qué separan los complejos de unión entre odontoblastos?", "El compartimento dentinario de la cámara pulpar."],
    ["¿Por qué retrocede la capa odontoblástica?", "Porque aumenta el espesor de dentina depositada."],
    ["¿Cómo crecen los túbulos dentinarios?", "Se alargan junto con las prolongaciones odontoblásticas."],
    ["¿Qué sustancia de 45 kDa es rica en aspartato y fosfoserina?", "DPP."],
    ["¿Qué fija la DPP en gran cantidad?", "Calcio."],
    ["¿Qué controla la DPP además del inicio de mineralización?", "El tamaño y la forma del mineral."],
    ["¿Qué tipo de molécula es la DSP?", "Un proteoglucano de aproximadamente 100 kDa."],
    ["¿Qué son los cuerpos en ábaco del odontoblasto?", "Precursores de gránulos de secreción formados en el Golgi."],
    ["¿Qué células forman inicialmente la dentina del manto?", "Células subodontoblásticas."],
    ["¿De qué están hechas las fibras de Von Korff?", "Pequeños haces de colágeno."],
    ["¿De qué células se diferencian los odontoblastos?", "Células periféricas de la papila dental."],
    ["¿Hacia qué polo secretan predentina los odontoblastos?", "Hacia el polo apical, lejos de la papila."],
    ["¿Qué sigue a los odontoblastos durante dentinogénesis?", "Una ola de mineralización."],
    ["¿Qué fibrillas son más finas: las de predentina o las maduras?", "Las de la predentina."],
    ["¿Qué estímulos pueden transmitir las prolongaciones odontoblásticas?", "Estímulos desde la superficie dental hacia nervios pulpares."],
    ["¿Dónde penetran algunas fibras nerviosas pulpares?", "En las porciones proximales de los túbulos dentinarios."],
    ["¿Qué dientes poseen cuernos pulpares destacados?", "Los dientes con más de una cúspide."],
  ]},
  { topic: "Pulpa y periodonto", subtopic: "Periodonto y encía", cards: [
    ["¿Qué forma la pared del alvéolo?", "Una capa delgada de hueso compacto alveolar propiamente dicho."],
    ["¿A qué se fija el periodonto en el lado óseo?", "Al hueso alveolar propiamente dicho."],
    ["¿Qué dos procesos se observan normalmente en la superficie alveolar?", "Resorción y depósito óseo."],
    ["¿Qué enfermedad destruye con frecuencia el hueso alveolar?", "La enfermedad periodontal."],
    ["¿Qué puede ocurrir al hueso si falta oclusión funcional?", "Puede destruirse o reabsorberse."],
    ["¿Qué otro nombre recibe el ligamento periodontal?", "Membrana periodóntica."],
    ["¿Qué terminaciones sensitivas abundan en el periodonto?", "Terminaciones propioceptivas y nociceptivas."],
    ["¿Qué células pueden diferenciarse para remodelar hueso y cemento?", "Células progenitoras del ligamento periodontal."],
    ["¿Qué son las PDLSC?", "Células madre multipotenciales del ligamento periodontal."],
    ["¿De qué dientes pueden obtenerse PDLSC humanas?", "De dientes permanentes o deciduales sanos."],
    ["¿Qué tejidos podrían regenerar las PDLSC?", "Hueso alveolar, encía, ligamento y cemento."],
    ["¿Qué porción gingival no está adherida directamente al diente?", "La encía libre."],
    ["¿Cómo se llama el borde coronal de la encía libre?", "Margen gingival."],
    ["¿Qué tapiza la pared externa del surco gingival?", "Epitelio del surco."],
    ["¿Qué epitelio forma el sello en el fondo del surco?", "Epitelio de unión."],
    ["¿Qué células inflamatorias atraviesan normalmente el epitelio de unión?", "Neutrófilos."],
  ]},
  { topic: "Glándulas salivales", subtopic: "Acinos y células mioepiteliales", cards: [
    ["¿Qué forma general tienen los acinos serosos?", "Esférica."],
    ["¿Qué forma general tienen los acinos mucosos?", "Tubular."],
    ["¿Cómo se orienta una célula serosa?", "Base amplia sobre lámina basal y ápice estrecho hacia la luz."],
    ["¿Dónde se almacenan los gránulos de cimógeno serosos?", "En el citoplasma apical."],
    ["¿Cómo se tiñe la región apical serosa con H&E?", "Eosinófila por los gránulos proteicos."],
    ["¿Qué pliegues puede presentar la base de la célula serosa?", "Pliegues basales y basolaterales interdigitados."],
    ["¿Qué mantiene unidas a células serosas cerca del ápice?", "Complejos de unión."],
    ["¿Qué actividad cíclica presentan las células mucosas?", "Síntesis, almacenamiento y descarga de mucinógeno."],
    ["¿Qué estímulos desencadenan descarga mucosa?", "Estimulación hormonal y nerviosa."],
    ["¿Por qué la región apical mucosa aparece vacía con H&E?", "El mucinógeno se pierde durante el procesamiento."],
    ["¿Dónde se concentran RER y mitocondrias en la célula mucosa?", "En la porción basal."],
    ["¿Qué ocurre en el Golgi de la célula mucosa?", "Se agregan carbohidratos a proteínas para formar mucina."],
    ["¿Cómo se ven las células mucosas con congelación rápida?", "Redondas, separadas y con gránulos bien conservados."],
    ["¿Qué células rodean juntas la luz en un acino mixto bien preservado?", "Células mucosas y serosas."],
    ["¿Dónde más se ubican células mioepiteliales además de los acinos?", "Bajo la porción proximal del sistema de conductos."],
    ["¿Cómo puede verse el núcleo mioepitelial con H&E?", "Como una pequeña silueta redonda junto a la membrana basal."],
    ["¿Qué marcador contráctil disminuye en Sjögren?", "Actina alfa de músculo liso, α-SMA."],
    ["¿Qué glándulas afecta principalmente el síndrome de Sjögren?", "Salivales y lagrimales."],
    ["¿Qué infiltrado caracteriza a Sjögren?", "Linfocitos, macrófagos y plasmocitos."],
    ["¿Qué reemplaza acinos normales en Sjögren avanzado?", "Linfocitos."],
  ]},
  { topic: "Glándulas salivales", subtopic: "Conductos salivales", cards: [
    ["¿Qué glándulas carecen típicamente de conductos estriados?", "Las glándulas mucosas."],
    ["¿Por qué los conductos intercalados mucosos son difíciles de ver?", "Son muy cortos y poco desarrollados."],
    ["¿Qué actividad enzimática poseen los conductos intercalados?", "Carbonato-deshidratasa."],
    ["¿Dónde suele estar el núcleo del conducto estriado?", "En posición central."],
    ["¿Qué especialización lateral tienen sus células?", "Pliegues basolaterales entrelazados."],
    ["¿Cómo se compara el diámetro del estriado con el acino?", "Con frecuencia es mayor."],
    ["¿Qué acompaña al estriado en el poco tejido conjuntivo circundante?", "Vasos y nervios paralelos."],
    ["¿Cuál es el epitelio de un conducto excretor pequeño?", "Cúbico simple."],
    ["¿Qué epitelio aparece después en conductos excretores mayores?", "Cilíndrico seudoestratificado o cúbico estratificado."],
    ["¿Qué epitelio puede encontrarse cerca de la desembocadura bucal?", "Plano estratificado."],
    ["¿Qué conductos recorren tejido conjuntivo facial y cervical?", "Stensen y Wharton, respectivamente."],
  ]},
  { topic: "Glándulas salivales", subtopic: "Glándulas salivales mayores", cards: [
    ["¿Dónde se localiza la parótida?", "Debajo y delante del oído."],
    ["¿Cómo son sus conductos estriados?", "Grandes y muy visibles."],
    ["¿Qué enfermedad vírica afecta clásicamente la parótida?", "Paperas."],
    ["¿Qué nervio puede dañarse en paperas o cirugía parotídea?", "El facial, NC VII."],
    ["¿Dónde se localiza la submandibular?", "Debajo de cada lado del piso bucal, cerca de la mandíbula."],
    ["¿Dónde está su papila de desembocadura?", "Lateral al frenillo lingual."],
    ["¿Qué unidades aparecen entre los acinos serosos submandibulares?", "Acinos mucosos con semilunas serosas."],
    ["¿Dónde está la sublingual respecto de la submandibular?", "Anterior a ella, en el piso bucal."],
    ["¿Cómo drenan los múltiples conductos sublinguales?", "A Wharton o directamente al piso bucal."],
    ["¿Qué conductos se ven con mayor frecuencia en cortes de sublingual?", "Conductos interlobulillares."],
  ]},
  { topic: "Glándulas salivales", subtopic: "Saliva", cards: [
    ["¿Cuánto puede superar el volumen salival a otras secreciones por peso glandular?", "Hasta 40 veces."],
    ["¿Qué sensación puede indicar la falta de saliva?", "Sed."],
    ["¿Cómo ayuda la saliva a la deglución?", "Humedece los alimentos secos."],
    ["¿Qué medio aporta para estimular botones gustativos?", "Un medio acuoso para sustancias disueltas y suspendidas."],
    ["¿Hasta dónde continúa actuando la amilasa salival?", "En esófago y estómago."],
    ["¿Qué bacteria menciona el texto como sensible a lisozima?", "Estafilococos."],
    ["¿Qué concentración relativa de K+ tiene la saliva frente a sangre?", "Aproximadamente siete veces mayor."],
    ["¿Qué otros iones contiene en cantidad importante?", "Calcio, fosfato, cloruro y tiocianato."],
    ["¿Qué metabolito nitrogenado contiene la saliva?", "Urea."],
    ["¿Qué efecto tienen anticuerpos y agentes antibacterianos sobre caries?", "Retrasan la acción bacteriana."],
    ["¿Qué fármacos pueden reducir mucho la secreción salival?", "Anticolinérgicos."],
    ["¿Qué forma de IgA libera el plasmocito al conjuntivo?", "IgA dimérica y monomérica."],
    ["¿En qué membrana se inserta el pIgR?", "En la membrana plasmática basal de la célula glandular."],
    ["¿Por qué mecanismo entra el complejo pIgR–dIgA?", "Endocitosis mediada por receptor."],
    ["¿En qué polo se escinde el pIgR?", "En la membrana apical."],
  ]},
  { topic: "Correlaciones clínicas", subtopic: "Clínica e identificación", cards: [
    ["¿Qué bacteria se asocia principalmente con inicio de caries?", "Streptococcus mutans."],
    ["¿Qué bacterias se asocian con progresión activa de caries?", "Lactobacilos."],
    ["¿Cómo se llaman las masas bacterianas sobre el diente?", "Placa dentobacteriana."],
    ["¿Qué carbohidrato frecuente favorece colonias acidogénicas?", "Sacarosa."],
    ["¿Qué concentración de flúor en agua considera óptima el texto?", "0.5-1.0 ppm."],
    ["¿Qué ion sustituye el fluoruro en hidroxiapatita?", "El ion hidroxilo."],
    ["¿Qué tres efectos anticaries tiene el flúor?", "Resistencia ácida, acción antimicrobiana y remineralización."],
    ["¿Qué tejidos calcificados puede destruir la caries?", "Esmalte, dentina y cemento."],
    ["¿Cómo se trata una lesión cavitada?", "Excavación y reemplazo con material restaurador."],
    ["¿Qué materiales restauradores menciona el texto?", "Amalgama, resina compuesta y cemento de ionómero vítreo."],
    ["¿Por dónde avanzan bacterias al quedar expuesta la dentina?", "Por los túbulos dentinarios."],
    ["¿Qué ocurre al alcanzar la pulpa?", "Se produce una respuesta inflamatoria y puede requerirse tratamiento de conducto."],
    ["¿Dónde ocurren la mayoría de los tumores salivales?", "En glándulas salivales mayores."],
    ["¿Cómo suele presentarse un tumor salival benigno?", "Como tumefacción indolora."],
    ["¿Qué síntomas sugieren compromiso nervioso parotídeo?", "Debilidad facial, parálisis o dolor persistente."],
    ["¿Qué tratamiento se usa con frecuencia para tumores salivales?", "Extirpación quirúrgica."],
    ["¿Qué tratamiento adicional se usa si el tumor es maligno?", "Radioterapia posoperatoria."],
    ["¿Qué síndrome puede aparecer tras cirugía parotídea?", "Síndrome de Frey o auriculotemporal."],
  ]},
]

const slug = (value: string) => value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")

export const cap16ExtraFlashcards: Flashcard[] = details.flatMap(group =>
  group.cards.map(([front, back], index) => ({
    id: `histo-cap16-${slug(group.subtopic)}-extra-${String(index + 1).padStart(4, "0")}`,
    subject: "Histología", book: "Ross", chapter: "Capítulo 16",
    topic: group.topic, subtopic: group.subtopic, front, back,
    tags: ["Capítulo 16", group.subtopic]
  }))
)
