import type { Flashcard } from "./cards"

type Group = { topic: string; cards: readonly (readonly [string, string])[] }

// Banco del capítulo 21 de Ross, agrupado por órgano para el menú de estudio.
const groups: readonly Group[] = [
  { topic: "Fundamentos endocrinos", cards: [
    ["¿Qué rasgo anatómico distingue a una glándula endocrina de una exocrina?", "La endocrina carece de conductos excretores y libera sus productos hacia el intersticio y los vasos."],
    ["¿Qué distingue el control endocrino, paracrino y autocrino?", "Endocrino: acción a distancia por la circulación; paracrino: acción sobre células vecinas; autocrino: acción sobre la misma célula que secreta la señal."],
    ["¿Qué clase química de hormonas deriva del colesterol?", "Los esteroides."],
    ["¿Dónde se localizan en general los receptores de hormonas peptídicas y catecolaminas?", "En la superficie celular."],
    ["¿Dónde actúan principalmente los receptores de hormonas esteroideas y tiroideas?", "Dentro de la célula, en citoplasma o núcleo, para regular la expresión génica."],
    ["¿Qué diferencia la retroalimentación negativa de la positiva?", "La negativa inhibe el estímulo original; la positiva lo refuerza."],
  ] },
  { topic: "Hipófisis e hipotálamo", cards: [
    ["¿Qué origen embrionario tiene la adenohipófisis?", "El ectodermo del techo de la bucofaringe, que forma la bolsa de Rathke."],
    ["¿Qué origen embrionario tiene la neurohipófisis?", "El neuroectodermo del piso del diencéfalo."],
    ["¿Cuáles son las tres porciones de la adenohipófisis?", "Porción distal, porción intermedia y porción tuberal."],
    ["¿Cuáles son las dos porciones de la neurohipófisis?", "Porción nerviosa e infundíbulo."],
    ["¿Qué arterias irrigan principalmente la eminencia media y la porción tuberal?", "Las arterias hipofisarias superiores."],
    ["¿Qué arterias irrigan principalmente la porción nerviosa?", "Las arterias hipofisarias inferiores."],
    ["¿Cómo llegan las hormonas reguladoras hipotalámicas a la porción distal?", "Se liberan al plexo capilar primario de la eminencia media y viajan por las venas porta hipofisarias al plexo secundario de la porción distal."],
    ["¿Qué característica de la irrigación explica que la adenohipófisis reciba directamente las señales del hipotálamo?", "La mayor parte de la porción distal no tiene irrigación arterial directa; recibe sangre del sistema porta hipotalamohipofisario."],
    ["¿Cómo se disponen las células endocrinas de la porción distal?", "En cordones y nidos separados por capilares sinusoidales fenestrados."],
    ["¿Qué cuatro hormonas adenohipofisarias son tróficas para otras glándulas endocrinas?", "ACTH, TSH, FSH y LH."],
    ["¿Qué dos hormonas adenohipofisarias actúan principalmente sobre tejidos no endocrinos?", "GH y prolactina."],
    ["¿Qué células de la porción distal son acidófilas y qué secretan?", "Somatótropas → GH; lactótropas → prolactina."],
    ["¿Qué células de la porción distal son basófilas y qué secretan?", "Corticótropas → ACTH; gonadótropas → FSH y LH; tirótropas → TSH."],
    ["¿Qué precursor producen las corticótropas?", "Proopiomelanocortina (POMC), que se procesa para formar ACTH y otros péptidos."],
    ["¿Qué regula la secreción de GH por las somatótropas?", "GHRH y grelina la estimulan; somatostatina la inhibe."],
    ["¿Qué hormona hipotalámica mantiene inhibida de forma tónica la secreción de prolactina?", "Dopamina."],
    ["¿Qué hormona hipotalámica estimula TSH y también puede estimular prolactina?", "TRH."],
    ["¿Qué hormona hipotalámica estimula la secreción de ACTH?", "CRH."],
    ["¿Qué hormona hipotalámica estimula FSH y LH?", "GnRH."],
    ["¿Qué hormona hipotalámica inhibe GH y TSH?", "Somatostatina."],
    ["¿Cuál es la función principal de GH en el crecimiento corporal descrita por Ross?", "Estimula la producción de IGF-1 en hígado y otros tejidos, favoreciendo el crecimiento."],
    ["¿Qué células adenohipofisarias aumentan en tamaño y número durante embarazo y lactancia?", "Las lactótropas."],
    ["¿Qué identifica histológicamente a la porción intermedia humana?", "Folículos o quistes con coloide, restos de la luz de la bolsa de Rathke."],
    ["¿Qué caracteriza a las células foliculoestrelladas de la adenohipófisis?", "No secretan hormonas; forman una red de soporte y señalización mediante uniones comunicantes."],
    ["¿Qué porción adenohipofisaria forma una vaina alrededor del infundíbulo?", "La porción tuberal."],
    ["¿Dónde se sintetizan la ADH y la oxitocina que se liberan por la neurohipófisis?", "En neuronas de los núcleos supraóptico y paraventricular del hipotálamo."],
    ["¿Qué hace realmente la porción nerviosa de la hipófisis con la ADH y la oxitocina?", "Las almacena y libera; no las sintetiza."],
    ["¿Qué son los cuerpos de Herring?", "Dilataciones de axones neurosecretores de la neurohipófisis que acumulan gránulos con ADH u oxitocina."],
    ["¿Qué célula glial característica sostiene los axones de la neurohipófisis?", "El pituicito."],
    ["¿Cuál es el efecto renal principal de la ADH?", "Aumenta la permeabilidad al agua y su reabsorción en los segmentos distales y conductos colectores."],
    ["¿Qué receptor renal media el efecto antidiurético de la ADH?", "El receptor V2 basolateral."],
    ["¿Qué dos estímulos principales aumentan la liberación de ADH?", "Aumento de la osmolalidad plasmática y disminución del volumen sanguíneo."],
    ["¿Qué dos tipos de células/tejidos contrae la oxitocina en sus funciones principales?", "Músculo liso uterino y células mioepiteliales mamarias."],
    ["¿Qué estímulo inicia el reflejo de eyección láctea mediado por oxitocina?", "La succión del pezón."],
    ["¿Qué diferencia la diabetes insípida central de la nefrogénica?", "En la central falta ADH; en la nefrogénica el riñón no responde adecuadamente a la ADH."],
    ["¿Por qué el SIADH causa hiponatremia?", "El exceso de ADH retiene agua y diluye el sodio sérico."],
    ["¿En qué dos niveles actúan las hormonas de un órgano diana para retroalimentar el eje endocrino?", "En la adenohipófisis y en el hipotálamo."],
  ] },
  { topic: "Glándula pineal", cards: [
    ["¿Qué hormona secretan principalmente los pinealocitos?", "Melatonina."],
    ["¿Cómo cambia la secreción de melatonina con la luz?", "Aumenta en oscuridad y se inhibe con la luz."],
    ["¿Qué células gliales acompañan a los pinealocitos?", "Las células intersticiales, parecidas a astrocitos."],
    ["¿Qué son los cuerpos arenáceos de la pineal?", "Calcificaciones o «arenilla cerebral» que aumentan con la edad."],
    ["¿Qué función principal tiene la melatonina en el capítulo?", "Participa en la regulación de los ritmos circadianos."],
  ] },
  { topic: "Glándula tiroides", cards: [
    ["¿Cuál es la unidad estructural y funcional de la tiroides?", "El folículo tiroideo."],
    ["¿Qué reviste un folículo tiroideo normal?", "Una sola capa de epitelio folicular, por lo general cúbico simple o cilíndrico bajo."],
    ["¿Qué célula tiroidea produce T3 y T4?", "La célula folicular."],
    ["¿Qué célula tiroidea produce calcitonina?", "La célula parafolicular o célula C."],
    ["¿Por qué una célula C no participa directamente en el procesamiento del coloide?", "Está en la periferia del epitelio folicular, dentro de la lámina basal, pero no contacta la luz folicular."],
    ["¿De qué estructura embrionaria derivan las células C?", "Del cuerpo ultimobranquial asociado con la cuarta bolsa faríngea."],
    ["¿Cuál es el principal componente del coloide tiroideo?", "Tiroglobulina."],
    ["¿La tiroglobulina del coloide es una hormona activa?", "No; es una forma extracelular de almacenamiento y precursor de T3 y T4."],
    ["¿Qué hace singular a la tiroides entre las glándulas endocrinas?", "Almacena grandes cantidades de precursor hormonal fuera de las células, en el coloide folicular."],
    ["¿Dónde se sintetiza y hacia dónde se secreta la tiroglobulina?", "Se sintetiza en las células foliculares y se secreta por su polo apical a la luz folicular."],
    ["¿Por qué membrana entra el yoduro sanguíneo a la célula folicular y mediante qué transportador?", "Por la membrana basolateral mediante el cotransportador sodio/yoduro (NIS)."],
    ["¿Qué transportador lleva el yoduro desde la célula folicular hacia el coloide?", "Pendrina, en la membrana apical."],
    ["¿Qué enzima oxida el yoduro y cataliza la yodación de la tiroglobulina?", "Peroxidasa tiroidea (TPO)."],
    ["¿Qué producen, respectivamente, la yodación de un residuo de tirosina con uno o dos átomos de yodo?", "MIT y DIT."],
    ["¿Qué combinación de residuos yodados produce T3?", "MIT + DIT."],
    ["¿Qué combinación de residuos yodados produce T4?", "DIT + DIT."],
    ["¿Qué efecto tiene TSH sobre la recuperación del coloide?", "Estimula la endocitosis de tiroglobulina por las células foliculares."],
    ["¿Qué vía de reabsorción del coloide libera principalmente T3 y T4 de la tiroglobulina?", "La vía lisosómica, mediante proteólisis de la tiroglobulina endocitada."],
    ["¿Qué hace la vía transepitelial de megalina con la tiroglobulina?", "La transporta intacta hacia el lado basolateral y evita su degradación lisosómica."],
    ["¿Cuál es la hormona que la tiroides secreta en mayor cantidad: T3 o T4?", "T4."],
    ["¿Cuál es la hormona tiroidea más activa biológicamente: T3 o T4?", "T3."],
    ["¿Qué le ocurre a parte de la T4 en los tejidos periféricos?", "Se desyoda y se convierte en T3."],
    ["¿Qué proteínas transportan la mayor parte de T3 y T4 en sangre?", "Principalmente globulina fijadora de tiroxina (TBG) y transtiretina; también albúmina."],
    ["¿Qué hormona hipofisaria estimula a las células foliculares tiroideas?", "TSH, secretada por las tirótropas de la adenohipófisis."],
    ["¿Qué eje explica el control principal de la síntesis de T3 y T4?", "TRH hipotalámica → TSH adenohipofisaria → células foliculares → T3/T4; T3/T4 retroinhiben hipotálamo e hipófisis."],
    ["¿Cómo suele verse un folículo tiroideo intensamente estimulado?", "Epitelio folicular más alto y coloide con zonas de reabsorción en el borde apical."],
    ["¿Cuál es la acción de la calcitonina sobre la calcemia descrita por Ross?", "Tiende a disminuirla al inhibir la resorción ósea; su papel fisiológico en humanos no está bien definido."],
    ["¿Qué efecto tiene una carencia de hormonas tiroideas durante el desarrollo fetal?", "Puede causar alteraciones irreversibles del desarrollo del SNC y retraso del crecimiento."],
  ] },
  { topic: "Glándulas paratiroides", cards: [
    ["¿De qué bolsas faríngeas derivan las paratiroides inferiores y superiores?", "Inferiores de la tercera; superiores de la cuarta."],
    ["¿Qué célula paratiroidea secreta PTH?", "La célula principal."],
    ["¿Qué rasgo citológico destaca en la célula oxífila paratiroidea?", "Citoplasma muy acidófilo por abundancia de mitocondrias."],
    ["¿Qué cambio de calcemia estimula la secreción de PTH?", "La disminución del calcio sérico."],
    ["¿Qué efecto neto tiene PTH sobre calcio y fosfato séricos?", "Aumenta el calcio y disminuye el fosfato."],
    ["¿Por qué la PTH no activa directamente a los osteoclastos?", "Los osteoclastos no poseen receptor para PTH; la señal les llega a través de células osteoblásticas/osteocitos y el sistema RANKL–RANK."],
    ["¿Qué efecto óseo tiene la exposición continua a PTH?", "Favorece la formación y actividad de osteoclastos y aumenta la resorción ósea."],
    ["¿Qué efecto óseo puede tener la exposición breve e intermitente a PTH?", "Aumenta la formación y la masa ósea."],
    ["¿Qué efectos renales directos tiene PTH sobre calcio y fosfato?", "Aumenta la reabsorción de calcio y la excreción de fosfato."],
    ["¿Cómo favorece la PTH la absorción intestinal de calcio?", "Estimula la activación renal de vitamina D, que aumenta la absorción intestinal de calcio."],
  ] },
  { topic: "Glándulas suprarrenales", cards: [
    ["¿Qué secretan principalmente corteza y médula suprarrenales?", "Corteza: hormonas esteroideas; médula: catecolaminas."],
    ["¿De qué origen embrionario son la corteza y la médula suprarrenales?", "Corteza: mesodermo; médula: cresta neural."],
    ["¿Qué dos vías sanguíneas llegan a la médula suprarrenal?", "Arteriolas medulares directas y sinusoides procedentes de la corteza."],
    ["¿Qué característica singular tiene la vena adrenomedular central?", "Haces longitudinales de músculo liso en su pared."],
    ["¿En qué orden se disponen las tres zonas corticales desde la cápsula hacia la médula?", "Glomerular → fasciculada → reticular."],
    ["¿Qué zona cortical secreta aldosterona?", "Zona glomerular."],
    ["¿Qué zona cortical secreta principalmente cortisol?", "Zona fasciculada."],
    ["¿Qué zona cortical secreta principalmente andrógenos suprarrenales?", "Zona reticular."],
    ["¿Cómo se organiza histológicamente la zona glomerular?", "En grupos ovoides y columnas curvas de células pequeñas, justo bajo la cápsula."],
    ["¿Cómo se organiza histológicamente la zona fasciculada?", "En cordones rectos largos de una o dos células de espesor, separados por sinusoides."],
    ["¿Por qué las células de la zona fasciculada suelen verse vacuoladas en H&E?", "Sus abundantes lípidos se extraen durante el procesamiento del tejido."],
    ["¿Cómo se organiza histológicamente la zona reticular?", "En cordones anastomosados de células más pequeñas y oscuras, algunas con lipofuscina."],
    ["¿Qué rasgos ultraestructurales sugieren síntesis de esteroides en células corticales?", "REL abundante, mitocondrias con crestas tubulares e inclusiones lipídicas."],
    ["¿Qué sistema regula principalmente la secreción de aldosterona de la zona glomerular?", "El sistema renina–angiotensina–aldosterona, en especial angiotensina II."],
    ["¿Qué sistema regula principalmente la zona fasciculada?", "CRH hipotalámica → ACTH adenohipofisaria → secreción de glucocorticoides."],
    ["¿Qué sistema regula principalmente la zona reticular?", "El eje CRH–ACTH."],
    ["¿Qué efecto renal principal tiene la aldosterona?", "Aumenta la reabsorción de Na+ y la secreción de K+ en segmentos distales renales."],
    ["¿Qué célula de la médula suprarrenal libera adrenalina o noradrenalina?", "La célula cromafín."],
    ["¿Por qué se considera a la célula cromafín equivalente funcional de una neurona simpática postsináptica?", "Recibe acetilcolina de una fibra simpática presináptica y libera catecolaminas a la sangre."],
    ["¿Qué tipo de vesícula caracteriza a la célula cromafín secretora de noradrenalina?", "Vesículas grandes con centro muy electrodenso."],
    ["¿Qué tipo de vesícula caracteriza a la célula cromafín secretora de adrenalina?", "Vesículas más pequeñas y menos electrodensas."],
    ["¿Cómo favorecen los glucocorticoides corticales la producción medular de adrenalina?", "Llegan a la médula por la sangre cortical e inducen la enzima que convierte noradrenalina en adrenalina."],
    ["¿Cómo se relaciona la corteza suprarrenal fetal con la placenta?", "Forman una unidad fetoplacentaria e intercambian precursores para completar la síntesis de esteroides."],
    ["¿Qué ocurre con la zona fetal de la corteza suprarrenal después del nacimiento?", "Involuciona rápidamente mientras madura la corteza permanente."],
  ] },
]

// Ampliación de alto rendimiento. Se agrega después de las tarjetas originales
// de cada órgano para conservar los IDs y el progreso de estudio existentes.
const expansion: Readonly<Record<string, readonly (readonly [string, string])[]>> = {
  "Fundamentos endocrinos": [
    ["En una muestra sin conductos y con abundantes capilares, ¿qué tipo de glándula sospecharías?", "Una glándula endocrina: sus hormonas pasan al intersticio y de allí a la circulación."],
    ["¿Qué patrones histológicos ayudan a reconocer tiroides, suprarrenal y paratiroides?", "Tiroides: folículos con coloide; suprarrenal: cordones corticales; paratiroides: nidos o cordones compactos de células."],
    ["¿Qué es el sistema neuroendocrino difuso (SNED)?", "Células endocrinas dispersas en distintos órganos que secretan señales con efectos endocrinos, paracrinos o autocrinos."],
    ["¿Por qué las hormonas esteroideas suelen circular unidas a proteínas plasmáticas?", "Son lipofílicas; las proteínas transportadoras facilitan su transporte y las protegen de la degradación."],
    ["¿Qué dos familias hormonales derivadas de tirosina tienen comportamientos de receptor distintos?", "Catecolaminas: receptores de superficie; hormonas tiroideas: receptores intracelulares, principalmente nucleares."],
    ["¿Qué consigue una cascada de segundos mensajeros tras activar un receptor de membrana?", "Amplifica la señal hormonal y modifica con rapidez la actividad de la célula diana."],
    ["¿Qué vía de receptor de superficie se asocia con la insulina?", "Una vía con actividad tirosina-cinasa, no un receptor nuclear de esteroides."],
    ["Si una glándula produce hormona pero el tejido diana no responde, ¿dónde puede estar el defecto?", "En la respuesta del tejido diana, por ejemplo en su receptor o en la señalización posterior."],
  ],
  "Hipófisis e hipotálamo": [
    ["En H&E, ¿cómo se distinguen acidófilas, basófilas y cromófobas de la porción distal?", "Acidófilas: citoplasma rosado; basófilas: citoplasma violáceo; cromófobas: citoplasma poco teñido."],
    ["¿Por qué el color en H&E no basta para identificar con certeza cada hormona adenohipofisaria?", "Varios tipos celulares comparten afinidad tintorial; la inmunocitoquímica identifica su producto hormonal."],
    ["¿Cuál es el tipo secretor más abundante en la adenohipófisis?", "La somatótropa, productora de GH."],
    ["Una célula adenohipofisaria PAS positiva y basófila puede pertenecer a ¿qué tres linajes?", "Corticótropas, gonadótropas o tirótropas; se requiere identificación hormonal para distinguirlas."],
    ["¿Por qué una lactótropa puede verse cromófoba después de secretar?", "Al descargar sus vesículas acidófilas, pierde gran parte de la tinción citoplasmática característica."],
    ["¿Qué hormona inicia la formación de leche y cuál provoca su eyección?", "La prolactina inicia y mantiene la producción; la oxitocina contrae las células mioepiteliales y expulsa la leche."],
    ["¿Qué produce un adenoma somatótropo activo antes y después del cierre de las placas de crecimiento?", "Antes: gigantismo; después: acromegalia, por exceso de GH."],
    ["¿Qué células hipofisarias se buscan si el exceso hormonal procede de POMC/ACTH?", "Las corticótropas de la adenohipófisis."],
    ["¿Qué hacen FSH y LH en el ovario, en términos generales?", "FSH favorece el desarrollo folicular; LH participa en la maduración final, la ovulación y el cuerpo lúteo."],
    ["En el testículo, ¿con qué procesos se relacionan FSH y LH?", "FSH con la espermatogénesis; LH con las células de Leydig y la secreción de andrógenos."],
    ["¿Qué cambio de prolactina esperarías si se interrumpe la llegada de dopamina hipotalámica?", "Aumento de prolactina, porque se pierde su inhibición tónica."],
    ["¿Qué rasgo microscópico permite distinguir la porción nerviosa de la distal?", "La nerviosa contiene axones neurosecretores y pituicitos; la distal, cordones de células endocrinas con sinusoides."],
    ["¿Qué trayecto siguen ADH y oxitocina desde el hipotálamo hasta la sangre?", "Se sintetizan en neuronas hipotalámicas, viajan por sus axones al lóbulo posterior y se liberan a capilares fenestrados."],
    ["Si ves dilataciones axonales con material neurosecretor en la hipófisis, ¿qué estructura y porción son?", "Cuerpos de Herring de la neurohipófisis."],
    ["¿Qué semejanza tienen pituicitos y células intersticiales de la pineal?", "Ambos son elementos gliales de sostén, con rasgos parecidos a astrocitos."],
    ["¿Cómo reduce la ADH el volumen de orina a nivel de los conductos colectores?", "Al activar receptores V2 favorece la inserción de acuaporina 2 y la reabsorción de agua."],
    ["Con ADH normal o alta y poliuria intensa, ¿qué tipo de diabetes insípida sospecharías?", "Nefrogénica: el riñón no responde a la ADH circulante."],
    ["¿Qué dos componentes pueden estar alterados en la diabetes insípida nefrogénica congénita descrita por Ross?", "El receptor renal V2 de ADH o el canal de agua acuaporina 2."],
    ["¿Qué patrón de orina y sodio sérico orienta a SIADH?", "Orina inapropiadamente concentrada e hiponatremia por retención de agua."],
    ["¿Por qué una lesión del hipotálamo puede alterar la adenohipófisis aunque no destruya sus células?", "Porque interrumpe las hormonas reguladoras que normalmente le llegan por el sistema porta hipofisario."],
  ],
  "Glándula pineal": [
    ["¿De qué región embrionaria deriva la glándula pineal?", "Del neuroectodermo del techo posterior del diencéfalo."],
    ["¿Dónde buscarías la pineal con respecto al tercer ventrículo?", "En su pared posterior, unida al encéfalo por un pedículo corto."],
    ["¿Cómo se organizan los pinealocitos en el parénquima?", "En grupos o cordones dentro de lóbulos separados por tabiques conjuntivos."],
    ["¿Qué rasgo de sus prolongaciones apoya la actividad neuroendocrina de los pinealocitos?", "Sus extremos ensanchados se asocian estrechamente con capilares sanguíneos."],
    ["¿Por qué pueden verse los cuerpos arenáceos en estudios de imagen?", "Son calcificaciones radioopacas de la línea media."],
    ["Además de regular ritmos circadianos, ¿qué eje puede modular la melatonina según Ross?", "Puede inhibir la secreción de GnRH y modular la actividad esteroidogénica gonadal."],
  ],
  "Glándula tiroides": [
    ["¿Qué dos componentes reconocerías primero en una microfotografía de tiroides?", "Folículos delimitados por epitelio simple y luz llena de coloide."],
    ["¿Qué aspecto del epitelio sugiere una tiroides poco activa frente a una muy estimulada?", "Poco activa: epitelio más bajo; estimulada: células foliculares más altas, incluso cilíndricas."],
    ["¿Qué significan los bordes festoneados o vacuolas de reabsorción del coloide?", "Que las células foliculares están captando coloide para liberar hormona tiroidea."],
    ["¿Hacia qué polo de la célula folicular se vierte primero la tiroglobulina?", "Hacia el polo apical, a la luz del folículo, donde forma parte del coloide."],
    ["¿Por qué la célula folicular está próxima a capilares fenestrados?", "Porque libera T3 y T4 por el polo basolateral hacia la circulación."],
    ["Si el NIS basolateral no funciona, ¿qué paso de la síntesis tiroidea se compromete primero?", "La captación de yoduro desde la sangre por la célula folicular."],
    ["Si falla la pendrina apical, ¿qué transporte se dificulta?", "El paso del yoduro hacia la luz folicular y el coloide."],
    ["¿Qué efecto tiene bloquear la peroxidasa tiroidea sobre la tiroglobulina?", "Disminuye la oxidación del yoduro, su incorporación a tirosinas y el acoplamiento para formar T3/T4."],
    ["Un folículo muy activo con epitelio alto y coloide festoneado, ¿con qué enfermedad autoinmune se asocia clásicamente?", "Con enfermedad de Graves, por estimulación sostenida del receptor de TSH."],
    ["¿Qué hacen los autoanticuerpos de Graves en la célula folicular?", "Se unen al receptor de TSH y lo estimulan, elevando la síntesis y liberación de hormonas tiroideas."],
    ["¿Qué lesión histológica caracteriza a la tiroiditis de Hashimoto según el capítulo?", "Apoptosis de células tiroideas y destrucción de folículos por autoinmunidad."],
    ["¿Por qué la falta de yodo puede producir bocio aunque disminuya la hormona tiroidea?", "La menor T3/T4 aumenta el estímulo de TSH, que causa hipertrofia tiroidea."],
    ["¿Qué síntomas orientan a exceso de hormona tiroidea por metabolismo acelerado?", "Pérdida de peso, sudoración, taquicardia y nerviosismo."],
    ["¿Qué componente del tejido conjuntivo contribuye al edema del hipotiroidismo del adulto?", "Acumulación de ácido hialurónico en la matriz extracelular dérmica."],
    ["¿Qué hacen las desyodasas D1/D2 y D3 con la T4?", "D1/D2 la convierten en T3 activa; D3 favorece la formación de T3 inversa inactiva."],
    ["¿Por qué una alteración de MCT8 puede dañar el desarrollo cerebral pese a T3 circulante elevada?", "Impide el transporte adecuado de T3 hacia las neuronas; la hormona sanguínea no llega eficazmente a su diana."],
    ["¿Qué consecuencias centrales y somáticas puede causar hipotiroidismo congénito no corregido?", "Alteración irreversible del desarrollo del SNC y retraso generalizado del crecimiento."],
  ],
  "Glándulas paratiroides": [
    ["¿Cómo se distinguen en H&E células principales y oxífilas paratiroideas?", "Las principales son pequeñas y pálidas; las oxífilas, mayores y de citoplasma intensamente eosinófilo."],
    ["¿Qué célula domina numéricamente el parénquima paratiroideo?", "La célula principal, responsable de la secreción de PTH."],
    ["¿Por qué una paratiroides adulta normal puede contener muchos adipocitos?", "El tejido adiposo del estroma aumenta con la edad; no indica por sí solo una lesión."],
    ["¿Por qué una paratiroides inferior puede hallarse cerca o dentro del timo?", "Porque ambas estructuras derivan de la tercera bolsa faríngea y descienden juntas durante el desarrollo."],
    ["En una tiroidectomía, ¿por qué importa preservar tejido paratiroideo funcional?", "Su pérdida puede causar hipocalcemia grave y tetania, incluso de músculos respiratorios."],
    ["¿Qué sensor permite a la célula principal ajustar PTH a la calcemia?", "El receptor sensible al calcio: la hipocalcemia estimula PTH y la hipercalcemia la inhibe."],
    ["¿Por qué el efecto óseo de PTH sobre osteoclastos es indirecto?", "Los osteoclastos no tienen receptor de PTH; la señal pasa por células osteoblásticas y RANKL–RANK."],
    ["¿Qué cambio en RANKL y osteoprotegerina favorece la resorción ósea con PTH sostenida?", "Aumenta la señal RANKL y disminuye la protección de osteoprotegerina, favoreciendo osteoclastos."],
    ["¿Por qué puede emplearse PTH intermitente en osteoporosis?", "Porque pulsos breves pueden estimular formación ósea y aumentar masa ósea, a diferencia de exposición continua."],
    ["¿Qué enzima renal estimula PTH para activar vitamina D?", "La 1α-hidroxilasa, que forma 1,25-dihidroxivitamina D."],
    ["¿Por qué aumenta el calcio intestinal cuando se secreta PTH?", "De modo indirecto: PTH activa vitamina D en el riñón y esta favorece la absorción intestinal de calcio."],
  ],
  "Glándulas suprarrenales": [
    ["En un corte suprarrenal, ¿qué región rodea a cuál?", "La corteza esteroidogénica periférica rodea a la médula cromafín central."],
    ["¿Por qué la médula suprarrenal recibe sangre con glucocorticoides corticales?", "Parte de su riego procede de sinusoides que atraviesan primero la corteza."],
    ["¿Qué neurotransmisor liberan las fibras simpáticas presinápticas sobre células cromafines?", "Acetilcolina; la célula cromafín responde liberando catecolaminas a la sangre."],
    ["¿Qué diferencia morfológica separa a una célula cromafín de una neurona simpática postsináptica típica?", "La célula cromafín no posee un axón funcional largo: vierte su secreción a capilares."],
    ["Un tumor de células cromafines con crisis de hipertensión y palpitaciones sugiere ¿qué diagnóstico?", "Feocromocitoma, por secreción excesiva de catecolaminas."],
    ["¿Cómo se llama un tumor cromafín extrasuprarrenal?", "Paraganglioma."],
    ["¿Qué efecto tiene el cortisol cortical sobre la producción medular de adrenalina?", "Induce la enzima PNMT, que convierte noradrenalina en adrenalina."],
    ["¿Dónde buscarías histológicamente la zona glomerular?", "Justo bajo la cápsula, en pequeños grupos o arcos de células."],
    ["¿Qué hallazgo permite reconocer la zona fasciculada a bajo aumento?", "Cordones rectos largos de células claras o vacuoladas, separados por sinusoides."],
    ["¿Por qué la zona fasciculada no sintetiza aldosterona?", "Carece de aldosterona-sintasa; esa capacidad corresponde a la zona glomerular."],
    ["¿Qué pigmento puede oscurecer células de la zona reticular?", "Lipofuscina acumulada en su citoplasma."],
    ["¿Qué diferencia el control principal de zona glomerular frente a fasciculada?", "Glomerular: sistema renina–angiotensina; fasciculada: eje hipotalámico–hipofisario con ACTH."],
    ["¿Por qué un tratamiento prolongado con glucocorticoides puede dificultar la cicatrización?", "Suprime respuestas inflamatorias e inmunitarias necesarias para reparar tejidos."],
    ["¿Qué cambio metabólico hepático promueve el cortisol durante una demanda energética?", "Favorece la gluconeogénesis y aumenta la disponibilidad de glucosa."],
    ["¿Qué región suprarrenal fetal involuciona tras el nacimiento?", "La zona fetal cortical, mientras madura la corteza permanente."],
    ["¿Qué pista vascular ayuda a identificar médula suprarrenal en un corte?", "La vena adrenomedular central con haces de músculo liso longitudinal en su pared."],
  ],
}

export const cap21Flashcards: Flashcard[] = groups.flatMap((group, groupIndex) =>
  [...group.cards, ...expansion[group.topic]].map(([front, back], index) => ({
    id: `histo-cap21-${String(groupIndex + 1).padStart(2, "0")}-${String(index + 1).padStart(3, "0")}`,
    subject: "Histología",
    book: "Ross",
    chapter: "Capítulo 21",
    topic: group.topic,
    subtopic: group.topic,
    front,
    back,
    tags: ["Capítulo 21", group.topic]
  }))
)
