import type { Flashcard } from "./cards"

type Pair = readonly [string, string]
type Group = { topic: string; subtopic: string; cards: readonly Pair[] }

// Basado exclusivamente en el capítulo principal (líneas previas a Histología 101).
const groups: readonly Group[] = [
  { topic: "Fundamentos urinarios", subtopic: "Funciones y organización", cards: [
    ["¿Qué órganos integran el aparato urinario?", "Dos riñones, dos uréteres, la vejiga y la uretra."],
    ["¿Qué estructura transporta orina desde cada riñón hasta la vejiga?", "El uréter."],
    ["¿Qué función renal elimina productos de desecho metabólico?", "La filtración sanguínea y su excreción en la orina."],
    ["¿Cómo contribuye el riñón al equilibrio acidobásico cuando los líquidos son demasiado ácidos?", "Excretando iones hidrógeno."],
    ["¿Cómo responde el riñón a líquidos corporales demasiado alcalinos?", "Excretando bicarbonato."],
    ["¿Qué fracción aproximada del gasto cardíaco reciben los riñones?", "Alrededor del 25%."],
    ["¿Cómo se llama el líquido filtrado inicialmente en el glomérulo?", "Ultrafiltrado glomerular u orina primaria."],
    ["¿Qué procesos modifican el ultrafiltrado para formar orina definitiva?", "Reabsorción selectiva y secreción específica."],
    ["¿Qué desechos nitrogenados normales contiene la orina definitiva?", "Urea, ácido úrico y creatinina."],
    ["¿Qué hormona renal estimula la formación de eritrocitos en médula ósea?", "Eritropoyetina."],
    ["¿Qué células renales producen eritropoyetina según el texto?", "Células endoteliales de capilares peritubulares corticales."],
    ["¿Qué enzima renal inicia la formación de angiotensina I?", "Renina."],
    ["¿Qué conversión de vitamina D ocurre en túbulos proximales renales?", "25-OH vitamina D3 a 1,25-(OH)2 vitamina D3 o calcitriol."],
    ["¿Qué efecto sistémico principal tiene el calcitriol activo?", "Aumenta absorción intestinal de calcio y fosfato, y moviliza calcio óseo."],
  ]},
  { topic: "Riñón", subtopic: "Anatomía macroscópica y compartimentos", cards: [
    ["¿En qué espacio abdominal se encuentran los riñones?", "En el espacio retroperitoneal."],
    ["¿Cuál riñón suele ubicarse un poco más bajo?", "El derecho."],
    ["¿Qué estructura entra y sale por el hilio renal?", "Vasos y nervios renales; también emerge la pelvis renal."],
    ["¿Cómo se llama el espacio interno junto al hilio que contiene pelvis, vasos y grasa?", "El seno renal."],
    ["¿Qué dos capas componen la cápsula renal?", "Una externa de fibroblastos y colágeno, y otra interna más celular."],
    ["¿Qué región renal externa contiene corpúsculos renales?", "La corteza."],
    ["¿Qué región renal interna contiene las pirámides?", "La médula."],
    ["¿Qué proyecciones corticales separan pirámides renales?", "Las columnas renales."],
    ["¿Qué estructura forma un lóbulo renal?", "Una pirámide medular y la corteza asociada."],
    ["¿Hacia dónde se proyecta la papila renal?", "Hacia un cáliz menor."],
    ["¿Cómo se llama la superficie papilar perforada por conductos de Bellini?", "Área cribosa."],
    ["¿Qué forman en corteza los túbulos rectos y conductos colectores agrupados?", "Los rayos medulares."],
    ["¿Qué región cortical contiene corpúsculos renales y túbulos contorneados entre rayos?", "El laberinto cortical."],
  ]},
  { topic: "Nefrona", subtopic: "Segmentos, polos y tipos", cards: [
    ["¿Cuál es la unidad estructural y funcional del riñón?", "La nefrona."],
    ["¿Qué dos componentes fundamentales forman una nefrona?", "El corpúsculo renal y su sistema tubular."],
    ["¿Qué estructura capilar contiene el corpúsculo renal?", "El glomérulo."],
    ["¿Qué polo del corpúsculo recibe la arteriola aferente y deja salir la eferente?", "El polo vascular."],
    ["¿En qué polo se inicia el túbulo contorneado proximal?", "En el polo urinario."],
    ["¿Qué segmentos integran el segmento grueso proximal?", "Túbulo contorneado proximal y túbulo recto proximal."],
    ["¿Qué segmentos integran el segmento grueso distal?", "Túbulo recto distal y túbulo contorneado distal."],
    ["¿Qué parte de la nefrona forma la U completa del asa de Henle?", "Túbulo recto proximal, segmentos delgados y túbulo recto distal."],
    ["¿Qué segmento tubular toca el polo vascular para formar la mácula densa?", "El túbulo recto distal o rama gruesa ascendente."],
    ["¿Qué segmento recibe el líquido del túbulo contorneado distal?", "El túbulo conector y luego el conducto colector cortical."],
    ["¿Qué nefronas tienen asas muy largas que penetran profundamente en médula?", "Las yuxtamedulares."],
    ["¿Qué nefronas poseen asas cortas limitadas a la médula externa?", "Las corticales o subcapsulares."],
    ["¿Qué tipo de nefrona es crucial para concentrar la orina?", "La nefrona yuxtamedular."],
    ["¿Qué conductos reciben la confluencia de túbulos conectores de muchas nefronas?", "Los conductos colectores corticales."],
    ["¿Qué conductos grandes desembocan en el cáliz menor desde la papila?", "Los conductos papilares de Bellini."],
  ]},
  { topic: "Corpúsculo renal", subtopic: "Barrera de filtración y cápsula", cards: [
    ["¿Cuáles son los tres componentes de la barrera de filtración glomerular?", "Endotelio fenestrado, membrana basal glomerular y podocitos."],
    ["¿Qué rasgo distingue las fenestraciones del endotelio glomerular?", "Son numerosas, grandes y carecen de diafragma."],
    ["¿Qué acuaporina facilita movimiento rápido de agua en endotelio glomerular?", "AQP-1."],
    ["¿Qué dos células producen en conjunto la membrana basal glomerular?", "El endotelio y los podocitos."],
    ["¿Qué tinción resalta especialmente la membrana basal glomerular?", "PAS."],
    ["¿Qué tipo de colágeno forma la red principal de la MBG?", "Colágeno tipo IV."],
    ["¿Qué alteración hereditaria de colágeno IV causa hematuria y proteinuria progresivas?", "Síndrome de Alport."],
    ["¿Qué células forman la capa visceral de la cápsula de Bowman?", "Los podocitos."],
    ["¿Cómo se llaman las prolongaciones secundarias entrelazadas de los podocitos?", "Pedicelos."],
    ["¿Qué espacio queda entre pedicelos de podocitos vecinos?", "La ranura de filtración."],
    ["¿Qué proteína es clave en el diafragma de la ranura de filtración?", "Nefrina."],
    ["¿Qué epitelio forma la capa parietal de la cápsula de Bowman?", "Epitelio plano simple."],
    ["¿Qué espacio recibe la orina primaria entre capas visceral y parietal?", "El espacio urinario o de Bowman."],
    ["¿Con qué epitelio continúa la capa parietal en el polo urinario?", "Con epitelio cúbico del túbulo contorneado proximal."],
    ["¿Qué límite de tamaño restringe de modo importante la MBG?", "Partículas mayores de aproximadamente 70 kDa o 3.6 nm de radio."],
    ["¿Qué hallazgo urinario sugiere lesión de la barrera glomerular?", "Albuminuria o hematuria significativa."],
  ]},
  { topic: "Corpúsculo renal", subtopic: "Mesangio y aparato yuxtaglomerular", cards: [
    ["¿Qué forman las células mesangiales junto con su matriz extracelular?", "El mesangio."],
    ["¿Dónde se localizan las células mesangiales intraglomerulares?", "Entre capilares glomerulares, confinadas por la MBG."],
    ["¿Qué función depuradora cumplen las células mesangiales?", "Fagocitan y endocitan residuos y complejos atrapados en el filtro."],
    ["¿Qué función estructural tiene la matriz mesangial?", "Dar soporte a regiones capilares donde la MBG es incompleta."],
    ["¿Qué mediadores pueden secretar células mesangiales?", "IL-1, PGE2 y PDGF."],
    ["¿Qué propiedad permite a células mesangiales responder a presión arterial alta?", "Su capacidad contráctil para modular distensión glomerular."],
    ["¿Qué tres componentes integran el aparato yuxtaglomerular?", "Mácula densa, células yuxtaglomerulares y células mesangiales extraglomerulares."],
    ["¿Qué concentración vigila la mácula densa en el líquido tubular?", "La de sodio."],
    ["¿Qué secretan las células yuxtaglomerulares?", "Renina."],
    ["¿De qué tipo celular derivan las células yuxtaglomerulares?", "De células musculares lisas modificadas de la arteriola aferente."],
    ["¿Qué convierte la renina a partir del angiotensinógeno?", "Angiotensina I."],
    ["¿Dónde convierte la ECA la angiotensina I en angiotensina II según el texto?", "En endotelio de capilares pulmonares."],
    ["¿Qué hormona suprarrenal estimula la angiotensina II?", "Aldosterona."],
    ["¿Qué hace la aldosterona en células principales de túbulos conectores y colectores?", "Aumenta reabsorción de sodio y agua y secreción de potasio."],
    ["¿Qué efecto vascular adicional tiene angiotensina II?", "Vasoconstricción potente."],
  ]},
  { topic: "Túbulo proximal", subtopic: "Morfología y reabsorción", cards: [
    ["¿Cuál es el sitio inicial y principal de reabsorción del ultrafiltrado?", "El túbulo contorneado proximal."],
    ["¿Qué especialización apical identifica al túbulo contorneado proximal?", "Un borde en cepillo de microvellosidades largas."],
    ["¿Qué rasgo basal ayuda a reconocer al túbulo proximal en histología?", "Estriaciones basales por mitocondrias entre evaginaciones basales."],
    ["¿Qué porcentaje aproximado del ultrafiltrado se reabsorbe en el túbulo proximal?", "Alrededor del 65%."],
    ["¿Qué bomba impulsa la reabsorción de sodio en células proximales?", "ATPasa Na+/K+."],
    ["¿Qué canal facilita reabsorción de agua en túbulo proximal?", "AQP-1."],
    ["¿Qué sustancia se reabsorbe casi por completo mediante SGLT2 en el túbulo proximal?", "Glucosa."],
    ["¿Qué transportador basolateral libera glucosa desde células proximales hacia intersticio?", "GLUT2."],
    ["¿Qué proporción aproximada de aminoácidos filtrados recupera el túbulo proximal?", "Cerca del 98%."],
    ["¿Cómo se recuperan proteínas y péptidos grandes filtrados en túbulo proximal?", "Por endocitosis y degradación lisosómica."],
    ["¿Qué sucede con los aminoácidos liberados de proteínas endocitadas?", "Se reciclan y vuelven a la circulación."],
    ["¿Qué segmento recupera glucosa remanente mediante SGLT1?", "El túbulo recto proximal."],
    ["¿Qué transportador basolateral acompaña a SGLT1 en túbulo recto proximal?", "GLUT1."],
  ]},
  { topic: "Asa renal y túbulo distal", subtopic: "Contracorriente y ajuste iónico", cards: [
    ["¿Qué rama del asa de Henle es muy permeable al agua?", "La rama delgada descendente."],
    ["¿Qué ocurre con el agua en la rama delgada descendente dentro de médula hiperosmótica?", "Sale por ósmosis y concentra el líquido tubular."],
    ["¿Qué rama del asa es prácticamente impermeable al agua y reabsorbe sales?", "La rama ascendente delgada."],
    ["¿Por qué la rama ascendente se denomina segmento diluyente?", "Reabsorbe NaCl sin agua y deja el líquido tubular hipoosmótico."],
    ["¿Qué proteína secretan células de rama gruesa ascendente y aparece en cilindros urinarios?", "Uromodulina o proteína de Tamm-Horsfall."],
    ["¿Qué otro nombre recibe el túbulo recto distal?", "Rama gruesa ascendente del asa renal."],
    ["¿Qué relación tiene el túbulo contorneado distal con el proximal en un corte cortical?", "Es menos tortuoso y por eso se ven menos perfiles distales."],
    ["¿Qué función global cumple el asa renal con vasos rectos paralelos?", "Crear el multiplicador por contracorriente que concentra orina."],
    ["¿Qué sustancias se reabsorben de forma parcial a lo largo del túbulo urinario?", "Agua, sodio y bicarbonato."],
    ["¿Qué sustancias se secretan hacia el ultrafiltrado como parte de actividad tubular?", "Creatinina y ácidos y bases orgánicos."],
  ]},
  { topic: "Conductos colectores", subtopic: "Células, hormonas y acuaporinas", cards: [
    ["¿Qué dos tipos celulares principales aparecen en conductos colectores?", "Células principales claras y células intercaladas oscuras."],
    ["¿Qué hormona regula de manera aguda la permeabilidad al agua del conducto colector?", "Hormona antidiurética o ADH."],
    ["¿Qué acuaporina se inserta en membrana apical de células principales en respuesta a ADH?", "AQP-2."],
    ["¿Dónde se localizan AQP-3 y AQP-4 en células principales?", "En la membrana basolateral."],
    ["¿Qué efecto tiene ADH sobre la reabsorción de agua?", "La aumenta al permitir inserción de AQP-2 apical."],
    ["¿Qué hormona estimula reabsorción de sodio y secreción de potasio en células principales?", "Aldosterona."],
    ["¿Qué tipo de célula colectora participa en regulación acidobásica?", "La célula intercalada."],
    ["¿Cómo cambia el epitelio de conductos colectores al aumentar su diámetro hacia papila?", "De cúbico a cilíndrico."],
    ["¿Qué nombre recibe el conducto colector terminal grande que se abre en papila?", "Conducto de Bellini."],
  ]},
  { topic: "Circulación renal", subtopic: "Vasos, linfáticos e inervación", cards: [
    ["¿Qué arterias corren entre las pirámides renales?", "Las arterias interlobulares."],
    ["¿Qué arterias siguen el límite entre corteza y médula?", "Las arterias arqueadas."],
    ["¿Qué ramas arteriales ascienden por la corteza y originan arteriolas aferentes?", "Las arterias interlobulillares."],
    ["¿Qué vaso entra al glomérulo?", "La arteriola aferente."],
    ["¿Qué vaso sale del glomérulo y genera una segunda red capilar?", "La arteriola eferente."],
    ["¿Qué red rodea túbulos en corteza tras salir de glomérulos corticales?", "Los capilares peritubulares."],
    ["¿Qué vasos largos acompañan asas de Henle de nefronas yuxtamedulares?", "Los vasos rectos."],
    ["¿Qué efecto tiene la constricción de arteriolas aferentes sobre filtración glomerular?", "La disminuye."],
    ["¿Qué efecto tiene la constricción de arteriolas eferentes sobre filtración glomerular?", "La aumenta."],
    ["¿Qué sistema autónomo domina la inervación vasomotora renal?", "El simpático."],
  ]},
  { topic: "Vías urinarias", subtopic: "Urotelio y distensión", cards: [
    ["¿Qué epitelio reviste cálices, uréteres y vejiga?", "Epitelio de transición o urotelio."],
    ["¿Qué propiedad funcional caracteriza al urotelio?", "Esencialmente impermeable a sales y agua."],
    ["¿Cómo se llaman las células superficiales grandes del urotelio?", "Células sombrilla o en cúpula."],
    ["¿Qué cambio sufren células sombrilla cuando se distiende la vejiga?", "Se aplanan y expanden su superficie apical."],
    ["¿Qué capa del urotelio contiene células madre?", "La capa basal."],
    ["¿Qué capa reemplaza rápidamente una célula sombrilla perdida?", "La capa intermedia."],
    ["¿Qué proteínas forman las placas rígidas de membrana apical urotelial?", "Uroplaquinas."],
    ["¿Qué vesículas aportan membrana apical durante distensión vesical?", "Vesículas fusiformes."],
    ["¿Qué ocurre con vesículas fusiformes durante micción?", "La membrana añadida se recupera por endocitosis."],
    ["¿Qué mecanismo impide el paso de agua, urea y protones por placas uroteliales?", "La estructura cristalina de uroplaquinas y uniones ocluyentes."],
    ["¿Qué adhesina de E. coli uropatógena se une a uroplaquinas?", "FimH."],
  ]},
  { topic: "Vías urinarias", subtopic: "Uréter, vejiga y uretra", cards: [
    ["¿Qué movimiento impulsa orina desde cálices hacia vejiga?", "Contracciones peristálticas de músculo liso."],
    ["¿Qué capas musculares se describen en un uréter distal?", "Longitudinal interna, circular media y longitudinal externa."],
    ["¿En qué parte del uréter aparece la capa longitudinal externa?", "En su extremo distal."],
    ["¿Cómo reduce la vejiga distendida el reflujo hacia uréteres?", "Comprime los orificios ureterales por su trayecto oblicuo intramural."],
    ["¿Qué región triangular vesical permanece lisa sin pliegues?", "El trígono."],
    ["¿Qué músculo liso expulsa orina al contraerse la vejiga?", "El músculo detrusor."],
    ["¿Qué esfínter involuntario rodea el orificio uretral interno?", "El esfínter uretral interno."],
    ["¿Qué efecto produce el sistema simpático durante fase de almacenamiento?", "Relaja detrusor y contrae esfínter uretral interno."],
    ["¿De qué segmentos medulares surge el parasimpático para la micción?", "S2 a S4."],
    ["¿Qué efecto parasimpático desencadena micción?", "Contrae detrusor y relaja esfínter uretral interno."],
    ["¿Qué nervio permite control voluntario del esfínter uretral externo?", "El nervio pudendo."],
    ["¿De qué músculo está formado el esfínter uretral externo?", "Músculo esquelético estriado."],
    ["¿Qué epitelio reviste inicialmente la uretra prostática?", "Urotelio."],
    ["¿Qué segmento uretral masculino está rodeado por cuerpo esponjoso?", "La uretra esponjosa o peneana."],
    ["¿Qué glándulas femeninas homólogas a próstata secretan junto a uretra?", "Las glándulas parauretrales de Skene."],
  ]},
  { topic: "Corpúsculo renal", subtopic: "Selectividad, lesión e identificación", cards: [
    ["¿Qué capa de la MBG mira hacia los pedicelos podocitarios?", "La lámina rara externa."],
    ["¿Qué capa de la MBG mira hacia el endotelio capilar?", "La lámina rara interna."],
    ["¿Qué capa central de la MBG actúa como filtro físico rico en colágeno IV?", "La lámina densa."],
    ["¿Qué propiedad de heparán-sulfato en la MBG restringe proteínas aniónicas?", "Su carga negativa."],
    ["¿Qué ocurre con sitios aniónicos de MBG en nefropatía diabética?", "Se reducen de manera significativa, sobre todo en lámina rara externa."],
    ["¿Por qué la barrera de filtración no debe considerarse una estructura pasiva?", "Porque sus componentes pueden remodelar su permeabilidad."],
    ["¿Qué región ocupa el espacio subpodocítico?", "Entre pedicelos con diafragmas y el cuerpo celular del podocito."],
    ["¿Qué función posible tiene el espacio subpodocítico interconectado?", "Regular el flujo de líquido a través de la barrera glomerular."],
    ["¿Qué cambio de la capa parietal puede verse en algunas glomerulonefritis?", "Proliferación de células epiteliales parietales."],
    ["¿Qué enfermedad autoinmunitaria ataca componentes de MBG y progresa rápidamente?", "El síndrome de Goodpasture."],
    ["¿Por qué albúmina en orina es clínicamente significativa?", "Sugiere alteración física o funcional de la barrera de filtración."],
  ]},
  { topic: "Túbulos renales", subtopic: "Distal, conector e identificación", cards: [
    ["¿Qué rasgo luminal ayuda a diferenciar un túbulo distal de uno proximal en H&E?", "El distal tiene una luz más nítida porque carece de borde en cepillo prominente."],
    ["¿Por qué suelen verse menos perfiles de túbulos contorneados distales en corteza?", "Porque son menos tortuosos que los proximales."],
    ["¿Qué parte tubular retorna al polo vascular antes de convertirse en túbulo distal contorneado?", "La rama gruesa ascendente o túbulo recto distal."],
    ["¿Qué estructura conecta con frecuencia el túbulo distal con el conducto colector cortical?", "El túbulo conector arqueado."],
    ["¿Qué segmento tubular reabsorbe bicarbonato y participa en secreción de amonio?", "El túbulo contorneado distal."],
    ["¿Qué propiedad del túbulo distal permite ajustar concentración de sodio y potasio?", "Su transporte selectivo de Na+, K+, Cl− y bicarbonato."],
    ["¿Qué célula colectora presenta citoplasma más claro y contornos celulares definidos?", "La célula principal."],
    ["¿Qué célula colectora tiene abundantes mitocondrias y participa en manejo acidobásico?", "La célula intercalada."],
    ["¿Qué sucede con la concentración urinaria si falta respuesta adecuada a ADH?", "Se reduce la reabsorción de agua y la orina permanece más diluida."],
    ["¿Qué respuesta de AQP-2 es inmediata cuando actúa ADH?", "Vesículas intracitoplasmáticas se fusionan con membrana apical."],
    ["¿Qué respuesta tardía de ADH sostiene la permeabilidad al agua?", "Aumenta síntesis e inserción de AQP-2."],
    ["¿Qué epitelio reviste el conducto colector medular interno cercano a papila?", "Epitelio cilíndrico simple."],
    ["¿Qué sustancia se reabsorbe en el proximal de forma esencialmente completa en condiciones normales?", "La glucosa."],
  ]},
  { topic: "Histofisiología renal", subtopic: "Concentración, intersticio y equilibrio", cards: [
    ["¿Qué mecanismo concentra el intersticio medular para permitir orina hiperosmótica?", "El multiplicador por contracorriente."],
    ["¿Qué estructuras trabajan en paralelo con asas largas para conservar el gradiente medular?", "Los vasos rectos."],
    ["¿Qué papel desempeñan los vasos rectos en contracorriente?", "Actúan como intercambiadores por contracorriente."],
    ["¿Qué segmento colector ajusta finalmente la concentración de orina en la médula?", "El conducto colector medular."],
    ["¿Qué población intersticial cortical participa en producción de eritropoyetina?", "Células asociadas a capilares peritubulares corticales."],
    ["¿Qué sustancia vasodilatadora puede producir el endotelio glomerular y participa en glomerulopatías?", "Óxido nítrico."],
    ["¿Qué efecto tiene pérdida de inervación simpática renal sobre flujo sanguíneo renal?", "Lo incrementa por pérdida de vasoconstricción simpática."],
    ["¿Qué tipo de capilar se asocia estrechamente con túbulos proximales para recuperar líquido?", "Capilar peritubular fenestrado."],
    ["¿Qué consecuencia fisiológica tiene que el líquido intersticial medular sea hiperosmótico?", "Favorece salida de agua de la rama descendente y del colector cuando hay ADH."],
    ["¿Por qué los vasos rectos son largos en nefronas yuxtamedulares?", "Para acompañar sus asas largas y apoyar concentración medular."],
    ["¿Qué volumen de ultrafiltrado se produce aproximadamente por día según el texto?", "Unos 180 litros."],
    ["¿Qué volumen aproximado recupera el túbulo proximal de ese ultrafiltrado?", "Unos 120 litros por día."],
  ]},
  { topic: "Vías urinarias", subtopic: "Detalles histológicos y uretra", cards: [
    ["¿Cuántas capas celulares puede mostrar el urotelio de una vejiga vacía?", "Seis o más capas."],
    ["¿Cuántas capas aparentes suele mostrar una vejiga distendida?", "Aproximadamente tres."],
    ["¿Qué tipo de uniones refuerzan la barrera paracelular de células sombrilla?", "Uniones ocluyentes herméticas."],
    ["¿Qué forma adoptan células intermedias del urotelio?", "Forma piriforme, conectadas por desmosomas."],
    ["¿Qué capas no están bien definidas debajo de lámina propia en vías urinarias?", "Muscular de la mucosa y submucosa."],
    ["¿Qué orientación muscular es interna en porciones tubulares de vías urinarias?", "Longitudinal con espiral abierta."],
    ["¿Qué orientación muscular es externa en porciones tubulares urinarias?", "Circular con espiral apretada."],
    ["¿Qué clase de tejido forma la adventicia del uréter?", "Tejido conjuntivo con adiposo, vasos y nervios."],
    ["¿Qué porción de uretra masculina recibe los conductos eyaculadores?", "La uretra prostática."],
    ["¿Qué epitelio suele revestir la uretra membranosa?", "Cilíndrico estratificado o seudoestratificado."],
    ["¿Qué tipo de secreción producen glándulas parauretrales de Skene?", "Una secreción alcalina."],
    ["¿Qué epitelio puede encontrarse antes de la terminación de uretra femenina?", "Epitelio plano estratificado."],
  ]},
]

const slug = (value: string) => value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")

export const cap20RebuiltFlashcards: Flashcard[] = groups.flatMap(group =>
  group.cards.map(([front, back], index) => ({
    id: `histo-cap20-${slug(group.subtopic)}-${String(index + 1).padStart(3, "0")}`,
    subject: "Histología", book: "Ross", chapter: "Capítulo 20", topic: group.topic, subtopic: group.subtopic,
    front, back, tags: ["Capítulo 20", group.subtopic]
  }))
)
